internal/model/model.go, internal/model/puller.go, internal/model/puller_test.go, internal/scanner/blocks.go, test/sync_test.go
So integration tests are failing:
http://build.syncthing.net/job/syncthing-integration/192/console
but on Windows I get a bunch of access denied bullcrap, and on my linux container they are passing.
If I add back the old `hash the whole file in the finisher`, for some reason it starts working fine?! 
http://build.syncthing.net/job/syncthing-integration/193/console
:scream:
=> Hash blocks after receipt, try multiple peers (fixes #1166)

internal/model/queue_test.go
I'm trying to update the syncthing package for NixOS, but the tests are failing because of one instance of Go 1.4 syntax:
internal/model/queue_test.go:194:7: expected operand, found 'range'
internal/model/queue_test.go:200:3: expected '{', found 'EOF'
This changes it to valid 1.3 syntax.
Another option would be to just change this page to say that Go 1.4 is now required, but that would make things hard for people, since Fedora, Ubuntu and NixOS all come with Go 1.3 right now.
=> Don't use Go 1.4 range syntax in queue_test.go

cmd/syncthing/gui.go
I had bug report (syncthing/syncthing-gtk#56) recently, from guy that managed to break his Syncthing managed by Syncthing-GTK installation, when he manually upgraded to unsupported Syncthing daemon version. He did it, because he saw that green, friendly-looking button `Upgrade To vXYZ` in WebUI.
That's why that button has to die :)
Ok, now, in all seriousness, this PR disables `Upgrade To...` button in WebUI, but **only** if STNOUPGRADE is specified. As you can see bellow, it does it by adding `enabled` field to `/rest/upgrade` response and adding this field to condition under which button is shown. I believe that it shouldn't break anything else.
And you can protect users from themselves by merging this ;-)
=> Return HTTP/500 from /rest/upgrade if STNOUPGRADE is defined

gui/index.html
The "Quick guide to supported patterns" link now points to the wiki article and will open in a new page/tab to avoid disrupting the settings page.
=> "Quick guide to supported patterns" link updated

gui/assets/css/overrides.css, gui/index.html
Small improvements for footer navbar (ref #1154)
- add icons
- link to Syncthing wiki
- show footer navbar on small devices (non-fixed)
=> Small improvements for footer navbar (ref #1154)

internal/protocol/protocol.go
Also refactors the readerLoop to switch on the type of `msg` directly, as it saves us from type asserting everywhere and we can directly look into the message fields.
=> Reject Index and Request messages with unexpected flags

internal/db/leveldb.go, internal/protocol/protocol.go
Turns out I actually need this myself, so probably others do as well.
=> Remove nil filenames from database and indexes (fixes #1243)

internal/model/puller.go, internal/osutil/osutil.go, test/h2/config.xml, test/sync_test.go, test/util.go
Just did a basic test renaming folders, seemed to work.
A possible change would be not to take this shortcut if versioning is enabled, and let the file to be assembled from blocks, as the versioned file has to be copied to the archive anyway.
=> Efficient renames (fixes #1217)

internal/config/wrapper.go, internal/upgrade/upgrade_supported.go
Since we might not always have a chance to clean up, hence
let's leave it to the OS.
Furthermore, try to clean up as much as we can.
=> Put temporary files in the OS temp directory (fixes #1239)

CONTRIBUTING.md
Link in contributing.md points to the old discourse link rather than the github wiki.
=> Fix documentation link

Godeps/Godeps.json, Godeps/_workspace/src/github.com/syncthing/protocol/counting.go, Godeps/_workspace/src/github.com/syncthing/protocol/message.go, Godeps/_workspace/src/github.com/syncthing/protocol/message_xdr.go, Godeps/_workspace/src/github.com/syncthing/protocol/protocol.go, build.go, cmd/syncthing/gui.go, cmd/syncthing/memsize_darwin.go, cmd/syncthing/memsize_linux.go, cmd/syncthing/memsize_solaris.go, cmd/syncthing/memsize_unimpl.go, cmd/syncthing/memsize_windows.go, cmd/syncthing/perfstats_unix.go, internal/db/blockmap.go, internal/db/blockmap_test.go, internal/db/leveldb.go, internal/db/leveldb_xdr.go, internal/db/set.go, internal/db/set_test.go, internal/db/truncated.go, internal/db/truncated_xdr.go, internal/events/events.go, internal/lamport/clock.go, internal/lamport/clock_test.go, internal/model/model.go, internal/model/model_test.go, internal/model/puller.go, internal/model/puller_test.go, internal/model/sharedpullerstate.go, internal/scanner/blocks.go
This is kind of an opinionated change but I think it's a worthy cleanup. Unsigneds are for bitfields. Integers are for numbers, enabling arithmetic like subtractions and for loops without getting shot in the foot. Using plain integers enables operations like `if foo < bar-1` and `diff = foo - bar` on things like our version numbers etc, which is liable to be a bug on unsigned integers. So:
- "int" for numbers that will always be laughably smaller than four billion, and where we don't care about the serialization format.
- "int32" for numbers that will always be laughably smaller than four billion, and will be serialized to four bytes.
- "int64" for numbers that may approach four billion or will be serialized to eight bytes.
- "uint32" and "uint64" for bitfields, depending on required …
=> Integer type policy

internal/config/config.go
=> Ensuring path separator at the end of the folder path. (fixes #1262)

AUTHORS, cmd/syncthing/memsize_netbsd.go
Here is memorySize() to make syncthing work on NetBSD. Based on Darwin implementation.
=> Implement memorySize() for NetBSD

etc/linux-systemd/system/syncthing@.service, etc/linux-systemd/user/syncthing.service
- Removed environment file to keep the service file minimal.
"systemctl edit syncthing.service" does the job if somebody wants
to customize the service.
- Changed "cmdline.target" to "default.target" as "cmdline.target"
does not exist in systemd.special:
http://www.freedesktop.org/software/systemd/man/systemd.special.html
- Added a missing "After=network.target".
=> Some systemd tweaks

internal/model/model.go, internal/model/puller.go, test/filetype_test.go, test/util.go
Two problems happened here. One is that we didn't detect deletion of files inside the ex-directory, because `Lstat("someFileThatWasADir/someotherfile")` doesn't return a "does not exist", it returns an "is not a directory" (referring to "someFileThatWasADir"). The second is that our file reuse logic may kick in so that we try to override "someFileThatWasADir" by renaming something else, which doesn't work when it already exists as a directory. (The last problem is probably really unusual in practice, but happes in the test because we use empty files so they have the same hash, so will be reused...)
=> Handle corner cases with dir->file changes

cmd/syncthing/connections.go, cmd/syncthing/main.go
We've been doing the `bep/1.0` negotiation as part of the TLS handshake since forever, but not verified the result. Doing this now gains us a somewhat cleaner error ("peer did not negotiate bep/1.0" instead of "connected to $someRandomDeviceID"; "unexpected EOF") when someone inadvertently points their sync connection to the GUI port or the other way around. We might possibly break compatibility with other client implementations, but I think that's OK, if worth highlighting on the forum before release.
=> Verify negotiated protocol bep/1.0

internal/osutil/osutil.go
This PR introduces an error when the path is not a directory, when expecting a writable directory. I don't think this was ever part of a particular problem, I just observed this code while patching something else. I think it is not correct/perfectly safe because the current code still calls the fn() if the path would not be a directory. Feel free to update the error msg.
=> Exit and error if the target is not a directory

internal/config/config.go, internal/config/config_test.go, internal/config/testdata/v8.xml
This adds a migration for announce-v6.syncthing.net. With this enabled, global discovery will work for IPv6 as well. It has the negative effect of showing a red "1/2" on global announce servers for hosts without IPv6... Should we do something about that?
=> Add global announce server on IPv6

etc/linux-runit/run
Some distros (Ubuntu, Debian?) don't link `chpst` to `setuidgid`, as it
could conflict with djb daemontools installation.  If daemontools isn't
going to be referenced in the README, then the example runit config
should reference the runit packaged utility.
=> Use chpst instead of djb name setuidgid

etc/linux-runit/README.md, etc/linux-runit/log/run, etc/linux-runit/run
- Changed call to `chpst` to `exec`
- Moved logging to `log/run` per `runsv` standard
While trying to use syncthing with runit, I noticed that the existing script doesn't behave properly.  The process tree created on start looks like this:
├─runsvdir─┬─runsv───runsvdir───runsv
│          └─runsv───run─┬─logger
│                        └─syncthing─┬─syncthing───10*[{syncthing}]
│                                    └─6*[{syncthing}]
Though, when you: `sudo sv down /etc/service/syncthing/` the `TERM` signal isn't propogated or trapped, so syncthing is orphaned and adopted by init (PID 1):
├─runsvdir─┬─runsv───runsvdir───runsv
│          └─runsv
├─syncthing─┬─syncthing───10*[{syncthing}]
│           └─6*[{syncthing}]
user     22676     1  0 20:05 ?        00:00:00 /home/user/bin/syncthing …
=> Fix syncthing process reparenting with runit

.gitignore, build.go
Another attempt at this. Uses a `RELEASE` file if it exists (we can make our build system create one),a Git tag if one is available, or the directory name (this works for just downloading a release tarball from Github, stepping into it and running ./build.sh).
=> Get version from RELEASE file if it exists, or guess from directory (fixes #1449)

internal/config/config.go, internal/model/model.go, internal/scanner/walk.go, internal/scanner/walk_test.go
When the folder config `AutoNormalize` is on (which is the default), we automatically fix normalization errors in file names. Most users will never notice. The ones that care about this kind of stuff should be pleased that we fix their inconsistencies.
=> Automatically fix file name normalization errors (fixes #430)

internal/versioner/staggered.go
prevents
```
staggered.go:215: WARNING: versioner: stat /home/alex/syncthing-test/instance01/Sync/.stversions/link~20150319-174419.txt: no such file or directory
```
when the version is a symlink
=> use Lstat instead of Stat to prevent errors with symlinks

etc/linux-systemd/system/syncthing@.service, etc/linux-systemd/user/syncthing.service
Syncthing should not try to start a browser when invoked by systemd.
Furthermore we do not need any timestamps in the journal as systemd
already handles this for us.
=> systemd: Set -logflags to 0, provide -no-browser flag

internal/model/rwfolder.go
We need an explicit chmod() when creating a new directory.
Otherwise a new directory may be created with a different permission
from the one received from an originating device, because the umask
is applied to the mode given to mkdir().
The incorrect permission is later sent back to the originating device
and the original permission will be lost.
=> Preserve the permission of a newly created directory

cmd/stevents/main.go, cmd/syncthing/main.go, internal/config/config.go
Because 8080 is reserved for dev purposes and with the betas going on, this could be a good time to fix this.
=> Change (default) GUI port from 8080 to 8384 ('ST' in ascii values)

cmd/syncthing/gui.go, internal/model/model.go, internal/scanner/walk.go, internal/scanner/walk_test.go
Related to https://github.com/syncthing/syncthing-inotify/commit/b886866fd7c1a605fb58c186a36e63786a10eef7
- (Partially) fixes renames for inotify clients
- Improves scanning performance when many files change at the same time (i.e. when scan requires are initiated by external clients)
Note: it was mentioned that this might need a lock before exchanging the updated index to other clients, but I'm not sure where to put it. The current patch should be a regression without this lock so that's why I invoke the PR already.
=> Support multiple scan query strings at the same time

cmd/syncthing/main.go
This reverts the GC behavior to the Go default of triggering GC when the
heap has grown 100% compared to after the previous GC. We were setting
this to 25% to keep memory usage at a minimum, but it has a pretty
severe performance cost (especially when syncing large files) as we keep
triggering GC too often.
This documents the tweak in the `-help` message so users can decide for
themselves, and sticks to whatever the Go runtime developers thinks is
best for the default.
=> Remove default GC tweak

etc/linux-systemd/system/syncthing@.service, etc/linux-systemd/user/syncthing.service
The systemd exit code definitions (introduced in c586a17, refs #1324) caused
problems. Per default systemd considers a return code != 0 as failed. So when
you click on "Restart" in the WebUI an error appears:
```
systemd[953]: syncthing.service: main process exited, code=exited, status=3/NOTIMPLEMENTED
systemd[953]: Unit syncthing.service entered failed state.
systemd[953]: syncthing.service failed.
systemd[953]: syncthing.service holdoff time over, scheduling restart.
systemd[953]: Started Syncthing - Open Source Continuous File Synchronization.
systemd[953]: Starting Syncthing - Open Source Continuous File Synchronization...
syncthing[13222]: [LFKUK] INFO: syncthing v0.10.30 (go1.4.2 linux-amd64 default) builduser@jara 2015-03-29 07:46:44 UTC
```
To fix this error we have to add the …
=> systemd: Fix error code definitions to prevent failed units

cmd/syncthing/main.go, cmd/syncthing/main_test.go, internal/config/wrapper.go, internal/model/model.go, internal/model/model_test.go, internal/model/rofolder.go, internal/model/rwfolder.go, test/ignore_test.go
Checks health before accepting every scanner batch, also
recovers from errors without having to restart.
I found it impossible to write tests for stopping between batches, since I cannot really access the walker, nor the channel outside of the Scan method, hence "fingers crossed" it works.
=> More graceful handling on folder errors (fixes #762)

cmd/syncthing/main.go
When executing syncthing with the -reset flag, an incorrect target directory is used.
Was:
```
20:19:58 INFO: Reset: Moving /home/user/Sync -> /home/Sync.syncthing-reset-1427653198358523653
```
should be:
```
20:19:58 INFO: Reset: Moving /home/user/Sync -> /home/user/Sync.syncthing-reset-1427653198358523653
```
=> Fix -reset folder target

internal/model/rwfolder.go, internal/model/sharedpullerstate.go, test/conflict_test.go
Probably I've missed about six hundred corner cases, but this seems to cover the basics... What is expected is that when there are simultaneous edits, one will win (the `ConcurrentGreater` one, i.e. it depends on the device ID:s involved) and be pulled by the other device. That device will notice the conflict and move it's old file to `filename (Syncthing conflicted $date $time).ext` and do the pull as usual. At next scan, the conflicted file will be discovered and synced out to the other devices...
=> Handle conflicts when pulling (fixes #220)

cmd/syncthing/gui.go, cmd/syncthing/gui_csrf.go, cmd/syncthing/locations.go, cmd/syncthing/main.go, cmd/syncthing/monitor.go, cmd/syncthing/tls.go, test/.gitignore, test/cli_test.go, test/conflict_test.go, test/filetype_test.go, test/h2/config.xml, test/httpstress_test.go, test/ignore_test.go, test/manypeers_test.go, test/parallell_scan_test.go, test/reconnect_test.go, test/symlink_test.go, test/sync_test.go, test/transfer-bench_test.go, test/util.go
At some future time, should have a routine to clean up various oldcrap that we'll have accumulated in the user's config dir. This will result in a full rescan, but I don't see an easy way around that since we need to rewrite the format of all entries in the index anyway.
=> Move index to index-v0.11.0.db (new format) and centralize location config

cmd/syncthing/gui.go, cmd/syncthing/main.go, internal/model/model.go, test/reset_test.go, test/syncthingprocess.go
```syncthing -reset``` clears the entire Syncthing DB and restart the program
```/rest/reset``` clears the entire Syncthing DB and restart the program
```/rest/reset&folder=default``` clears the indexes of the 'default' folder
In response to https://github.com/syncthing/syncthing/pull/1562
=> Update reset API to reflect new use cases.

internal/model/model.go, internal/model/rwfolder.go, internal/model/rwfolder_test.go, test/transfer-bench_test.go
This batches database updates, which is a pretty big win on many small files. I added two benchmark tests, one for many (50.000) small files, one for a few (100) large files. It also changes the `LocalIndexUpdated` event to be per commit, not per file (that was pretty expensive for some reason). We already have the `ItemStarted` and `ItemFinished` events per file.
Pre change:
```
$ go test -v -tags "integration benchmark" -run Benchmark
=== RUN TestBenchmarkTransferManyFiles
2015/04/05 15:35:01 Cleaning...
2015/04/05 15:35:01 Generating files...
2015/04/05 15:35:16 Starting sender...
...
2015/04/05 15:40:13 Verifying...
2015/04/05 15:40:16 Sync took 4m38.013740143s
--- PASS: TestBenchmarkTransferManyFiles (314.54s)
```
Post change:
```
$ go test -v -tags "integration benchmark" -run …
```
=> Use separate routine for database updates in puller

internal/beacon/broadcast.go, internal/beacon/multicast.go, internal/discover/discover.go
Moves the interface looping out one level and spins up a multicast beacon per interface.
=> Use a socket per interface for v6 multicast (fixes #1563)

cmd/syncthing/main.go, cmd/syncthing/main_test.go, internal/config/config.go, internal/config/config_test.go, internal/config/wrapper.go, internal/model/model.go, internal/model/model_test.go, internal/model/rwfolder.go
There are many approaches to this... This one works on the assumption that it's safest for most of the code if the change is done as early as possible, i.e. at config loading time, lest we forget some critical  place where a conversion might need to be done. And it also assumes that we should not put the `\\?\` in the config or show it to the user in the GUI, as they may be scared and confused by it. If we think most Windows users are fine with `\\?\` being visible then we can just add it at config loading and not do the dance with RawPath/Path...
I've tested that this starts on Windows and seems to hash files while mentioning paths starting with `\\?\` in the debug output... Some more Windows testing would be nice.
=> Handle long filenames on Windows (fixes #1295)

Godeps/Godeps.json, Godeps/_workspace/src/github.com/calmh/xdr/bench_test.go, Godeps/_workspace/src/github.com/calmh/xdr/bench_xdr_test.go, Godeps/_workspace/src/github.com/calmh/xdr/cmd/genxdr/main.go, Godeps/_workspace/src/github.com/calmh/xdr/encdec_test.go, Godeps/_workspace/src/github.com/calmh/xdr/encdec_xdr_test.go, Godeps/_workspace/src/github.com/calmh/xdr/reader.go, Godeps/_workspace/src/github.com/syncthing/protocol/message_xdr.go, internal/db/leveldb_xdr.go, internal/discover/packets_xdr.go
When reading lengths on the wire we get an uint32 and convert it into an int for `make()` and indexing. This is a problem because sizes larger than 2^31 will become a negative int on 32 bit builds. This can happen when there is a protocol mismatch. This change explicitly checks for sizes less than zero and returns ElementSizeExceeded...
(There's also some unrelated XDR crap because a method changed from private to public and the chart drawing method changed and I forgot to regenerate it...)
=> Update XDR dependency (fixes #1606)

Godeps/Godeps.json, Godeps/_workspace/src/github.com/syncthing/protocol/vector.go, Godeps/_workspace/src/github.com/syncthing/protocol/vector_test.go, Godeps/_workspace/src/github.com/thejerf/suture/pre-commit, internal/model/model.go, internal/model/rwfolder.go, test/conflict_test.go
This make sure(-ish...) that we come up with a new short ID (used in the version vectors) when the index is removed. This we are in conflict, so non-identical files will go through the conflict handling.
=> Index reset should generate file conflicts (fixes #1613)

internal/model/rwfolder.go, internal/osutil/osutil.go, internal/osutil/osutil_test.go
=> Make targets writeable before removal on Windows (fixes #1610)

cmd/syncthing/gui.go
By doing it init(), the monitor process also gets a subscription thing
running, which is unnecessary (and really confused me when seeing it in
the debug output).
=> Don't initialize subscription in init()

cmd/syncthing/main.go
Currently, the release candidates don't auto upgrade because they don't consider themselves a release or a beta.
=> Loosen the requirements on what can be upgraded to what

cmd/syncthing/gui.go, internal/model/model.go, internal/model/model_test.go
Some updates to make the REST JSON nicer, discovered while documenting it. I think this should be the last changes, and nothing super dangerous. The `/rest/db/file` call returned a raw protocol.FileInfo, with capitalized keys. The `/rest/db/need` should have the same keys and format etc. I changed so that we usually return timestamps as timestamps instead of epoch numbers, and formatted flags in octal. The latter is more for human consumption than machine at the moment... so it's the one thing that may be the wrong thing to do :)
=> Clean up REST JSON a little further

internal/events/events.go
This is a large source of output from the new lock logging, and it
doesn't seem to accomplish anything useful that I can see. Running
integration with the race detector to make sure...
=> events.Subscription.Poll does not seem to require locking

cmd/syncthing/audit.go, cmd/syncthing/auditsvc_test.go, cmd/syncthing/locations.go, cmd/syncthing/main.go, cmd/syncthing/monitor.go, test/.gitignore
Fairly simple thing to write the event stream to a file. Writes to timestamped files in the config directory, cleans out those who are over a week old on startup. Do we need advanced rotation and stuff? This was mostly for easier debugging, but it seems like it could be useful in other cases as well possibly.
=> Add audit log feature

internal/upnp/upnp.go
Some routers are sensitive to the capitalization in  "SOAPAction" in the HTTP-header in SOAP request. See issue #1696. This modification follows the recommendation of preserving caps in HTTP-headers in go described on http://stackoverflow.com/questions/26351716/how-to-keep-key-case-sensitive-in-request-header-using-golang?lq=1
=> Fix capitalization in HTTP-header in SOAP request (fixes #1696)

internal/upnp/upnp.go
Some routers do not respond when too many subsequent SOAP-requests are sent directly after eachother and will generate an EOF-error in the call DefaultClient.Do(req). This is the case for instance for Linksys WRT120N. This modification adds a req.Close = True following the description of the problem on http://stackoverflow.com/questions/17714494/golang-http-request-results-in-eof-errors-when-making-multiple-requests-successi
=> Fix to for routers that cannot handle many open HTTP-connections

cmd/syncthing/gui.go, cmd/syncthing/main.go, cmd/syncthing/summarysvc.go
This breaks out the GUI stuff into a separate service, and cleans up the contract between it and the folder summary service a bit. All this "breaking out into a service" stuff is meant to end up with components that can individually restart on config changes and so on...
This intentionally leaves gui.go in a slightly untidy state (methods for one type interspersed among another) because I want to keep the diff down to emphasize what *didn't* change. A separate commit can move things around later.
=> Break out GUI into an API service

internal/osutil/osutil.go, test/util.go
Open issues:
- The integration tests fail on Windows because two folders have a different casing, although they are 100% in sync according to Syncthing
- We should do something extra for case-insensitive filesystems on other platforms as well.
=> Partial fix for #1743

internal/model/model.go, internal/model/rofolder.go, internal/model/rwfolder.go
Without this, when an index update comes in we only do a new pull if the
remote `localVersion` was increased. But it may not be, because the
index is sent alphabetically and the file with the highest local version
may come first. In that case we'll never do a new pull when the rest of
the index comes in, and we'll be stuck in idle but with lots of out of
sync data.
A serious person might write a test for this...
=> Trigger pull check on remote index updates (fixes #1765)

cmd/syncthing/upnpsvc.go
=> Only restart global discovery on UPnP change if it was enabled to start with (fixes #1799)

cmd/syncthing/gui.go, cmd/syncthing/main.go, cmd/syncthing/usage_report.go
Now stops and starts based on config changes directly. It's a two step thing, with a persistent "manager" that listens for config changes and creates or deletes the actual service on demand. I think this is the last "break out *foo* into a service" in preparation of beginning to merge non-restart config changes...
=> Break out usage reporting into a service

AUTHORS, internal/config/config.go, internal/db/leveldb.go, internal/db/namespaced.go, internal/db/set.go, internal/db/virtualmtime.go, internal/db/virtualmtime_test.go, internal/model/model.go, internal/model/rwfolder.go, internal/scanner/walk.go
Fixes #831.
I believe I've addressed all of the issues raised in #1802.
This PR includes #1803.
Note that this patch removes the lenientMtimes option completely, as it's no longer necessary.
=> Implement virtual mtime support for Android

gui/index.html
It does not work with a custom locale.
However, locale support for the `medium` tag works on [Plunker](http://plnkr.co/edit/TdRKA3wg1aKIFZPdvrwo?p=preview), do we use a customized locale feature?
=> Show date and time for web GUI notification (fixes #1833)

internal/upnp/upnp.go, internal/upnp/upnp_test.go
I cannot test this with my network setup, so check this patch carefully.
Moreover, I'm not sure if soapRequest returns an error when permanent leasing is required `if r.StatusCode >= 400 {`
=> Set permanent UPnP lease when required

cmd/syncthing/main.go
I haven't been able to reproduce any performance advantage of having it
set higher and it reduces the memory footprint a bit.
=> Reduce db write cache to (2*) 4 MiB

internal/model/rwfolder.go, internal/model/sharedpullerstate.go
As mentioned in the discussion of issue #1339, you will probably also need the fix for #400 to completely solve this problem for all combinations of ignorePermission settings across servers.
=> Change permissions of newly created files and directories (fixes #1339)

internal/model/model.go, test/transfer-bench_test.go, test/util.go
This adds caching to the `Request()` method so that we avoid loading the full FileInfo from database on each incoming request. There's also some hacking around in the benchmarks to be able to performance test this. Diff is best viewed as [white-space insensitive diff](https://github.com/syncthing/syncthing/pull/1872/files?w=1).
=> Large file transfer

internal/model/rwfolder.go
We introduced the dbUpdater routine to handle many small files
efficiently, but the folder stats call is almost equally expensive as it
results in two distinct write transactions to the database. This moves
it to the same routine.
(Doesn't make a *huge* difference with leveldb actually, but reduces the
50k-files benchmark time by 25% on my experimental bolt branch...)
=> Reduce db writes for small files

cmd/syncthing/verbose.go, internal/events/events.go, internal/model/rwfolder.go, internal/model/sharedpullerstate.go
We forgot to generate ItemFinished when the initial temp file creation failed. This make sure we do, and also we don't need to continue passing it though the chain as there is nothing to close or deregister.
Also fixes the "error" item in the event to be either a `null` or a string (as documented), instead of however the JSON serializer wants to interpret the actual error type we happen to get.
=> Fix ItemFinished

internal/beacon/broadcast.go
Not performing net.InterfaceAddrs() check in the constructor, as that means we wouldn't start
the read loop, which completely kills it.
=> Silence discovery warnings (fixes #1388)

cmd/syncthing/connections.go, cmd/syncthing/debug.go, cmd/syncthing/gui.go, cmd/syncthing/main.go, cmd/syncthing/usage_report.go, internal/config/commit_test.go, internal/config/config.go, internal/config/debug.go, internal/config/wrapper.go, internal/db/blockmap.go, internal/model/model.go, internal/model/model_test.go, internal/model/progressemitter.go
So this is the thing that might lead up to non-restart config changes. This doesn't get there, but lays the groundwork. It's not complete yet, but some comments would be nice. Please check the description for the `Committer` interface at the top of `config/wrapper.go` to see if that makes sense going forward; the rest is basically just plumbing to implement the interface in a couple of places, and the API does attempt restartless config changes just to show it works, kinda...
=> Configuration commit thingy

gui/scripts/syncthing/core/controllers/syncthingController.js
sometimes after restart process syncthing '/rest/db/status' for folder may return data with 'state' = empty string
=> fix disappeared status of folder after restart syncthing

internal/beacon/broadcast.go, internal/discover/discover.go
My theory is that some error condition on the socket results in it
blocking for writes, which maybe also blocks reads... This separates the
two into separate services with their own socket, with restarts and
retries as appropriates on write timeouts and read/write errors. It
should be more robust, hopefully, but I have a hard time testing the
actual error conditions...
=> More resilient broadcast handling (fixes #1907)

cmd/syncthing/locations.go, cmd/syncthing/main.go
If STGUIASSETS is not set, look for assets in $confdir/gui by default.
Simplifies deploying overrides and stuff.
=> Default GUI override dir

internal/model/model.go
Allows correlating LocalIndexUpdate events on one device with RemoteIndexUpdated on another to make sure the cluster has converged.
=> Add version to LocalIndexUpdate event.

gui/scripts/syncthing/core/controllers/syncthingController.js
When adding a new folder, the selected pull order in the dropdown menu is empty. This patch sets it to random, which is the default according to config.go.
=> Set default pull order in webGUI

gui/index.html
Put thisDeviceName first in page tile so browser tabs can be distinguished when there are multiple Syncthing tabs that are small  and chopping off the end of the page title.
=> Put thisDeviceName first in page tile to make small browser tabs distinguishable

internal/model/model.go, internal/model/rofolder.go, internal/model/rwfolder.go, test/sync_test.go
(Not really done yet, PR for integration tests etc)
This does the basically minimal changes to make scans not run in parallell with pulling. There is great cleanup potential with the various "scanFolderBlah" functions that shouldn't really live in model, but in some folder type I think... But that's the next thing.
=> Serialize scans (fixes #1391)

internal/config/config.go
Renaming them puts the user in a difficult situation as they can't
rename them back in the GUI. This way, they need to fix the config in
the same way it got broken (manual editing or external tool).
=> Don't rename duplicate folders (fixes #1675)

gui/index.html, gui/scripts/syncthing/core/filters/groupFilter.js, gui/scripts/syncthing/core/services/filterStabilize.js, gui/scripts/syncthing/core/services/memoize.js
Upgrading to bootstrap 3.3.5 meant that checkboxes inside a div with
column-count:3 set would be unclickable in Chrome: in fact, the entire
div appears to sit on top of its contents, making interaction impossible.
This affected both the 'show folder with these devices' and 'these devices
can access this folder' sections of the UI.
I'm not sure what the the underlying cause is, but moving to Bootstrap's
grid system appears work around the issue. Devices/folders have to be
explicitly split out into rows, otherwise the final element appears offset.
To do this grouping by row, a new filter (groupFilter) has been added, which
turns an input of e.g. [1, 2, 3, 4, 5] with a groupSize of 3 into
[[1, 2, 3], [4, 5]]. However altering the collection in this way throws
Angular into an infinite watch …
=> Use bootstrap grid instead of column-count:3 for aligning checkboxes (fixes #2029)

cmd/syncthing/gui_csrf.go, internal/config/wrapper.go, internal/model/model.go, internal/osutil/atomic.go, internal/osutil/atomic_test.go
This captures the common pattern of writing to a temp file and moving it
to it's real name only if everything went well. It reduces the amount of
code in some places where we do this, but maybe not as much as I
expected because the upgrade thing is still a special snowflake...
=> Add osutil.AtomicWriter

gui/scripts/syncthing/core/controllers/syncthingController.js
#editIgnores can be opened from #editFolder. When a modal is open, the
class modal-open is applied to <body>, which ultimately means that the
browser will scoll to the modal's content. However, #editFolder was
finishing its close animation (and removing this modal-open class)
after #editIgnores had set modal-open (and had started its open
animation). The end result is that <body> ends up without modal-open
when #editIgnores is open, and so the browser doesn't properly scroll.
Instead, only open the #editIgnores once #editFolder has finished closing.
=> Allow #editIgnores to scroll in browser (fixes #2041)

gui/index.html
Prevent double curly brace notation from displaying momentarily before angular.js compiles/interpolates document
=> Double curly brace notation displaying

cmd/syncthing/gui_csrf.go, internal/config/wrapper.go, internal/model/model.go, internal/osutil/atomic.go, internal/osutil/atomic_test.go
This captures the common pattern of writing to a temp file and moving it
to it's real name only if everything went well. It reduces the amount of
code in some places where we do this, but maybe not as much as I
expected because the upgrade thing is still a special snowflake...
=> Add osutil.AtomicWriter (take two)

Godeps/Godeps.json, Godeps/_workspace/src/github.com/syncthing/protocol/conflict_test.go, Godeps/_workspace/src/github.com/syncthing/protocol/message.go, internal/db/leveldb.go, test/conflict_test.go
This modifies the leveldb stuff to send the full file data to `ldbUpdateGlobal`, so that it can make a better decision on which file to promote to "global". If there's a conflict it grabs the data for the conflicting file and uses the new method on `FileInfo` to decide who wins.
The intention is that:
1. Modifications wins over deletes. This means the deleting side sees the file resurrected, but I think that's fine.
2. Newer modification time wins over older
3. Lowest device ID wins (as before)
Actual resolution algo in https://github.com/syncthing/protocol/pull/15
=> Determine conflict winner based on change type and modification time (fixes #1848)

internal/config/config.go, internal/model/model.go, internal/model/model_test.go
This seemed like a fairly simple addition. If configured to ignore deletes, just drop incoming index updates with that bit set. There ought to have been an enhancement ticket for this behavior somewhere, but I can't find it.
=> Optionally ignore remote deletes

gui/scripts/syncthing/app.js
Excuse me in advance for writing a bit of a long story. The source of the error isn't quite obvious so I wanted to explain the szenario in detail. There is a TLDR at the end. of this PR.
So, this error popped up after I extracted the "needed files" modal dialog to a separate component. At first I was wondering why the bug did not pop up earlier. This is most likely due to a "race condition alike" situation. It is caused by the vendor/angular/angular-dirPagination.js component. Usually the directive gets rendered/executed, when window.guiVersion has been initialized by one of the previous requests, whose respose carries 'x-syncthing-version'. angular-dirPagination itself makes use of HTML templates, which are embedded as a JS string and stored into angulars $templateCache. This is a very …
=> fix(core): prevent endless reload on cache requests

gui/index.html
github is taking over;)
(I did not regenerate the assets because of https://github.com/syncthing/syncthing/pull/2108)
=> Update credits for dependencies (fixes #2082)

gui/index.html, gui/syncthing/device/editDeviceModalView.html, gui/syncthing/folder/editFolderModalView.html
I've carefully checked https://github.com/syncthing/syncthing/pull/1954 for further regressions and this patch reverts some remaining small changes. I don't see why `editingSelf` was added.
=> Revert small changes made during reorg GUI

cmd/syncthing/main.go, lib/osutil/rlimit_unix.go, lib/osutil/rlimit_windows.go
This will decrease the risk of running out of file descriptors for the database and other bad things, which could otherwise potentially happen if we're serving lots of requests and scanning in parallel, etc.
Windows doesn't have a per process open file limit like Unix so we don't need to worry about it there.
=> Increase open file (fd) limit if possible

lib/versioner/staggered.go
The title of https://github.com/syncthing/syncthing/issues/2165 is not that appropriate, but there is no separate issue for the bug itself ;)
https://github.com/syncthing/syncthing/pull/2171 works also when time zone is UTC-x which it does not without the fix.
=> Fix time zone error in staggered versioning (fixes #2165)

.gitignore, build.go, cmd/stsigtool/main.go, lib/signature/signature.go, lib/signature/signature_test.go, lib/upgrade/signingkey.go, lib/upgrade/upgrade_supported.go
This fixes something that's not really super serious but has been nagging me for a while. We use to download upgrades securely from GitHub and then just quickly verify an MD5 to see that the file wasn't a partial download or something. However this fails when the client can't verify the GitHub/S3 certificates (bad or missing CA roots, it happens) and doesn't protect against someone compromising our GitHub account or having it man-in-the-middled (corporate proxy for example). It also doesn't help at all if upgrades are loaded from some some other insecure source.
So this replaces the md5 check with a full ECDSA signature check. The build script can take a private key when building the archive as `go run build.go -sign ~/syncthing.priv tar` and will then include a `syncthing.sig` file with …
=> Use signed releases for automatic upgrade

cmd/syncthing/connections.go, cmd/syncthing/connections_tcp.go, lib/model/connection.go, lib/model/model_test.go, lib/relay/relay.go
I'm picking through the relay code in order to fully understand it and made some changes along the way that makes sense to me... Basically,
- Rename Basic connections to Direct to better match IsDirect and how I think about the whole thing... :)
- Tweak the field names of IntermediateConnection
- Remove some unused stuff and simplify the start/stop code on relay.Svc
I think these should be safe. Relaying seems to work still. :)
=> Small refactorings on relay

cmd/syncthing/gui.go
This is feature request and PR at once, related to <a href="https://forum.syncthing.net/t/issue-with-syncthing-gtk-on-reconnecting-to-network/5388">problem with handling sleeping / hibernation</a> in ST-GTK.
To put it simple, it is possible to Syncthing daemon to restart without Syncthing-GTK noticing, for example, when restart is handled by service manager and ST-GTK lags after PC is resuming from hibernation.
Currently only way how to detect such restart is by detecting event ids going backwards. But that has proven pretty-much impossible with HTTP implementation I'm using, as Syncthing timeouting request with no events and system timeouting request because Syncthing is not there anymore looks the same. Also, requesting event with high ID from freshly restarted Syncthing will simply …
=> Feature request: startTime in system/status

lib/config/config.go, lib/config/config_test.go, test/h2/config.xml
Note that I added this to the existinvg 11-to-12 migration, as we haven't made a release with config version 12 yet. Developers will need to fix up manually.
=> Local discovery should use the same port on v4 as v6 (fixes #2201)

lib/beacon/multicast.go
This makes it possible to run multiple instances on the same box, all
receiving local discovery packets. Tested on Mac, Windows, supposed to
work on at least Linux too. For Windows, there may be issues with XP and
earlier, but meh...
=> Bind to IPv6 multicast group instead of ::

lib/fnmatch/fnmatch.go, lib/fnmatch/fnmatch_test.go, lib/ignore/ignore.go, test/ignore_test.go
Rewritten so that fnmatch doesn't need to know or care about (?i) at all, as it gets a flagset anyway.
=> Correctly handle (?i) in ignores (fixes #1953)

lib/discover/discover.go, lib/osutil/ping.go, lib/relay/relay.go
This is getting a bit annoying.
Ideally the relay struct and all the utility functions should live in the relay package together with the utility functions, but XDR generation cannot generate stuff across packages.
Alternatively, we could have  the type defined twice, also a RelayList type which has .FromStrings([]string), and maybe .ToDiscoveryRelaySlice()
=> Pick a single relay (fixes #2182)

NICKS
Since my amount of received emails increased over the time, I would like
to separate my private email address from my "community email address".
=> Add my "community email address" to NICKS

cmd/syncthing/main.go, lib/config/config.go
Allows things like this in the `<options>` element:
```
<alwaysLocalNet>10.0.0.0/8</alwaysLocalNet>
```
=> Add custom networks that are considered local (internal routing, VPN etc)

cmd/stfinddevice/main.go, cmd/syncthing/connections.go, cmd/syncthing/externaladdr.go, cmd/syncthing/gui.go, cmd/syncthing/main.go, cmd/syncthing/upnpsvc.go, lib/discover/client_udp.go, lib/discover/discover.go, lib/discover/discover_test.go, lib/events/events.go
This adds a thing that provides a list of external addresses, similar to how the relay service provides a list of active relays. It's passed to the discovery thing and used to build the discovery packet. The reason I want this is that I want to be able to pass this thing to both the local discovery package and the soon to be created global discovery package. I envision that as a separate package to the local discovery one as I don't see it sharing any mechanisms once we move to the TLS based discovery (as I think we agreed to do, sort of).
(I see that discovery as doing an HTTPS POST with our certificate to announce, and HTTPS GET (without providing our certificate, as it's not necessary) for lookups.)
(Both the local and global discovery packages/services would implement some simple …
=> Add external address tracker object

cmd/syncthing/connections.go, cmd/syncthing/main.go, lib/relay/relay.go
This makes it so we can initialize the relay management and then give
that to the connection management, instead of the other way around.
This is important to me in the discovery revamp I'm doing, as otherwise
I get a circular dependency when constructing stuff, with relaying
depending on connection, connection depending on discovery, and
discovery depending on relaying.
With this fixed, discovery will depend on relaying, and connection will
depend on both discovery and relaying.
=> Invert initialization dependence on relay/conns

lib/discover/local.go, lib/discover/localpackets.go, lib/discover/localpackets_xdr.go
The XDR encoder doesn't understart slices of strings very well. It can
encode and decode them, but there's no way to set limits on the length
of the strings themselves (only on the length of the slice), and the
generated diagrams are incorrect. This trivially works around this,
while also documenting what the string actually is (a URL).
=> Encapsulate local discovery address in struct

etc/linux-systemd/system/syncthing@.service, etc/linux-systemd/user/syncthing.service
This patch adds syncthing-inotify.service as an optional dependency to
syncthing.service. That means, if syncthing-inotify.service is
available, it is started and stopped with syncthing.
See discussion here:
https://forum.syncthing.net/t/gnome-shell-extension-syncthing-icon/5759
=> Pull syncthing-inotify.service as an optional dep

cmd/syncthing/main.go, lib/connections/connections.go, lib/connections/connections_tcp.go, lib/connections/debug.go, lib/connections/limitedreader.go, lib/connections/limitedwriter.go
The connections service no longer depends directly on the
syncthing model object, but on an interface instead. This
makes it drastically easier to write clients that handle
the model differently, but still want to benefit from
existing and future connections changes in the core.
This was motivated by burkemw3's interest in creating a
FUSE client that can present a view of the global model,
but not have all of the file data locally.
The actual decoupling was done by adding a
ConnectionHandlingModel interface. This interface is an
extension of the protocol.Model interface that also
handles connections alongside the modified service.
There were a few dependencies in connections.go to
work through.
In a couple instances, connections.go was using variables
in the main package. Since it moved …
=> Decouple connections service from model

README.md
I just wanted to add the freenode webchat link, because people who are
not used to irc can join the chatroom instantly. I tried to clean up the
markdown file a bit and moved the links to the footer; that makes the
"source code" less ugly.
In the end I am not sure what's nicer; either having these ugly inline links or shifting link id numbers when inserting a new link in the middle... I just leave this worldshaking work here, because it is better than reverting everything again and just add the freenode link. :dancer:
=> Cleanup markdown inline link mess

lib/ignore/ignore.go, lib/model/model.go
An error on opening .stignore will satisfy os.IsNotExist() and not be
reported. Other errors will be reported and stop the folder, including
is-not-exist errors from #include as these are passed through fmt.Errorf.
Also fixes minor issue where we would not print cause of folder stopping
to the log.
Also fixes minor issue with capitalization of errors.
=> Correctly report errors encountered parsing ignores (fixes #2309)

lib/model/model.go, lib/osutil/osutil.go, lib/osutil/osutil_test.go
This is part one in a series of attempts to solve the "case insensitive renames break stuff" problem. This handles *files* renamed from `foo` to `Foo`, but not directories. Basically it makes the scanner case sensitive always, so that it picks up on the change. The puller sees it as a rename and does the right thing (there might be an issue if the contents change as well).
For directories it's not that easy, as the puller (in the case of a "normal" directory rename) wants to create the new directory and move the files over there. But we can't do that, because the existing variant of the directory is in the way and makes it look like we don't need to, and then we detect it as missing due to the case sensitive scanner... Tricky business.
=> Case insensitive renames, part 1

cmd/syncthing/main.go, lib/discover/cache.go, lib/discover/cache_test.go
Sources are given a priority, lower being better, when added to a
CachingMux.
=> Add discovery source priorities (fixes #2339)

lib/model/sharedpullerstate.go
This is a workaround / incorrect fix for a bug that's bit me enough in production for me to want to do something about it... I'm open for suggestions for better ways to handle it. Basically it solves the situation where the puller is eternally stuck in
```
INFO: Puller (folder "default", file "foo/bar"): dst stat dir: stat /home/jb/Sync/foo: no such file or directory
```
The only way to fix this manually is otherwise to create the directories it's complaining about, which may be hundreds spread out in a deep hierarchy... (This typically happens when someone drops something large into the sync folder, then realizes their mistake and immediately removes it.)
And yes, we should handle that better somehow...
=> Create missing directories

lib/config/config.go, lib/config/config_test.go
Just incase we want to show some stats in the future, such as a Geo-IP based map of where relays are, their dot size being proportional to global rate limits,
together with potentially how much data in total has been transferred, and how many sessions there by crawling relay status pages etc ;)
Changes already done in relaysrv and relaypoolsrv.
=> Change relaypoolsrv endpoint

lib/model/model.go
Here's another potentially controversial one. Not doing a db lookup of requests cuts about 20% of RAM usage (total process size) when serving lots of small files, more if the files are larger probably. Even with our fancy and complicated request validation cache stuff in place.
I've added checks to verify that:
- the requested file is inside the folder
- that it's not being ignored
We lose checks for requests to get:
- deleted files. Who cares? if the file exists, we are obviously out of sync with reality.
- invalid files. I always viewed the invalid bit as advisory ("don't ask me about this file, because I'm not really sure what it contains").
Am I missing some security concern here?
=> Don't validate requests against the database

cmd/syncthing/main.go, cmd/syncthing/main_test.go, lib/model/model.go, lib/model/model_test.go, lib/model/rwfolder_test.go
Overwriting configuration files is likely to happen if a
user syncs their home directories across computers. In this
case, the biggest risk is that all nodes will end up with
the same certificate and thus Device ID.
When the model prepares a folder for syncing, it checks to
see if the configuration files this instance is using are
getting synced. If the are getting synced, and they aren't
getting ignored, a warning is emitted.
This will not prevent a user from shooting themselves in
the foot, and will not cover all cases (e.g. symlinks).
It should provide _something_ for many users in this
situation to go on, though.
=> Emit warning when sync could overwrite configuration

lib/db/leveldb.go, lib/db/set.go, lib/db/set_test.go, lib/model/model.go
This keeps LocalSize and Global in RAM for instant querying, saving us having to walk the database to get it. Speeds up the GUI and so on.
=> Keep LocalSize & GlobalSize data in RAM

lib/db/truncated.go, lib/protocol/message.go
Here's one more. Speeds up and reduces allocations on those operations, at the price of
having a manually tweaked XDR decoder for FileInfoTruncated.
```
benchmark                         old ns/op      new ns/op      delta
BenchmarkReplaceAll-8             1868198122     1880206886     +0.64%
BenchmarkUpdateOneChanged-8       231852         172695         -25.51%
BenchmarkUpdateOneUnchanged-8     230624         179341         -22.24%
BenchmarkNeedHalf-8               104601744      109461427      +4.65%
BenchmarkHave-8                   29102480       34105026       +17.19%
BenchmarkGlobal-8                 150547687      172778045      +14.77%
BenchmarkNeedHalfTruncated-8      102471355      76564986       -25.28%
BenchmarkHaveTruncated-8          28758368       14277481       -50.35% …
```
=> Don't load block list in ...Truncated methods

lib/relay/client/client.go, lib/relay/client/dynamic.go, lib/relay/client/methods.go, lib/relay/client/static.go, lib/relay/relay.go
Did some manual tests in the playground, such as kicking off two clients in parallel, first connecting,
second one getting a message about already being connected, falling back to the second address.
=> Add separate client for dynamic relays (fixes #2368)

cmd/syncthing/main.go
'AlwaysLocalNets' was getting printed, but was getting used
when setting up connections. Now, the nets that should be
considered local are printed and used.
=> Consider 'AlwaysLocalNets' in bandwidth limiters

AUTHORS, etc/linux-upstart/README.md, etc/linux-upstart/system/syncthing.conf, etc/linux-upstart/user/syncthing.conf
Added documentation and examples for Ubuntu-like linux systems using Upstart as the init system in response to syncthing/syncthing#2315.
=> Documentation and examples for autostarting with Upstart

lib/scanner/.gitignore, lib/scanner/blocks.go, lib/scanner/walk_test.go
By using copyBuffer we avoid a buffer allocation for each block we hash, and by allocating space for the hashes up front we get one large backing array instead of a small one for each block. For a 17 MiB file this makes quite a difference in the amount of memory allocated:
benchmark               old ns/op     new ns/op     delta
BenchmarkHashFile-8     102045110     100459158     -1.55%
benchmark               old allocs     new allocs     delta
BenchmarkHashFile-8     415            144            -65.30%
benchmark               old bytes     new bytes     delta
BenchmarkHashFile-8     4504296       48104         -98.93%
=> Reduce allocations in HashFile

lib/db/leveldb.go, lib/db/set.go
This moves the `ldb*` functions into being methods on `dbInstance` and transaction objects. The win here right now is just that it's a little neater. However I have a plan for some optimizations that will require us keeping a small amount of in memory state on the database, and this gives us some place to store that...
The methods can be reorganized for a better order and split into separate files maybe, but I opted to keep the diff easy to read for now and can do that in a separate move-around commit later.
=> Add database and transaction instances

cmd/syncthing/monitor.go
I don't think this is *too* nasty... This enables renaming the log file for rotation, and within at most a minute we'll reopen a new file at the specified name.
We don't do any magic locking, so theoretically this should work on Windows too, although doing log rotation there is left as an exercise for the reader... Just doing nothing results in same behavior as we have right now.
=> Enable log rotation by automatically closing log file (fixes #2251)

cmd/syncthing/gui.go, lib/config/config.go
I see no reason not to do this, and it gives a unified place (the prepare()
call) to initialize cached attributes and so on.
=> Run JSON decoding through the usual setting of defaults and fixing up

lib/config/config.go, lib/config/config_test.go, lib/config/folderconfiguration.go
The Path() call is quite expensive as it does a lot of string splits and joins, and ends up being responsible for a sizable percentage of the allocations done in Request() since it's called there every time.
We can't actually *cache* it because the FolderConfig is copied everywhere, so we populate the cachedPath field on deserialization. That leaves stuff that creates the object from scratch, which is basically the tests, using the slow method.
=> Cache the folderconfig Path() call

cmd/syncthing/usage_report.go, lib/config/config.go, lib/config/wrapper.go
To get green indicators without v6 (or without v4, but at least today this is rare...) without manually configuring all servers (and breaking stuff on changes to the discovery servers like today :laughing: )
=> Add default-v4 and default-v6 as options for discovery

lib/model/model.go
Related to https://github.com/syncthing/syncthing-android/issues/473 and https://github.com/syncthing/syncthing/commit/944d9c84a087f70d0ab5c281b7c37fcc9c796ccd
ConnectionStats returns connection information for all devices, even when disconnected.
=> Correct commentary for ConnectionStats

cmd/syncthing/gui.go
This adds some stuff to track calls to the /rest interface, as we're anyway carrying around the metrics package now. It gives this kind of data on the /rest/debug/httpmetrics endpoint:
```
{
"/rest/db/completion": {
"count": 4,      // number of times this path has been called since startup
"percentilesMs": [
4.146201,   // 50th, 95th and 99th percentile response times
6.278776,
6.278776
],
"ratesPerS": [
0.11767717391438157, // 1 minute, 5 minute and 15 minute call rates per second
0.5452685329550784,
0.7040391390753369
],
"sumMs": 17  // total number of ms we've spent in this method since startup
},
"/rest/db/status": {
"count": 3,
"percentilesMs": [
0.776,
1.013,
1.013
],
"ratesPerS": [
0.0882578804357862,
0.40895139971630884,
0.5280293543065027
],
"sumMs": 2
},
...
```
Actually using …
=> Add metrics for HTTP calls

lib/config/folderconfiguration.go, lib/model/rwfolder.go, lib/model/sharedpullerstate.go, lib/protocol/message.go, lib/rc/rc.go, test/sync_test.go
This implements sparse file support. It does this by
- Using `Truncate()` on the temp file to set it to the final size immediately. On NTFS and Unixes this creates a sparse file; on Mac it's just a large file full of zeroes.
- Not transferring / copying full blocks of zeroes, as these are already present in the file. The exception is if we're reusing a temp file, which might not have zeroes in the right place.
End result is that we don't transfer full blocks of zeroes and may or may not create a sparse file on the destination depending on the filesystem in use. It also means we automatically sparsify existing files when transferring them (again, when supported by the fs).
Blocks of all zeroes that are not exactly BlockSize-sized are not handled specially, so the last block of zeroes in a …
=> Handle sparse files (fixes #245)

lib/upgrade/upgrade_common.go, lib/upgrade/upgrade_supported.go
This allows me to see errors like:
```
[F2C6I] 17:05:32 INFO: Couldn't query Github:  Get https:/
/api.github.com/repos/syncthing/syncthing/releases?per_page=30: x509: failed to 
load system roots and no roots provided```
```
On my FreeNAS (minimal FreeBSD) installation rather than the ambiguous ```Automatic upgrade: couldn't fetch release information``` (which could be caused by two different cases in ```SelectLatestRelease```).
=> Log problems fetching releases

lib/model/sharedpullerstate.go
Because for dirs Size() returns 128.
=> Fix symlinks (fixes #2524)

lib/osutil/atomic.go
I haven't touched Go before so though this would be a simple fix.
Turns out I am having trouble getting it to compile and run on android so I thought Zillode  or Nutomic could check if I made a ridiculous mistake.
=> Don't chmod in Atomic on android (fixes  #2472)

lib/discover/cache.go, lib/discover/discover.go, lib/discover/global.go
This is a second alternative to #2543
=> Accept Retry-After header on discovery lookup failures

lib/relay/client/static.go
The first handshake occurred before setting the Deadline, which could
cause an unintended hang.
=> staticClient.connect(): don't handshake twice (fixes #2547, #2548)

build.go, cmd/syncthing/main.go, cmd/syncthing/usage_report.go, lib/config/config.go
Also fixes what I think migh thave been a bug where we did not use the
proxy for usage reports. And removes the BuildEnv field that we don't
need any more.
=> Remove Android hacks (fixes #2505)

lib/upnp/upnp.go
Previously, when unmarshing the SOAP error code data we would overwrite
the original err, typically with null since the parsing of the error
code information succeeds. If we don't have a upnp 725 error, we would fall
back to returning null or no error. This broke our upnp error handling
logic for AddPortMappings as it would think it succeeds if it gets a 718
permission error.
=> upnp: Use a separate error for the error unmarshalling

etc/linux-systemd/system/syncthing@.service, etc/linux-systemd/user/syncthing.service
PR #2578 enables us to remove the exit code 2 from the list of
success status codes, because SIGINT will be handled properly.
I have also converted STNORESTART to --no-restart for the sake
of consistency.
=> systemd: Remove exit code 2, due to #2578

cmd/syncthing/main.go
While addressing other features, I noticed the main() function was growing too big and a few minor edge cases not being handled, so this refactors it a little bit in favor of more focused functions.
=> Refactor main.go

cmd/syncthing/main.go
--browser-only assumes syncthing is already running and will open the
user's browser in the URL:port currently used in the configuration if
the GUI is enabled.
=> Add command line option to open GUI (fixes #2210)

lib/config/guiconfiguration.go
I feel this is more like the expected behaviour.
=> Only override TLS settings if scheme is specified

cmd/syncthing/main.go, cmd/syncthing/monitor.go
This is a first step towards getting rid of the global variables currently in use (plus some minor improvements along the way). The remaining globals will take quite a bit of refactoring, so they will have to be addressed in later commits.
=> Remove some global variables from main.go

cmd/syncthing/main.go
I'm not really sure under what circumstances MkdirAll returns a nil
error but a subsequent stat fails, but apparently it can happen and we
need to handle it. The "mode >= 0" was a no-op, and we never call
ensureDir anyway without the intention of ensuring the mode, so removed
that.
=> Don't crash on stat error in ensureDir (fixes #2608)

cmd/syncthing/gui.go
This makes the output of version vectors easier to understand, by encoding the ID as the first character group of the device ID. I.e.
```json
"global": {
"flags": "0644",
"localVersion": 673634,
"modified": "2015-12-21T14:48:28+01:00",
"name": "Lightroom Catalog.lrcat",
"numBlocks": 6105,
"size": 800092160,
"version": [
"9186365928295258957:48",
"16401037966434831212:1",
"17926325417065620423:104",
"18446744073709551615:1"
]
},
```
becomes
```json
"global": {
"flags": "0644",
"localVersion": 673634,
"modified": "2015-12-21T14:48:28+01:00",
"name": "Lightroom Catalog.lrcat",
"numBlocks": 6105,
"size": 800092160,
"version": [
"P56IOI7:48",
"4OODCIS:1",
"7DDRT7J:104",
"7777777:1"
]
},
```
which I think makes everyone happier. I also don't think we've ever advertised it as anything other than …
=> Humanize serialization of version vectors

cmd/syncthing/main.go
This gets rid of redundant checks and centralizes the logic of loading
the config files so that we don't have to keep doing the same thing in
multiple places.
=> Centralize config loading logic (also fixes #2509)

lib/config/config.go, lib/config/config_test.go, lib/config/testdata/duplicates.xml
We pick the first one and keep that.
=> Ensure loaded config is free of duplicate devices (fixes #2627)

lib/model/model.go, lib/protocol/hashalgorithm.go, lib/protocol/hashalgorithm_test.go, lib/protocol/protocol.go
This implements the changed part of the protocol spec in that it interprets the hash algorithm bits in the ClusterConfig message. These must currently always be zero (SHA256), otherwise the folder is stopped with an "unknown hash algorithm from [some device id]" error.
Moves the FolderRejected event from the index message to the clusterconfig message as we now actually look through the folder list there.
=> Detect nonstandard hash algo and stop folder (ref #2314)

gui/syncthing/core/syncthingController.js
This changes the default in the GUI for max conflicts from unlimited to ten. Old configs still convert to unlimited (as that was the old behavior), and existing config values aren't touched.
=> Change default max conflicts to 10 (fixes #2604)

lib/model/rwfolder.go
Skip conflict handling for conflict files, and log it at info level. No test for this, but I'll have one in my new puller implementation I promise...
=> Don't conflict copy conflict copies (fixes #2605)

cmd/syncthing/gui_csrf.go, cmd/syncthing/gui_test.go
Prior to this change, we generate a new CSRF token in response to every GET request that doesn't have one already, and we keep the 10 last tokens we generated. A problem with this is that a new browser visit generates at least one, sometimes several, requests that result in new tokens. This means that a GUI that is left running gets its token revoked after ten visits by other browsers, or sometimes much less (at least Safari generates GET for / and /apple-touch-icon-precomposed.png simultaneously, thus consuming two tokens).
This causes things like config POSTs that don't "take" and so on.
With this change, we keep a few more tokens around, and we reorder the list based on usage. So a browser session that is alive gets its token moved to the head of the list on each request, thus ensuring …
=> Don't allow in use CSRF tokens to expire (fixes #1008)

lib/connections/connections_tcp.go
This ensures (if it works) that we pass the actual configured name to a SOCKS proxy, thus enabling dialing stuff like horriblename.onion:22000 for those who like Tor etc.
=> Don't unnecessary resolve destination address

lib/model/model.go, lib/model/model_test.go, lib/protocol/protocol.go, lib/protocol/protocol_test.go, lib/protocol/wireformat.go
Adds a Closed() method on protocol.Connection and clears up
wireformatConnection a little too.
=> Don't leak sendIndexes on disconnect (fixes #2589)

lib/model/model.go, lib/model/rwfolder.go
This isn't exactly squeaky clean, but much of this code is already marked for deletion, so... It handles the symtom, in that we don't try to perform operations on a nil fileset after the folder has been removed, and stops handling pulling operations a bit quicker when the folder has been removed.
This really needs some automated testing but I'm not sure where to add it currently; writing an integration test for this scenario is rather cumbersome and a bit error prone.
=> Don't crash on folder remove while pulling (fixes #2705)

cmd/syncthing/main.go, lib/logger/logger.go, lib/logger/logger_test.go, lib/model/model.go
I think I imagined it as a sort of anti-Fatal from the beginning, as the last output when we did something successfully and then exited. But we don't do that and the distinction seems unnecessary to keep around. Fewer levels is simpler.
=> The "OK" log level is silly and should not exist

lib/model/model.go
I've verified that this does what's expected by running syncthing under ```strace -f -e trace=lstat``` and calling variations of ```curl -X POST "http://127.0.0.1:44644/rest/db/scan?folder=default&sub=02&sub=03&next=9600"```. I'm not sure how 9b9fe0d6 was supposed to work; perhaps something changed since the time it was introduced, or perhaps I've overlooked something. I'm pretty sure the relevant integration tests in ```test/scan_test.go``` will be broken because of my changes, but I currently don't know how to run them.
=> rest/db/scan: Only scan the requested subdirectories/files.

debian/postinst
According to http://linux.die.net/man/1/pkill the signal name must be **before** anything else.
This fix has to be confirmed first by anyone else. I am on debian testing now and there is a newer version which is not affected by the problem; see #2728 .
=> Correct order of pkill(1) arguments in debian script (fixes #2728)

cmd/syncthing/gui.go
```
jb@syno:~/s/g/s/syncthing $ curl -X POST -i http://localhost:8385/rest/system/config
HTTP/1.1 307 Temporary Redirect
Location: https://localhost:8385/rest/system/config
Date: Fri, 29 Jan 2016 10:09:16 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```
=> Return status code 307 instead of 302 when redirecting from HTTP to HTTPS

AUTHORS, NICKS, gui/default/syncthing/core/syncthingController.js
Invalid ng-model value is assigned `null` by angular.js which is being matched as `object`, thus disappear in the UI when a minus sign is entered.
=> Handle null case for invalid ng-model value (fixes #2392)

cmd/syncthing/main.go
```
jb@syno:~/s/g/s/syncthing $ syncthing -paths
Configuration file:
/Users/jb/Library/Application Support/Syncthing/config.xml
Database directory:
/Users/jb/Library/Application Support/Syncthing/index-v0.13.0.db
Device private key & certificate files:
/Users/jb/Library/Application Support/Syncthing/key.pem
/Users/jb/Library/Application Support/Syncthing/cert.pem
HTTPS private key & certificate files:
/Users/jb/Library/Application Support/Syncthing/https-key.pem
/Users/jb/Library/Application Support/Syncthing/https-cert.pem
Log file:
/Users/jb/Library/Application Support/Syncthing/syncthing.log
GUI override directory:
/Users/jb/Library/Application Support/Syncthing/gui
Default sync folder directory:
/Users/jb/Sync
```
=> Add -paths option to print config, key, database paths

cmd/syncthing/gui.go
Better than the confusing result of getting a blank fileinfo that looks
valid apart from being all crap.
=> Return "No such object in the index" when /rest/db/file gets called on something that doesn't exist

cmd/syncthing/gui.go
While performing additional testing on CORS with browsers (Chrome/Firefox), I have spotted an issue with the current order of the middleware (CSRF and CORS). During a [pre-flight request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests), the X-API-Key header is not sent which cause the `csrfMiddleware` to perform a redirect. As a result, the pre-flight request fails.
By swapping the corsMiddleware and the csrfMiddleware, the OPTIONS requests are first processed before any security checks.
=> Move CORS middleware to process un-authenticated OPTIONS requests

etc/linux-systemd/system/syncthing-resume.service
This systemd service restarts Syncthing after resume from suspend via sending SIGHUP. By default Syncthing detects resume from sleep on its own by looking for jumps in the system clock. Since systemd knows exactly when the system resumes from sleep let's trigger the Syncthing restart from there. Doing this in systemd eliminates some annoying delay, as the service is restarted immediately after resume. Also, using the systemd dependency mechanism syncthing-inotify is restarted as well.
```
$ journalctl -e --identifier syncthing --identifier syncthing-inotify --identifier systemd
Feb 22 09:44:27 kronos systemd[1]: Reached target Sleep.
Feb 22 09:44:27 kronos systemd[1]: Starting Suspend...
Feb 22 09:44:33 kronos systemd[1]: Time has been changed
Feb 22 09:44:33 kronos systemd[963]: Time has …
```
=> systemd: Add syncthing-resume.service

PULL_REQUEST_TEMPLATE.md
People want to add themselves to AUTHORS. That's fine, but it's not enough as it also needs to be added to NICKS and script/authors.go needs to be run. I'd rather have us do this and do it correctly so lets document that people should not worry about it.
The paragraph is a bit long winded and there is a risk it will not get read. Suggestions to make it less verbose while conveying the same intent are welcome.
=> Update pull request template with authorship info

cmd/syncthing/gui.go
If we pass an invalid object to sendJSON, it'll silently write an empty 200 response. With this change we should return a 500 with an `{"error": "something"}` in it instead. I think.
None whatsoever as I can't reproduce an error here right now. Lets have canton7 see if he can get something from this in #2854 before merging.
=> cmd/syncthing: Return 500 with an error object instead of empty 200 on marshalling error in REST response

lib/ignore/ignore.go, lib/ignore/ignore_test.go
Actual speed difference according to benchmarks is hidden in the noise
Also make the "pattern" field for each entry match what is actually
evaluated, or it looks like we have duplicates in the `expanded` JSON field.
Those unit tests, they rock.
=> lib/ignore: Remove pattern for foo/** which is already covered by foo/

cmd/syncthing/gui_windows.go
No idea under what conditions this happens, but it does as far as we can see from debugging.
=> cmd/syncthing: Skip a calculation if timediff is zero (fixes #2854)

lib/config/config.go, lib/config/config_test.go, lib/config/optionsconfiguration.go, lib/config/testdata/v13.xml, lib/upgrade/upgrade_supported.go
Bring v0.12 branch up to date with reality and enable future upgrades.
We'll have to rework v0.13 to bump the config format to 14, but that's no issue.
**Do not merge with st-review!** It'll probably merge to master and fuck up. Use the button.
=> lib/config: Update size constraints and URL (ref #3086)

lib/fs/debug.go, lib/fs/filesystem.go
This adds a new debug facility "walkfs" which does the same thing as "fs", but it also applies to operations when walking a filesystem. I added this unconditionally on another PR for debugging, but it doesn't really belong there, so lets discuss/decide here (original comments: https://github.com/syncthing/syncthing/pull/4584/files#r156240587).
=> lib/fs: Introduce walkfs debug facility

gui/default/syncthing/core/syncthingController.js, gui/default/syncthing/folder/editFolderModalView.html, lib/versioner/external.go
Substitute '\\' with '/' in paths in External File Versionining (fixes #4560). Spaces are handled correctly. When the variable is read in back-end (Go file), the '\\' is already parsed, hence substitution is done in front-end.
Edit: I was wrong, we can see unparsed input in .go file as well
I've just changed path separator from Windows-style to Linux-style. Both separators work well on Windows, so there is no need to test.
Previously documentation didn't work, now it will.
=> Substitute '\' with '/' in paths in External File Versionining (fixes #4560)

gui/default/vendor/fancytree/LICENSE, gui/default/vendor/moment/LICENSE
I even included a screenshot.
Add missing vendor licenses so that the following MIT License condition is respected:
> The above copyright notice and this permission notice shall be
> included in all copies or substantial portions of the Software.
I have looked at the license file and confirmed that it exists and that it present.
=> add missing vendor licenses

lib/scanner/walk.go
Do not panic.
Yeah, that's the thing. @imsodin I don't understand the error handling here. What does the thing above my code do, exactly (the thing with `path == "."`)? If I attempt to homogenize it with the regular error handling, in returning `sendErr` for example, tests fail. Why?
=> lib/scanner: Error handling in walk function (fixes #4753)

lib/db/meta.go
So, negative counts should never happen and hence the original idea to
panic. However, this sucks as the panic will happen in a folder runner,
be automatically swallowed by suture, and the runner gets restarted but
now we are in a bad state. (Related: #4758)
At the time of writing the global list is somewhat in flux (we've
changed how ignored files are handled, invalid bits, etc.) and I think
that can cause unusual conditions here. Hence just fixing up the numbers
instead until the next full recount interval.
=> lib/db: Don't panic on negative counts

lib/fs/basicfs.go, lib/fs/basicfs_unix.go, lib/fs/basicfs_windows.go
https://forum.syncthing.net/t/error-when-sync-dest-to-nonexistant-root-directory-on-windows/11277/18  
Main purpose of this PR for now is to provide diffs/builds for testing to @wwutz that actually compile on windows (anyone else interested is obviously also welcome to test).
To reproduce run the following while `F:\FOO` does not exist:
```golang
package main
import (
"fmt"
"github.com/syncthing/syncthing/lib/fs"
)
func main() {
base := `F:\`
targ := `FOO\BAR`
testFs := fs.NewFilesystem(fs.FilesystemTypeBasic, base)
if err := testFs.MkdirAll(targ, 777); err != nil {
fmt.Printf("Base: %v, target: %v, err: %v", base, targ, err)
}
}
```
Result:  
`Base: F:\, target: FOO\BAR, err: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.`
@calmh Am I right assuming that a …
=> lib/fs: Fix MkdirAll failure due to \\?\

cmd/strelaysrv/main.go, cmd/strelaysrv/pool.go
Fix what used to work but now doesn't.
None whatsoever. @wwwutz?
=> cmd/strelaysrv: Don't patch the default HTTP client (fixes #4745)

lib/model/rwfolder.go
This doesn't happen today, but it might in the future if the block size were increased or made variable and we were talking to a client from the future...
=> lib/model: Don't panic if block size in index is larger than protocol block size

lib/model/model.go, lib/model/model_test.go, lib/osutil/osutil.go
This fixes the same issues as #4584 but without the combined db/fs scan. The basic idea is to only mark files as deleted, if we really are sure they are deleted. I.e. only if the lstat error is `IsNotExist` or a parent is a link/file.
=> lib/model: More precise deletion detection (fixes #2571, fixes #4573)

lib/model/model.go
This change should have been in #4750, but depended on #4765, that's why it now gets its own minuscule PR.
=> lib/model: Mark deleted file as conflicting when un-ignoring

cmd/syncthing/main.go, lib/db/leveldb.go
This was necessary for me to get everything to play nice after imsodins latest changes, and I think we might as well throw it in there as part of this release.
=> cmd/syncthing: Reset delta indexes after the latest index changes

gui/default/syncthing/transfer/remoteNeededFilesModalView.html
If there is multiple folders, it is beneficial to have an overview over them at the beginning and it should be obvious that they are expandable. In the case of a single folder, that's less so, therefore it will be expanded by default now.
=> gui: In remote need use index and auto-expand if only one folder (fixes #4759)

cmd/syncthing/main.go, lib/db/leveldb_dbinstance.go, lib/db/leveldb_test.go
When dropping delta index IDs due to upgrade, only drop our local one.
Previously, when dropping all of them, we would trigger a full send in
both directions on first connect after upgrade. Then the other side
would upgrade, doing the same thing. Net effect is full index data gets
sent twice in both directions.
With this change we just drop our local ID, meaning we will send our
full index on first connect after upgrade. When the other side upgrades,
they will do the same. This is a bit less cruel.
unit
=> cmd/syncthing, lib/db: Be nicer about dropping deltas on upgrade

vendor/github.com/Zillode/notify/notify.go, vendor/manifest
This adds a recover step to the notify package to avoid the panic. We should get something like this upstreamed. In the meantime I want to get a release out and this fixes the issue for our FreeBSD build.
(Slightly related, I think we should adopt the Zillode/notify fork into the syncthing organization so we can more easily manage it, as I think it's single-use for Syncthing only at this point? We can do that as another fork if we want to keep the Zillode/notify import path around as well.)
=> vendor: Don't panic in FS watcher on old FreeBSD (fixes #4806)

lib/ignore/ignore.go, lib/logger/logger.go
The entire `Matcher` struct is logged at debug level in some places which accesses members which are protected by a lock. Prevent that by implementing `Stringer`, which also makes the output more readable.
This resulted in a (racy) testing dead-lock by goroutines acquiring `Matcher.mut` and `logger.mut` in opposite order. Fixed by acquiring the logging lock after "printing" variables.
=> lig/ignore, lib/logger: Fix race and potential dead-locks when logging

lib/nat/structs.go, lib/nat/structs_test.go
Fix a deadlock when removing a NAT port mapping.
`clearAddresses` write locks the struct and then calls `notify`. `notify` in turn tries to obtain a read lock on the same mutex. The result was a deadlock. This change unlocks the struct before calling `notify`.
I am not sure how to automate the testing of this change.
Graham Miln (grahammiln) <graham.miln@miln.eu>
=> lib/nat: Fix clearAddresses/notify deadlock.

lib/fs/basicfs_test.go, lib/fs/basicfs_watch.go, lib/fs/basicfs_watch_errors_linux.go, lib/fs/basicfs_watch_test.go
Fix error detection and modify the error message to point to the appropriate FAQ entry (syncthing/docs#381).
Updated existing, incorrect test. It still is "artificial", as we can't reproduce the actual error in the backend (needs root).
=> lib/fs: Fix and update error about inotify watch limit (fixes #4833)

lib/model/model.go, lib/model/requests_test.go, lib/scanner/walk.go, lib/scanner/walk_test.go
See #4841. While `func (v Vector) DropOthers(id ShortID) Vector` does modify the underlying slice in place if possible, it doesn't always and is thus not to be used to modify the Vector in place (as are all the `Vector` methods). This resulted in files that should be updated as conflict to override the global state, which in case of non-existing files leads to data loss across the cluster.
@calmh Would you prefer PRs against the release branch for stuff like this or always to master?
Unit tests on un-ignoring in the model when no file exists and in the scanner when there is a file. Also tested manually with the reproducer given in the issue.
=> lib/scanner, lib/model: Actually assign version when un-ignoring (fixes #4841)

cmd/syncthing/gui_statics.go
mimetypes for assets aren't always submitted (for example, if not using compiled-in assets).
I used Chrome developer tools to ensure that assets were loaded properly when the value of the envvar `STGUIASSETS` was non-empty at runtime. Before this fix, the browser refused to load the assets due to identical mimetype errors triggered for each asset. After this fix, all assets are loaded successfully.
=> cmd/syncthing/gui_statics.go: Set Content-Type header regardless of asset location

lib/fs/basicfs.go, lib/fs/basicfs_watch.go, lib/fs/basicfs_watch_test.go
This was uncovered by accident in #4811: https://build.syncthing.net/viewLog.html?buildId=18757&buildTypeId=Syncthing_BuildLinuxCross  
But it's sufficiently different to get it's own PR/review. Essentially the notify backend always resolves symlinks in paths, while `basicFilesystem` does not. This makes path returned by the notify library look like they were outside of the folder root. In addition `unrooted` strips the leading path separator even if the path isn't below root, which the previous check didn't account for.
One test to check the symlinked root scenario and one directly on `unrootedChecked` for the path separator issue.
=> lib/fs: Don't panic when watching a folder with symlinked root

script/genassets.go
We did this to minimize source size and make it compile faster. Nowadays byte slice literals compile as fast as anything, and the source isn't checked in so it doesn't matter how big it is.
Not using base64 avoids a decode step at startup and makes the binary about 400k smaller.
=> script: Don't base64 encode the assets

cmd/syncthing/gui.go
Remove spurious `gui.go:985:  DEBUG:  <nil>` on successful call `time.Parse()` in  `getSystemLog` and `getSystemLogTxt`.
Turn on gui debug
=> cmd/syncthing/gui.go: remove spurious <nil> debug for time.Parse()

lib/model/rwfolder.go
Bumping the limit to 2 * the max block size (16 MiB) is a slight
increase compared to previously. Nonetheless I think it's good to allow
us to queue one request and have one on the way in, or conversely have
one large block on the way in and be able to ask for smaller blocks from
others at the same time.
=> lib/model: Increase the default pull limit (fixes #4883)

lib/osutil/traversessymlink.go, lib/osutil/traversessymlink_test.go
It's windows specific - I'll explain if the build server confirms it, nothing to do for anyone here (yet) :)
=> lib/osutil: Fix TraversesSymlink with symlinked fs root on windows (fixes #4875)

cmd/stcli/cmd_errors.go
Was getting this error on 
```
$ ./stcli -k APIKEY -e 'ENDPOINT' errors show
panic: interface conversion: interface {} is nil, not string
goroutine 1 [running]:
main.errorsShow(0xc4200d8300)
/home/pkp/go/src/github.com/syncthing/syncthing/cmd/stcli/cmd_errors.go:48 +0x424
github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/cli.Command.Run(0x89eabb, 0x4, 0x0, 0x0, 0x8a55d2, 0x13, 0x0, 0x0, 0x0, 0x0, ...)
/home/pkp/go/src/github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/cli/command.go:108 +0x5d4
github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/cli.(*App).RunAsSubcommand(0xc42007d6c0, 0xc4200d8180, 0xc420051918, 0x2)
/home/pkp/go/src/github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/cli/app.go:217 +0x56e …
```
=> Fixes error in syncthing-cli for 'errors show' command

lib/config/config.go, lib/config/folderconfiguration.go, lib/config/wrapper.go, lib/model/model.go, lib/model/model_test.go
Currently cluster configs are built based on the folders in the model internals. Paused folders are removed from the model, so they don't get into the cluster config. Thus to another device it looks like the folder was removed/unshared. This in itself is already incorrect. If this happens to all folders shared with one device, this device is removed on the remote if we are marked as introducer (#4897).
This delegates the creation of cluster configs to the config package and only adds the
index IDs and sequence numbers in the model. It also ensures that all lists of devices and
folders in the config are sorted by ID.
Added a test to check that the cluster config contains paused folders.
=> lib/config, lib/model: Include paused folders in cluster config (fixes #4897)

gui/default/index.html, gui/default/syncthing/app.js, gui/default/syncthing/core/binaryFilter.js, gui/default/syncthing/core/localeNumberFilter.js, gui/default/syncthing/core/metricFilter.js, gui/default/syncthing/core/naturalFilter.js
Localize Numbers, to add a thousands separator and set the decimal separator to the users locale.
The `toLocaleString` function uses the OS's locale. I didn't try to get the locale from the language selection, as it is not fine enough, as e.g. Switzerland has different chars for thousand / decimal separator than Germany, but both use the German translations (probably).
Manually tested in Firefox and Chrome on Windows 7, Linux and Android, and in IE11 on Windows 7. (with German locale)
Before:
After:
=> gui: localize numbers (fixes #4896)

lib/model/model_test.go
I by accident stumbled over 
```golang
return introducedBy.Equals(introducedBy)
```
in model_test.go which looks decidedly incorrect. <strike>Fixing it also lets `TestIntroducer` fail. Looks like a big review fail. I am looking into the test failures atm.</strike> `TestIntroducer` still passes though, so I guess reviewers got lucky (and code writer made his homework) :P
=> lib/model: Fix test function for introducer

Dockerfile
added EXPOSE to Dockerfile. this way these ports will show up in docker front-ends like cockpit.
When including the EXPOSE and VOLUME functions, a front-end for docker will know which ports and what folders this container will use, therefore allowing users to more easily adjust these settings. 
I re-built the container from scratch and no issues were found. To test it for yourself just paste in the one line and re-build the container with docker build.
=> Update Dockerfile to incorporate exposed ports

lib/db/leveldb_dbinstance.go
syncthing version git-2343c82c33dea213d9ccd0236f3132e161cb270c
- How to  reproduce
1. Add a folder ~/test/0000  get folder ID apv4v-f4ngi
2. Remove the folder in the previous step
3. Re-Add folder and keep folder ID is apv4v-f4ngi
4. SendIndexes is Endless loop. like sequence id from 0-200,86-200,86-200,86-200..... 
model.go:1783 insert line
```
l.Infof("222222222## sequence: %d %s", f.Sequence, f.Name)
```
can be see the log
....
....
[ABCDE] 2018/05/08 23:43:18.185937 model.go:1783: INFO: 222222222## sequence: 100 README.md
[ABCDE] 2018/05/08 23:43:18.185956 model.go:1783: INFO: 222222222## sequence: 101 syncmap.go
[ABCDE] 2018/05/08 23:43:18.185978 model.go:1783: INFO: 222222222## sequence: 102 syncmap.go
[ABCDE] 2018/05/08 23:43:18.185999 model.go:1783: INFO: 222222222## sequence: 86 …
=> lib/db: Remove all sequences related to the folder (fixes #4928)

build.go
After a huge pull on master (i.e. no caching), the test timed out repeatedly (intel i5-2520M) due to the scanner package (I think it's the hysteresis tests which needs to do a lot of hashing). I propose to extend the test timeout to 2min.
=> build: Increase test timeout to 2min

lib/model/folder.go, lib/model/rofolder.go, lib/model/rwfolder.go
The actual pull method (which is really the only thing that differs between them) is now an interface member which gets overridden by the subclass.
"Subclass?!" Well, this is dynamic dispatch with overriding, I guess.
Yeah, about that. I'm going to implement the damn recv only folder. As part of that I need to clean shit up. I hope to try to do that in manageable steps so it doesn't turn into an impossible-to-review ball of mud diff. No promises, though.
In the end I want something like the `folder` type that has all the scaffolding and looping and stuff, a `puller` member that implements the pull (like this PR) and something similar on the scan side. Possibly a scan results filter of some sort. Then the three folder types built out of these components.
It compiles, and it passes the …
=> lib/model: Refactor {ro,rw}folder serve loop into just folder

cmd/syncthing/gui.go
Because machines don't care, and sometimes humans read the output.
=> cmd/syncthing: Return formatted JSON in API

gui/default/syncthing/core/notificationDirective.js, gui/default/syncthing/core/notifications.html, gui/default/syncthing/core/syncthingController.js
The directive lives in its own isolated scope (where we put the visible() function). The stuff transcluded into the notification directive lives in the root scope and doesn't have access to the directive scope. Hence we cannot call dismiss() from *inside* the directive.
Similarly, `config` does not exist by itself in the directive scope, we need `$parent` to access the root scope.
Reference: https://docs.angularjs.org/guide/directive#isolating-the-scope-of-a-directive
How this worked before is a mystery. My guess is Angular bug with directive scope that was fixed in 1.3. One possibility is that `transclude` plus `scope: true` (which doesn't make sense as that is supposed to be an object) resulted in the root scope being used in the directive itself. This would then "work" as long as there …
=> gui: Fix scopes in notification directive (fixes #4941)

cmd/syncthing/usage_report.go, gui/default/index.html, gui/default/syncthing/core/syncthingController.js, gui/default/syncthing/folder/editFolderModalView.html, lib/config/foldertype.go
It's been a year and a half since we started accepting the new names.
It's time we start producing them.
@AudriusButkevicius @canton7 @kozec will this break all the wrappers? It changes the folder type returned by the /rest/system/config call and the string on disk. If so should we hold off a little while or should we just say that we will *never* change the names and scrap this?
We still accept the old type in incoming configs, and should probably continue to do so forever.
The reason for the change is that the future trio `readwrite`, `readonly`, `recvonly` [makes no sense whatsoever](https://thedailywtf.com/articles/What_Is_Truth_0x3f_) (which is why Heiko introduced the new names way back).
=> all: Serialize folder types to new names

lib/db/leveldb_test.go, lib/db/testdata/v0.14.48-ignoredfiles.db.jsons, lib/db/util_test.go
This adds a couple of utilities for transporting databases in JSON and a test to load a database and verify a couple of invalid bits. The test itself is quite pointless at the moment (apart from verifying the utility functions work), but it lays the groundwork for testing the migration of this data in the next step (after the invalid bit should be changed to local flags for local files).
When that happens we need to have a database in the old format already there in order to be able to test the migration.
=> lib/db: Add db and test with invalid files

cmd/stdiscosrv/database.go, cmd/stdiscosrv/stats.go
Once a device has been missing for a long time, and noone has asked about it for a long time, delete the record.
Already live. (I made a mistake when deploying it live the first time and it deleted old records that still had current `missed` times, hence the current rise in requests and lookup failures.)
=> cmd/stdiscosrv: Delete records for abandoned devices

lib/db/benchmark_test.go, lib/db/leveldb_dbinstance.go, lib/db/set.go, lib/db/set_test.go, lib/model/model.go
Currently walking the db with a prefix is broken in the presence of a file, that has the same prefix, as the entire walk is aborted when such a file is encountered.
Added new unit test.
=> lib/db: Fix prefixed walks (fixes #4925)

lib/db/leveldb_transactions.go, lib/db/set_test.go
@calmh spotted a mistake in keeping meta counts when updating the global list and the previous newest version is replaced, see https://github.com/syncthing/syncthing/pull/4958#discussion_r190543670 This fixes that issue and adds a test for it. I put it into this separate PR to not block the fix on a unrelated bigger change.
=> lib/db: Update global count when removing the previous global version

lib/watchaggregator/aggregator.go
It never triggered the race detection before, now it did for once. The folder id never changes, so store that on creation.
=> lib/watchaggregator: Prevent race on config update

lib/fs/filesystem.go, lib/watchaggregator/aggregator.go, lib/watchaggregator/aggregator_test.go
See #4953  and https://forum.syncthing.net/t/discussing-fs-watcher-delays-4953  
When the watcher sends events, it now checks if the only remaining (=delayed) events are removals. If it is the case, these removals don't need to be delayed any further and are thus sent right away.
To do that it is necessary to keep track of how many events of which types are currently tracked. So instead of iterating over the "event-tree" whenever total count is needed, the aggregator now has a `counts` field which is continuously updated.
I added a removal event to the end of the existing `TestDelay` test. To check that it is sent immediately, I needed to refactor the test setup, which unfortunately didn't get any simpler in the process. I also added some `t.Helper()`s and more detailed error reporting, …
=>  lib/watchaggregator: Speedup propagation of removals (fixes #4953) 

lib/fs/basicfs_test.go, lib/fs/basicfs_unix.go, lib/fs/basicfs_watch.go, lib/fs/basicfs_windows.go, lib/fs/basicfs_windows_test.go
On windows, check if paths coming from the FS watcher are 8.3 ones and convert to "normal", similar to how @canton7 did it for synctrayzor: https://github.com/syncthing/syncthing/issues/4956#issuecomment-389580448
=> lib/fs: Resolve 8.3 filenames from watcher (ref #3800)

gui/default/syncthing/core/syncthingController.js
To reiterate @calmh's statement in #4983: I am fixing this only because it is a bug - it is still not recommended to sync '/'.
=> gui: Don't remove the slash from path '/' (fixes #4983)

lib/protocol/protocol.go, lib/protocol/protocol_test.go
Tested by adding a GOARCH=386 test run to the builder...
=> lib/protocol: Correct block size calculation on 32 bit archs (fixes #4990)

gui/default/index.html
Hide line for "allowed networks" (advanced config) in device panel if it is empty.
yep
=> gui: Hide "allowed networks" if empty

gui/default/assets/css/overrides.css, gui/default/index.html, gui/default/syncthing/app.js, gui/default/syncthing/core/binaryFilter.js, gui/default/syncthing/core/localeNumberFilter.js, gui/default/syncthing/core/metricFilter.js, gui/default/syncthing/core/percentFilter.js, gui/default/syncthing/transfer/neededFilesModalView.html
This is more or less a continuation of the number localization in  #4902. Now it's no longer about localization but a reasonable amount of digits. The new "policy" is that only show three significant digits if there are decimals and maximally two decimals. I.e. don't change something like 24378273, and display 14.2323 as 14.2, 4.2323 as 4.23 and 0.21312 as 0.21. For percentages I even went to just 2 significant digits, because percentages just feel like two digit information to me (because 0-99 (please ignore 0-9)). That saves space and doesn't hurt my sensitive eyes with insignificant digits :P  
This still wasn't enough to prevent ellipsis on big total states, so I additionally gave some of the white space from the header column to the data column.
=> gui: Restrict shown decimals and restrict size of header columns

lib/config/folderconfiguration.go, lib/config/wrapper.go, lib/model/model.go, lib/model/model_test.go
Original/main purpose is to actually fix #4870. In the previous PR I tried to deduce whether the folder is paused from the information within the model. That clearly fails, because paused folders aren't in the model. 
Paused folders also caused problems elsewhere in the past (cluster config for one). `folderDevices` and `deviceFolders` is fully redundant and additionally they track information about which folder is shared with whom -> that's actually config business (again, paused folders). So I moved that functionality to wrapper.go and adapted all affected sections in model.go (sometimes adding the distinction between a unshared vs just paused folder).
=> lib/config, lib/model: Handle shared with information in config (fixes #4870)

lib/protocol/protocol_test.go
Specify the current behavior of the function, as there was no test already that I could find.
Indeed.
=> lib/protocol: Test for IsEquivalent

cmd/syncthing/main.go, lib/db/leveldb.go, lib/db/leveldb_dbinstance.go, lib/db/leveldb_dbinstance_updateschema.go
Refactor done by @calmh in #4952 (unmerged) on top of #4958.
Only functional change: Database schema updating happens on database initialization instead of being triggered on startup from main.
=> lib/db: Move database schema migration into its own file

lib/config/folderconfiguration.go, lib/model/model.go
Currently an error while creating the folder root is both handled by logging at warning level and returned. Now it is not logged and it's left to the caller to handle the error. The warning is logged in the model and if such an error occurs, the folder marker creation is skipped, as it will fail anyway and create a redundant warning.
None.
=> lib/config, lib/model: Don't warn and return error to prevent double warning

lib/model/folder.go
Tested manually.
Don't cut a new RC quickly. The ignores stuff might need fixing/adjustments (haven't investigated the reports yet) too, and this PR is purely cosmetic.
=> lib/model: Don't set watch error on folder creation (fixes 5005)

cmd/syncthing/gui_statics.go
If-Modified-Since condition is incorrect, causing HTTP to always return StatusNotModified
=> cmd/syncthing: Browser is not refreshed after UI file update

lib/model/model.go
Fixing #5028 as followup to #4982.
None due to the racy nature of the issue.
=> lib/model: Release both locks when waiting for services to stop (fixes #5028)

gui/default/vendor/angular/angular-sanitize.js, gui/default/vendor/angular/angular.js
It was removed in the last vendor update.
As requested by the MIT license:
> The above copyright notice and this permission notice shall be included in
> all copies or substantial portions of the Software.
=> angular.js: restore license

gui/default/vendor/angular/angular-dirPagination.js.LICENSE, gui/default/vendor/angular/angular-sanitize.js.LICENSE, gui/default/vendor/angular/angular-translate-loader-static-files.js.LICENSE, gui/default/vendor/angular/angular-translate.js.LICENSE, gui/default/vendor/angular/angular.js.LICENSE, gui/default/vendor/bootstrap/LICENSE, gui/default/vendor/daterangepicker/LICENSE, gui/default/vendor/jquery/LICENSE
Follow-up on @calmh's proposition in #5035:
> Other option would be to just drop a license.txt here with the MIT license.
=> gui/vendor: ship license files

Dockerfile, README-Docker.md
Allows for configuring the UID and GID Syncthing runs as in the container. Uses [su-exec](https://github.com/ncopa/su-exec) from the Alpine repos to accomplish this. Addition of su-exec results in <2MB increase in image size.
I've been using the [same approach](https://github.com/nvllsvm/docker-syncthing/blob/master/entrypoint.sh#L4-L5) in my Syncthing image for sometime on systems with varying UIDs and GIDs without issue.
I performed the following tests, each with a freshly created folder on the host mounted as volume /var/syncthing:
- started container without environment variables overridden. Verified configuration files written to the host folder had UID 1000 and GID 1000.
- started container with PUID=123 and PGID=456. Verified configuration files written to the host folder had UID …
=> Add configurable UID and GID to Docker container

cmd/stcli/cmd_general.go
The `stcli` now knows a new trick to get and prettyprint the config in JSON format and print it pretty on the console. This very handy for development and remote debugging.
It seems the stcli tool has no tests (manual only). The addition can be manually tested as follows:
```
$ stcli --apikey <apikey> config
{
"devices": [
{
"addresses": [
"dynamic"
],
"allowedNetworks": [],
"autoAcceptFolders": false,
"certName": "",
"compression": "metadata",
.......
}
```
I have searched through the docs but it seems the `stcli` tool is undocumented. So I have no documentation to add.
=> cmd/stcli: Add config command and output pretty JSON

Dockerfile
A slight optimization on the recent Dockerfile updates in
https://github.com/syncthing/syncthing/commit/5bb72dfe5dc063ceec0b0617246bd3d86a64bfe8#diff-3254677a7917c6c01f55212f86c57fbf
* Using --no-cache instead prevents unnecessarily
adding about 1.3MB of Alpine package data
* This reduces the uncompressed image size with about 6%.
Local build and run works
=> dockerfile: install su-exec without updating.

lib/db/leveldb_dbinstance_updateschema.go, lib/db/leveldb_transactions.go, lib/db/set_test.go
Fixes #5053 by doing the check, if the globally updated file needs to be added/removed from the need bucket, before updating the meta counter. Thus it happens on every update, not only if the first item in the global list is affected by the update. An update can be relevant to what's locally needed without happening at the front of the global list, if it involves conflicting files.
This also requires a recalculation of the need bucket. As the local flags change was introduced in dbVersion 5, but is not yet introduced in the release branch, dbVersion 5 needs to be skipped. The local flags change now happens to 7 (for master), while the need bucket reset happens to 6 (for release). Thus even if someone is running master, the transition will happen correctly. 
The diff looks bigger than it …
=> lib/db: Catch unignored/conflicting files as needed (fixes #5053)

lib/model/folder_sendrecv.go, lib/model/model_test.go, lib/model/requests_test.go
This is an improvemnt of PR #4493 and related to (and maybe fixing) #4961 and #4475. Maybe fixing, because there is no clear reproducer for that problem.
The previous PR added a mechanism to resurrect missing parent directories, if there is a valid child file to be pulled. The same mechanism does not exist for dirs and symlinks, even though a missing parent can happen for those items as well. Therefore this PR extends the resurrection to all types of pulled items.
In addition I moved the `IsDeleted` branch while iterating over `processDirectly` to the existing `IsDeleted` branch in the `WithNeed` iteration. This saves one pointless assigmenet and `IsDeleted` query. Also 
New request test to check that the parent of a directory is resurrected.
=>  lib/model: Also handle missing parent dir non-regular items 

lib/model/folder_sendrecv.go
Currently unavailable files show up as out-of-sync in the UI without any progress
or explanation. Now these files will be added to the failed items. The changed
count isn't inreased, as there is no point in retrying those files until a change
in connection happens. At that point, a pull will be scheduled anyway.
None.
=> lib/model: Record error for unavailable files

Dockerfile
A dedicated user is necessary to create relative references via `~/<folder>` or `$HOME/<folder>`. Having the syncthing process just running under a unprivileged UID/GID, will remove the home folder relation and therefore will result in nonexistent shares after update.
Fixes the changes introduced in #5041
=> [docker] Create a dedicated syncthing user

lib/config/config.go, lib/config/guiconfiguration.go, lib/config/wrapper.go, lib/model/model_test.go
This is a guess as to what could be the cause for #5063.
In the last debug logs the relevant part was:
```
[GXVUP] 22:26:43 INFO: Existing folder default false
[GXVUP] 22:26:43 INFO: Existing folder gdrxc-frazc false
[GXVUP] 22:26:43 INFO: Existing folder jjnhx-nhqzq false
[GXVUP] 22:26:43 INFO: Missing folder ewa2m-zcpje
// CommitConfiguration in the model coming in:
[GXVUP] 22:26:43 INFO: from folder map[
default:...
ewa2m-zcpje:...
gdrxc-frazc:...
[GXVUP] 22:26:43 INFO: to folder map[
ewa2m-zcpje:...
gdrxc-frazc:...
jjnhx-nhqzq:...
default:...
[GXVUP] 22:26:43 INFO: Adding folder "test1" (jjnhx-nhqzq)
```
So `ewa2m-zcpje` was introduced, but it somehow overwrote an existing folders spot in the config.
=> lib/config: Copy inputs and copy config outputs

cmd/strelaypoolsrv/main.go, cmd/strelaypoolsrv/stats.go, cmd/strelaypoolsrv/stats_test.go
Comment explains it.
Not tested, as usual.
=> cmd/strelaypoolsrv: Prevent scraped metrics moving backwards

gui/default/syncthing/core/syncthingController.js
Every time we open a dialog we register a new callback, but never deregister the old one. 
This uses one time callbacks in places where I think it makes sense (such as paths where the callback will be re-registered on modal being shown).
=> gui: Use one instead of on to have callbacks fire one

lib/db/meta.go, lib/db/set_test.go
As discussed, fixes regression in invalid accounting. The new unit test passes in 0.14.48, but not 0.14.49.
=> lib/db: Don't account remote invalid files (fixes #5089)

build.go
@wwwutz (https://github.com/syncthing/syncthing/pull/5093#issuecomment-409890926)
> oops, I should have tested better!
> 
> Now I get a 404 page not found so it builds, but the assets are missing.
> 
> any hints how to debug ?
It's me that should have tested better... Thanks for catching this!  
I didn't expect it to build fine, but generate empty assets. However it's actually quite obvious: Before generation happened in the non-temprorary dir, now it happens in the temporary dir. However the `gui/` dir isn't copied to the temp dir -> no assets. Fixed by copying over `gui/`.
=> build: Also copy gui to temporary GOPATH

gui/default/syncthing/device/editDeviceModalView.html
Fix the Device modal's "Incoming Rate Limit" label from "Outgoing" to "Incoming".
=> gui: Fix incorrect label

lib/model/model.go
Next try at fixing the following panic (from https://github.com/syncthing/syncthing/issues/5043#issuecomment-411097106):
```
Panic at 2018-08-07T10:24:04-05:00
panic: runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x91f1cc]
goroutine 577 [running]:
github.com/syncthing/syncthing/lib/model.(*Model).Closed(0xc420211320, 0x7f3481835e60, 0xc4224d3710, 0x0, 0x0)
/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/model/model.go:1262 +0x50c
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).close.func1()
/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:833 +0x206 …
```
=> lib/model: Catch racy nil deref in ClusterConfig

lib/watchaggregator/aggregator.go, lib/watchaggregator/aggregator_test.go
This is a follow-up to #4955, where the notification of deletions was made faster.  In the logs from #5092 (unrelated issue) I realized a small mistake in the implementation: Currently only "pure" deletions are returned early, if there is no other types of events. There's no point in delaying mixed events either, if no non-remove events exist.
I wrote a small test to check that there is no delay in this scenario. And I also fixed a minor bug in the output in case of a timing test failure.
=> lib/watchaggregator: Don't delay mixed events only

lib/model/model.go
This is a regression from #4974 and thus affecting v0.14.49. Discovered thanks to this report:
https://forum.syncthing.net/t/panic-deadlock-detected-at-fmut/11976  
The regression being present in v0.14.49 makes this no v0.14.50 RC material. However as it is pretty bad, I'd propose to make an exception and include it anyway.
Not that it makes it any better, but the reason for including the config stuff in the `fmut` lock was probably the edge case I now handled by checking that `m.folderCfgs[folder]` is really present.
=> lib/model: Always release the lock

lib/model/model_test.go, lib/model/progressemitter_test.go, lib/model/requests_test.go
While writing a test (not this PR) I noticed a problem in tests addressed in this PR:  Temporary files were deleted in setup functions, instead of at the end of tests:  
- `setupModelWithConnectionManual`:  
https://github.com/syncthing/syncthing/pull/5128/files#diff-5943690a8b9407e04ad15ac110b5d9c0L626  
- `newState`:  
https://github.com/syncthing/syncthing/pull/5128/files#diff-9accdb1b2ab06368238d103a1f87b3c6L159).
Also `newState` added folders, but didn't start them: https://github.com/syncthing/syncthing/pull/5128/files#diff-9accdb1b2ab06368238d103a1f87b3c6R163
And `createTmpWrapper` needlessly returned it's path, which is redundant with `wrapper.ConfigPath()`.
I am aware the diff is horrible, but the only non-cosmetical changes are those I mentioned above.
=> lib/model: Small fixes to test convenience functions

lib/config/folderconfiguration.go, lib/model/folder_sendrecv.go
I was thinking about the keep pulling and deleting stuff when disk is full and noticed that currently the availabilty check happens too early: If a file is unavailable, it's not pushed to the queue meaning deletes can't be matched against it -> potential renames (don't need availability) won't be detected.
None, passes existing tests. This is a small optimization not a bug and I am lazy right now -> no additional unit test.
=> lib/model: Check availability later to catch renames

lib/model/folder_recvonly_test.go, lib/model/folder_sendrecv.go
For some weird reason receive-only tests do show failures occurring during pulling. By `TestReceiveOnlyRevertNeeds` repeatedly I can consistently get the following issue:
```
2018/08/19 22:57:21.466474 progressemitter.go:196: DEBUG: progress emitter: updated interval 1s
2018/08/19 22:57:21.467116 set.go:78: INFO: No stored folder metadata for "ro": recalculating
2018/08/19 22:57:21.467529 progressemitter.go:62: DEBUG: progress emitter: timer - looking after 0
2018/08/19 22:57:21.467594 progressemitter.go:81: DEBUG: progress emitter: nothing new
2018/08/19 22:57:21.467630 model.go:849: DEBUG: Index (in): AIR6LPZ-7K4PTTV-UXQSMUU-CPQ5YWH-OEDFIIQ-JUG777G-2YQXXR5-YD6AWQR / "ro": 2 files
2018/08/19 22:57:21.468473 events.go:249: DEBUG: log 1 RemoteIndexUpdated map[items:2 version:42 …
```
=> lib/model: Fixes on receive-only test setup and pulling

lib/db/set.go, lib/db/structs.go, lib/model/model.go, lib/model/model_test.go, lib/model/requests_test.go
Ready for review - windows only test was verified to work and fix is now in place.  
<strike>**Do not merge**. This does not yet contain the fix for #5125, only the unit test that should reproduce it (<strike>i.e. if the new windows test passes, that's a failure</strike> it fails :) ).</strike>
When recurse unignoring (#4811), not only the scanner side of things should have been adapted, the model side of things (detecting ignores and deletes) as well.  
When adding more fine grained control over invalid files via local flags (#4952), the existing `IsIgnored` condition isn't enough anymore to filter files before checking whether they were deleted.
Unit tests for both issues.
=> lib/model: Fix regressions detecting deletes/ignores (fixes #5125, fixes #5127)

cmd/stdiscosrv/apisrv.go, cmd/stdiscosrv/apisrv_test.go
Filter out ludicrous stuff both from explicitly announced addresses and
potential automatic replacements.
Unit
=> cmd/stdiscosrv: Be more picky about allowed addresses (fixes #5151)

lib/db/debug.go, lib/db/leveldb_dbinstance.go, lib/db/set.go, lib/db/set_test.go, lib/model/model.go
The problem here is that we would update the sequence index before
updating the FileInfos, which would result in a high sequence number
pointing to a low-sequence FileInfo. The index sender would pick up the
high sequence number, send the old file, and think everything was good.
On the receiving side the old file is a no-op and ignored. The file
remains out of sync until another update for it happens.
This fixes that by correcting the order of operations in the database
update: first we remove old sequence index entries, then we update the
FileInfos (which now don't have anything pointing to them) and then we
add the sequence indexes (which the index sender can see).
The other option is to add "proper" transactions where required at the
database layer. I actually have a branch for that, …
=> lib/db: Fix inconsistency in sequence index (fixes #5149)

Dockerfile
This removes the user and group juggling, which would fail when given
for example a PGID that already existed as the "syncthing" group could
then not be created with that PGID. It's not reasonable to expect the
user to know which group/user names/IDs are already present in the
Docker image.
Instead we now just launch under the specified IDs, while manually
setting the HOME env var to give us a home directory - the only thing we
needed the user entry for anyway.
Also updates to Go 1.11 and building without upgrades instead of
disabling by env var.
I've ran it manually under existing and non-existing IDs, and it works for me; previously it didn't.
```
$ docker run -it --rm -e PUID=2 -e PGID=2 syncthing
$ docker run -it --rm -e PUID=12345 -e PGID=12345 syncthing
```
=> dockerfile: Improve UID/GID handling (fixes #5180)

lib/fs/basicfs.go, lib/fs/basicfs_test.go, lib/fs/basicfs_unix.go, lib/fs/basicfs_watch.go, lib/fs/basicfs_watch_test.go, lib/fs/basicfs_windows.go, lib/fs/basicfs_windows_test.go
https://forum.syncthing.net/t/panic-bug-notify-backend-is-processing-a-change-outside-of-the-filesystem-root/12133
Essentially there seems to be a problem with drive letter casing on windows again, but the test checking that is useless. This is currently just an attempt to make that test work and reproduce the problem, not yet a fix in itself.
=> lib/fs: Case insensitive conversion to rel path on windows

lib/model/model.go
Wrong debug function and `batch.reset()` is already done by `batch.flush` some lines above.
=> lib/model: Polish

cmd/syncthing/main.go
It appears that there was no help option and usage was printed as an error for unknown options (which is ok).
Explicit -help option allows you to print help and get zero exit code.
=> help command line option

lib/model/folder_recvonly.go, lib/model/folder_sendrecv.go, lib/model/model_test.go, lib/model/requests_test.go, lib/protocol/bep_extensions.go, lib/protocol/protocol.go, lib/scanner/walk.go
#5194 
The most relevant changes are those to `deleteFile`, `renameFile` and in the new `checkToBeDeleted` functions. The rest is just restructuring and fixes for existing tests.
Three new unit tests.
=> all: Check files on disk/in db when deleting/renaming (fixes #5194)

lib/db/keyer.go, lib/db/keyer_test.go, lib/db/leveldb.go, lib/db/leveldb_dbinstance.go, lib/db/leveldb_dbinstance_updateschema.go, lib/db/leveldb_test.go, lib/db/leveldb_transactions.go, lib/db/meta.go, lib/db/set.go, lib/db/smallindex.go
This breaks out the key generation stuff into a separate type. It's cleaner on its own, and it prepares for future stuff.
=> lib/db: Refactor key handling (ref #5198)

lib/scanner/walk.go
Mostly just refactoring to have less redundancy. Also there is a small fix to `scanner.CreateFileInfo`: Before it did set the `Permissions` and time fields of `FileInfo` for symlinks, which we do not actually want to record.
=> lib/scanner: Centralise protocol.FileInfo creation

cmd/syncthing/gui_auth_test.go
Newly added auth tests uses a high strength factor for bcrypt, which
takes ages under -race. No reason for that.
=> cmd/syncthing: Use lower strength factor in auth tests (fixes #5206)

lib/fs/basicfs_unix.go, lib/fs/basicfs_watch.go, lib/fs/basicfs_watch_test.go, lib/fs/basicfs_windows.go
See #5226 and  https://forum.syncthing.net/t/findfirstfile-error/12140/18:  
Apparently `filepath.EvalSymlinks` may fail in special circumstances (e.g. confirmed with ramdisk with IMDisk driver). This is potentially an upstream issue, as they do seem to support `\\?` prefixes, but given it's only reproducible in one very specific case, I doubt that's going to be fixed. Therefore I added a workaround by wrapping `filepath.EvalSymlinks` in `evalSymlinks`, which retries the call without the prefix on windows on failure.
=> lib/fs: Try EvalSymlinks without '\\?\' prefix on failure (fixes #5226)

lib/model/folder_sendrecv.go
This fixes a bug introduced in #5195, which isn't released yet. `performFinish` already does a db update if appropriate, therefore the one in `renameFile` is redundant.
Running model tests with `STTRACE=model` enables some additional checks. Before this PR these checks resulted in panics, now they don't. (Ideally, these checks should always be enabled when testing).
=> lib/model: Prevent repeat db update

lib/fs/fakefs.go, lib/fs/fakefs_test.go, lib/fs/filesystem.go, lib/fs/types.go
This adds a new fake filesystem type. It's described rather extensively
in fakefs.go, but the main point is that it's for testing: when you want
to spin up a Syncthing and have a terabyte or two of random files that
can be synced somewhere, or an inifitely large filesystem to sync files
into.
It has pseudorandom properties such that data read from one fakefs can
be written into another fakefs and read back and it will look
consistent, without any of the data actually being stored.
To use:
<folder id="default" path="whatever" ...>
<filesystemType>fake</filesystemType>
This will create an empty fake filesystem. You can also specify that it
should be prefilled with files:
<folder id="default" path="whatever?size=2000000" ...>
<filesystemType>fake</filesystemType>
This will create a …
=> lib/fs: Add fakefs

gui/default/syncthing/transfer/remoteNeededFilesModalView.html
The missing button means I have to tap on the really small border (~2mm wide?) around the modal to get out of it (or press "back" button and be kicked from WebView).
This change adds the `Close` button even for the list of files in the `Remote Devices` section (the one with multiple folders within modal).
Tested with Firefox on desktop, but it should be ok even for Android's WebView.
Ref: https://github.com/syncthing/syncthing/blob/c2b0d309fb4595ccc68ff2e267ef7b25fc3f4225/gui/default/syncthing/device/globalChangesModalView.html#L30
=> Fix missing 'Close' button on remote devices' files

lib/model/folder_sendrecv.go
In a recent change (#5201) this return disappeared. The effect is that
we first shortcut the file and then also treat it normally. This results
in to database updates after each other, which are bound to end up in
the same batch. This means we remove one sequence entry and add two.
Not marking the issues as fixed, because I need to do more testing and
there are other discrepancies...
=> lib/model: Don't flake out on shortcutting files (ref #5258, #5257, #5234)

lib/model/folder_sendrecv.go
Just exchange the two checks before pulling: Do the one without accessing the folder root first.
None. The specific fixed issue might have already been solved before, but this solves it for sure.
=> lib/model: Don't check folder health if there is nothing to pull (fixes #2497)

lib/db/instance.go, lib/db/keyer.go
This doesn't cause any catastrophic issues other than FileInfos
lingering in the database forever... But the prefix here was wrong
(including a nil device ID) resulting in this cleanup being a no-op.
=> lib/db: Properly remove FileInfos when dropping folder

lib/model/folder_sendrecv.go
> That return ended [up here](https://github.com/syncthing/syncthing/commit/60eb9088ff75891bffc3baf1c8fb63cfaeba93ce#diff-cf783533b0c2c4fe7c3a325925917a56R1157) -- worth removing at the same time (since it's useless)?
by @canton7 at https://github.com/syncthing/syncthing/commit/9d7a811e7291bd14c021416adb0b951bc4d049f9#commitcomment-30863072
Hardly worth a PR, but I still had to file one - annoys me too much xD
=> lib/model: Unnecessary return

lib/config/folderconfiguration.go
#5267
https://forum.syncthing.net/t/insufficient-space-error-from-v0-14-51-with-sshfs/12276
This only changes things in the corner-case where free space is smaller than the space required for the pull operation (`usage.Free - req <= 0`).
=> lib/config: Disable folder free disk check when configured (fixes #5267)

cmd/syncthing/verboseservice.go
#5270
None. Any unit test that checks if the assertions are correct would have to generate the data sent to `events.Logger.Log` itself, which does not guarantee that the actual data sent somewhere in the code corresponds to that. This is an intrinsic flaw of working with interfaces here, but it makes life much easier - trade-offs...
=> cmd/syncthing: Correct type assertion in verboseService (fixes #5270)

build.go
Heya :wave: ,
A small update for the golint import path as this has been changed last February. 
Fixes error "code in directory GOPATH/src/github.com/golang/lint/golint expects import golang.org/x/lint/golint" while running the
`go run build.go setup` command.
1. Check out the master branch. 
1. Run `go run build.go setup`
1. Acknowledge the error when the setup is trying to go get github.com/golang/lint/golint
1. Checkout this PR
1. Retry `go run build.go setup`
1. Acknowledge that the error is fixed
1. Run `go run build.go lint` to confirm that the linter still works
Have a nice day :tada:
=> Update golint import path

cmd/stdiscosrv/main.go, cmd/strelaypoolsrv/main.go, cmd/strelaysrv/main.go, cmd/syncthing/gui.go, cmd/syncthing/main.go, lib/discover/global_test.go, lib/tlsutil/tlsutil.go, lib/tlsutil/tlsutil_test.go
This changes the TLS and certificate handling in a few ways:
- We always use TLS 1.2, both for sync connections (as previously) and
the GUI/REST/discovery stuff. This is a tightening of the requirements
on the GUI. AS far as I can tell from caniusethis.com every browser from
2013 and forward supports TLS 1.2, so I think we should be fine.
- We always greate ECDSA certificates. Previously we'd create
ECDSA-with-RSA certificates for sync connections and pure RSA
certificates for the web stuff. The new default is more modern and the
same everywhere. These certificates are OK in TLS 1.2.
- We use the Go CPU detection stuff to choose the cipher suites to use,
indirectly. The TLS package uses CPU capabilities probing to select
either AES-GCM (fast if we have AES-NI) or ChaCha20 (faster if we …
=> cmd/*, lib/tlsutil: Refactor TLS stuff (fixes #5256)

gui/default/syncthing/settings/settingsModalView.html
When seeing a [screenshot of the settings in the forum](https://forum.syncthing.net/t/usage-reporting/12337/4?u=imsodin) I considered it a bit weird that UR is the only thing without a title. Turned out, the title is conditional on whether it's an RC or not. This makes the title unconditional:
=> gui: Show usage reporting title regardless of RC

lib/logger/logger.go
=> lib/logger: Disable debug flags without debugging (fixes #4780)

lib/model/folder_sendrecv.go
Once scenario where #5291 can happen: A valid file exists on a remote -> put in the queue. While other stuff in the queue is processed, that file vanishes/gets invalidated/..., such that there are now only invalid files in the global list. Therefore when the file is processed from the queue and the global file queried, it is now invalid -> check for that (like we already check for deletion, file type, ...).
=> lib/model: Check if files from queue are invalid (fixes #5291)

lib/connections/service.go
#5299 
The device config is queried from the wrapper multiple times during the connection process. Therefore it may happen that a device exists in the beginning of the attempt, and is removed at the point changed in this PR. The underlying problem is this inherent racyness of the current config system (#5298). Until that's fixed, lets not panic here and just drop the connection attempt.
=> lib/connections: Don't panic on removed device (fixes #5299)

lib/fs/filesystem.go, lib/fs/filesystem_test.go
Just makes logged permissions a bit easier to read.
=> lib/fs: Use os.FileMode.String for fs.FileMode

gui/default/syncthing/core/syncthingController.js, gui/default/syncthing/device/editDeviceModalView.html, gui/default/syncthing/folder/editFolderModalView.html
To allow **selecting or if all selected let deselecting all tick boxes** (toggle) when adding new folder (`Add Folder`), new device (`Add Remote Device`) or using `Edit` button on folder (under 'Folders') and device (under 'Remote Devices').
- **`Select All`**
- **`Deselect All`**
No need.
=> gui: 'Select/Deselect All' tick box when adding new folder/device or editing folder/device(#fixes 4000)

lib/model/folder_sendrecv.go
The fixed problem is likely the cause of https://forum.syncthing.net/t/0-14-52-file-deletion-issues/12436. "Likely" because I didn't reproduce (try to) myself, but the mechanism is clear: Local device ignores permissions but the remote does not, then different permissions let the consistency check fail when deleting the file and scheduls it for scanning. Scanning won't detect a change, because it does correctly ignore permissions.
=> lib/model: Don't compare permissions if IgnorePerms is true

lib/scanner/blocks_test.go, vendor/github.com/chmduquesne/rollinghash/adler32/adler32.go, vendor/github.com/chmduquesne/rollinghash/bozo32/bozo32.go, vendor/github.com/chmduquesne/rollinghash/buzhash32/buzhash32.go, vendor/github.com/chmduquesne/rollinghash/buzhash64/buzhash64.go, vendor/github.com/chmduquesne/rollinghash/rabinkarp64/rabinkarp64.go, vendor/github.com/chmduquesne/rollinghash/roll/main.go, vendor/manifest
Updates the package and fixes a test that depended on the old behavior
of Write() being equivalent to Reset()+Write() which is no longer the
case. The scanner already did resets after each block write, so this is
fine.
=> lib/scanner, vendor: Update github.com/chmduquesne/rollinghash (fixes #5334)

lib/fs/filesystem.go, lib/fs/util.go, lib/ignore/ignore.go, lib/model/folder.go, lib/model/model.go, lib/scanner/walk.go
https://github.com/syncthing/syncthing/issues/5324#issuecomment-438179326 by @calmh :
> Path prefixes are Hard™ :)
Make it harder to mess prefixes up by replacing the `strings.HasPrefix(..., ...+pathSeparator)` dance with `fs.IsParent(..., ...)`.
=> lib: Introduce fs.IsParent (fixes #5324)

etc/linux-systemd/system/syncthing@.service, etc/linux-systemd/user/syncthing.service
This fixes #5286 by adding security options to Syncthing systemd service files.
See the related pull request for the relay service options, for the rationale on the choice of options : https://github.com/syncthing/syncthing/pull/5350#pullrequestreview-182004704
In summary :
* we want to reduce the scope of what the executable can do, because syncthing will likely run on public facing IP, so is a target for attack
* we want to restrict capabilities, but not overdo it because the service will not run as root anyway
* we can not be as restrictive as with the relay service because its uses, and particularly the paths it will read/write to are not predictible
Compared to the relay hardening options:
* we use `ProtectSystem=full` instead of the more restrictive `ReadOnlyPaths=/ …
=> Add hardening options to syncthing systemd services (fixes #5286)

lib/model/folder_sendrecv_test.go
Set up the event subscription earlier, try to be less dependent on timeouts.
I can't make it fail, but lets have the slow ass builders run it a few times...
=> lib/model: Attempt to unflake Deregister tests (fixes #5362)

build.go
Fix permission problem when building syncthing from a system-wide toolchain.
Also see https://github.com/golang/go/issues/24674
and https://github.com/NixOS/nixpkgs/issues/51825
build is wip
not required
ok
=> build.go: avoid rebuilding cgo.go

lib/watchaggregator/aggregator.go
=> lib/watchaggregator: Properly unsubscribe from events when stopping (ref #5372)

lib/events/events.go, lib/events/events_test.go
Per @imsodin's suggestion.
Here the event Logger is rewritten as a service with a main loop instead of mutexes. This loop has a select with essentially two legs: incoming events, and subscription changes. When both are possible select will chose one randomly, thus ensuring that in practice unsubscribes will happen timely and not block the system.
Style wise I guess it's debatable if it's cleaner to have the `funcs` channel or separate channels and messages for subscribes and unsubscribes. This was the smaller change and is a pattern I've seen and used in a lot of other places so I think it's fairly idiomatic...
Ignore whitespace when reviewing this.
=> lib/events: Become a service (fixes #5372)

lib/scanner/walk.go, lib/scanner/walk_test.go
Fixes and adds unit test for #5385.
=> lib/scanner: Don't report error on missing items (fixes #5385)

lib/db/meta.go
As discussed and explained by @calmh in https://forum.syncthing.net/t/hanging-panics-in-integration-tests/12574/6. Does not change anything, because there is no reason to panic there, but it's still more correct this way (and I get to add debug panics without additional hassle)
=> lib/db: Defer unlock to avoid hangup on panic

lib/rc/rc.go
If the syncthing process exits before startup integration tests are hanging indefinitely as `rc.Process.AwaitStartup` is blocked and also panics somewhere else in the code don't propagate to the test (don't know exactly why, it's not the meta lock issue). So I replaced the lock/cond mechanism with channels and monitor the Syncthing process instead of only checking it when `rc.Process.Stop` is called.
Result: Fast abortion and indication of panics in integration tests.
Ran integration tests with "artificial panics".
=> lib/rc: Fix hangups when Syncthing process ends unexpectedly

lib/scanner/walk.go, lib/scanner/walk_test.go
Fix #5397 introduced in #5215:  
Move UTF8 validity check to the front and report regardless of filesystem errors. Then check for ign/temp/internal before reporting filesystem errors. An argument could be made that errors on temporary files should be reported, as the reason for the error might cause the temporary file to not be removed. However we didn't report above debug level before #5215, so that's a separate issue in my opinion.
None.
=> lib/scanner: Check ignore patterns before reporting error (fixes #5397)

cmd/ursrv/static/index.html, gui/default/assets/css/overrides.css
Modern OSes ship with high-quality fonts that can be used out of the box with a simple change. It tends to be slightly more consistent across platforms too, even though it's still not perfect (especially on the Linux side of things).
I didn't edit vendored libraries such as the date range chooser, but some of them still refer to the "old" font stack; let me know if I should edit them anyway.
See https://github.com/twbs/bootstrap/pull/19098 for more information.
Tested in Chromium 70 on Fedora 29, Edge 17 on Windows 10 and Safari 11.1 on macOS 10.13; see screenshots below.
**Chromium 70 on Fedora 29 (dark theme):**
**Edge 17 on Windows 10 (light theme):**
**Safari 11.1 on macOS 10.13 (light theme):**
=> gui: Use a modern font stack inspired by Bootstrap 4

lib/config/size.go
Use a better error message when disk space is running low. Without this PR, the user gets the error `error on folder XXX: 0.578253 % < 1 %`, which is not helpful. With this PR, the error becomes
error on folder XXX: not enough free space, 0.578253 % < 1 %
I successfully checked that all the tests ran by `go test` pass.
N/A
Maurizio Tomasi <ziotom78@gmail.com>
=> Improve messages when free space is running out

lib/model/folder.go
https://forum.syncthing.net/t/error-on-folder-myfolder-myfolder-context-canceled/12611
If the folder is stopped (restarted, paused, ...) we should not set its error state and thus display a warning in the weg UI.
None.
=> lib/model: Check folder context before setting error state

lib/config/size.go
That change was based on behaviour of v0.14.51 (see discussion in #5415).
=> lib/config: Revert #5415

lib/model/folder.go, lib/model/folder_sendrecv.go, lib/model/model.go
https://forum.syncthing.net/t/stop-folder-when-loading-ignores-fails/12612
Currently on pulling we don't reload the ignores, we just check the hash of what the model has against the previously seen hash. That means if loading ignores  fails, pulling will still happen and potentially creating a whole lot of previously ignored data.
Now the ignore patterns are loaded from file before pulling, aborting it if it fails. This means the previous hash doesn't need to be tracked anymore
Doing this revealed some cruft laying around: `ignoresChanged` was still passed to `pullerIteration` but not used anywhere in there (a wonder go didn't complain, usually it's very thorough on that kind of stuff). `IgnoresChanged` is not used outside of folder services anymore, therefore I removed it from the …
=> lib/model: Don't pull if ignores failed to load and cleanup

gui/default/index.html
Make sync status accessible for screen readers and colorblind users
=> gui: Make sync status accessible by screen readers (fixes #2697)

lib/db/blockmap.go, lib/db/meta.go, lib/db/meta_test.go, lib/db/set.go
This is a followup to (or a part of) #5394, to get the less disruptive changes in.  
The main change is illustrated by the unit test: The device sequence number is now also updated for invalid files. And it is not updated for the global device. These are the only two changes in functionality. The entire blockmap change is just polish, and most changes around meta are intended to make sequence handling more obvious/robust. Meaning introducing functions to access and update the device sequence number (hiding the zero bucket aspect).
New unit test `TestMetaSequences`.
=>  lib/db: Fix sequence updating for remote invalid items

lib/logger/logger.go, lib/logger/logger_test.go
Less odd stuff on the console, including beeps.
Unit. Also, benchmarks:
```
pkg: github.com/syncthing/syncthing/lib/logger
BenchmarkLog-4             	  300000	      3461 ns/op	   0.58 MB/s	     352 B/op	       6 allocs/op
BenchmarkLogNoStripper-4   	  500000	      3241 ns/op	   0.62 MB/s	     352 B/op	       6 allocs/op
PASS
```
I think the penalty is fine. (Those "MB/s" are in fact "Mlogentries/s".)
In comparison to the previous PR, doing it at the Writer level avoids both having to deal with runes or code points which means it's faster (UTF-8 bytes behave the way we need), and avoids whatever was the deal with the stack level stuff on old Go.
=> lib/logger: Strip control characters from log output (fixes #5428)

lib/model/model.go, lib/model/model_test.go
Avoid generating path components that are invalid or confusing when doing the auto accept dance.
Unit test on the sanitation function.
=> lib/model: Sanitize paths used for auto accepted folders (fixes #5411)

lib/connections/structs.go, lib/model/model.go, lib/model/model_test.go, lib/protocol/protocol.go, lib/protocol/protocol_test.go
This avoids waiting until next ping and timeout until the connection is actually
closed both by notifying the peer of the disconnect and by immediately closing
the local end of the connection after that. As a nice side effect, info level
logging about dropped connections now have the actual reason in it, not a generic
timeout error which looks like a real problem with the connection.
Inspired by the logs containing tons of misleading lines about connection failures posted in https://forum.syncthing.net/t/syncthing-reconnect-disconnect-cycles-frequent/12675
Manual testing on test setup by un-/pausing folders.
=> all: Send Close BEP msg on intentional disconnect

build.go
Seems that `CGO_ENABLED=1 CC=foo go run build.go` actually tries to compile build.go with an android compiler and link against local non-android system headers which obviously does not work.
Also, CGO_ENABLED=1 should also probably be -cgo-enabled, but that's not a problem for now.
I guess prior to Go 1.10, it worked somehow differently?
=> build: Add -cc argument that is not used by build.go

lib/protocol/protocol.go
While waiting for the Close BEP message to be sent, sending something else (that was randomly chosen in a switch over the Close) may fail and thus cause `internalClose` to be called, while the once is active -> deadlock.
This fixes this scenario by having separate onces for sending the close message and actually closing.
Should I revert https://github.com/syncthing/syncthing/commit/24ffd8be99bf21ade538fde04f1ff2bded06c53f and do this PR on top or is it fine as a followup like this?
Don't see a way to trigger the described scenario reliably.
=> lib/protocol: Fix potential deadlock when closing connection (ref #5440)

docker/Dockerfile, docker/README.md, docker/hooks/build, docker/hooks/push, docker/multiarch.Dockerfile
This refactors the Dockerfile into a multiarch.Dockerfile, that is provided along with build hook scripts to push a manifest from DockerHub to DockerHub. Fixes #5436.
My fork builds successfully on DockerHub. See [cloud](https://cloud.docker.com/repository/registry-1.docker.io/dargmuesli/syncthing/builds/4f7112fe-0482-42d9-b367-b1c8414f7c13) (I'm not sure if someone else can) or [hub](https://hub.docker.com/r/dargmuesli/syncthing)
There are no documentation changes necessary as Docker manifests make it possible to pull the correct image automatically and thus remove the architecture (tag) selection step.
=> Multiarch for Docker

cmd/syncthing/gui.go, gui/default/index.html, gui/default/syncthing/core/syncthingController.js, gui/default/syncthing/settings/settingsModalView.html
This adds booleans to the /system/version response to advice the GUI whether the running version is a candidate release or not. (We could parse it from the version string, but why duplicate the logic.)
Additionally the settings dialog locks down the upgrade and usage reporting options on candidate releases. This matches the current behavior, it just makes it obvious what actually *can* be chosen.
The usage reporting settings locks down 1) when on a candidate version 2) when on a non-candidate version and selecting candidate upgrades. The latter isn't strictly necessary but it's what was already happening, and it also illustrates that the choice will be taken from you if you do upgrade to a candidate so I think this is fine.
Manual
On candidate:
On release:
=> cmd/syncthing, gui: Settings dialog upgrades/reporting for candidates (fixes #4216)

lib/db/db_test.go, lib/db/instance.go, lib/db/schemaupdater.go, lib/db/set.go, lib/db/set_test.go, lib/db/structs.go, lib/db/transactions.go
There was a problem in iterating the sequence index that could result
in missing updates. The issue is that while the index was (correctly)
iterated in a snapshot, the actual file infos were read dirty outside of
the snapshot. This fixes this by doing the reads inside the snapshot,
and also updates a couple of other places that did the same thing more
or less harmfully (I didn't investigate).
To avoid similar issues in the future I did some renaming of the
getFile* methods - the ones in a transaction are just getFile, while the
ones directly on the database are variants of getFileDirty to highlight
what's going on.
There's a new unit test. Unfortunately it rather needs to run longer than is acceptable in the short test suite. Without the change, the test would fail after a few seconds. …
=> lib/db: Fix iterating sequence index (fixes #5340)

lib/db/instance.go, lib/db/set.go, lib/db/transactions.go
This does similar renaming as in #5462, just on getGlobal* instead of getFile*. 
Despite my previous comment this is definitely not RC material, it's solely for somewhat better naming consistency with #5462.
=> lib/db: Add "dirty" function terminology to getGlobal (ref #5462)

lib/db/instance.go, lib/db/set.go
Add a utility function `unchanged` that determines whether two `FileIntf` are the same from a database perspective (i.e. whether or not the update needs to happen).
=> lib/db: Deduplicate comparing old and new items

lib/db/instance.go, lib/db/schemaupdater.go, lib/db/transactions.go
Second to last PR :)
In some places we do use/share byte buffers for keys, in some we don't. In this PR the use is made consistent such that buffers are used for all "normal" operations. Normal in the sense that they aren't part of some kind of "special" operation, but happen often (every loop of update, drop, ...).
=> lib/db: Consistent use of buffers

lib/db/blockmap.go, lib/db/blockmap_test.go, lib/db/instance.go, lib/db/keyer.go, lib/db/set.go
This is a successor to https://github.com/syncthing/syncthing/pull/5394 and has the same goal, but with less moving parts. By integrating `BlockMap` into `instance`/`keyer` all operations can now be done in `instance.updateLocalFiles` sequentially. Meaning the batch will only be flushed to db in a state, where all "update operations" for the contained items are done.
None.
=> lib/db: Do all update operations on a single item at once

lib/model/folder_sendrecv.go
`lastError` is declared outside of the loop and reused in the next iteration -> don't redeclare.
Until now I thought that `errDirNotEmpty` should never happen. Recent support threads on the forum made one mechanism clear, how you can end up with this error:
1.    Devices A and B have the same file at `foo/bar`, device A has ignore pattern `bar`.
2.   On A the user deletes `foo` is deleted -> Syncthing marks foo as deleted and sends that info to B - it doesn’t do anything about `foo/bar`, as it’s ignored.
3.   B tries to get in sync, thus tries to delete `foo` but correctly realizes that there is still `foo/bar` and thus throws this error.
The new error is a bit more descriptive based on this scenario.
=> lib/model: Improve errors while pulling

lib/config/optionsconfiguration.go
> when I start syncthing on a fresh installation it creates the config on first launch. There, "minHomeDiskFree" and "minHomeDiskFreePct" tags are both present in the generated xml while "minHomeDiskFreePct" is deprecated and unused. Relevant PR was #4087 .
> It's missing omitempty
=> lib/config: Add omitempty to DeprecatedMinHomeDiskFreePct (fixes #5482)

lib/rc/rc.go, test/override_test.go
Integration tests failed consistently locally. Apparently the renames wrapped in `t.Log` for some reason didn't take effect, thus ensuing tests failed. The rest is minor stuff that I noticed while debugging the above.
In addition on CI the integration tests currently fail due to gomodules. I wanted to try and fix it, but apparently I don't have the permissions.
=> test, lib/rc: Integration test fixes and polish

lib/model/model_test.go, lib/model/requests_test.go
Many model tests depend on a specific order of scans/pulls/... The by default enabled watching for changes can interfere with this pattern and thus change the tested scenario, which can make tests fail randomly, thus disable it explicitly.
=> lib/model: In tests disable watching for changes by default (fixes #5246)

cmd/syncthing/monitor.go
=> cmd/syncthing: Pass SIGTERM on in monitor (fixes #5493)

cmd/syncthing/auditservice.go, cmd/syncthing/cpuusage_unix.go, cmd/syncthing/gui.go, cmd/syncthing/gui_auth.go, cmd/syncthing/gui_statics.go, cmd/syncthing/gui_test.go, cmd/syncthing/main.go, cmd/syncthing/mocked_config_test.go, cmd/syncthing/monitor.go, cmd/syncthing/monitor_test.go, cmd/syncthing/perfstats_unix.go, cmd/syncthing/usage.go, cmd/syncthing/usage_report.go, lib/model/folder_sendrecv.go, lib/model/model.go, lib/nat/interface.go, lib/nat/service.go, lib/protocol/hello.go, lib/upgrade/upgrade_common.go
I'm working through linter complaints, these are some fixes. Broad
categories:
1) Ignore errors where we can ignore errors: add "_ = ..." construct.
you can argue that this is annoying noise, but apart from silencing the
linter it *does* serve the purpose of highlighting that an error is
being ignored. I think this is OK, because the linter highlighted some
error cases I wasn't aware of (starting CPU profiles, for example).
2) Untyped constants where we though we had set the type.
3) A real bug where we ineffectually assigned to a shadowed err.
4) Some dead code removed.
There'll be more of these, because not all packages are fixed, but the
diff was already large enough.
In the end I intend to enable the golang-ci cloud service that runs these linter checks on changed lines on pull …
=> all: Fix some linter errors

cmd/syncthing/main.go, lib/config/config.go, lib/config/wrapper.go
A lot of things that are done in main are obsolete, as the config generation already takes care of it. In addition I moved ensuring free ports to the config package and removed some dead code from the config wrapper.
=> cmd/syncthing, lib/config: Update default config creation

lib/model/folder_recvonly_test.go, lib/model/folder_sendrecv_test.go, lib/model/model_test.go, lib/model/testos_test.go
Results in relevant files/line numbers on test failures.
Also our new bot indirectly detected a small slip of mine: An os that fails on errors really doesn't need to return a nil error.
=> lib/model: Helperize test os and remove error return value

lib/model/requests_test.go
Both more readable test results and less mess lying around as cleanup functions can execute.
=> lib/model: Fail test instead of panic due to closing channel twice

lib/model/folder_recvonly_test.go, lib/model/folder_sendrecv_test.go, lib/model/model_test.go, lib/model/requests_test.go
Currently throughout model tests we use a mix of `device1` and `protocol.LocalDeviceID` for the "local device-id". In this PR I add another device-id called `myID` which should always be used for the local id, e.g. when passed to `NewModel`. Any additional remote devices are then `device1` and `device2`.
=> lib/model: Don't use LocalDeviceID as normal id in tests

lib/db/lowlevel.go, lib/model/model.go
I saw the `dbLocation` stuff and wondered what it was used  for. It isn't.
=> lib/db, lib/model: Remove dead code

etc/linux-desktop/syncthing-start.desktop, etc/linux-desktop/syncthing-ui.desktop
Make .deb builds more pleasing to the Debian package linter.
Frankly, none.
=> etc: Add keywords to .desktop files (fixes #5365)

lib/model/folder_recvonly_test.go, lib/model/model_test.go, lib/model/requests_test.go
Use functions (methods on `config.Wrapper`, test utility functions, ...) to handle configuration - it's less error prone (and less redundant).
=> lib/model: Use functions to generate config

lib/model/model_test.go, lib/model/requests_test.go
This is purely for convenience, consistency and deduplication - no functional change.
=> lib/model: Introduce setupModel test utility

lib/config/folderconfiguration.go, lib/config/size.go, lib/config/wrapper.go, lib/model/folder.go
Currently we check disk space at the path passed to `config.Wrapper`, which works for `cmd/syncthing` as the database is at the same place, but it's not right in general. Now the check is done at `locations.Get(locations.Database)`.
=> lib/config, lib/model: Use path from locations to check disk space for db

lib/model/folder_sendrecv_test.go, lib/model/model_test.go, lib/model/requests_test.go, lib/model/sharedpullerstate_test.go
Moves a lot of tests that run in `lib/model/testdata` but don't need the files there to temporary directories, to prevent any interaction. Some send-receive tests needed a temporary file, which is now copied over from testdata to the temporary dir. I hope this fixes the flakiness of the `TestDeregisterOnFailIn...` tests. It has been confirmed that it fixes a lot of the flakiness on openbsd. 
=> lib/model: Run more tests in tmp dir

lib/model/model_test.go, lib/model/progressemitter_test.go, lib/model/requests_test.go
Quite a few  `defer m.Stop()` statements were missing. And cleanup of temporary directories caused test failures on openbsd, so just don't fail the test (compromise: temp stuff rarely persisting vs flaky test).
=> lib/model: Various model test fixes and polish

cmd/syncthing/gui.go, cmd/syncthing/main.go, cmd/syncthing/monitor.go, lib/config/config.go, lib/config/folderconfiguration.go, lib/logger/logger.go, lib/model/model.go
A package/library has no business calling `os.Exit` ever, but that's what `logger.Fatal...` does. Solution: Panic on errors that just must not happen or bubble errors up until they reach `cmd/syncthing` (or whoever calls) and let them decide on what's to do.
Tests pass and test setup starts and GUI reacts to input.
=> all: Get rid of fatal logging

.codecov.yml, build.go
To get the whole codecov thing actually running someone with permissions to modify the build process on the team city CI. Just a step running tests with the new `-coverage` option and then upload the report to codecov (see https://github.com/codecov/example-go#travis-ci). Probably we should wait for the end of Jakobs holidays :)
=> build: Add option to get test coverage

lib/db/blockmap_test.go, lib/db/instance.go, lib/db/lowlevel.go, lib/db/namespaced.go, lib/db/schemaupdater.go, lib/db/transactions.go
Flush the batch when exceeding a certain size, instead of when reaching a number
of batched operations.
Move batch to lowlevel to be able to use it in NamespacedKV.
Increase the leveldb memory buffer from 4 to 16 MiB.
See discussion in #5531.
=> lib/db: Flush batch based on size and refactor (fixes #5531)

etc/linux-desktop/syncthing-ui.desktop
Spec says nothing about using double-quotes here. They don't get stripped when line is used by DEs, resulting in inconsistent experience.
Tested manually on KDE and XFCE.
=> etc: Remove unnecessary quotes in .desktop

lib/scanner/blocks.go, lib/weakhash/benchmark_test.go
Seems the rolling adler32 implementation is super slow when executed on large blocks, even tho I can't explain why. Use standard adler when we don't need to roll
```
BenchmarkFind1MFile-16    	     	     	     	     100	  18739828 ns/op	  55.95 MB/s	  398924 B/op	      20 allocs/op
BenchmarkBlock/adler32-131072/#00-16     	     	     200	   9678923 ns/op	1083.36 MB/s	 2654929 B/op	     163 allocs/op
BenchmarkBlock/bozo32-131072/#00-16      	     	      20	  73577340 ns/op	 142.51 MB/s	 2654928 B/op	     163 allocs/op
BenchmarkBlock/buzhash32-131072/#00-16   	     	      20	  61456805 ns/op	 170.62 MB/s	 2654928 B/op	     163 allocs/op
BenchmarkBlock/buzhash64-131072/#00-16   	     	      20	  61651235 ns/op	 170.08 MB/s	 2654928 B/op	     163 allocs/op …
```
=> lib/scanner: Use standard adler32 when we don't need rolling

README-Docker.md
Plus some formatting.
If you rather wish to add a `VOLUME` tag to the Dockerfile, feel free to close this alternative solution.
=> docs: Correct Docker README (#5480)

gui/default/index.html, lib/connections/service.go, lib/connections/structs.go, lib/model/model.go, lib/model/model_test.go, lib/tlsutil/tlsutil.go
This enables TLS 1.3 negotiation on Go 1.12 by setting the GODEBUG
variable. For now, this just gets enabled on test versions (those with a
dash in the version number).
Users wishing to enable this on production builds can set GODEBUG
manually.
The string representation of connections now includes the TLS version
and cipher suite. This becomes part of the log output on connections.
That is, when talking to an old client:
Established secure connection .../TLS1.2-TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
and now potentially:
Established secure connection .../TLS1.3-TLS_AES_128_GCM_SHA256
(The cipher suite was there previously in the log output, but not the
TLS version.)
I also added this info as a new Crypto() method on the connection, and
propagate this out to the API and GUI, where it can …
=> lib/tlsutil: Enable TLS 1.3 when available, on test builds (fixes #5065)

gui/default/syncthing/core/aboutModalView.html
All copyright notices are revised based on avalilable source code (gui/default/vendor and `go mod vendor`-generated vendor dir.
sasha-s/go-deadlock contains no copyright notice whatsoever, so I just left it as it was.
none
=> gui: Update copyright notices (fixes 5569)

lib/model/folder_sendrecv.go, lib/model/folder_sendrecv_test.go, lib/model/sharedpullerstate.go, lib/model/sharedpullerstate_test.go
The original intention was to remove the meaningless `finisher` context, prompted by a report with this log line:
```
[...] 10:10:15 INFO: Puller (folder "..." (...), file "..."): finisher: pull: no such file
```
Then realized, that it's not the only place with non-ideal contexts and that there is `errors.Wrap`, so I switched to using that and in the process removed/added/changed some contexts.
And while at it I most likely found a bug that overwrites conflicts. I didn't have time to write a unit test to reproduce it, but I am pretty sure about it, so I added comments at the relevant places.
=> lib/model: Use errors.Wrap for pull errors

lib/model/model_test.go
When adding the code that's removed in this PR I wasn't aware that `osutil.TempFile` with an empty dir argument creates the file in a platform specific temporary directory. And `os.RemovAll("/tmp")` was a very smart move (not that it would have worked, but still).
=> lib/model: Use temp dir from osutils in tests

lib/model/folder_sendrecv_test.go, lib/model/model_test.go, lib/model/requests_test.go
Returning the temporary directory as well as the `folder` is redundant, the latter is just `.Filesystem().URI()`. Also in some tests we need that folder, not just it's root path.
I have a few other changes to tests incoming, if you'd rather have just one PR please say so: https://github.com/syncthing/syncthing/compare/master...imsodin:modelTestImpr  
The most relevant and only change that isn't just polish is the last one: https://github.com/syncthing/syncthing/commit/031e0b510733c0383c5fca167bb4966e4f1150e8
=> lib/model: Improve test utilities

lib/model/folder_recvonly_test.go, lib/model/folder_sendrecv_test.go, lib/model/model_test.go, lib/model/requests_test.go, lib/model/testos_test.go
As there's already `fatalOs.must`, why not change that to `must(fatal, func() error)` to save a few constructs like
```
if err := fn(...); err != nil {
t.Fatal(err)
}
```
However now a few days after that thought I am no longer convinced that this is really any better:
```diff
-	if err := ioutil.WriteFile("testdata/testrm2", []byte("Hello"), 0644); err != nil {
-		t.Fatal(err)
-	}
+	must(t, func() error { return ioutil.WriteFile("testdata/testrm2", []byte("Hello"), 0644) })
```
Since variadic return values don't exist, it's anyway just a partial patch.
Before sending the change to oblivion I'd like to hear another opinion.
=> lib/model: Introduce must test utility

lib/model/folder.go, lib/model/folder_recvonly.go, lib/model/folder_sendonly.go, lib/model/folder_sendrecv.go, lib/model/folder_sendrecv_test.go, lib/model/model.go
It's very ugly and totally unnecessary that folder code needs to reach into the model maps holding the fmut to get the db fileset and ignore patterns. A possible final goal would be to fully separate model and folders (and I might have already done some work towards that). This does not conflict with the gui PR.
=> lib/model: Pass fset & ignores on folder creation

cmd/syncthing/main.go
Compiled and tested manually on linux-amd64, works as expected.
=> cmd: Add check for newer config file and an option to override it (fixes #4921)

lib/config/folderconfiguration.go
Fixes #5599, followup to #5405.
=> lib/config: Set UseLargeBlocks to true by default (fixes #5599)

lib/model/model.go, lib/model/requests_test.go
The deleted `shouldDebug` block is duplicated on the lines just above it.
The first removed return exits the test preemptively. Removing the second doesn't change anything, but it's still superfluous.
=> lib/model: Debug and test fixes

gui/default/index.html, gui/default/syncthing/core/syncthingController.js
Previously whenever there were any failures, those were failures during pulling and thus the folder was also out of sync as in there are needed files. Now that failures can occur when scanning, this is not the case and there can be failed items with no indication whatsover in the folder status. As folders aren't really out-of-sync due to scanning errors, I added the new state "Failed Items". It only takes effect if the folder is not out of sync.
Manual testing.
=> gui: Add new folder state "Failed Items" (fixes #5456)

test/conflict_test.go
The change in 225c0dda805fbed69d745abce935130dcaf68763 (#5511) results in
conflicts being immediately scanned and synced, while the test expects just one
conflict on either side. Change it to expect the same conflict on both sides.
There is no bug here and nothing related to RC.
=> test: Update conflict integration test (ref #5511)

lib/model/folder_sendrecv.go
The `DeregisterOnFailIn...` tests are still flaky:  
https://build.syncthing.net/project.html?projectId=Syncthing&buildTypeId=&tab=testDetails&testNameId=-1067371058420929398&order=TEST_STATUS_DESC&branch_Syncthing=__all_branches__&itemsCount=50  
https://build.syncthing.net/project.html?projectId=Syncthing&buildTypeId=&tab=testDetails&testNameId=-6699784144011712658&order=TEST_STATUS_DESC&branch_Syncthing=__all_branches__&itemsCount=50  
They always fail with everything deregistered except the progress emitter:
```
folder_sendrecv_test.go:609: event took 5.020876ms
folder_sendrecv_test.go:619: Still registered 1 0 0
```
In the test we wait for the item finished event before checking and in the finisher, we emit that event before deregistering from the progress emitter. Apparently …
=> lib/model: Send item finished event after deregistering (fixes #5362)

lib/model/folder_sendrecv.go
Pulling can be quite slow and consume lots of memory. While working on reactivating #4980 I noticed some of the intermediate storage of file infos to process is not necessary or can be avoided. There are two main changes:
1. Remove `processDirectly` by really processing those items directly.  
Concerns dirs&symlinks only, should be beneficial in all scenarios. I also remove the ordering by component count, as that is a noop due to elements in the db being sorted lexicographically, which implies parents first as well.
2. Check for metadata only file changes before pushing items to queue.  
This is aimed mostly at initial sync with preexisting data or big deletions: A huge list of out-of-sync items, but they are all equal. In this case we save all the queue storage and sorting and one …
=> lib/model: Optimize puller for meta only changes

lib/model/folder_sendrecv.go, lib/model/queue.go
I am not actually certain it fixes #5332 for lack of reproducer, but it's likely the cause: When a file cannot be pulled, it isn't removed from the queue and readded on the next try. And the queue is never reset, so that stays there "forever" (as long as the folder is constantly running). I fixed that instance and added `jobQueue.Reset` that removes everything from queue that's invoked when the iteration is finished - in case the folder is stopped (or I missed something else). And I noticed a missing `changed++` on rename, which is largely cosmetic (as in can't think of an adverse effect right now).
=> lib/model: Missing queue.Done and reset between pulls (fixes #5332)

lib/model/folder.go, lib/model/folder_recvonly.go, lib/model/folder_recvonly_test.go, lib/model/folder_sendonly.go, lib/model/folder_sendrecv.go, lib/model/folder_sendrecv_test.go, lib/model/model.go, lib/model/requests_test.go
Updating the db after pulling or scanning is done in model, while all the actual work is done in folder -> move it there. This also avoids having to pass the model update functions as arguments to folder methods.
=> lib/model: Update db on scan/pull in folder

lib/fs/basicfs_watch.go
Should fix #5578 according to this https://forum.syncthing.net/t/filesystem-watcher-errors-getfileinformationbyhandle-w-incorrect-function/12974/12  
However it's obviously super ugly and finding the real change between Go 1.11 (worked) 1.12 (fails) or revisiting the use of `\\?\` in general as proposed by calmh would be preferable:
> Do we need `\\?\` anywhere at all any more? Go 1.8 (!) added a change 10 that should use long filenames “when possible” which I think should cover all the regular OS stuff. Maybe the filewatcher library does need it if it does direct syscalls, but then it could fixup the path to whatever is the right format, and maybe only do so if it’s longer 260 chars etc?
However the former needs debugging and I don't want to do the latter without more thought/testing put …
=> lib/fs: When watching remove \\?\ for drive letters (fixes #5578)

lib/model/model.go
The returned errors on a file request don't match the descriptions in the BEP:
> 0: No Error (data should be present)
> 1: Generic Error
> 2: No Such File (the requested file does not exist, or the offset is outside the acceptable range for the file)
> 3: Invalid (file exists but has invalid bit set or is otherwise unavailable)
=> lib/model: Request errors conforming to BEP specs

lib/model/model.go, lib/model/model_test.go
This is the result of https://forum.syncthing.net/t/pull-no-such-file-error/13139/22
Currently the block index is calculated from requested offset and size, but that's not correct for the last block, which usually is smaller than the file's blocksize.
=> lib/model: Fix block index calculation for recheckFile (fixes #5649)

lib/model/folder_sendrecv.go, lib/model/model.go, lib/model/progressemitter.go, lib/model/progressemitter_test.go
The main purpose is to make the progress emitter actually en-/disable when `ProgressUpdateIntervalS` is changed between negative and positive. This requires to make some kind of cleanup on disabling, that deregisters all already sent progress updates on connected remotes. And the way puller states and connections were saved (separating folder id and file name by `//` instead of a double map), and copies created on every send (5s by default) seemed overly complicated, so I changed that using maps. There's probably more potential for simplification, but I didn't want to deviate much from how it worked before.
=> lib/model: Refactor progressEmitter to de-/activate by config (fixes #4613)

lib/model/folder_sendrecv.go, lib/scanner/walk.go
The file might be a directory or symlink, so call it generically "item", as already done in other places.
=> lib/scanner, lib/model: File -> item when logging error

lib/fs/filesystem_test.go, lib/fs/util.go
Add testing to `fs.IsParent` and fix test failures.
=> lib/fs: Improve IsParent

cmd/strelaypoolsrv/gui/index.html
> When AngularJS injects dependencies into a function that does not have an explicit dependency specification, it matches up dependencies with function parameters by name. This is dangerous, since some source code transformations such as minification may change the names of parameters. Such a renaming will break the AngularJS application.
https://lgtm.com/rules/1505800326162/
This methodology is used some lines further down, but please review as I'm unsure about possible implications.
https://github.com/syncthing/syncthing/blob/e302ccf4b4fa0c2fba77036be7f5114b5574412d/cmd/strelaypoolsrv/gui/index.html#L220
=> cmd: Missing explicit dependency injection

gui/default/syncthing/core/majorUpgradeModalView.html
Using AngularJS markup (that is, AngularJS expressions enclosed in double curly braces) in HTML attributes that reference URLs is not recommended: the browser may attempt to fetch the URL before the AngularJS compiler evaluates the markup, resulting in a request for an invalid URL.
=> gui: Use of AngularJS markup in URL-valued attribute

lib/model/model.go, lib/protocol/protocol.go
This is rather pedantic protocol level race, but who knows, maybe someone got bitten by it anyway at some point:  
Cluster-config must be the first message sent, but there is a tiny window in `AddConnection` between releasing `pmut` and sending the message, in which the puller (which can be up and running hard) can send a request on that connection. If that happens, the remote side will close the connection (silently for now, resulting in a timeout eventually - see https://github.com/syncthing/syncthing/pull/5645).
=> lib/protocol: Don't send any messages before cluster config

lib/protocol/protocol.go
Regression introduced in #5646 as identified by @rahrah in #5674, thus luckily not yet released.
=> lib/protocol: Don't close asyncMessage.done on success (fixes #5674)

lib/protocol/protocol.go
Calling `internalClose` in `writerLoop` calls `wg.Wait` which waits for the deferred `wg.Done` also in `writerLoop`: face -> wall
=> lib/protocol: Fix yet another deadlock (fixes #5678)

cmd/syncthing/main.go, lib/db/instance.go, lib/db/lowlevel.go, lib/db/transactions.go, lib/model/folder_recvonly_test.go, lib/model/model_test.go, lib/model/requests_test.go
We currently don't close the database, just call `os.Exit`. At the same time we do not keep track of whatever is currently accessing the database (model, api, ...), which is fine in many cases, but not for a few random `panic`s we have in our code and `goleveldb.DB.NewIterator` (https://github.com/syndtr/goleveldb/issues/235, other functions just report `goleveldb.ErrClosed`). Therefore I had to add some bubblewrap to prevent panics after close.
This does not ensure that we are in a consistent state on close, but it at least explicitly closes the database instead of crashing it. Doing that would probably require actually keeping track of everything the model does and adding `model.Close` that ensures everything is terminated before it returns - I'd say that would be quite a lot of work.
=> cmd, lib/db: Actually close goleveldb (fixes #5505)

lib/model/model.go
In most places we already follow these practice, I adjusted the rest. This should be a trivial change that at best reduces time waited for locks and at worst just makes code more consistent, but as it is about locks please still have an actual good look at it.
Whenever possible:
- Release locks early:  
If possible just get whatever you need and then release before doing the processing.
- Defer unlocks:  
Just in case of early returns and panics
=> lib/model: Consistent use of locks

gui/default/syncthing/core/logViewerModalView.html
Replaces `Log tailing paused. Scroll to bottom continue.` with `Log tailing paused. Scroll to the bottom to continue.` in the web GUI's log viewer modal.
`Nitroretro <nitroretro@protonmail.com>`
=> gui: Fix typo in log viewer modal

lib/protocol/protocol.go
As brought up by @calmh in the most recent PR (#5685) in a string of PRs related to handling closing of protocol connections, the way I introduced these changes wasn't particularly trust inspiring and the affected code is critical.
There were three involved changes, with follow-up fixes each:
1. Propagating closing of connection in model to protocol: #5440 -> #5442 
2. Sending cluster configs first: #5646 -> #5675 
3. Do not call the model after calling `*model.Closed` (fixes cluster config panic #4170): #5657 -> #5679 (unmerged: #5685)
My proposal for the next RC is to revert these changes (0229f04) and redo one unrelated change (337ae59). This brings us back to a state, that has been in place for a long time. There are known problems, but we were able to live with them for a long time, …
=> lib/protocol: Revert unreleased changes related to closing connections

lib/model/fakeconns_test.go, lib/model/model_test.go, lib/model/requests_test.go, lib/model/testutils_test.go
I created some tests regarding connection handling, mostly in protocol but also wanted one for closing from model. That required another type of fake connection, backed by the real `protocol.Connection`. As Audrius mentioned before, it's getting messy with all these test helper functions. Therefore I separated code that is not exclusively used in just one test file to separate test files. This PR is entirely code shuffling, no "real" changes.
=> lib/model: Move test utilities to separate files

lib/fs/basicfs_unix.go, lib/fs/basicfs_watch.go, lib/fs/basicfs_windows.go, lib/fs/basicfs_windows_test.go
When checking paths from watches we resolve win83 stuff on the full path including root, but we never checked root itself. Funnily we haven't been bitten by it in production, potentially because of a side-effect of `filepath.EvalSymlinks`. Now we go the save way and treat both the root and paths from watches the same way. Hopefully fixes part of #5706
=> lib/fs: Consider win83 for root path as well when watching (ref #5706)

lib/model/model.go
Fix an obvious logic error in the model when handling `ClusterConfig` messages.  Checking for `IndexID == 0` inside a block where `IndexID != 0` was a precondition.  This should now correctly clear local index data when the remote side announces an IndexID of zero.
Builds okay with this change, and the test suite fails locally for reasons I think are unrelated to this change (same FAILs on master).  I don't know enough about the protocol internals to imagine a real-world test scenario.  The logic error seems clear enough though, causing the intended handling code not to be called.
=> Remove superfluous check for IndexID in remote ClusterConfig.

gui/default/index.html, gui/default/syncthing/core/syncthingController.js, lib/api/api.go, lib/api/mocked_connections_test.go, lib/connections/service.go, lib/connections/structs.go
Aids in understanding why a device is not connecting.
This adds functionality in the connetions service to track the last error per address. That is in turn exposed in the /rest/system/status API method, as that is also where we already show the listener status from the connection service.
The GUI uses this info where it lists addresses, showing errors (if any) in red underneath each address. The time of the last connection attempt is in a tooltip, because there really isn't space to put it somewhere better. :(
I also slightly refactored the existing status method on the connection service to have a better name and return typed information, including an `ok` bool when the `error` is missing, to be clearer and friendlier.
I've only tested this manually. Automated testing of this seems …
=> lib/api, lib/connections, gui: Show connection error for disconnected devices (fixes #3345)

Dockerfile, script/docker-entrypoint.sh
Using the [preferred "exec" form](https://docs.docker.com/engine/reference/builder/#entrypoint) of the ENTRYPOINT directive allows the user to pass additional command line arguments to the `syncthing` command when using `docker run` or `docker create`.
I built a new image and tagged it:
```
% docker build . -t sthing
```
And then ran the image with no options to check that it behaved like before:
```
% docker run sthing
...
[Q3FAA] 21:25:45 INFO: My name is "70dd5dd00c6f"
^C[monitor] 21:25:56 INFO: Signal 2 received; exiting
[Q3FAA] 21:25:56 INFO: Shutting down
[Q3FAA] 21:25:56 INFO: Exiting
```
It was especially important that pressing "CTRL+C" in the terminal continued to deliver the interrupt signal to syncthing. (The `exec` in the entrypoint script takes care of that.)
Then, ran with …
=> docker: Create entrypoint script (fixes #5631)

test/transfer-bench_test.go, test/usage_unix.go, test/usage_windows.go
This is just a bit of polish for the integration transfer benchmarks:  
50000 files took more than 10min on my machine, and 10min is the internal timeout of the supervisor stuff (lib/rc).  
Also transfer rates are so low, that `%.1f`with MiB wasn't particularly useful. And I now print time per MiB instead of total time, to get rid of variation due to slightly varying total MiBs transferred.
=> test: Report time per MiB on transfer benchs

lib/model/model_test.go, lib/model/requests_test.go, lib/model/testutils_test.go
I did some changes on model tests and got weird flaky errors, that turned out to be completely unrelated to these changes, but a test race condition introduced in https://github.com/syncthing/syncthing/pull/5592. This does only affect tests that do the dirty trick of exchange the ignores object in the model map, no problem in code whatsover. Previously it was enough to change the ignores object on model, now we need to make sure we change it after the folder is added, but before it's started, as it is passed to the folder instead of the folder getting it from the model.
I also took the opportunity to move `alwaysChanged` to the utilities file.
=> lib/model: Fix test flakyness regression (ref #5592)

lib/model/fakeconns_test.go, lib/model/model_test.go, lib/testutil/testutils.go, lib/testutils/testutils.go
The added test would have caught a deadlock that in the end resulted in the revert of all these changes (https://github.com/syncthing/syncthing/pull/5688).
lib/testutil is currently only used in model, but I wrote some more tests reproducing e.g. #4170 in lib/protocol which will also use this code. I intentionally put it into lib/testutil not lib/util, as this is code that should never be included in production code. And there's certainly more test helpers useful in many packages, e.g. lib/model/testos_test.go which could go there in the future.
=> lib/model, lib/testutils: Test closing a connection on folder restart

lib/model/model.go, lib/model/model_test.go
The idea is that we notify connected remotes that were stopping instead of just dropping the connection.
=> lib/model: Close connections when model is stopped

lib/model/model_test.go
This fixes the test flakyness "accidentally" introduces in https://github.com/syncthing/syncthing/pull/5733
=> lib/model: Readd special handling of conn close in TestIssue5063

lib/protocol/common_test.go, lib/protocol/protocol.go, lib/protocol/protocol_test.go
We have to make sure, that the receiver/model isn't called after its `Closed` method is called. Due to the blocking nature of the underlying reader, we can't wait for reading to finish. Therefore reading is done in a separate routine and we wait for the routine handling the read message to terminate.
=> lib/protocol: Don't call receiver after calling Closed (fixes #4170)

lib/fs/basicfs.go, lib/fs/basicfs_unix.go, lib/fs/basicfs_watch.go, lib/fs/basicfs_watch_test.go, lib/fs/basicfs_watch_unsupported.go, lib/fs/basicfs_windows.go, lib/fs/basicfs_windows_test.go, lib/fs/errorfs.go, lib/fs/fakefs.go, lib/fs/filesystem.go, lib/fs/logfs.go, lib/model/folder.go
This adds the plumbing necessary to pass errors from a successfully set up watch to whoever receives the events and uses this to pass the outside root error on instead of panicking on it.
The handling on the model/folder side is pretty simple right now and works the same way as watch setup errors: Retry watching every minute and do a full rescan. The rescan is done through the rescan timer, such that we do at most one full rescan per minute, which is the default for folders without watching.
=> lib/fs, lib/model: Add error channel to Watch to avoid panics (fixes #5697)

lib/protocol/protocol.go, lib/protocol/protocol_test.go
As per BEP cluster config should be the first message sent, which is now enforced in protocol package.
=> lib/protocol: Don't send anything else before cluster config

lib/protocol/protocol.go, lib/protocol/protocol_test.go
Flaky tests are not always just annoying, they can also detect negligent mistakes...
https://build.syncthing.net/project.html?projectId=Syncthing&testNameId=1232013402783664888&tab=testDetails
=> lib/protocol: Return from ClusterConfig when closed

lib/model/model_test.go, lib/protocol/protocol.go, lib/protocol/protocol_test.go
Currently sending the close message has the same priority as sending any other message, so might block for a long time (ping timeout, i.e. 90s), same if the underlying connection is not working. If we knowingly close the connection (folder restart or whatever) there's no point in waiting that long. I added `CloseTimeout` variable to set how long we do wait, and set it to 10s, which is simply magic, so feel free to propose another.
=> lib/protocol: Prioritize close msg and add close timeout

gui/default/syncthing/core/syncthingController.js
See https://github.com/syncthing/syncthing/issues/5652 for details. Essentially angular calls functions after the modal is closed for no discernible (to me) reason. This prevents these calls from doing anything (and producing an error in some cases).
Tested manually.
=> gui: Don't call API when no modal is open (fixes #5652) 

gui/default/syncthing/core/syncthingController.js, gui/default/syncthing/folder/editFolderModalView.html, lib/config/folderconfiguration.go, lib/model/folder.go, lib/scanner/walk.go, lib/scanner/walk_test.go
We now always use large / variable blocks.
This also needs a doc update, specific mention in the release notes and, potentially, a notice dialog on first startup? I personally think we *don't* need to do an alert for it, as it's not that big of a deal and it's not particularly actionable by the user anyway.
=> all: Remove "large blocks" config

lib/connections/quic_dial.go, lib/connections/quic_listen.go, lib/connections/quic_misc.go
It's unexpected that `&(*foo)` does not work :/
=> lib/connections: Do not leak FDs, fix address copy (fixes #5767)

lib/fs/basicfs_windows.go, lib/fs/basicfs_windows_test.go
This PR fixes #5609 by circumventing the "access denied" error of `filepath.EvalSymlinks`. In the current implementation of `EvalSymlinks`, it makes a [`FindFirstFile` system call](https://github.com/golang/go/blob/44d3bb998ca00e49d9e0138954287af206b614bf/src/path/filepath/symlink_windows.go#L34) for every ancestor directories. Therefore it will fail if If the user lacks access permission to any of those ancestors.
This PR introduces a fallback method to get the ["normalized"](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-getfinalpathnamebyhandlew#remarks) path from a more suitable WinAPI call, `GetFinalPathNameByHandle` which tries to query the norm path from the file system directly without visiting any ancestor directory. Therefore it can circumvent the above …
=> lib/fs: Fallback EvalSymlinks method on windows (fixes #5609)

lib/model/model.go
And crash reporting is coming in :D 
https://crash.syncthing.net/report/e8/a1/e8a10dcdd334c71b6f020da6a832266ae3c73d6ea9acc106137790bdb17587e5
```
10:01:35 INFO: syncthing v1.1.4 "Erbium Earthworm" (go1.12.5 linux-amd64) teamcity@build.syncthing.net 2019-05-12 19:17:55 UTC
Panic at 2019-06-05T10:33:43+02:00
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0xa65a3d]
goroutine 5911 [running]:
github.com/syncthing/syncthing/lib/model.(*model).ScanFolders.func1(0xc0001ca2c0, 0xc000358730, 0xb, 0xf18b20, 0xc000d15860, 0xc000c015f0, 0xf1eba0, 0xc000d15870)
/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/model/model.go:2020 +0x1ad
created by github.com/syncthing/syncthing/lib/model.(*model).ScanFolders …
```
=> lib/model: Prevent nil deref if folder stopped (fixes #5780)

etc/linux-systemd/user/syncthing.service
Systemd service hardening options related to mount namespaces are unsupported for Systemd user instances.
The Systemd documentation has been updated to reflect this: 
> This option is only available for system services and is not supported for services running in per-user instances of the service manager.
https://www.freedesktop.org/software/systemd/man/systemd.exec.html
Note that this has no impact and the options are simply ignored, so remove them for clarity.
=> Remove Systemd hardening options unsupported in user mode

build.go
Our currently calculated coverage is quite a bit lower than it actually is, as go by default only considers coverage of the currently tested package even if many packages are given (as in our case with `lib/...`). On my system this change doesn't work, I reported it upstream at https://github.com/golang/go/issues/30374#issuecomment-493425265. If this passes it proofes something is broken on my side and we can use it, otherwise it works as another data point for the upstream issue.
=> build: Include cross-package test coverage

gui/default/syncthing/core/syncthingController.js
Yet another check that shouldn't be necessary, but apparently is:  
When shutting down Syncthing from the web UI, I get a JS error:
```
Error: data.reverse is not a function
refreshGlobalChanges</<@http://localhost:8385/syncthing/core/syncthingController.js:729:24
$http/promise.success/<@http://localhost:8385/vendor/angular/angular.js:9452:11
processQueue@http://localhost:8385/vendor/angular/angular.js:13337:27
scheduleProcessQueue/<@http://localhost:8385/vendor/angular/angular.js:13353:27
$eval@http://localhost:8385/vendor/angular/angular.js:14589:16
$digest@http://localhost:8385/vendor/angular/angular.js:14405:15
$apply@http://localhost:8385/vendor/angular/angular.js:14694:13
scheduleApplyAsync/applyAsyncId<@http://localhost:8385/vendor/angular/angular.js:14984:11 …
```
=> gui: Check data before calling .reverse()

gui/default/assets/css/overrides.css
break table layout and add button margin on small screens
Optimize GUI for small screens
manual UI tests
=> gui: Optimize folder/device info for small screens (fixes #5774)

cmd/syncthing/main.go, lib/db/lowlevel.go
This adds a 10s timeout on closing the db and additionally cancels active
db iterators and waits for them to terminate before closing the db.
@calmh I hope the amount of introduced complications passes below the bar - I am actually quite happy with it, but I suspect mine is also a bit high :)
=> cmd/syncthing, lib/db: Exit/close db faster (fixes #5781)

lib/model/model_test.go, lib/versioner/simple.go, lib/versioner/staggered.go, lib/versioner/staggered_test.go, lib/versioner/trashcan.go, lib/versioner/trashcan_test.go, lib/versioner/util.go
Idk, wrote the code, tests pass, did not test.
The problem is that version restoration now happens based on mtime of the file not the name, so restoring requires looking up all versions.
=> lib/versioner: Fix staggered version cleanup and all versioner restoration (fixes #5807)

lib/model/folder_sendrecv.go
The previous `itemChanged` already scheduled scanning, but the same was done on the caller side in most places (which isn't problematic, but useless).  I made that behaviour explicit by calling it `scanIfItemChanged`. And it now returns `errModified` if it was changed in case the caller wants to know about that, shortening the code in many places.
=> lib/model: Correct/unify check if item changed

lib/model/model.go
This change is motivated by a particular fmut lock panic, e.g. https://sentry.syncthing.net/syncthing/syncthing/issues/29/events/3325/:
```
[many more levels in goleveldb]
github.com/syndtr/goleveldb/leveldb.(*Snapshot).Get(0xc000d592f0, 0xc000c5b450, 0x5e, 0xca, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
C:/BuildAgent/work/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190318030020-c3a204f8e965/leveldb/db_snapshot.go:113 +0x162
github.com/syncthing/syncthing/lib/db.(*instance).checkGlobals(0xc000cd7c80, 0xc0001e3120, 0x10, 0x10, 0xc0006166c0)
C:/BuildAgent/work/174e136266f8a219/lib/db/instance.go:467 +0x629
github.com/syncthing/syncthing/lib/db.(*FileSet).recalcCounts(0xc000616480)
C:/BuildAgent/work/174e136266f8a219/lib/db/set.go:94 +0x10e
github.com/syncthing/syncthing/lib/db.NewFileSet(0xc000072cc0 …
```
=> lib/model: NewFileSet outside fmut

cmd/stcrashreceiver/sentry.go, cmd/stcrashreceiver/sourcecodeloader.go
One complication is that in our production builds the paths that hit the loader look like "/opt/tcagent/syncthing-1-work/174e136266f8a219/lib/db/lowlevel.go" which doesn't contain our package path nor a clear marker for where the "root" directory is. I opted instead to look for the /lib/ or /cmd/ component which is always present somewhere in our packages.
It appears to work:
=> cmd/stcrashreceiver: Add source code loader

gui/default/index.html, gui/default/syncthing/core/syncthingController.js, lib/model/folder_summary.go, lib/model/model.go
As usual with the web UI this wasn't as straight forward than I though, but this time the reason was in the model: Folder summaries are not sent on download progress events, but they do include information from download progress events. So if one wants to account download progress in the web UI, there's no way to know which download progress events are already accounted for in the last folder summary and which are not. Solution: Don't account download progress in folder summary. Anyone who wants the fine grained updates can do that subscribing to folder summaries and download progress events.
And I noticed the syncing status without a percentage at the end of a sync. In my opinion it's better to say that we are syncing at 100% (deleting stuff) than just syncing with no info, as the latter …
=> gui, lib/model: Fix download progress accounting (fixes #5811)

go.mod
I locally updated to the go1.13 beta and now the go toolchain always adds this annoying `go 1.13` line to the end of go.mod. I am bound to accidentally include that at some point through `git commit -a`. This behaviour disappears if I manually add `go 1.12` to go.mod. I have no clue what this does, I found no documentation on it at all and the only reference I found was in a tutorial, writing (emphasis mine):
> It created a go.mod file which contains the module import path and **version of the Go this module was created on**.
https://medium.com/rungo/anatomy-of-modules-in-go-c8274d215c16
So I assume this won't do any harm and it will prevent me from adding some kind of a reference to a beta go version into Syncthing.
If anyone knows what this line is about or how its appearance can be …
=> build: Add go major version to go.mod

go.mod, go.sum
We have notify related panics in sentry, so I looked at whether upstream had changes. There's been one fix for the windows file watcher, that doesn't seem related to the panic we have, but nevertheless it's good to have the fix in our builds.
=> build: Update notify dependency

lib/relay/client/dynamic.go
The problem was hidden in plain sight. Luckily spinning up a test instance for entirely different reasons triggered a relay error and thus an unexpected crash:
```
runtime: goroutine stack exceeds 1000000000-byte limit
fatal error: stack overflow
runtime stack:
runtime.throw(0xd8d6cc, 0xe)
/media/ext4_data/Linux/source/go/src/runtime/panic.go:758 +0x72
runtime.newstack()
/media/ext4_data/Linux/source/go/src/runtime/stack.go:1046 +0x6e9
runtime.morestack()
/media/ext4_data/Linux/source/go/src/runtime/asm_amd64.s:449 +0x8f
goroutine 209 [running]:
sync.(*RWMutex).RLock(0xc00003a680)
/media/ext4_data/Linux/source/go/src/sync/rwmutex.go:43 +0x5e fp=0xc0229b8340 sp=0xc0229b8338 pc=0x46ffae
github.com/syncthing/syncthing/lib/relay/client.(*dynamicClient).Error(0xc000442000, 0x0, 0x0) …
```
=> lib/relay: Call the proper Error method (ref #5806)

lib/db/instance.go, lib/model/model.go
Takes care of the "Wrong" cases in #5839, does not address the borderline ones. And is based on manual scanning of `grep "panic("` output, so hopefully I did catch all occurrencies, but not certainly.
=> lib/db, lib/model: Remove folder info from panics (ref #5839)

lib/model/folder.go
The first thing that happens when a folder is started is also starting the filesystem watching, so there will be a meaningful or no error almost immediately. There's no reason to have an artificial "watch not yet started" error. While at it I also simplified some related, tangential stuff and fixed one minor bug (comment in diff).
=> lib/model: Remove pointless error that watch hasn't started (fixes #5833)

lib/versioner/external.go
This commit adds support for a new placeholder, %FILE_PATH_FULL%, to the
command of the external versioner. The placeholder will be replaced by
the absolute path of the file that should be deleted.
I want syncthing to move deleted file versions to the [FreeDesktop.org Trash](https://specifications.freedesktop.org/trash-spec/trashspec-1.0.html). There is already a set of scripts, [trash-cli](https://github.com/andreafrancia/trash-cli), that can be used to interact with the trash on command line, but it requires the absolute path of the file that should be moved to trash. If the existing placeholders were used, a wrapper script would be required, because constructs like `"%FOLDER_PATH%/%FILE_PATH%"` are not supported. By using the new placeholder, no wrapper script is necessary: …
=> lib/versioner: Replace all placeholders in external command (fixes #5849)

lib/model/folder_sendrecv.go, lib/model/model.go
The first one is just an unnecessary conversion from  int to int that I discovered while grepping for `int(` and `int32(`. The other two cases are the problematic ones identified by @calmh in #5837.
=> lib/model: Fix integer conversion (fixes #5837)

cmd/strelaysrv/status.go, lib/protocol/counting.go, lib/scanner/walk.go, lib/stun/stun.go
There was really nothing to fix, as I checked the entire code base and **all** atomically accessed 64-bit variables (via sync/atomic) **are** actually 64-bit aligned.
This is the commit message:
Per the [`sync/atomic` bug note](https://golang.org/pkg/sync/atomic/#pkg-note-BUG):
> On ARM, x86-32, and 32-bit MIPS, it is the caller's
> responsibility to arrange for 64-bit alignment of 64-bit words
> accessed atomically. The first word in a variable or in an
> allocated struct, array, or slice can be relied upon to be
> 64-bit aligned.
All atomic accesses of 64-bit variables in syncthing code base are
currently ok (i.e they are all 64-bit aligned).
Generally, the bug is triggered because of incorrect alignement
of struct fields. Free variables (declared in a function) are
guaranteed to be …
=> all: add comment to ensure correct atomics alignment (closes #5813)

lib/api/api_test.go, lib/config/config.go, lib/config/config_test.go, lib/config/folderconfiguration.go, lib/config/testdata/dupdevices.xml, lib/config/testdata/dupfolders.xml, lib/config/testdata/ignoredfolders.xml, lib/config/testdata/pullorder.xml
Throw an error while cleaning/checking the config if a folder path is empty, as that's simply not valid. Currently we just ignore/mask it by not creating a filesystem and hoping nobody will ever do it, but panic reporting says it happens (#5853). 
There's a test explicitly checking that an empty folder path is accepted and blame points at this PR/issue: https://github.com/syncthing/syncthing/issues/2471 https://github.com/syncthing/syncthing/pull/3370 Allowing the folder path to be empty seems to be a tangential change there and it talks about "folders being invalid". I don't even know what that concept was, it certainly doesn't exist anymore so I don't think this contains any reason to block this change in behaviour (disallowing empty folder path in config).
=> lib/config: Error on empty folder path (fixes #5853)

lib/model/model.go, lib/protocol/protocol.go
This change has a few connected elements:
1. Stopping a folder now waits on the closed connections to stop before removing the folder elements from the model (this is the actual fix of #5828).
2. The utility function closing connections now returns the closed channels of these connections, such that the caller can wait on them if required (convenience and doing both things (closing and getting closed channels) under the same lock).
3. Speed up calls to `protocol.Close` and sending close messages in the protocol:  
Close now spawns a goroutine for both sending the close message and closing, while before it spawned the goroutine just for closing after sending the message. Thus the caller can quicker go on with whatever else it needs to do and if it needs to wait, it already now has to wait …
=> lib/model, lib/protocol: Track closing connections (fixes #5828)

cmd/syncthing/main.go, go.mod, lib/syncthing/auditservice.go, lib/syncthing/auditservice_test.go, lib/syncthing/cpuusage.go, lib/syncthing/cpuusage_solaris.go, lib/syncthing/cpuusage_unix.go, lib/syncthing/cpuusage_windows.go, lib/syncthing/debug.go, lib/syncthing/superuser_unix.go, lib/syncthing/superuser_windows.go, lib/syncthing/syncthing.go, lib/syncthing/syncthing_test.go, lib/syncthing/verboseservice.go
Just in case anyone is bored ( :P ) this is a stab at a first step for refactoring cmd/syncthing. It does not tackle any of the hard problems (logging), it just adds an interface to start the "Syncthing application" and separates things done in cmd (env vars, loading config, ...) and in the application itself.
And this separation is one point of discussion, because it's pretty clear in some cases, but pretty arbitrary in other. One "underlying motivation" for decisions was, to limit interactions with filesystem or OS in general on the lib side and keep the interface simple. I marked items which I could just as well see in the other category with (?). A probably non-exhaustive list:
cmd:
- Loading config from file
- Parsing command line options and env vars.
- Handling signals
- (?) CPU …
=> all: Refactor cmd/syncthing creating lib/syncthing (ref #4085)

cmd/syncthing/main.go, cmd/syncthing/monitor.go, lib/config/config.go, lib/config/config_test.go
The global `myID` variable was never set. To prevent that from happening, I removed the global variable and pass `myID` around where necessary and call with `protocol.DeviceID{}` where the ID doesn't matter (upgrade checks and such) to make the behaviour explicit.
=> cmd/syncthing: Ensure myID is set by making it local (fixes #5859)

lib/relay/client/dynamic.go, lib/relay/client/static.go
We were always adding a bunch of empty relays, I guess we just didn't
use to print errors about them.
=> lib/relay: Prevent spurious relay error message (fixes #5861)

lib/syncthing/syncthing.go
Before we waited for the service to stop before setting its exit status, which means anyone that called `Run` or `Wait` before gets the wrong exit status.
Restarting from UI now works.
=> lib/syncthing: Modify exit status before stopping (fixes #5869)

lib/beacon/beacon.go, lib/beacon/broadcast.go, lib/beacon/multicast.go, lib/nat/registry.go, lib/nat/service.go, lib/relay/client/dynamic.go, lib/stun/stun.go, lib/util/utils.go
Now instead of various services not terminating at all or only after like forever, everything shuts down more or less immediately. Beware this is late-night-iterating between fixing something, getting another trace, fixing the next hangup, ... - some of my approaches taken are probably on the crude/heavy-handed side, but they seem to be working, so it's at least a basis to improve on.
=> lib: Ensure timely service termination (fixes #5860)

lib/syncthing/auditservice.go, lib/syncthing/auditservice_test.go, lib/syncthing/syncthing.go, lib/syncthing/verboseservice.go
This is a an unrelated side-effect to working on un-globalifying events. The only difference except using `util.AsService` is that I now subscribe to events in the constructor thus the whole `WaitForStart` business is not required anymore, as the service already listens for events after construction. And Unsubscribe happens in `Stop`, not deferred on `serve`, as suture might restart the service (serve being called multiple times).
=> lib/syncthing: Refactor to use util.AsService

lib/model/folder_sendonly.go, lib/model/model.go
This PR removes the following two panics:
https://sentry.syncthing.net/share/issue/36dca98f1c154311b1e868aaa07e4ccc/  
https://sentry.syncthing.net/share/issue/0203181ba1674e1ba4f1d54929eee492/  
The one in folder_sendonly is simply useless, as it doesn't represent an unrecoverable/dangerous state nor does it provide useful info to find out why it happens. Without throwing a panic that item might be incorrectly shown as out-of-sync in the UI, but that's better than a panic, as the user could report that to us and we might be able to find out why it happens.
In model we previously did check the wrapper when starting a folder. That's incorrect, as starting a model is triggered by the wrapper, but at the point that we actually do it the wrapper might already be updated again. Simply ignoring …
=> lib/model: Remove incorrect/useless panics

lib/fs/basicfs_watch_eventtypes_kqueue.go
> The problem might related to this comment (https://github.com/rjeczalik/notify/blob/master/watcher_kqueue.go#L157):
> ```
> 		// Create event is not supported by kqueue. Instead NoteWrite event will
> 		// be registered for a directory. If this event will be reported on dir
> 		// which is to be monitored for Create, dir will be rescanned
> 		// and Create events will be generated and returned for new files.
> 		// In case of files, if not requested NoteRename event is reported,
> 		// it will be ignored.
> ```
> 
> We use platform specific events, not the cross-platform `notify.Create` which is created "synthetically" according to this comment. I'll investigate whether it's fine to mix both.
Looking at the event description in the notify library I think we also need to subscribe to …
=> lib/fs: Fix kqueue event list (fixes #5308)

lib/model/model.go
It's fine to temporarily let go of fmut, we do it also while tearing down the folder and possibly other places. There's a restart mutex held during the entire process.
=> lib/model: Create new file-set after stopping folder (fixes #5882)

go.mod, go.sum, lib/config/folderconfiguration.go, lib/db/db_test.go, lib/db/set_test.go, lib/model/folder.go, lib/model/folder_sendonly.go, lib/model/folder_sendrecv.go, lib/model/model_test.go, lib/protocol/bep_extensions.go, lib/protocol/protocol_test.go, lib/scanner/walk.go
This is a product of https://forum.syncthing.net/t/ignore-permissions-different-mtimes-on-android-sdcard/13342 - I am not aware of an issue for this, please point me to it if it already exists.
This adds the folder config option "ModTimeWindowS" and uses this in the functions to compare file infos, which in turn are used when scanning or checking files on disk when pulling. When a folder is `prepare`d I use https://github.com/shirou/gopsutil to get the fs type and set the window to 2s (if not already at 2s or bigger). It's quite likely that this will fail on android, so currently it's likely on the android wrappers to set the correct window. If there's a better option to get the fs type or otherwise decide on whether to use a window or not, than using a secondary feature of this package, …
=> lib: Add mtime window when comparing files

cmd/syncthing/main.go, lib/syncthing/syncthing.go, lib/syncthing/utils.go
https://github.com/syncthing/syncthing/issues/4085#issuecomment-512351134:
> I've noticed that there are still a few things in main.go which would be desirable to have in the library as well. Checkout c_bindings.go of my tiny C wrapper and you will spot the code I've just copied and pasted from main.go. That is of course not a good solution. I haven't copied over code for handling previous config file versions and cleaning up the config directory but that would be useful, too.
Expose those tasks as utility functions in lib/syncthing and move those utilities to `lib/syncthing/utils.go`.
Start and stop test instance.
=> cmd/syncthing, lib/syncthing: Create library utils (ref #4085)

lib/db/lowlevel.go
This adds a set of magical environment variables that can be used to
tweak the database parameters. It's totally undocumented and not
intended to be a long term or supported thing.
It's ugly, but there is a backstory. I have a couple of large
installations where the database options are inefficient or otherwise
suboptimal (24/7 compaction going on and stuff like that). I don't
*know* the correct database parameters, nor yet the formula or method to
derive them by, so this requires experimentation. Experimentation needs
to happen partly in production, and rolling out new builds for every
tweak isn't practical. This provides override points for all reasonable
values, while not changing anything by default.
Ideally, at the end of such experimentation, we'll know which values are
relevant to …
=> lib/db: Add hacky way to adjust database parameters

lib/config/wrapper.go, lib/model/model.go
Wrapper methods generally don't save by themselves.
=> lib/config, lib/model: Don't save on every pending folder/device update (fixes #5888)

lib/api/api.go
We never stopped the `http.Server` in the API on stops or restarts due to config changes. Due to closing connections on model stop and all the stuff about graceful stopping, this meant events were sent after `/rest/system/shutdown` succeeded, which set the web UI back to online.
Tested shutdown, restart and config change (through theme).
=> lib/api: Close server before exiting serve (fixes #5866)

cmd/stcrashreceiver/stcrashreceiver.go
This changes the on disk format for new raw reports to be gzip
compressed. Also adds the ability to serve these reports in plain text,
to insulate web browsers from the change (previously we just served the
raw reports from disk using Caddy).
=> cmd/stcrashreceiver: Store and serve compressed reports

lib/model/requests_test.go
https://build.syncthing.net/project.html?projectId=Syncthing&testNameId=-1297911307479147500&tab=testDetails
When pulling the test encounters a file that has changed, thus scanning is scheduled before pulling again and getting the remote file. This means for the same file there's two updates locally, one from scanning that's immediately superseded with one from pulling. In a reasonably fast scenario the index update is only sent for the final version, but it's totally fine if the intermediate version is sent too, but that wasn't allowed in the tests before.
=> lib/model: Fix flakyness of TestRequestRemoteRenameChanged

lib/syncthing/syncthing.go
Besides the once to prevent closing multiple times I also moved assigning `a.err` into that new once, as it technically could race with `Error`.
=> lib/syncthing: Stop only once (fixes #5908)

lib/model/requests_test.go
>  A test ends when its Test function returns or calls any of the methods FailNow, Fatal, Fatalf, SkipNow, Skip, or Skipf. Those methods, as well as the Parallel method, must be called only from the goroutine running the Test function.   
> https://golang.org/pkg/testing/#T
In some places I just replaced `Fatal` with `Error` (when the test finishes anyway after or it's just a "fail-safe" condition that anyway never should be triggered), in other's I moved the code that calls `Fatal` outside of the goroutines.
=> lib/model: Don't call t.Fatal in goroutines (fixes #5901)

cmd/syncthing/blockprof.go, cmd/syncthing/heapprof.go, cmd/syncthing/monitor.go, lib/config/config.go, lib/locations/locations.go, lib/model/folder_sendrecv.go, lib/model/sharedpullerstate.go, lib/model/util.go, lib/model/utils_test.go
I replaced all panics containing an error in any form, except for serialization and db stuff.
The first commit is entirely dedicated to shared puller states, where a comment claims that it needs to duplicate `inWritableDir`, but I fail to see how. They do use `fs.ModePerm` and do not change permissions if they are ignored, but the fromer is something that should also happen in all other places and the latter is in my opinion wrong: We should still try to follow "leave no trace", but not complain if it fails.
And `lib/locations` does not use logger, so I used plain `fmt.Println` to emit the error before panicking for simplicity. Is that fine or might the crash parsing choke on that?
=> all: Remove potentially problematic errors from panics (fixes #5839)

lib/connections/relay_listen.go
Currently a fatal relay listening error can go undetected (well maybe debug logging in lib/relay, but even if), and the only indication the user is presented with is the suture supervisor logging like in https://github.com/syncthing/syncthing/issues/5915:
```
2019-07-31 16:01:30 c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (2.745697 failures of 2.000000), restarting: false, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
```
This adds logging of an error at `Info` level, and "demotes" the existing logging on relay client creation error from `Warning` to `Info` level. It is just a failing relay, not really something to notify the user …
=> lib/connections: Log errors in relay clients

gui/default/syncthing/core/syncthingController.js
The check if config has unsaved changes compares `tmpOptions` to `config.options`, but only the latter got the updated values from `_listenAddressesStr` into `listenAddresses`. Tested manually.
=> gui: Parse strings before copying options object (fixes #5824)

lib/stun/stun.go
NATSymmetricUDPFirewall actually is not NAT at all, but means the machine has a global IP address and an UDP firewall in front (RFC calls it Symmetric UDP Firewall). This is punchable fine, both theoretically and also practically in testing.
See https://forum.syncthing.net/t/issues-with-quic-transport/13590/6 , this allows to use QUIC also for hosts which are behind an UDP firewall with a global IP address. 
I tested with a host behind a `NATSymmetricUDPFirewall` and after the change, punching worked fine. 
to the corresponding pull request on https://github.com/syncthing/docs or describe
the documentation changes necessary.
based on …
=> Add NATSymmetricUDPFirewall to punchable NATs

go.mod, go.sum, lib/connections/quic_dial.go, lib/connections/service.go, lib/connections/structs.go, lib/connections/tcp_dial.go
Duplicates some checks, but meh.
=> lib/connections: Validate device id before assuming success (fixes #5934)

lib/model/model.go
While looking at the trace in https://github.com/syncthing/syncthing/issues/5929 I noticed that there's nothing accessed in `ConnectionStats` that's protected by `fmut` and getting a `runner` should only acquire a read lock.
=> lib/model: Fix incorrect locking

lib/tlsutil/tlsutil.go
They are arguable outdated and we are better off trusting the standard
library than trying to keep up with it ourselves.
=> lib/tlsutil: Remove hardcoded curve preferences (fixes #5940)

lib/model/model.go
Looking at the trace in https://github.com/syncthing/syncthing/issues/5929 again, `ClusterConfig` is waiting to acquire a write-lock - this seems like a very good candidate for causing the unresponsiveness/lots of goroutines trying to acquire a lock. I don't see any reason for it to be a write lock, nor for holding the lock over the entire function - the only protected thing that's accessed is `m.folderFiles` in the first loop. So essentially this seems like a correct and obvious change to me, but still a somewhat scary one.
=> lib/model: Less locking in ClusterConfig

lib/api/mocked_connections_test.go, lib/connections/service.go
Bot complained in https://github.com/syncthing/syncthing/pull/5886 that we return an unexported object from an exported function. Fixing that requires adding another interface to `connections.Service`, which is already implemented by `*connections.service` (also line breaking :) ).
=> lib/connections: Return exported intf from exported function

lib/config/folderconfiguration.go
This is relevant to the current RC.
=> lib/config: Prevent nil deref in debug logging (fixes #5955)

lib/model/folder_sendrecv_test.go, lib/model/model.go, lib/model/sharedpullerstate.go
There is no deadlock here, but if a write operation takes really long, that can block `model.pmut` (see https://forum.syncthing.net/t/new-panic-v1-2-2-rc2/13647/2). This PR breaks this "lock-linking" in two places:
1. Separate locks for `sharedPullerState` and the contained file-descriptor. Thus really long writes do not block simple, but often used methods like `.Updated` or `Progress`.
2. Release `pmut` before calling `progressemitter.temporaryIndexUnsubscribe`.
=> lib/model: Optimise locking around conn-close and puller states

cmd/stupgrades/main.go
This is a tiny tool to grab the GitHub releases info and generate a
more concise version of it. The conciseness comes from two aspects:
- We select only the latest stable and pre. There is no need to offer
upgrades to versions that are older than the latest. (There might be, in
the future, when we hit 2.0. We can revisit this at that time.)
- We use our structs to deserialize and reserialize the data. This means
we remove all attributes that we don't understand and hence don't
require.
All in all the new response is about 10% the size of the previous one and
avoids the issue where we only serve a bunch of release candidates and
no stable.
=> cmd/stupgrades: Generate appropriate upgrade data (fixes #5924)

lib/rc/rc.go, test/filetype_test.go, test/h1/config.xml, test/h2/config.xml, test/h3/config.xml, test/override_test.go, test/reset_test.go, test/symlink_test.go
Integrations tests were broken due to removing the global event logging. And after fixing that, TestReset failed. Turns out it was racy between the first instance stopping and the second starting and the recent changes that wait for services to terminate before exiting made that race tip towards failure -> added a method to rc wait for Syncthing to stop. Also took the opportunity to update configs.
=> test: Update integration tests (config, build and test fixes)

lib/beacon/beacon.go, lib/beacon/broadcast.go, lib/beacon/multicast.go, lib/discover/local.go
Run methods as services instead of just kicking off a goroutine that will never stop.
=> lib/discover: Don't leak goroutines

lib/ignore/ignore.go, lib/ignore/ignore_test.go
If the line is just "#include" with nothing following it we would crash
with an index out of bounds error. Now it's a little more careful.
=> lib/ignore: Don't crash in partial #include line (ref #5985)

lib/model/folder.go
Assume a folder error was set due to bad ignores on the latest scan.
Previously, doing a manual rescan would result in:
1. Clearing the folder error, which schedules (immediately) an fs
watcher restart
2. Attempting to load the ignores, which fails, so we set a folder
error and bail.
3. Now the fs watcher restarts, as scheduled, so we trigger a scan.
Goto 1.
This change fixes this by not clearing the error until the error is
actually cleared, that is, if both the health check and ignore loading
succeeds.
=> lib/model: Correctly handle manual rescan with ignore error (fixes #5985)

build.go, cmd/stdiscosrv/database.pb.go, go.mod, go.sum, lib/db/structs.pb.go, lib/discover/local.pb.go, lib/protocol/bep.pb.go, lib/protocol/deviceid_test.pb.go
This is the result of:
- Changing build.go to take the protobuf version from the modules
instead of hardcoded
- `go get github.com/gogo/protobuf@v1.3.0` to upgrade
- `go run build.go proto` to regenerate our code
It could still connect to at least one device using the old code.
=> build: Upgrade github.com/gogo/protobuf

lib/connections/limiter.go, lib/connections/limiter_test.go
This splits large writes into smaller ones when using a rate limit,
making them into a legitimate trickle rather than large bursts with a
long time inbetween.
Unit test to make sure the end result is correct and I didn't fumble the offsets or whatnot.
=> lib/connections: Improve write rate limiting (fixes #5138)

lib/api/api.go, lib/api/api_auth_test.go, lib/api/api_csrf.go, lib/api/api_test.go
This is an experiment in testing, based on the advise to always call
t.Parallel() at the start of every test. Doing so makes tests run in
parallel, which is usually faster, but also exposes package level state
and potential race conditions better.
To support this I had to redesign the CSRF manager to not be package
global, which was indeed an improvement. And tests run five times faster
now.
=> lib/api: Refactor to run tests in parallel

build.go
Allow extending LDFALGS by setting EXTRA_LDFLAGS to be able to pass
-extldflags=-zrelro -ldflags=-extldflags=-znow for Arch Linux packaging
to get full relro.
Implements: #5999
fixes #5999 
Detect that relro is fully enabled.
```
checksec --file=./bin/syncthing
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH	Symbols		FORTIFY	Fortified	Fortifiable  FILE
Full RELRO      Canary found      NX enabled    PIE enabled     No RPATH   No RUNPATH   28521 Symbols     Yes	0		2	./bin/syncthing
```
Adds an EXTRA_LDFLAGS env variable which is able to extend the passed LDFLAGS to go build.
=> Allow extending of LDFLAGS in build.go

lib/db/instance.go, lib/db/set_test.go, lib/model/folder.go
This PR fixes a bug reported in https://forum.syncthing.net/t/problem-with-post-ignoring-a-file-sendonly-recvonly/13749, the issue should be created soon. It's here: #6008
The problem is, that it's not enough to check `IsInvalid` to decide whether a file info has changed, as it remains true if local flags change from local changed to ignored. However the difference is relevant and should be committed.
I added a unit test.
And the debug log fix in model is just something I noticed when reproducing the issue.
=> lib/db: Update db when only local flags change (fixes #6008)

lib/config/config.go
fixes #6010
Remove stun.voxgratia.org from the list of secondary STUN servers.
=> Remove stun.voxgratia.org STUN server

lib/fs/basicfs.go, lib/fs/basicfs_unix.go, lib/fs/basicfs_watch.go, lib/fs/basicfs_watch_test.go, lib/fs/basicfs_windows.go, lib/fs/basicfs_windows_test.go
This PR is a reaction to the following report:  
https://forum.syncthing.net/t/bug-report/13777  
```
2019-09-06 22:51:11: Watching for changes encountered an event outside of the filesystem root: f.root==\?\C:\Etc\Dev, root==\?\f:\dev, path==\?\c:\etc\dev. This should never happen, please report this message to forum.syncthing.net
```
I have no clue why and how it's possible that given the "real" path (no junctions) the windows watcher sometimes returns events for the "linked" path and the "real" path. So I extended the existing path juggling around watches to check against both the folder root as specified by the user and the folder root after applying "canonicalization" steps on it (`os.EvalSymlinks` and syscall stuff).
=> lib/fs: Check events against both the user and eval root

Dockerfile, README-Docker.md, README.md
Enable control of the GUI listener from Docker.
I ran the Docker image with `-e STGUIADDRESS=` and observed changes.
=> docker: Make it easy to disable the GUI, document it

lib/fs/basicfs_unix.go, lib/fs/basicfs_watch_test.go
The root check would allow things like c:\foobar\baz if the root was
c:\foo, because string wise that's a prefix. Now it doesn't.
=> lib/fs: Improve root check

lib/model/folder.go, lib/model/requests_test.go
Drop the entire version instead of just counters from others when un-ignoring a deleted item. This makes the behaviour consistent, in that files deleted locally do not get deleted on the entire cluster regardless of whether it was ever modified on any other device than the local one.
I added a new test for the scenario described in https://github.com/syncthing/syncthing/issues/6038 and had to adjust two existing tests, which explicitly checked for only the local counter being preserved in the vector. They now check that the vector is empty.
=> lib/model: Set empty version when unignoring deleted files (fixes 6038)

lib/db/lowlevel.go
Avoid apparent issues with large db settings on 32 bit archs.
(This is probably a goleveldb bug but I don't have the time/inclination to troubleshoot it.)
⁉️
=> lib/db: Always use small db settings on 32 bit archs

lib/api/api.go
Report what we're actually listening on, not just the string we were told to listen on.
Verified that it behaves as expected with `:1234` (gets auth warning) and `localhost:1234` (no auth warning). Also looked at the output of /rest/system/status.
New struct attribute isn't super pretty. It's race free because it's set in serve() and only accessed from routines started by server(). I tried the alternative to make the system status handler a closure that takes the address but that was more changes and even uglier.
=> lib/api: Report actual listener address (fixes #6049)

cmd/syncthing/debug.go, lib/api/debug.go, lib/beacon/debug.go, lib/config/debug.go, lib/connections/debug.go, lib/db/debug.go, lib/dialer/internal.go, lib/discover/debug.go, lib/events/debug.go, lib/fs/debug.go, lib/logger/logger.go, lib/model/debug.go, lib/nat/debug.go, lib/pmp/debug.go, lib/protocol/debug.go, lib/rc/debug.go, lib/relay/client/debug.go, lib/scanner/debug.go, lib/stats/debug.go, lib/stun/debug.go, lib/sync/debug.go, lib/syncthing/debug.go, lib/upgrade/debug.go, lib/upnp/debug.go, lib/ur/debug.go, lib/versioner/debug.go, lib/watchaggregator/debug.go
There are a lot of similar SetDebug calls which can be integrated into NewFacility. This pull request should not change behavior. I tested it with some, but not all facilities.
=> all, lib/logger: Refactor SetDebug calls

cmd/stdiscosrv/apisrv.go
Traefik 2 do not use the same header as nginx to pass client tls certificate (https://docs.traefik.io/middlewares/passtlsclientcert/). This PR add support for Traefik 2.
Also improve Nginx compatibility by adding $ssl_client_escaped_cert support (http://nginx.org/en/docs/http/ngx_http_ssl_module.html#var_ssl_client_escaped_cert replacement for $ssl_client_cert http://nginx.org/en/docs/http/ngx_http_ssl_module.html#var_ssl_client_cert which is deprecated).
Has been tested with a discovery server and both Traefik and Nginx reverse proxy.
Config file as below (client can use port 8443 to test Traefik and 9443 to test with Nginx) except certificate for nginx.
Docker image could be found here: https://hub.docker.com/r/cyprienoccitech/docker-discosrv
docker-compose.yml
```
version: '3.4' …
```
=> add support for Traefik 2 as reverse proxy

snapcraft.yaml.template
Without the desktop plug, launching the syncthing snap will not launch a browser window to the admin UI. Adding this one line will fix that. Tested here on my Ubuntu system with a build from tip of master.
When launching syncthing from the snap, the web UI admin tool is not launched. This is due to a missing security interface called `desktop`. Adding this interface (plug) grants permission to enable syncthing to launch xdg-open which in turn opens the web UI in a browser tab. 
I built the snap in a clean Ubuntu 16.04 lxc container, and installed the resulting snap on my Ubuntu 19.10 laptop. The resulting build successfully launches the web UI in a new tab on my default browser. 
I used the following command to build the snap
`go run build.go -goos linux -goarch amd64 snap`
Then installed …
=> Add desktop plug

gui/default/syncthing/folder/editFolderModalView.html
When there is no devices, selection buttons are available. Changes in this PR, hide buttons and help-block, in this case.
Manual testing
[Screenshot - after fix](https://imgur.com/gpQY1lw)
=> EditFolderModalView: Not display selection buttons in case of there is no devices (fixes #6056)

.golangci.yml
Per golang 1.13.1 upgrade, did some cleanup as well as upgrade golangci (v1.18.0 starting supporting go v1.13)
n/a
N/A
No user facing changes.
Relates to https://github.com/Homebrew/homebrew-core/pull/44765
=> build: Update golangci for go v1.13

go.mod, lib/api/api.go, lib/db/set.go, lib/db/structs.go, lib/protocol/bep_extensions.go
This should have been a tiny change to make `/rest/db/file` output a string for the file-type, like e.g. `/rest/db/need` already does. On the way I got rid of some duplication, which required extending `db.FileIntf`. And while at it I renamed `JSONDBFileInfo` to `JSONFileInfoTrunc`.
Checked that output of `/rest/db/file` indeed does print the file info as a string.
=> lib: Unify JSON marshalling of file infos in api

lib/util/utils.go, lib/util/utils_test.go
If something goes wrong with a service (e.g. #5932) there's no information about what created the service. This adds this information by retrieving the first stack frame outside of the `lib/util` package. Currently it is used to implement `fmt.Stringer` and printed if `Stop` is called more than once.
=> lib/util: Add caller info to service (ref #5932)

gui/default/index.html, gui/default/syncthing/core/syncthingController.js, lib/model/folder_sendrecv.go, lib/model/folderstate.go
See #6027:
> This issue is a companion to https://forum.syncthing.net/t/i-want-to-get-rid-of-the-syncing-status/13793/18. Basically every so often a user gets confused by Syncthing saying it's syncing, while they made sure manually that the data is already the same. The proposed solution is an additional state before "Syncing", while Syncthing is traversing the database to make a list of stuff it needs etc. Details in the forum or PR (incoming).
Copied a lot of testfiles and saw it stay in the new state for a short moment before going back to idle.
(Unrelated: Looks like pulling is faster than updating the global state in the web UI, which rises to 23 during/after pulling - however getting this screenshot required sub-second timing, so it's definitely not an issue.)
=> gui, lib/model: Add new state FolderPreparingSync (fixes #6027)

cmd/syncthing/main.go, lib/syncthing/syncthing.go, lib/syncthing/syncthing_test.go
There was already some discussion in IRC, for context:
> 15:32:21 - imsodin: The current mechanism is built around the idea of the whole thing as being a "one-shot" operation. I.e. you start it and then wait for an error, therefore no cleaning up is being done and onces used. And that's mostly due to racyness, as e.g. the api can call `Stop` before `startup` returns. However's first at stopping/producing an error gets to do that. My approach at fixing it would have been to close `stopped` at creation, and re-create it after successful startup.
> 15:45:11 - calmh: we can think about it. i first thought it was an emergency, but it's at least a bit cornercasey so no panic to fix
> 15:47:56 - calmh: however i'm thinking that API wise i'm not super excited about things that start routines in …
=> lib/syncthing: Prevent hangup on error during startup (fixes #6043)

go.mod, lib/sync/sync_test.go
`TestRWMutex` failed recently (https://build.syncthing.net/viewLog.html?buildId=47579&buildTypeId=Syncthing_Coverage). This change does not address the (flaky) test failure, merely prevents a panic due to the failure (because the panic is just confusing/a red herring).
And running any go command cleans this indirect entry from go.mod, so I'm trying to sneak that in too.
=> lib/sync: Cleanly fail instead of panic in tests

cmd/stdiscosrv/main.go, cmd/strelaypoolsrv/main.go, cmd/strelaysrv/main.go, cmd/syncthing/main.go, lib/api/api.go, lib/api/api_test.go, lib/discover/global_test.go, lib/syncthing/syncthing.go, lib/syncthing/utils.go, lib/tlsutil/tlsutil.go
This adds a certificate lifetime parameter to our certificate generation
and hard codes it to twenty years in some uninteresting places. In the
main binary there are a couple of constants but it results in twenty
years for the device certificate and 820 days for the HTTPS one. 820 is
less than the 825 maximum Apple allows nowadays.
This also means we must be prepared for certificates to expire, so I add
some handling for that and generate a new certificate when needed. For
our own certificates (common name Syncthing) we regenerate a month ahead
of time. For other certificates we leave well enough alone.
=> all: Update certificate lifetimes (fixes #6036)

go.mod, lib/scanner/walk.go, lib/scanner/walk_test.go
If the path to be scanned is below a symlink, the scanner goes ahead walking that path, as it never by itself needed to traverse the symlink. Now it checks before walking that the path given is not traversing any symlinks.
Get no results when scanning a path behind a symlink.
=> lib/scanner: Don't scan if input path is below symlink (fixes #6090)

go.mod, lib/model/folder_sendrecv.go, lib/model/folder_sendrecv_test.go
When deleting files/dirs we do not check for symlinks in the path. In #6090 this resulted in a scan being scheduled, because before deleting it checks the db and does not find the same as it sees on disk behind the symlink.
Check that neither a db update nor a scan goes through when trying to delete a file behind a symlink.
=> lib/model: Check for symlinks before deleting during pull (fixes #6090)

lib/model/model.go
I modified RemoveFolder to fix #6106 
After the changes, if someone tries to remove a folder, path of which is still referenced, the `.stfolder` won't be removed.
I checked changes manually. I'm not sure if unit tests are needed.
=> Fix removal of a marker when there are still folders referencing it (fixes #6106)

lib/protocol/bufferpool.go, lib/protocol/bufferpool_test.go
There was a logic error in Put() which made us put all large blocks into
segment zero, where we subsequently did not look for them.
I also added a lowest threshold, as we otherwise allocate a 128KiB
buffer when we need 24 bytes for a header and such.
After:
```
2019/11/04 18:21:49 Result: Wall time: 2.665497ms / MiB
2019/11/04 18:21:49 Result: 3.84e+05 KiB/s synced
2019/11/04 18:21:49 Receiver: Utime: 4.506592ms / MiB
2019/11/04 18:21:49 Receiver: Stime: 1.126973ms / MiB
2019/11/04 18:21:49 Receiver: MaxRSS: 321632 KiB
2019/11/04 18:21:49 Sender: Utime: 4.163059ms / MiB
2019/11/04 18:21:49 Sender: Stime: 963.312µs / MiB
2019/11/04 18:21:49 Sender: MaxRSS: 113696 KiB
```
Before:
```
2019/11/04 17:16:03 Result: Wall time: 2.77946ms / MiB
2019/11/04 17:16:03 Result: 3.68e+05 KiB/s synced …
```
=> Fix bufferpool puts (ref #4976)

lib/api/mocked_model_test.go, lib/model/folder_recvonly_test.go, lib/model/folder_sendrecv_test.go, lib/model/model.go, lib/model/model_test.go, lib/model/requests_test.go, lib/model/testutils_test.go, lib/syncthing/syncthing.go
Nobody outside of model has any business meddling directly with folders and starting folders together with the model also seems more fitting (and it has an almost neutral/slightly negative line count :) ).
Testing: Folders still start on startup.
=> lib/model: Add folders on start in model

lib/model/model.go
This is a regression introduced in PR #6005 / commit
f7b2e79fdcff1ce45d42e38d3fa446cf6de2efc8
The reference are create in `CommitConfiguration`, however that only handles updated devices. Devices that are present at model creation were never added (unless you removed and readded them).
=> lib/model: Add initial deviceStatRefs on model creation (fixes #6136)

lib/model/folder_sendrecv_test.go, lib/model/model_test.go, lib/model/requests_test.go
This is in reaction to these test timeouts:
https://build.syncthing.net/viewLog.html?buildId=49063&buildTypeId=Syncthing_BuildLinuxCross
https://build.syncthing.net/viewLog.html?buildId=49063&buildTypeId=Syncthing_BuildLinuxCross
It does not fix any flakyness (couldn't repro locally), but at least now these tests fail quickly instead of blocking everything until the global test timeout kicks in.
=> lib/model: Remove some testing deadlocks

gui/default/assets/css/theme.css, gui/default/syncthing/core/syncthingController.js, gui/light/assets/css/theme.css, lib/api/api_statics.go
Fixes #6115. In particular:
- moves the default theme into a new "light" theme,
- serves assets from other themes when the path starts with `theme-assets` and
- on the default theme, load the correct style depending on `prefers-color-scheme`.
*Instructions on how to activate dark mode on Firefox for testing are available [here](https://stackoverflow.com/a/56757527).*
- Open web UI with `prefers-color-scheme` set to `light` or `no-preference` → it has the light theme
- Open web UI with `prefers-color-scheme` set to `dark` → it has the dark theme
- Open web UI in a browser without support for `prefers-color-scheme` → it has the light theme
- Set "Light" theme → the web UI has the current default theme (regardless of `prefers-color-scheme`)
- Set a custom theme → the web UI has the custom …
=> gui, lib/api: Adds support for prefers-color-scheme (fixes #6115)

cmd/syncthing/monitor.go, lib/connections/service.go, lib/fs/util.go, lib/tlsutil/tlsutil.go
Home dir, exit code. Also dropping the TLS 1.3 thing since that's enabled by default in Go 1.13 that we normally build with.
=> Cleanup of things we can improve when requiring Go 1.12

lib/protocol/protocol.go, lib/protocol/protocol_test.go
We incorrectly gave a too small buffer to lz4.Compress, causing it to
allocate in some cases (when the data actually becomes larger when
compressed). This then panicked when passed to the buffer pool.
This ensures a buffer that is large enough, and adds tripwires closer to
the source in case this ever pops up again. There is a test that
exercises the issue.
=> lib/protocol: Buffer allocation when compressing (fixes #6146)

gui/default/assets/css/overrides.css
This allows better viewing when on a condensed screen, and reduces screen real estate slightly.
On smaller screens the padding of 15px is too much in these panels and modals. I have reduced them accordingly.
Built using docker.
New Panels:
Old Panels:
New Modal:
Old Modal:
I added a comment on the CSS I added, but none really required.
me, domenic@tgxn.net
=> Decrease padding on the panel and modal bodies.

lib/model/folder_sendrecv_test.go, lib/model/progressemitter_test.go
This is a followup to #6152: While preventing leaked goroutines is good, just closing all the channels results in races. So I added a wait group where necessary. And I found another leak in the progress emitter tests.
=> lib/model: Prevent cleanup-race in testing (ref #6152)

lib/model/model.go
This is basically #6154 but as unobtrusive as possible: Don't remove panics/functions and don't touch tests. I just refactors to make locking more consistent:
- Don't have `...Locked` functions that drop the lock halfway through -> move closing connections out of `startFolderLocked` and split `tearDownFolderLocked` into `stopFolder` and `removeFolderLocked`.
- Keep the lock continuously when restarting an existing or adding a new folder (add `newFolder` for the latter).
What I want to achieve is reduce complexity/margin for mistakes around locks and prevent that some other operation acquiring fmut comes in between adding-starting or removing-readding folders.
=> lib/model: Keep fmut locked while adding/starting/restarting folders

lib/model/fakeconns_test.go, lib/model/folder.go, lib/model/folder_sendrecv.go, lib/model/folder_sendrecv_test.go, lib/model/model.go, lib/model/model_test.go, lib/model/requests_test.go, lib/protocol/benchmark_test.go, lib/protocol/protocol.go, lib/protocol/protocol_test.go, lib/protocol/wireformat.go
This reduces the verbosity of the puller via the following:
- Don't drop the connection before stopping the folder. Instead make sure that an active connection doesn't prevent stopping the folder -> no connection lost errors.
- Don't log errors for items due to the folder being stopped: That's not a file level problem (and is inconsistent, we also don't log an error for all remaining files to be synced that aren't due to folder stopping).
- Only print errors if they are new/changed compared to the last pull iteration. For that instead of just removing errors before a pull iteration, track new errors in a new map and reset the old errors after the pull iteration. To offset for the lack of duplicate error reporting, I added a log line after every pull about how many files couldn't be …
=> lib/model: Don't info log repeat pull errors

gui/default/index.html, gui/default/syncthing/core/syncthingController.js, gui/default/syncthing/core/upgradeModalView.html
When clicking on upgrade button confirmation dialog will now appear (fixes #5887).
=> gui/default: Add upgrade confirmation dialog (fixes #5887)

gui/default/syncthing/device/editDeviceModalView.html
When adding a device, the list with nearby devices won't appear anymore, unless there are any such devices. Also, IDs of those devices will look more like links. Solves #6057 
Only manual testing has been done. This change can be tested by adding 'dummy' IDs to the `$scope.discovery` array in [`gui/default/syncthing/core/syncthingController.js:1442`](https://github.com/syncthing/syncthing/blob/0d14ee4142cf9f8cd4d2e037f545619562154c2b/gui/default/syncthing/core/syncthingController.js#L1442) and rebuilding.
=> gui/default: Make 'Nearby devices' look like links (fixes #6057)

gui/default/syncthing/core/syncthingController.js
This prioritizes non-idle folder states to fix #6169. The bug was introduced in https://github.com/syncthing/syncthing/pull/6117, making this PR RC material (even though just "cosmetic").
=> gui: Prioritize non-idle folder states (fixes #6169)

lib/model/model.go
While tracking down the origins and effects of config changes I noticed that introduction can result in multiple config changes. This PR collects all changes and commits it as a single config change. To not have to pass a folder and device map in and out of existing functions, I merged them into a single, largeish function. I can refactor if you'd rather have shorter functions with more arguments. 
This PR has no change in intended behaviour and existing tests still pass.
=> lib/config: Do introductions in a single config change

lib/relay/client/dynamic.go
Detected through https://sentry.syncthing.net/syncthing/syncthing/issues/730.  
Introduced in https://github.com/syncthing/syncthing/pull/6166 (unreleased).
The string method tries to acquire a lock that's not yet created -> pass a "manual" string.
=> lib/relay: Prevent lock nil deref when creation dynamic client

lib/model/folder_recvonly_test.go, lib/model/model.go, lib/model/model_test.go, lib/model/testutils_test.go
When internalizing handling of folders in the model (https://github.com/syncthing/syncthing/pull/6135) I missed that it is a supervisor, not "merely" a service. This did not lead to problems as apparently internally suture uses `Serve`. However in principle it could just as well use `ServeBackground`, and that's also what we do in tests.
In some tests the folder was just added, not started. As folders now automatically get added and started when the model is started, the folders then need to be removed and readded (without starting) in those tests.
=> lib/model: Also cover ServeBackground

gui/default/assets/css/overrides.css, gui/default/syncthing/core/aboutModalView.html, gui/default/syncthing/core/logViewerModalView.html
Fixes #6178 
1. Go to "Logs" view with removed font called "Consolas" in system. You should see default monospace font from OS.
2. Go to "About" page and resize it to less than 768px. You should properly see Syncthing logo and "dependency list" in one column instead of two.
=> UI enhancements on mobile

lib/config/config.go, lib/connections/quic_dial.go, lib/ignore/ignore.go, lib/model/model.go, lib/protocol/protocol.go, lib/relay/client/static.go, lib/tlsutil/tlsutil.go
This is prompted by concern over wrapped errors when filtering errors in https://github.com/syncthing/syncthing/pull/6177. And it's purely a grep/sed effort. We may still be dropping errors in places that could/should be wrapped.
=> lib: Wrap errors with errors.Wrap instead of fmt.Errorf

lib/model/fakeconns_test.go, lib/model/model.go, lib/model/progressemitter.go, lib/model/progressemitter_test.go, lib/model/requests_test.go, lib/protocol/protocol.go, lib/protocol/protocol_test.go, lib/protocol/wireformat.go
Not much interesting here, just a continuation of context on requests (https://github.com/syncthing/syncthing/pull/6149) and context on services (https://github.com/syncthing/syncthing/pull/6166).
=> lib/model, lib/protocol: Add contexts sending indexes and download-progress

lib/config/folderconfiguration.go, lib/model/model.go, lib/versioner/external.go, lib/versioner/external_test.go, lib/versioner/simple.go, lib/versioner/simple_test.go, lib/versioner/staggered.go, lib/versioner/staggered_test.go, lib/versioner/trashcan.go, lib/versioner/trashcan_test.go, lib/versioner/util.go, lib/versioner/versioner.go
This is a refactor while I was anyway rooting around in the versioner.
Instead of exporting every possible implementation and the factory and
letting the caller do whatever, this now encapsulates all that and
exposes a New() that takes a config.VersioningConfiguration.
Given that and that we don't know (from the outside) how a versioner
works or what state it keeps, we now just construct it once per folder
and keep it around. Previously it was recreated for each restore
request.
=> lib/versioner: Reduce surface area

cmd/strelaypoolsrv/main.go, cmd/strelaysrv/testutil/main.go, cmd/syncthing/main.go, lib/connections/quic_dial.go, lib/connections/relay_dial.go, lib/connections/relay_listen.go, lib/connections/service.go, lib/connections/structs.go, lib/connections/tcp_dial.go, lib/dialer/debug.go, lib/dialer/internal.go, lib/dialer/public.go, lib/discover/global.go, lib/nat/registry.go, lib/osutil/ping.go, lib/pmp/pmp.go, lib/rc/rc.go, lib/relay/client/dynamic.go, lib/relay/client/methods.go, lib/relay/client/static.go, lib/upgrade/upgrade_supported.go, lib/upnp/upnp.go, lib/ur/usage_report.go, lib/util/utils.go
The main change is using `DialContext` in lib/dialer. All other changes are just about propagating contexts to where dialing happens (which is quite a lot).  
When errors where used (logged, "registered" for web UI, ...), I filtered out `context.Canceled`, as this isn't a fault or in any other way actionable by the user. It's just an expected result of normal termination. 
None except for existing tests. It would definitely be nice if someone that uses proxies could test this. I am fairly certain it's ok, but there is one type assertion which could blow up at runtime (at the end of lib/dialer/internal.go - has a comment).
=> all: Use context in lib/dialer

.github/ISSUE_TEMPLATE.md
Since Syncthing current version is v1.3.1, the current proposal is that the GitHub issue template shows `v1.x.y` instead of `v0.x.y`.
=> Bump Syncthing version in GitHub issue template

lib/config/config.go, lib/config/config_test.go, lib/config/migrations.go, lib/config/optionsconfiguration.go, lib/config/wrapper.go, lib/connections/service.go, lib/stun/stun.go, lib/syncthing/syncthing.go, lib/ur/usage_report.go
This is also mainly to reduce an upcoming diff. However removing that wrap-hack in `connections.service` is in my opinion anyway worthwhile.
=> lib/config, lib/connections: Remove ListenAddresses hack

lib/upnp/upnp.go
The http request used for upnp discovery was malformed.
See https://play.golang.org/p/-S2WDBwK29m and notice the request ends in `\r\n` instead of `\r\n\r\n`
=> Ensure uPnP http requests have trailing \r\n

cmd/syncthing/main.go, cmd/syncthing/monitor.go, cmd/syncthing/monitor_test.go
Since we've taken upon ourselves to create a log file by default on Windows, this adds proper management of that log file. There are two new options:
```
-log-max-old-files="3"    Number of old files to keep (zero to keep only current).
-log-max-size="10485760"  Maximum size of any file (zero to disable log rotation).
```
The default values result in four files (syncthing.log, synchting.0.log, ..., syncthing.3.log) each up to 10 MiB in size. To not use log rotation at all, the user can say --log-max-size=0.
=> cmd/syncthing: Implement log rotation (fixes #6104)

lib/model/folder_summary.go
This is a regression from #6028: If syncing doesn't actually need to pull any data, the folder summary isn't triggered. This is in principle relevant for the current RC, however it's minor (maybe in practice not noticeable at all - I discovered it in code). It also listens to `LocalIndexUpdated`, which will cause a folder summary the next time the timer fires.
=> lib/model: Also send folder summary from sync-preparing (ref #6028)

gui/default/syncthing/core/syncthingController.js
In the GUI, the versions are not sorted in the restore modal, appearing in whatever random order the API is providing them as.  This is especially annoying to look through if you have a lot of versions for a file.  This PR forces the versions to be sorted by date in reverse order (so that after the current version, the next version is the latest version before that, and so forth).
I've tested it with staggered versioning in chrome and firefox, and you can see the change in drop down behavior in the screenshot below.
Before:
After:
I didn't actually see anything about that part of the UI in the docs.
=> gui: Sort versions by date in restore dropdown

lib/config/wrapper.go, lib/connections/service.go, lib/model/model.go, lib/model/progressemitter.go, lib/ur/usage_report.go
`db.NewFileSet` returns a `nil` object without error if the underlying db was closed. We ensure that all services are stopped when we close the db, but that doesn't guarantee that "nothing is happening anymore" for two reasons:
- Many (most?) services don't unsubscribe themselves on the config wrapper.
- Unsubscribing returns even if there is still an ongoing config change.
I consistently got panics locally (see https://github.com/syncthing/syncthing/issues/6133#issuecomment-559978898) which are now gone.
=> lib: Consistently unsubscribe from config-wrapper (fixes #6133)

lib/api/mocked_model_test.go, lib/model/model.go, lib/protocol/benchmark_test.go, lib/protocol/common_test.go, lib/protocol/nativemodel_darwin.go, lib/protocol/nativemodel_windows.go, lib/protocol/protocol.go
This adds error returns to model methods called by the protocol layer. Returning an error will cause the connection to be torn down as the message couldn't be handled. Using this to signal that a folder isn't
currently available will then cause a reconnection a few moments later, when it'll hopefully work better.
Tested manually by running with STRECHECKDBEVERY=0 on a nontrivially sized setup. This panics reliably before this patch, but just causes a disconnect/reconnect now.
```
[SYNO4] 08:30:57 INFO: Index for nonexistent folder "ourlp-uzomp"
[SYNO4] 08:30:57 INFO: Connection to ... at ... closed: receiver error: no such folder
...
[SYNO4] 08:30:58 INFO: Ready to synchronize "foto/2019" (ourlp-uzomp) (sendreceive)
[SYNO4] 08:30:59 INFO: Completed initial scan of sendreceive folder …
```
=> lib/model, lib/protocol: Use error handling to avoid panic on non-started folder (fixes #6174)

gui/default/syncthing/core/syncthingController.js
Fix for a small typo in a class name. Now it properly displays the 'arrow-down' icon next to a word 'Sync'.
=> gui/default: Fix a typo in a class name

gui/default/syncthing/core/syncthingController.js
This is essentially a follow up to https://github.com/syncthing/syncthing/pull/5759/files as the new issue (#6222) has the same underlying reason as https://github.com/syncthing/syncthing/issues/5652: Spurious api calls from angular land. The mitigation put in place fails in this specific case, as an empty object apparently isn't false in JS, so that check alone isn't enough.
=> gui: Prevent spurious api call (fixes #6222)

cmd/syncthing/main.go, lib/syncthing/syncthing.go, lib/syncthing/syncthing_test.go, lib/syncthing/utils.go
Instead of having the concrete `db.Lowlevel` type in Syncthing's libraries interface, this proposes to expose the `backend.Backend` interface. That's something a library consumer can actually implement themselves if they don't want to use "our" db backend.
=> lib/syncthing: Expose backend instead of lowlevel

lib/api/api.go, lib/api/api_test.go
We run lots of api services, but never stop them - which is annoying if you ever have to analyse a stacktrace of a test timeout.
=> lib/api: Prevent leaks in tests

lib/upgrade/upgrade_supported.go
There is no need to do this switch based on the current OS, instead do
it based on what the archive actually appears to be.
(Tested; works.)
=> lib/upgrade: Let Mac load .zip archives

script/docker-entrypoint.sh
su-exec sets $HOME, and we used to have this env call in there to fix
that up. It disappeared in the latest entrypoint.sh rewrite.
=> docker: Fix HOME setting

gui/default/syncthing/folder/editFolderModalView.html
For reasons unknown no separation is added here between the last line of the tab body and the separating line to the footer. And wrapping in `<p>` didn't do it either.  
For a screenshot of how it is now see #6240, with this PR well there's a line break before the horizontal line.
=> gui: Missing line break (fixes #6240)

gui/default/syncthing/core/syncthingController.js, lib/model/model.go
Another shot at the problem coming up every now and then (https://github.com/syncthing/syncthing/issues/4570 for history and https://forum.syncthing.net/t/syncing-percentage-out-of-scale/14249 for the most recent case). It does two things: In the folder summary make sure the reported needed bytes is never negative and in the web UI use the same logic as on remote device, i.e. when there's deletes only display 95%. As to why the needed bytes should be negative:
> This is essentially files becoming deleted while they are being downloaded.  
> https://forum.syncthing.net/t/syncing-percentage-out-of-scale/14249/2
As for testing: None. However it sounds plausible and even if it isn't actually the cause, it's a good safety measure in my opinion. If negative percentages come up again we can …
=> gui, lib/model: Prevent negative sync completion (fixes #4570)

lib/model/folder_sendrecv.go, lib/model/requests_test.go
As @AndrewSav stated in https://github.com/syncthing/syncthing/pull/5626#discussion_r363060566 (thanks for the persistence) the queue was reset too early, i.e. when the last files enter the copiers they are still in progress, but as `processNeeded` returns, they are no longer in the queue.
Added a new test that checks that there is an item in progress for a single item.
=> lib/model: Reset queue after all pulling is done (fixes #5867)

lib/config/folderconfiguration.go, lib/model/model_test.go
What should really happen is good documentation on the folder marker, why it's there and what it's disappearance, and then put a link to that into the error message. However I don't have the time for that and don't particularly feel like it either, especially after the insistent, and in my totally personal, potentially entirely unjustified view, quite entitled demand for a "solution. Nevertheless this has been on my todo list so I'd like to at least do a partial solution (and hey, maybe it actually happens for once that someone else than a maintainer steps up to write that particular bit of documentation that is so important (I agree)).
=> lib/config: Add some info to the folder marker missing (ref #5207)

lib/model/folder_summary.go
See https://forum.syncthing.net/t/rest-db-status-returns-404-on-startup/14329
If the api starts while the folder is not yet running or generally when querying `/rest/db/status` for a an about to be started folder, we return a 404. Now it is treated the same as a paused folder, i.e. send a valid folder summary. However the comment was wrong: We can't get any info from db for a paused folder, nevertheless it's important to get valid entries with zero values, otherwise the UI blows up.
=> lib/model: Return paused summary instead of error on paused folders

lib/syncthing/syncthing.go
<strike>When Syncthing is stopped externally (i.e. ctrl-c or signal), it is immediately terminated instead of waiting for service and db shutdown.</strike> This is not true: Due to the wait call in main we do not terminate immediately - <strike>I don't know what weird experiments I did before that made me believe it did</strike> I likely stumbled over https://github.com/syncthing/syncthing/issues/4774 (unrelated). Anyway I still think it is the right thing to do to only return from `Stop` once the app has fully terminated in terms of "least surprising behaviour".
=> lib/syncthing: Wait for actual termination on Stop()

cmd/syncthing/main.go, cmd/syncthing/monitor.go, etc/linux-desktop/syncthing-start.desktop
Syncthing is now always run through a monitor process. Reasons found in #5786 and it also fixes #4774 as predicted there :)
This will lead to a >20% increase in reports to sentry (according to data.syncthing.net and assuming most apt/arch/fedora/... use some kind of service manager) and an initial spike of old reports, just in case that needs some precautionary measures.
I also took the opportunity to add logging to the desktop entry (also tested to work).
I manually tested the following that without `-no-restart` it restarts on ctrl-c in subshell, on restart in UI and on auto-update and it does not restart on shutdown in UI, and with `-no-restart` it doesn't restart in any of the aforementioned cases.
=> cmd/syncthing: Always use monitor process (fixes #4774, fixes #5786)

lib/model/progressemitter.go, lib/model/progressemitter_test.go
Makes the logic a bit clearer and safer. This also sneakily redefines
the 0 interval to also mean disabled, whereas it previously meant ...
sometimes default to 1s, sometimes just spin.
=> lib/model: Handle progress emitter zero interval (fixes #6281)

lib/dialer/public.go, lib/relay/client/static.go
Seems to have slipped. Also adding logging back.
I don't think this is the root cause tho, as it should have been manifested as IO timeout.
=> lib/relays: Fix incorrect timeout, bring back logging (ref #6289)

cmd/syncthing/main.go, lib/db/lowlevel.go, lib/db/schemaupdater.go
Also retain the interval over restarts by storing last GC time in the
database. This to make sure that GC eventually happens even if the
interval is configured to a long time (say, a month).
=> lib/db: Configurable block GC time

lib/ignore/ignore.go, lib/ignore/ignore_test.go
Instead of panicking when we try to look closer at the empty pattern,
return something like `invalid pattern "(?d)" in ignore file: missing
pattern`.
=> lib/ignore: Don't crash on empty patterns (fixes #6300)

lib/db/structs.go, lib/model/folder.go, lib/model/folder_recvonly.go
This records the time a file was marked as deleted. It will, in the future, aid in garbage collecting old files.
=> all: Update metadata modtime on delete (ref #6284)

lib/db/backend/backend.go, lib/db/backend/leveldb_backend.go, lib/db/backend/leveldb_open.go, lib/db/blockmap_test.go, lib/db/db_test.go, lib/db/keyer_test.go, lib/db/namespaced_test.go, lib/db/set_test.go, lib/sync/sync.go
Looking into https://forum.syncthing.net/t/test-panic-on-go1-14beta1/14462 (fruitlessly) I saw lots of gc runners in the backtrace. Turns out we never close databases in tests. Closing then turns up a race in goleveldb:
```
==================
WARNING: DATA RACE
Read at 0x00c00014a8b0 by goroutine 64:
runtime.chansend()
/media/ext4_data/Linux/source/go/src/runtime/chan.go:142 +0x0
github.com/syndtr/goleveldb/leveldb.cAuto.ack()
/media/ext4_data/Coding/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_compaction.go:686 +0xab
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction()
/media/ext4_data/Coding/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_compaction.go:778 +0xc9
Previous write at 0x00c00014a8b0 by …
```
=> lib/db: Add closeWaitGroup to allow async operation

lib/db/lowlevel.go, lib/db/transactions.go
Bandage over the wound...
Also explicitly handle non-nil but empty block lists (if they should
ever pop up as an effect of unmarshalling changes or whatnot).
=> lib/db: Handle missing block lists as missing file (ref #6321)

lib/model/folder_recvonly_test.go, lib/model/model.go, lib/model/model_test.go
~~#6272 makes sure not running folders don't result in a 404 on the rest api, however the method  `Model.DBSnapshot` introduced in #6239 doesn't look at why a folder isn't running, it just returns a folder missing error if it's not running. So Synctrayzor still presents an error message due to a 404: https://forum.syncthing.net/t/rest-db-status-returns-404-on-startup/14329/19~~  
Looks like #6239 isn't easily compatible with not returning a 404. At least it isn't doable with the fixes in this PR. The PR in itself is still useful.
=> lib/model: Consistent error return values for folder methods on model

lib/fs/fakefs.go, lib/fs/fakefs_test.go, lib/model/folder_recvonly_test.go, lib/model/testutils_test.go
During some other work I discovered these tests weren't great, so I've
rewritten them to be a little better. The real changes here are:
- Don't play games with not starting the folder and such, and don't
construct a fake folder instance -- just use the one the model has. The
folder starts and scans but the folder contents are empty at this point
so that's fine.
- Use a fakefs instead of a temp dir.
- To support the above, implement a fakefs option `?content=true` to
make the fakefs actually retain written content. Use sparingly,
obviously, but it means the fakefs can usually be used instead of an
on disk real directory.
=> lib/fs, lib/model: Rewrite RecvOnly tests

lib/model/folder_summary.go, lib/model/model_test.go
This now actually addresses the 404 on the rest api that makes trouble for SyncTrayzor (https://forum.syncthing.net/t/rest-db-status-returns-404-on-startup/14329). The behaviour is, that we return an empty folder summary in that case. I think that's not a good API and instead the folder summary service should have access to the db for paused folders as well (e.g. global and local state are still useful info then), but that's a much bigger change. This just makes sure the behaviour doesn't change.
I didn't add a rest api error, as it can't use the model package. However I added a test in the model that makes sure that no error is returned when getting a folder summary for a paused folder.
=> lib/model: Return empty summary on paused folders (ref #6272)

lib/db/blockmap_test.go, lib/db/lowlevel.go, lib/db/schemaupdater.go, lib/db/transactions.go
The readWriteTransaction offered both `commit()` (the one to use) and
`Commit()` (via embedding) where the latter didn't close the read
transaction. This removes the lower cased variant in order to prevent
the mistake.
The only place where the mistake was made was the new gc runner, where
it would leave a read snapshot open forever.
=> lib/db: Use Commit() instead of commit()

lib/db/set.go
If we crashed after writing new file entries but before updating metadata in the database the sequence number and metadata will be wrong. This fixes that.
I have an elegant stress test for this, but it's too large to fit in the margins of this PR. I'm going to improve that a bit more (still bug hunting) and then commit it separately.
Testing it separately is annoying as we need to reach in and mess up the metadata which is tricky. :/
=> lib/db: Recover sequence number and metadata on startup (fixes #6335)

lib/db/meta.go
We store metadata in single flag buckets. On adding files to meta we do it right and just use the flags passed as arguments, on removing we do however use the localflags from the file. That's what is fixed in the first commit (single line). The second commit renames `flags` to `flag` in places where it should by just a single bit and adds a check to `countsPtr` that it is indeed the case.
Unfortunately (or not) I think this has no real-world implications, as we only ever have one local flag set on a file. If I am wrong on that, this might actually fix inconsistent local states.
=> lib/db: Use flags from arg not LocalFlags() updating meta

lib/db/backend/backend.go, lib/db/backend/leveldb_backend.go, lib/db/lowlevel.go, lib/db/meta.go, lib/db/set.go
This adds metadata updates to the same write batch as the underlying
file change. The odds of a metadata update going missing is greatly
reduced.
Bonus change: actually commit the transaction in recalcMeta.
This now makes the previous recovery thing not kick in during my stress testing...
=> lib/db: Keep metadata better in sync (ref #6335)

lib/upnp/upnp.go
During NAT discovery we block for 10s (NatTimeoutS) before returning.
This is mostly noticeable when Ctrl-C:ing a Syncthing directly after
startup as we wait for those ten seconds before shutting down. This
makes it check the context a little bit more frequently.
=> lib/upnp: Exit quicker

lib/db/transactions.go
In `recalcMeta` we first call `t.withAllFolderTruncated` and then `t.Commit`, while it isn't allowed to call anything except `Release` after `Commit`. For some reasons that doesn't blow up in tests. It did in a very weird way (segfault deep in leveldb) in a local feature branch, took me a while to find the cause (leveldb should return an error, not segfault, but that's hardly worth spending effort on).
Also from a conceptual standpoint I believe it's wrong to call `t.Commit` or `t.Release` anywhere else than the place where the transaction was created.
=> lib/db: Don't call backend.Commit twice (ref #6337)

lib/model/folder_summary.go
One of the causes of "panic: database is closed" is that we try to send
summaries after it's been closed. Calculating summaries can take a long
time and if we have a lot of folders it's not unreasonable to think
that we might be stopped in this loop, so prepare to bail here.
=> lib/model: Stop summary sender faster (ref #6319)

gui/default/syncthing/core/syncthingController.js, gui/default/syncthing/settings/settingsModalView.html, lib/api/api.go, lib/config/guiconfiguration.go, man/syncthing-config.5
This pull request solves #5979.
The problem is that a user may wish a unix socket to have specific permissions.
We can solve this by adding a configuration option for unix socket permissions.
Navigate under the web UI to Actions > Settings > GUI and change the GUI Listen Address line to a local file. That will be created as a web socket. Check the permissions of this file.
https://github.com/syncthing/docs/pull/492
=> lib/config, gui: Set unix socket permissions for GUI listen address (fixes #5979)

lib/db/structs.go, lib/db/transactions.go, lib/model/folder.go, lib/model/folder_recvonly.go, lib/model/folder_sendonly.go, lib/protocol/bep_extensions.go
I unsuccessfully tried to reproduce the scenario https://github.com/syncthing/syncthing/issues/6321#issuecomment-587548420. That's due to the GC not kicking in, even if noone actually has the blocks. It's enough for an ignored file to have the `BlocksHash`.
Nevertheless I believe this is a good change: It firstly makes sure that whenever `Blocks` is set to nil, so is `BlocksHash`. That means blocks can get GCed when everyone has ignored files, while it can't at the moment. I also put in a check in the db that panics if this isn't true. That could be changed to just fix it on the fly, but I'd rather know about it when it happens and fix it. And while checking for other places where the same mistake might happen, I ensured that wherever file infos are modified, that's happening through the …
=> lib: Modify FileInfos consistently (ref #6321)

lib/db/schemaupdater.go, lib/db/set.go
While #6336 and #6337 take care of preventing new sequence index problems, they do not clean up existing messes. This adds (extends) the schema transitions to check for and fix missing and duplicate sequence entries. I had to refactor the metadata loading/rechecking functions, such that they aren't methods of `FileSet` anymore.
The PR as it is is intended to go into a new 1.4.0 RC, as it addresses a problem that's partially fixed there. If we ship it in 1.4.0 the min Syncthing version needs to be modified.
=> lib/db: Schema update to repair sequence index (ref #6304)

lib/db/transactions.go
Minimal variant to get rid of #6353 (as opposed to https://github.com/syncthing/syncthing/pull/6354).
=> lib/db: Don't panic on incorrect BlocksHash (fixes #6353)

lib/db/transactions.go
Act like a normal FileInfo-marshal-and-save again when there are no blocks.
This seems like the simplest fix for the current debacle and also somewhat resistant to future mistakes.
=> lib/db: Allow put partial FileInfo without blocks (ref #6353)

lib/connections/service.go
Connection errors weren't getting populated in the GUI.
=> lib/connections: Actually record connection errors

cmd/syncthing/main.go
There's not indication that something happened when running with `-reset-database`, which can cause confusion (see https://forum.syncthing.net/t/database-to-upgrade-to-v1-4-0-rc-7/14563).
=> cmd/syncthing: Add indication that reset db happened

lib/dialer/public.go, lib/osutil/ping.go
Also the call site where it shouldn't anyway be looking at the conn when
the err is non-nil.
=> lib/dialer: Preserve nilness in error handling (fixes #6368)

cmd/syncthing/main.go, cmd/syncthing/monitor.go, cmd/syncthing/monitor_test.go
Currently we are truncating a file when opening it. And we aren't opening a file when creating a rotated logger, instead rotating and opening on first write. Now we don't truncate anymore and rotate only if the log exceeds the limit.
See also https://forum.syncthing.net/t/rotating-logfiles-on-every-start/14542
=> cmd/syncthing: Do not truncate/rotate logs at start

cmd/stindex/idxck.go, cmd/syncthing/main.go, lib/db/lowlevel.go, lib/db/schemaupdater.go, lib/db/transactions.go
I was working on indirecting version vectors, and that resulted in some
refactoring and improving the existing block indirection stuff. We may
or may not end up doing the version vector indirection, but I think
these changes are reasonable anyhow and will simplify the diff
significantly if we do go there. The main points are:
- A bunch of renaming to make the indirection and GC not about "blocks"
but about "indirection".
- Adding a cutoff so that we don't actually indirect for small block
lists. This gets us better performance when handling small files as it
cuts out the indirection for quite small loss in space efficiency.
- Being paranoid and always recalculating the hash on put. This costs
some CPU, but the consequences if a buggy or malicious implementation
silently substituted the …
=> lib/db: Slightly improve indirection (ref #6372)

lib/db/meta_test.go, lib/db/set.go
If we decide to recalculate the metadata we shouldn't start from
whatever we loaded from the database, as that data is wrong. We should
start from a clean slate.
=> lib/db: Correct metadata recalculation (fixes #6381)

cmd/stcli/client.go, cmd/stcli/errors.go, cmd/stcompdirs/main.go, cmd/strelaypoolsrv/main.go, cmd/stvanity/main.go, cmd/ursrv/main.go, lib/api/api_test.go, lib/config/config.go, lib/connections/service.go, lib/db/schemaupdater.go, lib/fs/basicfs_windows.go, lib/ignore/ignore.go, lib/model/model.go, lib/protocol/hello.go, lib/protocol/luhn.go, lib/rc/rc.go, lib/relay/client/client.go, lib/relay/client/dynamic.go, lib/relay/client/methods.go, lib/relay/client/static.go, lib/relay/protocol/protocol.go, lib/scanner/walk.go, lib/scanner/walk_test.go, lib/tlsutil/tlsutil.go, lib/upgrade/upgrade_supported.go, lib/versioner/util.go, lib/versioner/versioner.go, meta/copyright_test.go, test/sync_test.go, test/util.go
- In the few places where we wrap errors, use the new Go 1.13 "%w"
construction instead of %s or %v.
- Where we create errors with constant strings, consistently use
errors.New and not fmt.Errorf.
- Remove capitalization from errors in the few places where we had that.
=> all: Tweak error creation

lib/db/schemaupdater.go
We might get a "not found" at one point in the migration, which should not abort the whole thing. We'll just retry it, and the same error during normal (non-migration) operations would simply result in the file being skipped, not a full database error.
None so far... Hoping for testing from issue reporter
=> lib/db: Be more lenient during migration (fixes #6397)

lib/model/folder_sendrecv.go, lib/protocol/bep_extensions.go, lib/protocol/protocol_test.go
This is an optimization for faster equal checks on block lists.
=> lib/protocol: Use BlocksHash to compare block lists when available

lib/db/set_test.go
Unit Testing Only
I have a PR brewing with significant db changes (well finished, but sort of in "self-review") and as part of that I extend test coverage. In the large catch-all unit test checking global/local/remote/needed/... I added a second remote into the fray. Also I set sequences on all file infos, not just the local ones.
=> lib/db: Extend set test with second remote

cmd/syncthing/main.go
From https://github.com/syncthing/syncthing/issues/6384:
> This is usually fine, but sometimes we fuck up in release candidates and they crash. If that crash is early & persistent then the auto upgrade won't kick in and the user is stuck.
> 
> Maybe, potentially, we should consider doing the upgrade check early and before doing other stuff.
Of course it will never happen again that I produce a panic-inducing PR (ahem...), but nevertheless I believe that we definitely should do that.
I tested `-upgrade-check` `-upgrade` and with and without `STNOUPGRADE=1`: It all did the expected.
I made `checkUpgradeExitOnErr` a function variable instead of a global function, as I believe no functions except the `main...` ones should ever call `os.Exit`. If it is considered ugly, I'd rather go for the …
=> cmd/syncthing: Do auto-upgrade before startup (fixes #6384)

lib/db/transactions.go
`WithNeed` uses it's own logic to determine whether a file is needed as opposed to using `need`. And it tries multiple file entries in the global list, even though if a missing or invalid file is encountered. The former should be an error (there must never be a file in the global list that doesn't otherwise exist) and the latter is unnecessary, as there isn't anything valid after an invalid file in the global list.
=> lib/db: Use need func in withNeed and simplify

lib/db/lowlevel.go, lib/db/transactions.go
Doing other db work I noticed that `VersionList` is the only type where unmarshalling errors and invalid contents (empty) is just accepted and not acted on (neither fixed nor an error returned). For anything else, we just return the error. Looking at the history I don't see anything that justifies a special treatment for `VersionList`. Checkglobal now deletes invalid global entries and everywhere else they are just unmarshalled and an error is returned if invalid.
=> lib/db: Don't ignore failures unmarshaling version lists

lib/beacon/broadcast.go, lib/beacon/multicast.go
saves some traffic (potential mobile wakeups), may help with #5957.
built and run on Linux, seems to work correctly (broadcasts still sent on Ethernet interfaces, not sent on WireGuard interfaces)
I don't think this change requires documentation beyond a changelog message.
=> lib/beacon: only send *cast to flagged interfaces

lib/config/ldapconfiguration.go
Literally noone uses this so I don't see a need to call this out or
trigger a 1.5 release for it.
=> lib/config: Correct spelling of address in LDAP config

lib/db/schemaupdater.go
Checkpoint transactions during database schema update to reduce the memory usage.
=> lib/db: Checkpoint during schema updates (fixes #6422)

build.go, cmd/syncthing/main.go, etc/linux-desktop/syncthing-start.desktop, lib/locations/locations.go
Doesn't change anything for existing users. Neither does it change anything for windows and mac users. For linux users, if there is no db at the "usual place" and there's a relevant xdg env var or the directory `~/.local/share/syncthing` in place, put db and logs there. Also there's two new flags `-config` and `-data` accompanying `-home` to set separate dirs for config/keys and db/logs.
My test system picked the db up at a new location with command line flags.
=> cmd/syncthing, lib/locations: Separate data and config dirs (fixes #4924)

lib/db/db_test.go, lib/db/lowlevel.go, lib/db/structs.go, lib/db/transactions.go
If `checkGlobal` cleans out all entries in a global list entry (e.g. when it has only one entry pointing at nothing), it then commits that empty global list into the db. It's obviously not guaranteed to be the cause of #6425, but I can't find any way an empty list is committed in the other places we modify the global lists and adding check panics for empty global version lists and running integration tests didn't surface anything either - still no guarantee, but good enough imo.
~~Unfortunately I can't think of a good way to trigger `checkGlobals` on upgrade without a db schema upgrade, so the upgrade won't fix this immediately - ideas welcome.~~
See #6429 for a one-time check.
While checking everything I also found and removed two instances of useless code (`insertedAt` is never -1, we …
=> lib/db: Remove emptied global list in checkGlobals (fixes #6425)

lib/db/transactions.go
From #6427:  
> `readWriteTransaction.removeFromGlobal` has one path where an unexpected error is handled badly. As in the global list will then be inconsistent. `checkGlobal` then cleans that up later. This surfaced because of the `withNeed` refactor, which does not ignore invalid global list entries anymore.
=> lib/db: Fix removeFromGlobal and no filenames in error (fixes #6427)

lib/db/db_test.go, lib/db/lowlevel.go, lib/db/schemaupdater.go, lib/db/transactions.go
As of the latest database checker we are again putting files without
blocks. I'm not 100% convinced that's a great idea, but we also do it
for ignored files apparently so it looks like we probably should support
it.
=> lib/db: Don't whack blocks when putting truncated file

cmd/syncthing/main.go
Makes it truly equivalent to -no-restart, and also updates the option
descriptions to be more truthful.
=> cmd/syncthing: Properly handle STNORESTART=1 (fixes #6440)

cmd/syncthing/monitor.go
We set the STRESTART environment when starting the inner process after
the first time, but this didn't persist when restarting the monitor
process. Now it does.
=> cmd/syncthing: Don't open browser on upgrade restarts (fixes #6437)

gui/default/index.html, lib/model/folder_summary.go
Correct an oversight (also adjust total needed items, not just deleted) and an incorrectly named variable - no testing done.
=> gui, lib/model: Fix for folder stats with r-o and ignoreDel (fixes #6430)

gui/default/index.html, gui/default/syncthing/core/syncthingController.js
Closes #6416
Improve device status for unused ones by displaying if they are connected/disconnected/paused. 
Add a device without sharing anything with it connect/disconnect/pause it.
Test this on desktop and on mobile to see plain-text and only-icon status
=> gui: Improve unused device status

lib/model/folder_recvonly.go, lib/model/folder_sendonly.go
We previously didn't remove the local flag for files that only exist locally, resulting in those disappearing from local/global state, but still existing as locally changed items (thus override button and number of locally changed items remains in UI).
I also added two info log lines to the revert and override methods. Currently there's no clear indication of these operations happening in the logs. Given those are not regular operations, but ones triggered by the user, I believe that is appropriate verbosity.
=> lib/model: Unset local flag on deleted files (fixes #6436)

lib/api/api_auth.go
tls.Dial needs it for certificate verification.
=> lib/api: Set ServerName on LDAPS connections (fixes #6450)

lib/syncthing/syncthing.go
We currently save the version to db before repairing the db. Thus if repairing results in a panic, it won't be retried on a successive start. That in itself isn't that bad, as it probably anyway doesn't succeed, but we also have no way of knowing if the repairing ever happened. Thus lets just store the new version in db after all the operations triggered by an update went through.
=> lib/syncthing: Save version to db after upgrade ops are done (ref #6457)

lib/model/folder.go, lib/model/folder_recvonly.go, lib/model/folder_sendonly.go
Writing a test for https://github.com/syncthing/syncthing/pull/6433 I realised `Override` and `Revert` happen asynchronously, i.e. you can't depend on any order of folder operations in conjunction with those. In addition they both set folder state and update the db, so as far as I see they mustn't run asynchronously.
I added a general purpose `syncChan` - I could also add two special purpose chans for overriding and reverting instead if this is "too magic".
=> lib/model: Do Revert/Override synchronously

go.mod, lib/ur/memsize_darwin.go
syncthing currently spawns a process to get the memory size on Darwin. It can instead do a single system call to get this information.
The other BSDs could probably do this too, except that the "memsize" parameter name appears to be MacOS-specific.
Trigger a usage report in the UI: Settings, Anonymous Usage Reporting, Preview.
=> lib/ur: use sysctl syscall to get RAM size on Mac

lib/weakhash/benchmark_test.go
The block benchmark was using the wrong size in SetBytes, causing its
speeds to be off by a factor 100.
```
name                                  old speed      new speed      delta
Block/adler32-131072/#00-8             108GB/s ± 1%     1GB/s ± 1%  -99.23%  (p=0.008 n=5+5)
Block/bozo32-131072/#00-8             19.3GB/s ± 0%   0.1GB/s ± 1%  -99.23%  (p=0.008 n=5+5)
Block/buzhash32-131072/#00-8          26.8GB/s ± 0%   0.2GB/s ± 1%  -99.22%  (p=0.008 n=5+5)
Block/buzhash64-131072/#00-8          26.4GB/s ± 1%   0.2GB/s ± 0%  -99.23%  (p=0.008 n=5+5)
Block/vanilla-adler32-131072/#00-8     244GB/s ± 2%     2GB/s ± 3%  -99.23%  (p=0.008 n=5+5)
```
=> lib/weakhash: Fix speed reporting in benchmark

lib/protocol/protocol.go
Removes a channel from protocol.Connection to which no messages were ever sent.
=> lib/protocol: Remove unused channel Connection.preventSends

lib/protocol/deviceid.go, lib/protocol/luhn.go, lib/protocol/luhn_test.go
The previous implementation of the Luhn algorithm was very generic; its tests didn't cover the actual alphabet for device IDs. This new specialized version is shorter and has tests that cover the actual base-32 Luhn used. It's also almost 4× faster:
```
name         old time/op    new time/op     delta
Luhnify-8      1.00µs ± 1%     0.28µs ± 4%   -72.38%  (p=0.000 n=9+10)
Unluhnify-8     992ns ± 2%      274ns ± 1%   -72.39%  (p=0.000 n=10+9)
```
The unused luhnValidate function is gone.
=> lib/protocol: Faster Luhn algorithm and better testing

go.mod, go.sum
Thsi updates the `github.com/jackpal/gateway` to a version that doesn't use `/sbin/route` and `/sbin/ip`, indirectly fixing #5288.
Tests still pass, I also tested a local snap build, denials for those binaries are gone.
=> go.mod: Update jackpal/gateway dependency (fixes #5288)

lib/util/utils.go
This fixes a potential data race in lib/util.service. That type's Serve method sets a field, stopped, while holding a lock. Its Stop method, however, gets the field's value without synchronizing. The solution is to get the variable while holding the lock but only use it after unlocking.
=> lib/util: Fix potential data race

lib/rand/random.go, lib/rand/random_test.go, lib/rand/securesource.go
Various small fixes to the lib/rand package. The potentially controversial one is aa86ab22f8592a4308efe6579a0cf826d9372231, which makes rand.Int64 use the synchronized interface to crypto/rand.Reader in the lib/rand package.
=> lib/rand: Various fixes

lib/versioner/staggered.go
Make intervals more readable, which also address the "30 day" interval having the wrong value. Fixes #6410.
Describe what testing has been done, and how the reviewer can test the change
if new tests are not included.
to the corresponding pull request on https://github.com/syncthing/docs or describe
the documentation changes necessary.
=> lib/versioner: Fix "30 days" interval (fixes #6410)

lib/versioner/staggered_test.go
This extends the tests for intervals of the staggered versioner to cover
all intervals.
This relates to github issue #6410.
This is an addition to #6410. If the tests cover all intervals, wrong intervals would be detected regardless of their notation.
Run tests in `lib/versioner/staggered_test.go`, should be green. Modify any interval, tests should be red.
=> lib/versioner: Extended tests of intervals

lib/fs/basicfs.go, lib/fs/basicfs_test.go
This is a result of #6482, where the problem is that a basic fs with "" root points at "/". We actually have a test ensuring that behaviour:
https://github.com/syncthing/syncthing/blob/master/lib/fs/basicfs_test.go#L517
However that is in my opinion wrong in general and definitely inconsistent with golangs filepath package
>  If the result of this process is an empty string, Clean returns the string ".". 
and also our `fs.IsParent`, which treats "" the same as ".". Therefore I propose to change that behaviour.
=> lib/fs: Basic with empty root shouldn't point at /

lib/db/namespaced.go, lib/db/namespaced_test.go, lib/model/folder_sendrecv.go
Here are two unrelated patches that simplify the codebase. One replaces sha256.New + Write with the sha256.Sum utility function. The other replaces a []byte with a string to let the type system enforce immutability, instead of having to set the cap on the []byte.
=> lib/db, lib/model: Code simplifications

lib/db/set.go, lib/db/structs.go, lib/model/folder.go, lib/model/folder_recvonly_test.go
Scenario here is that a file is deleted locally on a receive-only folder, but exists on a remote. That remote is then removed. Currently that deleted file will show up as locally changed. When we delete something, we do pick this up in the scanner and mark it as not locally changed if noone else has the file. However in this scenario there is no change for the scanner to notice, as it is already deleted.
Unit test for the scenario described above.
=> lib/model: Handle deleted items on RO for remove remotes (fixes #6432)

gui/default/syncthing/core/syncthingController.js, gui/default/syncthing/transfer/neededFilesModalView.html
I wanted to fix https://github.com/syncthing/syncthing/issues/6408. From finding https://github.com/michaelbromley/angularUtils/issues/209 and the fact that the remote out of sync modal doesn't show the same issue, I thought that the changes in this PR would fix #6408 - it doesn't. It's still a good change in my opinion, makes the out of sync modal work more like the other modals and less LOC.
Out of sync modal still works.
=> gui: Refactor out-of-sync modal

lib/api/api_auth.go, lib/config/ldapconfiguration.go
This adds the functionality to run a user search with a filter for LDAP
authentication. The search is done after successful bind, as the binding
user. The typical use case is to limit authentication to users who are
member of a group or under a certain OU. For example, to only match
users in the "Syncthing" group in otherwise default Active Directory
set up for example.com:
<searchBaseDN>CN=Users,DC=example,DC=com</searchBaseDN>
<searchFilter>(&amp;(sAMAccountName=%s)(memberOf=CN=Syncthing,CN=Users,DC=example,DC=com))</searchFilter>
The search filter is an "and" of two criteria (with the ampersand being
XML quoted),
- "(sAMAccountName=%s)" matches the user logging in
- "(memberOf=CN=Syncthing,CN=Users,DC=example,DC=com)" matches members
of the group in question.
Authentication will only …
=> lib/api: Add LDAP search filters (fixes #5376)

cmd/strelaypoolsrv/main.go, cmd/strelaysrv/pool.go, cmd/strelaysrv/testutil/main.go, lib/relay/client/methods.go, lib/relay/client/static.go
See individual commits. In principle:
- Make the tester return an error instead of a boolean, and pass this back to the client for visibility.
- Improve the client to show better errors about what's going on
- Fix incorrect handling of the "incorrect response code" error on the pool server
- Fix incorrect status code accounting on the pool server
- Add configurable queue length and concurrency for the test routines on the server
(merge as I rebase, I guess, unless there are a lots of changes in the meantime)
=> cmd/strelay*: Various tweaks

lib/osutil/atomic.go, lib/osutil/atomic_test.go
This was needed in ancient times but not currently.
(To be borne out by unit test on Windows builder)
=> lib/osutil: Don't remove before rename on Windows (ref #6493)

cmd/strelaypoolsrv/main.go
Successful LRU cache lookups modify the cache's recency list, so RWMutex.RLock isn't enough protection.
Secondarily, multiple concurrent lookups with the same key should not lead to multiple rate limiters being created, so release the lock only when presence of the key has been ascertained.
=> cmd/strelaypoolsrv: Fix race condition in caching

lib/ignore/ignore.go, lib/ignore/ignore_test.go, lib/scanner/walk_test.go
The assumption when "optimizing" includes in https://github.com/syncthing/syncthing/pull/6151, that all rooted patterns without wildcards do not require scanning the entire tree is just not correct - at least not without additional smarts. We'd have to make sure that all the parent path components are also included. That's definitely doable, but not something I am interested in right now. So I just dumbed the logic down to just optimize includes in the root, nowhere else.
I needed to adjust the unit testing in lib/ignore, but the relevant test reproducing #6151 is in lib/scanner.
=> lib/ignore: Only skip for toplevel includes (fixes #6487)

lib/db/lowlevel.go, lib/db/transactions.go
This fixes the panic in #6457, however not the underlying problem.  
After quite extensive debugging with @eiszfuchs (thanks) the problem there became clear: While the check on upgrade makes sure there is a file info for ever global list entry, it does not unmarshal that file info. On dropping a file we do, and as part of unmarshalling we also look for the block list. That lookup then failed and caused the file not found error (which mislead me for a long time, as the file itself is there, just not the blocks).
Now we only get the truncated file info when dropping a file, which is enough and thus avoids the panic. The file info is still without a block list, so a problem will likely come up at some other point. And I have no clue what might cause it in the first place. In the debugged …
=> lib/db: Don't get blocklists on drop and missing continue (ref #6457)

cmd/stcrashreceiver/sentry.go, cmd/stcrashreceiver/stcrashreceiver.go
Seeing thousands of reports is no use when we don't know if they
represent one poor user or thousands.
I'm taking some effort to make the user ID meaningless and non-tracking.
=> cmd/stcrashreceiver: Enable (rough) affected users count

lib/db/lowlevel.go, lib/syncthing/debug.go, lib/syncthing/syncthing.go
This makes the GC runner a service that will stop fairly quickly when
told to.
As a bonus, STTRACE=app will print the service tree on the way out,
including any errors they've flagged.
=> lib/db: Make database GC a service, stop on Stop()

cmd/syncthing/main.go, lib/db/namespaced.go
Make sure we check for updates max once per minute, and attempt upgrades to the same version max once per hour. For that we store the last times we checked for and attempted an upgrade plus which version we attempted to upgrade to. The reason for the distinction is that we want to reasonably quickly pick up new releases (e.g. if we push a quick followup-release to something broken),  put not attempt repeatedly to check for upgrades or to try to upgrade to the same version.
In cmd/syncthing, we handle a db backend, not a lowlevel. However that's actually enough for `db.NamespacedKV`, I just needed to replace lowlevel with backend there.
Manually tested that upgrading still works. Then put garbage into the release url and the first time an error was printed, the second time not (check was …
=> cmd/syncthing, lib/db: Store upgrade info to throttle queries (fixes #6513)

lib/db/schemaupdater.go
I just stumbled over this error `delErr` which is defined outside of the iterator scope but never checked. Fixing it has virtually no impact (only <0.14.50), but I'd still rather have it fixed for the sake of it.
=> lib/db: Handle missed error variable in old schema upgrade

lib/db/blockmap.go
Removes an unused global variable in lib/db.
=> lib/db: Remove unused blockFinder global

lib/model/model.go, lib/model/model_test.go
sanitizePath in lib/model compiles the same RE every time it is called. Moving the RE to a global is not only faster, but also catches errors in the RE earlier.
=> lib/model: Harden sanitizePath

build.go, cmd/stdiscosrv/main.go, cmd/strelaysrv/main.go, lib/build/build.go
This changes the build script to build all the things in one go
invocation, instead of one invocation per cmd. This is a lot faster
because it means more things get compiled concurrently. It's especially
a lot faster when things *don't* need to be rebuilt, possibly because it
only needs to build the dependency map and such once instead of once per
binary.
In order for this to work we need to be able to pass the same ldflags to
all the binaries. This means we can't set the program name with an
ldflag; instead I made it auto detect using os.Executable().
When it needs to rebuild everything (go clean -cache):
( ./old-build -gocmd go1.14.2 build all 2> /dev/null; )  65.82s user 11.28s system 574% cpu 13.409 total
( ./new-build -gocmd go1.14.2 build all 2> /dev/null; )  63.26s user 7.12s …
=> build, lib/build: Build faster, auto detect program name

lib/model/folder.go
Delay trying to setup watches up to an hour on errors. If setting up is successful, the interval is reset if the watch lasted for longer than the retry interval, otherwise the retry interval is also increased and watching retried.
=> lib/model: Delay watch setup on errors (fixes #5731)

go.mod, go.sum, lib/db/lowlevel.go
I was hoping you'd wait just an hour longer to merge #6537, because I just changed the Blobloom API (methods and Config fields renamed). Here's an update to v0.1.1, which is faster still and is now under the Apache 2.0 license instead of MPL.
=> lib/db: Upgrade to Blobloom v0.1.1

lib/protocol/protocol.go, lib/rc/rc.go, lib/util/utils.go
Add Unlock before panic to avoid possible deadlock.
Three forgetting-unlock bugs are fixed in this PR:
1. In lib/protocol/protocol.go:
`func Request` forgets `c.awaitingMut.Unlock()` before panic
2. In lib/rc/rc.go:
`func eventLoop` forgets `p.eventMut.Unlock()` before panic
3. In lib/util/utils.go:
`func Stop` forgets `s.mut.Unlock()` before panic
=> lib/protocol, rc, utils: Add Unlock before panic

lib/model/folder.go, lib/model/folder_sendrecv.go, lib/model/model.go, lib/model/model_test.go
See #6557 for infos on what this fixes.
The main fix is not using `CheckHealth` when pulling (and eradicating that function).
Folder error state includes ignores - any method that claims to check folder health but doesn't check ignores is misleading: `s/getHealthError/getHealthErrorWithoutIgnores/'. A function called `getHealthError` that also loads ignores is quite opaque: `s/getHealthError/getHealthErrorAndLoadIgnores/`. Those are quite a mouthful, suggestions for betting naming/handling of that are very welcome.
=> lib/model: Refactor folder health/error handling (fixes #6557)

gui/default/syncthing/core/syncthingController.js
Just got a JS error using 1.5.0-rc.1 and the cause is obviously #6452 - apparently there was no download progress going on when I "manually tested" that. Thus it is RC material.
=> gui: Fix regression on refreshNeed (fixes #6560, ref #6452)

lib/config/folderconfiguration.go, lib/model/folder_sendrecv.go, lib/model/folder_sendrecv_test.go
Limit the number of outstanding writes at any given time to something sane.
⁉️
=> lib/model: Use semaphore to limit concurrent folder writes (fixes #6541)

lib/db/schemaupdater.go, lib/db/transactions.go
Removes some duplication around getting and unmarshaling global lists/`VersionList`.
No change in behaviour except for an old transition which will no longer ignore unmarshal errors (as it doesn't handle it itself).
=> lib/db: Refactor getting global lists

lib/model/progressemitter.go, lib/model/progressemitter_test.go
If the network is slow, this could block while holding a lock, and block other components that use progress emitter (Completion for the UI for example)
=> lib/model: Progress emitter network operations dont need to be blocking

lib/model/folder_sendrecv.go
Directly mention directory deletion instead of wrapping the error, as that can get forgotten (and is missing now in one place) and it's always necessary context to understand those errors.
And I tried to make the "incomprehensible error message" `errDirNotEmpty` more comprehensible @arpie42 @LinuxOnTheDesktop
=> lib/model: Improve errors when deleting dirs (fixes #6575)

gui/default/assets/css/overrides.css, gui/default/syncthing/device/globalChangesModalView.html, gui/default/syncthing/transfer/localChangedFilesModalView.html, gui/default/syncthing/transfer/remoteNeededFilesModalView.html
This change forces breakage of long file paths and names, so that the text does not overflow the available display area, which is the case in many places in the GUI right now, such as "Recent Changes" or "Out of Sync Items". See the commit for details.
I have tested in Chromium 79.0.3945.130 and IE 11.973.17763.0, but the `word-break: break-all` CSS rule itself is supported in all browsers, starting from at least IE 6.
Text cut and date not visible before:
Text wrapped and date visible after:
=> gui: Prevent text overflow in file lists (fixes #6268)

lib/model/folder_sendrecv_test.go, lib/model/model.go, lib/model/model_test.go, lib/model/requests_test.go, lib/model/testutils_test.go
Folders are never added and started separately except in tests and the "unlocked" functions aren't used at all except in tests, thus I merged the two into a single function. And I renamed `removeFolderLocked` to `deleteFolderEntriesLocked`, as it isn't the locked equivalent to `removeFolder`. These changes do not change functionality, they just make things more easier to understand and thus more robust (currently one might wonder about the relevance of the distinction of adding and starting a folder, when there isn't any).
For tests that need to inject a custom ignore option and previously did this by adding a folder, then changing ignores and the starting the folder, I just added a variant of `addAndStartFolder` where ignores are passed as an argument.
For send-receive tests that rely on …
=> lib/model: Merge add and start folder funcs and related refactor

go.mod, lib/model/folder.go, lib/protocol/vector.go, lib/protocol/vector_test.go
This makes version vector values clock based instead of just incremented
from zero. The effect is that a vector that is created from scratch
(after database reset) will have a higher value for the local device
than what it could have been previously, causing a conflict. That is, if
we are A and we had
{A: 42, B: 12}
in the old scheme, a reset and rescan would give us
{A: 1}
which is a strict ancestor of the older file (this might be wrong). With
the new scheme we would instead have
{A: someClockTime, b: otherClockTime}
and the new version after reset would become
{A: someClockTime+delta}
which is in conflict with the previous entry (better).
In case the clocks are wrong (current time is less than the value in the
vector) we fall back to just simple increment like today.
This scheme is …
=> lib/protocol: Avoid data loss on database wipe by higher version numbers (fixes #3876)

cmd/strelaypoolsrv/main.go, lib/api/api_statics.go, lib/api/api_test.go, lib/auto/auto_test.go, script/genassets.go
This changes the static asset storage in lib/api and cmd/strelaypoolsrv from []byte to string to prevent a copy of the 1.6MB of asset data at startup (verified by inspecting the assembler output, go tool compile -S gui.files.go). Since syncthing runs two processes, 3.2MB of RAM is saved.
This requires the HTTP server code to use WriteString instead of Write. I've checked the stdlib implementations of http.ResponseWriter and they implement io.StringWriter, so no performance should be lost there.
The only functional change is that the Content-Length is no longer set when sending static assets to a browser that doesn't understand gzip (using io.Copy was just the easiest option).
=> script: Store assets as strings

Dockerfile
When syncthing container is running in host network mode, the health check fails. However, the services work fine. On dashboard tools like Portainer, it gives a wrong impression that the services aren't responding.
Validated that in host network mode the docker container functions properly.
=> Removed health check from Dockerfile (fixes #6604)

lib/db/lowlevel.go
Not eat all the blocks
It didn't eat all my blocks (yet)
---
The diff looks like a no-op, but there's another (first) call site for bloomHash() where we correctly give it just the hash in question. On the second call site we need to extract the hash from the database key (i.e., chop off the leading type byte) and we do that before, now...
=> lib/db: Hold the bloom filter the right way (fixes #6614)

lib/model/model_test.go
Prevents panic on accessing the nil `res` below.
=> lib/model: Prevent panic on test failure (ref #6618)

.gitignore, lib/api/auto/.gitignore
Asset location changed: Use the same local .gitignore that's already in `cmd/strelaypoolsrv/auto`.
=> build: Update .gitignores for new asset locs (ref #6624)

lib/connections/quic_listen.go, lib/connections/relay_listen.go, lib/connections/service.go, lib/connections/structs.go, lib/connections/tcp_listen.go, lib/discover/global.go
So the first problem is that there is a race between the listeners starting and the global announce starting.
It seems global announce tries to send a notification straight away, at which point none of the listeners might be up yet, so it sends nothing, and backs off for 5 mins.
Second problem is that listeners starting/stopping do not actually notify of the addresses changing, which means the announcer does not know it needs to do something and, and we end up waiting the whole announceErrorRetryInterval (5mins) after startup before sending the first real announcement.
=> lib/connections: React to listeners going up and down faster

lib/db/transactions.go
This PR is a weird one: It corrects mistakes in #6413, but those mistakes are "benign". Meaning I only discovered them because I needed to change exactly that code for the global version list refactor and it looked off, however the both the old and corrected code do the same thing in the end. The corrected one is just less convoluted and/or actually takes the shortcuts intended (e.g. the return in line 809).
I suggest to look at it as separate commits: The complete diff is rather ugly, but the first four commits are straightforward (just moving stuff around). The last one isn't entirely straight forward, but it's still much clearer what's going on than in the full diff.
This is sort of a grey area in terms of RC: The PR only changes stuff that's RC specific, but there's also no real bug, …
=> lib/db: Fix updating/removing from global (ref #6413)

lib/db/lowlevel.go, lib/db/schemaupdater.go, lib/model/folder.go
The source of the problem is in lowlevel.go
I also have a variant for the release branch - it's a bit annoying due to the db schema numbers.
=> lib/db: Dont add symlinks to blocks map (fixes #6637)

lib/fs/basicfs_watch_test.go
We adjust `backendBuffer` before and after testing and that is accesses in `watchLoop`.
=> lib/fs: Prevent race-detector triggering in tests (fixes #6608)

lib/model/folder_sendrecv.go, lib/model/requests_test.go
There likely more tests that check for a specific, expected version vector. And that's now a race by definition, which probably isn't triggered often as it has seconds perecision and most tests take much less than a second.
=> lib/model: Adjust remote-rename-test to timer-based versions (fixes #6625)

Dockerfile
Fixed the health check instead of removing it for host networks as per @thedanbob's suggestions. Verified that the health check works for both host as well as non-host network configurations.
=> Fixed Docker health check for host networks (fixes #6604)

lib/db/db_test.go, lib/db/set.go, lib/db/set_test.go
From the code:
```
// If one file info is present multiple times, only keep the last.
// Updating the same file multiple times is problematic, because the
// previous updates won't yet be represented in the db when we update it
// again. Additionally even if that problem was taken care of, it would
// be pointless because we remove the previously added file info again
// right away.
```
Added a unit test updating the same file twice in one update, then checking that it's not present twice in the sequence bucket afterwards (it is now).
=> lib/db: Filter repeat files in one update (ref #6650)

lib/model/folder.go
We can't just drop the snap because it's in use elsewhere. This should
be equally functional.
=> lib/model: Partial revert of rename fix (fixes #6653)

cmd/syncthing/main.go
This is not an ignorable error, because it can happen if we fail to
allocate a free port for the GUI or sync port on first startup.
=> cmd/syncthing: Don't crash when failing to create default config (fixes #6655)

lib/model/folder_sendrecv.go
If we fail to take the rename shortcut we may crash on a later loop,
because we do trickiness with the indexes but the original buckets[key]
in "range buckets[key]" isn't re-evaluated so i exceeds the max index.
=> lib/model: Don't crash when taking rename shortcut (fixes #6654)

cmd/stindex/dump.go
Recently added DB key prefixes KeyTypeBlockListMap and KeyTypeVersion
were unknown to the stindex dumping tool.  Add basic parsing to dump
their key structure.  Clean up some surrounding code along the way.
This is not tested, as I haven't seen any such DB entries in my database yet.  Just wanted to find out what KeyType was listed with "???" that was a remnant of previous tests in #6443.
=> cmd/stindex: Add missing KeyType values in stindex dump code

lib/db/transactions.go
That's an oversight from #6367: If db debug logging is activated, we still panic on corrupt sequences, even though we now handle that (and warn). Happened when trying to debug a db problem: https://forum.syncthing.net/t/unable-to-solve-non-increasing-sequence-detected-error/15019  
I just relegated it to a debug log instead of removing entirely, as it might still be useful if that function is ever called in a different context than from model.
=> lib/db: Don't panic on seq. coruption when debugging

lib/db/meta.go, lib/db/set_test.go
This is v1.6.0 RC material.
Initialize device needs when it first enters metadata, not when it first changes its needs (#6668).
Added a new test that updates just a remote and then checks it doesn't need anything.
=> lib/db: Initialize need meta on first dev occurrence (fixes #6668)

lib/model/model.go
I am not aware of any problems caused by this, but it's clearly not useful to go ahead creating a cluster config when the device it is created for doesn't exist. As to why a device can disappear while the connection is still there: The usual config racyness. Returning an error here causes the device the connection to be closed, which is fine given we don't know the device.
=> lib/model: Handle concurrently removed device in ClusterConfig

lib/model/folder_sendrecv.go, lib/model/folder_sendrecv_test.go
https://forum.syncthing.net/t/problems-when-syncing-from-windows-to-synology-nas/14996
When a directory deleted on a remote contains receive-only files, rescanning won't help and the current error message wont direct the user at the actual problem (locally changed files).
Also the scan chan cannot be nil, that might be true in tests, but not everywhere else (we send to it without checking for nil-ness in various other places). And if it is nil in tests, that should be changed instead of having weird code paths like this.
=> lib/model: Fix checking children when trying to delete a dir (fixes #6646)

lib/api/mocked_config_test.go, lib/config/wrapper.go, lib/model/model.go
Currently for every auto-accepted folder in a cluster config, we change that folder in the config and wait for that change to happen. Now instead of committing to config, `handleAutoAccepts` returns the changed config object and all of the changes are committed at once in `ClusterConfig`.
=> lib/config, lib/model: Commit auto-accepted folders all at once

lib/db/backend/leveldb_backend.go
This reduces the size of our write batches before we flush them. This
has two effects: reducing the amount of data lost if we crash when
updating the database, and reducing the amount of memory used when we do
large updates without checkpoint (e.g., deleting a folder).
I ran our SyncManyFiles benchmark as it is the one doing most
transactions, however there was no relevant change in any metric (it's
limited by our fsync I expect). This is good as any visible change would
just be a decrease in performance.
I don't have a benchmark on deleting a large folder, taking that part on
trust for now...
=> lib/db: Adjust transaction flush sizes downwards

lib/scanner/blocks.go, lib/scanner/blocks_test.go
This is fallout from the discussion over at  #6674. It turns out that the function scanner.Validate does benefit from Adler-32 hashes, after rewriting it.
The current function checks a block against an expected Adler-32 hash, then against a SHA-256 if it doesn't match. The rewritten version skips the latter check, since the SHA-256 won't match if the Adler-32 doesn't (by the assumption made in the rest of the code base, that sha256(x) = sha256(y) implies x = y). I've written some benchmarks to show what this buys:
```
name        old time/op    new time/op    delta
Validate-8    68.4ms ± 1%    10.5ms ± 0%   -84.64%  (p=0.000 n=10+10)
name        old alloc/op   new alloc/op   delta
Validate-8    26.4kB ± 0%     0.0kB       -100.00%  (p=0.000 n=9+10)
name        old allocs/op  new allocs/op …
```
=> lib/scanner: Simplify, optimize and document Validate (#6674)

lib/model/folder.go
The pull fail pause is increased on every failed pause, even if the pull was triggered and thus happened way ahead of that pause:
```
May 28 20:27:07 [...] isn't making sync progress - retrying in 16m8.081801858s.
May 28 20:26:59 [...] isn't making sync progress - retrying in 8m5.21589791s.
May 28 20:26:53 [...] isn't making sync progress - retrying in 4m4.313521634s.
May 28 20:26:49 [...] isn't making sync progress - retrying in 2m2.50329418s.
May 28 20:26:47 [...] isn't making sync progress - retrying in 1m1.771580476s.
```
While not particularly harmful, it looks weird and definitely isn't the intention. Thus the last time a pull happened is now tracked and the puller pause is not increased if the time since the last pull is smaller than the current pause.
And the precision to which go …
=> lib/model: Don't increase pull pause on triggered pull

lib/connections/service.go
Don't hang on malformed URLs.
Manual.
=> lib/connections: Skip and warn on malformed URLs (fixes #6697)

cmd/syncthing/main.go, lib/config/optionsconfiguration.go
We inadvertently moved the cutoff to the wrong side of zero. Adding a small convenience function.
=> cmd/syncthing: Correct auto upgrade criteria (fixes #6701)

build.go
Adds a command to build.go that parses tags and tag messages to create a decent looking changelog. The purpose is to add something like `go run build.go --num-versions=10 changelog > CHANGES.txt` to the build/release process and thus automatically include a changelog in the release.
(Next sub-step is to also copy that file in to `gui/default/` and add a thing to show it in a notice on first start after upgrade.)
=> build: Add "changelog" command

lib/config/config.go
This fix adds missing quic listener on same port as TCP incase of default port being blocked
fixes #6679
=> lib/config: Add missing quic address in case of non-default port (fixes #6679)

lib/db/schemaupdater.go
This fixes two bugs in master on the schema transition for the new global version list.
=> lib/db: New VersionList migration fixes (ref #6638)

lib/build/build.go
This adds some env vars to the long version string as if they were build
tags. The purpose is to better understand what code was running or not
in the version output, usage reporting and crash reports. In order to
prevent possible privacy issues the actual value of the variable is not
reported, just the fact that it was set to something non-empty.
Example:
% ./bin/syncthing --version
syncthing v1.6.1+47-g1eb104f3-buildtags "Fermium Flea" (go1.14.3 darwin-amd64) jb@kvin.kastelo.net 2020-06-03 07:25:46 UTC [stnoupgrade, use_badger]
=> lib/build: Add some env vars as synthetic build tags

cmd/stcrashreceiver/sentry.go, cmd/stcrashreceiver/sentry_test.go
This extracts the extra tags from any `[foo]` stuff at the end of the
version and sends them to Sentry for indexing.
If I need to modify that regexp again I'll probably write a from scratch
tokenizer and parser for our version string instead...
=> cmd/stcrashreceiver: Pick up extra build tags and send to Sentry

cmd/stindex/dump.go, cmd/strelaysrv/listener.go, lib/db/db_test.go, lib/db/lowlevel.go, lib/db/meta.go, lib/db/transactions.go, lib/protocol/deviceid.go, lib/protocol/deviceid_test.go, lib/relay/protocol/packets.go
Return an error from DeviceIDFromBytes() if the length does not match,
instead of panicking.
Change all callers to handle the potential error value.  If possible,
pass it up or handle the condition gracefully, and panic immediately
after the function call in case there is no obvious better reaction.
Based on a related discussion in #6443.
Test suite passes, no functional changes expected.
=> lib/protocol: Avoid panic in DeviceIDFromBytes

lib/connections/service.go, lib/nat/service.go, lib/nat/structs_test.go
I added exported methods to control the nat service activity. The alternative would have been to subscribe the nat service to config changes, but this option felt a bit more straight forward/has less moving part.
=> lib/connections, lib/nat: Correctly dis-/enable nat (fixes #6552)

lib/scanner/walk.go
Stating every file in the scanner seems entirely superfluous, as we are already given the file info when walking the filesystem.
=> lib/scanner: Save one stat call per file

go.sum, lib/api/mocked_config_test.go, lib/config/wrapper.go, lib/connections/service.go
This PR is for the encryption branch (https://github.com/syncthing/syncthing/tree/encryption).
Avoids copying the entire config on every handled connection.
=> lib: Add FolderPasswords to config.Wrapper

lib/db/keyer.go, lib/db/keyer_test.go
This removes two unused methods.
=> lib/db: Remove unused keyer methods

cmd/strelaysrv/pool.go
Fixes #6733
When joining a relay pool, the relay server always prints this line to logs:
`Joined pool https://relays.syncthing.net/endpoint, failed to deserialize response: http2: response body closed`
It happens because the response body is already read and closed a few lines above the response is being tried to deserialize. The PR fixes the deserialization of the response to print a proper log message and use a proper rejoin time
Run the relay server, observe a proper joining message in logs:
`Joined pool https://relays.syncthing.net/endpoint, rejoining in 48m0s`
Nothing here
Nothing here
=> cmd/strelaysrv: Fix JSON unmarshalling when joining a relay pool (fixes #6733)
