syncthing/syncthing

internal/files/leveldb.go
internal/files/set.go
internal/files/set_test.go
internal/model/model.go
internal/model/puller.go
internal/scanner/walk.go

Prevents us from doing stupid things to the folder root (empty file
path) when nodes disconnect...
(integration running)

Use comma-ok idiom to signal files missing in database (fixes #1186)

---

internal/upnp/upnp.go
internal/upnp/upnp_test.go

Properly handle absolute URLs when parsing UPnP service control URLs

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/calmh/xdr/reader.go
internal/protocol/message.go
internal/protocol/message_xdr.go
internal/protocol/protocol.go
internal/protocol/protocol_test.go

Not all of the ones discussed, but the ones that are not in the middle of the clusterconfig message. *Should* be backwards compatible...
(Will need an update to https://github.com/syncthing/protocol/blob/master/BEPv1.md as well)

Add some new protocol fields

---

gui/assets/css/overrides.css
gui/index.html

- Added colored status indicator narrow screens.
- Added section headers

Added colored status indicator for narrow screens. (Fixes #1084)

---

gui/index.html

Rename "Last File Synced" to "Last File Received" (fixes #1145)

---

cmd/syncthing/main.go
internal/events/events.go
internal/model/model.go

DDoS github!
By the way, I hope you don't mind my commits traveling back in time.
Aiming for a stupid 1 commit a day, and need to cover up for dem
holidays.

Connecting to a newer node triggers autoupgrade check (fixes #1177)

---

gui/index.html

Was getting kinda annoying clicking links in the footer and it navigating away from the page, I've added "_blank" as the target to those links.

Change Bottom Bar links to a new tab/window

---

internal/model/model.go
internal/model/model_test.go

Requests from valid devices for valid folders should be rejected if the
folder is not shared with that device.

Verify folder<->device permission in Request

---

gui/index.html

Small improvements for job queue (introduced in #629)
- change to link element to indicate click action with pointer
- add title attribute for better usability
- move icon next to file name

Small improvements for job queue

---

gui/index.html

- Move panels (new device, new folder, notice) to top of page (#1270)
- Add missing icons to panel headers (restart, new folder, notice)

Move panels to top of page (ref #1270)

---

gui/index.html

Fix button "override changes" line break (fixes #1144)

Fix button "override changes" line break (fixes #1144)

---

etc/linux-systemd/system/syncthing@.service
etc/linux-systemd/user/syncthing.service

@AudriusButkevicius earns the credits for this pull request: https://github.com/syncthing/syncthing/issues/1324#issuecomment-72389066

Added exit code definitions to systemd service files (fixes #1324)

---

internal/model/puller.go

Extra comments explain current issues.

Fix issues with renames

---

internal/db/leveldb.go

This reduces the startup memory footprint by almost half on my normal setup. Heap profiling showed the most memory were allocated by `leveldb.Batch.grow()` because we create quite large batches when clearing indexes at startup. Even when that's removed, it doesn't hurt to keep batches from growing too large.

Reduce memory usage by writing smaller batches

---

cmd/syncthing/main.go

Typo fix. Fixes #1358

---

cmd/syncthing/gui.go
internal/db/leveldb.go
internal/db/set.go
internal/model/model.go
internal/model/model_test.go
internal/model/puller_test.go

We'll need this for the selective sync, plus useful to have in general, as other can query this.

Add /rest/tree API call

---

etc/windows/ReadMe.txt
etc/windows/SyncThingSetup.nsi
etc/windows/syncthingservice.xml

NSIS script to create Setup.exe for installing SyncThing on Windows as a
Service.

Windows Service Setup.exe

---

internal/model/puller.go
internal/model/sharedpullerstate.go
test/util.go

Related to https://github.com/syncthing/syncthing-android/issues/222

Fix chmod android

---

internal/scanner/walk.go

There is no user/group/others in Windows' read-only attribute,
and all "w" bits are set in os.FileInfo if the file is not read-only.
Do not send these group/others-writable bits to other devices
in order to avoid unexpected world-writable files on other platforms.

Do not send group/others-writable bits from Windows.

---

gui/index.html

use lowerCamelCase for file versioning display

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/calmh/xdr/cmd/genxdr/main.go
Godeps/_workspace/src/github.com/syncthing/protocol/message.go
Godeps/_workspace/src/github.com/syncthing/protocol/message_xdr.go

Lets get this in there while we're anyway going to break compatibility. Companion PR is https://github.com/syncthing/protocol/pull/9.

Add flags and options for future extensibility (fixes #1027)

---

internal/discover/discover.go

This reduces the amount of external queries by not repeating a query for
a given address if we have failed within the last three minutes.

Add negative cache time to global discovery

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/syncthing/protocol/common_test.go
Godeps/_workspace/src/github.com/syncthing/protocol/errors.go
Godeps/_workspace/src/github.com/syncthing/protocol/message.go
Godeps/_workspace/src/github.com/syncthing/protocol/message_xdr.go
Godeps/_workspace/src/github.com/syncthing/protocol/nativemodel_darwin.go
Godeps/_workspace/src/github.com/syncthing/protocol/nativemodel_unix.go
Godeps/_workspace/src/github.com/syncthing/protocol/nativemodel_windows.go
Godeps/_workspace/src/github.com/syncthing/protocol/protocol.go
Godeps/_workspace/src/github.com/syncthing/protocol/protocol_test.go
Godeps/_workspace/src/github.com/syncthing/protocol/wireformat.go
cmd/syncthing/main.go
internal/model/model.go
internal/model/model_test.go
internal/model/rwfolder.go

This cherry picks commits which were part of the temp index branch which are not necessarily related to temp indexes to start with.
Will allow me to make that branch much smaller.

Cherry-picks

---

cmd/syncthing/main.go

Expand locations during initialisation (fixes #1575).

---

AUTHORS
NICKS
gui/index.html

This is not supposed to be a change just to get me on the list of authors. I have stuff going on in the background, this just took precedence.

Fix a broken GUI string

---

internal/fnmatch/fnmatch_test.go

As suggested by @benapetr in https://github.com/syncthing/syncthing/commit/9fed75d59c1ea5d008eddc41d519c5ddeabc5751

Test combination of prefixes (@benapetr)

---

internal/config/config.go
internal/config/config_test.go
internal/config/testdata/example.xml
internal/config/wrapper.go

Copy configuration struct when sending Changed() events

---

cmd/syncthing/main.go

The exact time limits are a bit arbitrary of course.

Clean up config directory of old crap

---

cmd/syncthing/debug.go
cmd/syncthing/gui.go
cmd/syncthing/main.go

```bash
$ STTRACE=http syncthing
...
[P56IO] 2015/04/07 21:48:53.154593 gui.go:237: DEBUG: http: GET "/rest/system/upgrade": status 200, 84 bytes in 819.43 ms
[P56IO] 2015/04/07 21:48:53.167987 gui.go:237: DEBUG: http: GET "/rest/stats/folder": status 200, 267 bytes in 1243.85 ms
...
[P56IO] 2015/04/07 21:54:39.919058 gui.go:238: DEBUG: http: GET "/rest/events?since=16": status 200, 404 bytes in 2170.16 ms
...
[P56IO] 2015/04/07 21:58:46.285207 gui.go:238: DEBUG: http: GET "/bladdabludda": status 404, 19 bytes in 4.77 ms
```

Add HTTP request tracing

---

test/syncthingprocess.go

Not tested at all, and only works if the tests eventually give up and kill the process (rather than the tests getting killed due to timeouts waiting for something that will never happen).

Try capturing panics

---

gui/index.html
gui/scripts/syncthing/core/controllers/syncthingController.js

(Useful when debugging via screenshots...)

GUI version string includes OS and Arch

---

cmd/syncthing/gui.go
cmd/syncthing/main.go
internal/upgrade/upgrade_supported.go
internal/upgrade/upgrade_test.go
internal/upgrade/upgrade_unsupp.go

Current master does not build with -noupgrade tag

Fix compilation of -noupgrade builds

---

cmd/syncthing/main.go
internal/model/model.go
internal/model/rwfolder.go
internal/osutil/lstat_broken.go
internal/osutil/lstat_ok.go
internal/scanner/walk.go
internal/symlinks/symlink_windows.go
internal/versioner/external.go
internal/versioner/simple.go
internal/versioner/staggered.go

This might work, and causes minimal damage on non-Linux...

Work around broken Lstat on Android

---

cmd/syncthing/summarysvc.go
internal/db/truncated.go
internal/model/rwfolder.go

The first commit is smaller when viewed without whitespace changes...

Improve event handling a little bit.

---

internal/model/model.go

It had two different formats, and we use "items" instead of "numFiles" in other places.
(Discovered while documenting :)

Homogenize the LocalIndexUpdated event

---

internal/model/model.go

If all files are several gigs large, we will buffer hundreds of thousands of block infos in memory before committing to database, which is stupid.

Don't buffer large files a long time while scanning

---

cmd/syncthing/gui_auth.go

For https://github.com/syncthing/syncthing-android/issues/362 and similar in the future.

Reminder in debug output to explain high CPU usage

---

cmd/syncthing/connections.go
cmd/syncthing/main.go

I've started clarifying and moving out chunks into smaller more self contained services; this is the connection handling.

Break out connection handling into a service

---

cmd/syncthing/main.go
cmd/syncthing/upnpsvc.go
internal/config/config.go
internal/config/config_test.go
internal/upnp/upnp.go
test/h2/config.xml

This is a start to factor out and clarify the UPnP handling a little. But it also changes the behaviour somewhat, and I haven't tested it fully yet, so just a preview so far...

Break out UPnP port mapping into a service

---

build.go
build.sh
cmd/syncthing/gui.go
cmd/syncthing/gui_auth.go
cmd/syncthing/gui_csrf.go
cmd/syncthing/monitor.go
internal/config/config.go
internal/config/wrapper.go
internal/db/blockmap.go
internal/db/leveldb.go
internal/fnmatch/fnmatch.go
internal/ignore/ignore.go
internal/model/model.go
internal/model/model_test.go
internal/model/progressemitter.go
internal/osutil/osutil.go
internal/scanner/blocks.go
internal/scanner/walk.go
internal/sync/sync_test.go
internal/upgrade/upgrade_common.go
internal/upgrade/upgrade_supported.go
internal/upnp/upnp.go
internal/versioner/external.go
internal/versioner/simple.go
internal/versioner/staggered.go

With the exception of not requiring all exported things to be commented.

Run vet and lint. Make us lint clean.

---

internal/model/model.go
internal/scanner/walk.go
internal/scanner/walk_test.go

https://forum.syncthing.net/t/2564

User fewer hasher routines when there are many folders.

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/calmh/logger/logger.go
cmd/syncthing/main.go
cmd/syncthing/verbose.go

For the people who want to know what's going on.

Verbose logging

---

cmd/syncthing/main.go

This increases the database read and write caches from the default on machines (where we can detect) with lots of RAM. That increases performance at the price of using a little more RAM.

Adaptive database cache size

---

internal/fnmatch/fnmatch_test.go

Added test for combining case insensitive and negated patterns (fixes #1678)

---

cmd/syncthing/main.go

I'm not too happy with this patch because:
- I could not reuse the existing config.Load functionality (requires a deviceID)
- Code doesn't look too nice:/
- The HTTPS request does not verify signature (but this can be corrected if you feel this PR makes sense)

Upgrade running Syncthing instances (fixes #1692)

---

cmd/syncthing/monitor.go

`cmd.Wait()` closes the stdout and stderr fd:s, which is a race as these are accessed in parallell by the copyStdout and copyStderr functions. But when the process exits these exit anyway, so we can wait for them first.

Wait for stdout/stderr to close (fixes #1754)

---

cmd/stindex/main.go

This makes stindex simply iterate over every key in the database and print an interpretation of it, instead of using our internal database code. Makes it easier to debug corrupt or defective databases.

Simplify stindex

---

cmd/syncthing/main.go
internal/config/config.go
internal/config/config_test.go
internal/config/testdata/overridenvalues.xml

As per https://forum.syncthing.net/t/increased-memory-usage-since-0-11-2/2690

Tweak the database block cache size, and add config for it

---

cmd/syncthing/main.go

This makes the calculations depend on two constants, and caps it at 64 MiB for 8 GiB of RAM.

Further reduce maximum db block cache

---

internal/discover/discover.go
internal/upnp/upnp.go

Fixes UPnP failures on Windows.

Don't check interface flags on Windows

---

gui/index.html

Changes all date formatting to `yyyy-MM-dd HH:mm:ss`

Show date and time for web GUI notification (fixes #1833)

---

internal/upnp/upnp.go

Old code doesn't synchronize that the results actually get collected...

UPnP discovery results must not be collected in a background goroutine (fixes #1858)

---

internal/events/events.go

This is surprisingly memory expensive when Poll gets called a lot, such
as when syncing lots of small files generating itemstarted/itemfinished
events. It's line number three in this heap profile on the
TestBenchmarkManyFiles test:
jb@syno:~/src/github.com/syncthing/syncthing/test (master) $ go tool pprof ../bin/syncthing heap-13194.pprof
Entering interactive mode (type "help" for commands)
(pprof) top
80.91MB of 83.05MB total (97.42%)
Dropped 1024 nodes (cum <= 0.42MB)
Showing top 10 nodes out of 85 (cum >= 1.75MB)
flat  flat%   sum%        cum   cum%
32MB 38.53% 38.53%    32.01MB 38.54%  github.com/syndtr/goleveldb/leveldb/memdb.New
22.16MB 26.68% 65.21%    22.16MB 26.68%  github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).Get
13.02MB 15.68% 80.89%    13.02MB 15.68%  time.NewTimer …

Reuse a timer instead of allocating a new one in subscription.Poll

---

internal/model/rwfolder.go

Be more lenient against errors when deleting (fixes #1860)

---

internal/db/leveldb.go

Reuses key byte slices to reduce allocations:
benchmark                    old allocs     new allocs     delta
Benchmark10kReplace          178112         168615         -5.33%
Benchmark10kUpdateChg        567954         561557         -1.13%
Benchmark10kUpdateSme        238691         228680         -4.19%
Benchmark10kNeed2k           105382         103383         -1.90%
Benchmark10kHaveFullList     60230          60230          +0.00%
Benchmark10kGlobal           237484         227493         -4.21%
benchmark                    old bytes     new bytes     delta
Benchmark10kReplace          8725368       7661788       -12.19%
Benchmark10kUpdateChg        58155152      57441025      -1.23%
Benchmark10kUpdateSme        16130875      14996717      -7.03%
Benchmark10kNeed2k           6561685 …

Reduce allocations during iteration

---

cmd/syncthing/main.go

I don't remember why we started the GUI at the point we do, nor why we "start" the folder so long after "adding" them... If there was a good reason, yell! :)

Start folders before GUI/API (fixes #1918)

---

internal/model/rwfolder.go

Differentiate between content and metadata updates in ItemStarted/ItemFinished

---

internal/model/model.go

This skips the warning about "unsupported symlinks" for invalid or deleted symlinks (and as a side effect also accepts them into the index, which should be fine). It also prints the affected file paths to the log. This should be in the hypothetical list of "errored files" we should present instead of the cryptic "puller stopped" message in the future...

Dont warn about irrelevant symlinks, print path to culprit (ref #1945)

---

cmd/syncthing/gui.go
cmd/syncthing/main.go

The API never got the first few events ("Starting" etc) as it subscribed
too late. Instead, set up a subscription for it early on. If the API is
configured not to run this is unnecessary but doesn't hurt very much.

Fix API event subscription

---

cmd/syncthing/main.go

Include myID in the StartupComplete event

---

internal/model/model.go

The override should look like we detected the changes locally, or the
GUI and other things won't update correctly.
This is/was caught by the Override integration test, on my newly
refactored integration test suite which is soon ready for prime time, so
a test is coming. :)

Generate LocalIndexUpdated events in Override

---

internal/model/rwfolder.go

Incorrect error condition on shortcuts

---

gui/index.html
gui/scripts/syncthing/core/controllers/syncthingController.js

Simple State Summary of all local Folders

Display Local State Summary (All Folders)

---

cmd/syncthing/gui.go
internal/model/model.go
test/reset_test.go

The reset of all folders failed when there was no data for a given
folder, as it was not returned by db.ListFolders then. But we don't
really care about that, we can "reset" it anyway...

Fix reset DB

---

cmd/syncthing/gui.go
internal/model/model.go
internal/model/rwfolder.go

The only thing that comes to mind, apart from having an empty folder to start with, and then MkdirAll being the culprit.

Potential race between folder being added and scan (fixes #1986)

---

internal/model/rwfolder.go

This is a tentative fix for #2012, I've updated `handleDir()` in "rwfolder.go" to get the current value of the `setgid` bit of a directory and add that to the permissions used in `os.chmod`. I've tested this locally on my machine (running CentOS 6.5) between two Syncthing instances and it works, the `setgid` bit is now preserved locally on a machine.
I'm not sure if I've correctly handled the error of `Lstat` when creating a new directory, also I haven't tested this on non-linux.
I think this is probably the best way of resolving #2012, thoughts?

Preserve setgid bit on local directores (fixes #2012)

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/syncthing/protocol/protocol.go
Godeps/_workspace/src/github.com/syncthing/protocol/protocol_test.go
Godeps/_workspace/src/github.com/syncthing/protocol/wireformat.go
internal/model/model.go
internal/model/model_test.go

Also necessary for delta indexes and some other stuff...
https://github.com/syncthing/protocol/pull/14

Make sure connection is added to m.protoConn and m.rawConn before it's Start()ed (fixes #2034)

---

gui/index.html

Improve info text for device addresses (#2044)

Improve info text for device addresses (fixes #2044)

---

cmd/syncthing/main.go
internal/model/model.go
internal/model/model_test.go
test/norestart_test.go

Add folders without restart (fixes #2063)

---

internal/model/model.go
internal/rc/rc.go
test/scan_test.go

See https://forum.syncthing.net/t/does-updating-a-file-in-the-root-folder-watched-by-inotify-always-cause-full-rescan/5282/5

Reduce scanning effort

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/syncthing/protocol/common_test.go
Godeps/_workspace/src/github.com/syncthing/protocol/nativemodel_darwin.go
Godeps/_workspace/src/github.com/syncthing/protocol/nativemodel_unix.go
Godeps/_workspace/src/github.com/syncthing/protocol/nativemodel_windows.go
Godeps/_workspace/src/github.com/syncthing/protocol/protocol.go
internal/model/model.go
internal/model/model_test.go

Use protocol provided buffer for requests (fixes #1157)

---

gui/syncthing/folder/editFolderModalView.html
gui/syncthing/settings/settingsModalView.html

- settings: incoming/outgoing rate limit
- folder: maximum age (staggered file versioning)

Prevent negative values for number inputs

---

lib/model/rwfolder.go

This fixes a corner case I discovered in the symlink branch, where we
unexpectedly succeed in "replacing" an entire non-empty directory tree
with a file or symlink. This happens when archiving is in use, as we
then just move the entire tree away into the archive. This is wrong as
we should just archive files and fail on non-empty dirs in all cases.
New handling first checks what the (old) thing is, and if it's a
directory or symlink just does the delete, otherwise does conflict
handling or archiving as appropriate.

Clarify and correct handling of existing files/directories when pulling

---

cmd/syncthing/main.go

I thought we should be able to automatically drop and reinit the database when it's hopelessly hosed (as this is what we tell the users to do). However when implementing that I noticed https://github.com/syndtr/goleveldb/issues/121 and it turns out that `leveldb.RecoverFile` actually *does* handle this situation fine, it's just that we didn't take that code path because `leveldb/errors.IsCorrupted` doesn't do exactly what I thought it did. So the new `leveldbIsCorrupted` function takes care of that, and I didn't manage to cause corruption that triggered the resetDB code path, but it should work, right...? ;)

Recover from 'corrupted or incomplete CURRENT file' etc

---

lib/versioner/staggered_test.go

Can't reproduce https://github.com/syncthing/syncthing/issues/2165, any ideas?

Add unit test for staggered versioning (fixes #2165)

---

lib/model/model.go

https://forum.syncthing.net/t/syncthing-is-such-a-massive-resource-hog/5494/19?u=calmh
~~This is an opinion based PR... I'm not sure if the arm handling is appropriate, in particular. On the one hand we don't want to each through a phone battery in no time, on the other hand that poor little CPU certainly needs to put in all the effort it can to make any progress at all...~~
I removed the ARM case.

Adjust defaults for number of hashers based on OS

---

cmd/syncthing/usage_report.go

Relay server info, urVersion in ur

---

AUTHORS

The pull request #2259 has been merged faster than I was able to fix that
mistake. :) Sorry. Jenkins should be happy now as well.

Add my email to AUTHORS as well

---

lib/model/rwfolder.go

Instead, make sure we do the check as part of CheckFolderHealth before
pulling, and individually per file to try to not run out of space at
that stage.
(The latter is far from fool proof as we may pull lots of stuff in
parallell, but it's worth a try.)

Don't require free disk space when we might only update metadata

---

lib/model/model.go

Also clean up the logic a little, I thought it was a bit muddled.

Don't check for free space on master folders (fixes #2236)

---

cmd/syncthing/gui.go
cmd/syncthing/main.go
cmd/syncthing/summarysvc.go
cmd/syncthing/usage_report.go

Not necessarily the easiest way to fix just this bug, but the root cause
was using the (at that point uninitialized) cfg variable, so it seemed
sensible to just get rid of it to avoid that kind of crap.

Remove global cfg variable (fixes #2294)

---

cmd/syncthing/gui.go
cmd/syncthing/gui_auth.go
cmd/syncthing/main.go

Also removes STGUIAUTH and corresponding --gui-authentication as this
seems fundamentally insecure and I'm unsure of the actual use case for
it?
I recommend the [white space insensitive diff](https://github.com/syncthing/syncthing/pull/2336/files?w=1) on this one.

Fix STGUIAPIKEY and STGUIADDR overrides (fixes #2335)

---

lib/model/model.go
lib/osutil/osutil.go
lib/osutil/osutil_test.go

Reverts syncthing/syncthing#2337

Revert "Case insensitive renames, part 1"

---

lib/model/rwfolder.go

Plus copyright bump, minor grammatical fix.

Add missing parameter in disk space warning

---

gui/syncthing/device/editDeviceModalView.html
gui/syncthing/device/idqrModalView.html
gui/syncthing/settings/settingsModalView.html

Select text on click
- device ID
- remote device ID
- API key

Select text on click

---

man/refresh.sh

syncthing-bep(7) and syncthing-localdisco(7) had been added.

Update refresh.sh to fetch missing manpages

---

gui/assets/css/overrides.css
gui/index.html

Add space at bottom for scrolling on small resolutions

Add space for scrolling (fixes #2351)

---

cmd/syncthing/gui.go
cmd/syncthing/gui_auth.go
cmd/syncthing/main.go
lib/config/config.go
lib/config/config_test.go

Option -gui-address should accept scheme prefixes

---

cmd/syncthing/main.go
cmd/syncthing/usage_report.go

Print the single thread hash performance at startup

---

cmd/syncthing/addresslister.go
lib/config/config.go

I think those were all the unsafe cases.

Create a correct URL is more difficult than just slapping on a scheme (fixes #2316)

---

.gitignore
build.go
etc/firewall-ufw/README.md
etc/firewall-ufw/syncthing

This closes #2435 
Also updated .gitignore to not exclude the newly added preset for ufw.

Added ufw firewall application preset

---

lib/connections/connections.go

Prepping for some other changes here, makes the connection handling flow a little clearer.

Refactor out methods resolveAddresses, connectDirect, connectViaRelay

---

lib/upgrade/upgrade_supported.go

This is my first time messing with go, so be careful :smile:

made upgrade-system smarter (fixes #2446)

---

README.md

Just my 2 cents :)
Seems more clear for newbies.
Preview:

Update CI badge to specify environement (unix/windows)

---

lib/scanner/walk.go

This just renames a couple of variables and breaks out a few methods, with the exception of the one commit not marked "Refactor:", which I think does something wholly unnecessary. It tries to make sure we return filepath.SkipDir for symlinks, but as far as I know Walk does not follow symbolic links (the docs say so).
It passes the tests and the sync- and symlink integration tests.

Refactor the walk stuff a bit

---

cmd/syncthing/main.go
lib/db/leveldb_dbinstance.go

Might be good, probably doesn't hurt?

Compact database on startup (ref #2400)

---

man/refresh.sh

Since Github refuses me to push this trivial thing with
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: 3 of 3 required status checks are expected
To https://github.com/syncthing/syncthing.git
! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/syncthing/syncthing.git'
```
here is a PR for that. :)

Add syncthing-relay(7)

---

cmd/syncthing/main.go
cmd/syncthing/monitor.go

With this change, the behavior is as follows:
- SIGTERM / SIGINT: Exit cleanly (exit code 0)
- SIGHUP: Restart
This is the case both when hitting the monitor process or the inner
process, or if running with NORESTART (but then we won't restart,
obviously, just exit with code exitRestarting).
It enables "pkill -HUP syncthing" to do the right thing to restart all
Syncthings on package upgrade, for example.

Implement signal handling

---

lib/connections/connections.go

Making a PR just to produce a build.

More debug to reconnect loop

---

lib/model/model.go

Additional output on insufficient error (ref #2580)

---

lib/model/rwfolder.go

Use the [white space insensitive diff](https://github.com/syncthing/syncthing/pull/2601/files?w=1).

Don't verify free space for files when folder MinDiskFreePct==0 (fixes #2600)

---

cmd/syncthing/main.go

*Not actually tested on Windows*
The usual chicken-and-egg about having the command line option for logFile depend on the other command line options and having expanded the locations... I think this is the correct behavior again, but hey who knows. I can't be bothered to get a Windows running and the binary over there, but if someone happen to run Windows and wants to check that this fixes the "Log output saved to ${config}" crap that'd be awesome

Correctly set default logfile location on Windows (fixes #2608)

---

lib/model/rwfolder.go

Checks the existing blocks that can be reused when downloading a file so
that it only requires the space corresponding to the missing blocks.
This will prevent syncthing from claiming the folder doesn't have enough
space when resuming download of large files after they have been
partially downloaded.

WIP: Consider tempfile when checking for free space (fixes #2598)

---

lib/model/rwfolder_test.go

While trying to add tests to the space issue on #2598, I noticed these could be refactored a bit.
This creates a few utility functions to avoid repetition and removes some redundant checks.

Refactor rwfolder tests

---

cmd/syncthing/addresslister.go
cmd/syncthing/auditservice.go
cmd/syncthing/auditservice_test.go
cmd/syncthing/gui.go
cmd/syncthing/main.go
cmd/syncthing/summaryservice.go
cmd/syncthing/upnpservice.go
cmd/syncthing/usage_report.go
cmd/syncthing/verboseservice.go
lib/connections/connections.go
lib/discover/cache.go
lib/relay/relay.go
lib/upnp/upnp.go

Svc -> Service

---

lib/discover/cache.go
lib/discover/cache_test.go

We only need to protect the integrity of the "finders" and "caches" slices, and for that we only need an RLock except while actually appending to them. The actual finders and caches are concurrency safe on
their own.
With this change, slow lookups doesn't block status checks (the `ChildErrors()` call).

More fine grained locking in discovery cache (fixes #2667)

---

cmd/syncthing/main.go

Added STNODEFAULTFOLDER envvar to skip default folder creation

---

build.go
build.sh
lib/protocol/protocol_test.go

Because more info is nice.
Also tests are browseable in Jenkins.

Add XUnit compatible test results

---

cmd/syncthing/gui.go
cmd/syncthing/gui_test.go

This fixes both a race condition where we could assign s.stop from one
goroutine and then read it from another without locking, and handles the
fact that listener may be nil at shutdown if we've had a bad
CommitConfiguration call in the meantime.

Improve API/GUI shutdown handling (fixes #2694)

---

lib/model/rwfolder.go

Comments should explain it.
We happen to pass a deleted file to handleFile, which creates the shared puller state, truncates it at 128 bytes (.Size() returns 128 for deleted files), creates the temp file, pulls 0 blocks, and puts it in place.

Handle race while in the job queue (fixes #1263)

---

build.go

(build to reveal if this actually works through Jenkins...)

Codesign binaries in Mac OS X distribution packages

---

lib/osutil/rlimit_unix.go

RLimit comment typo

---

lib/upgrade/upgrade_supported.go

FetchLatestReleases: fix the error log message

---

cmd/syncthing/gui.go
cmd/syncthing/gui_auth.go
cmd/syncthing/gui_csrf.go
cmd/syncthing/main.go
lib/config/guiconfiguration.go

No idea whether this is idiomatic Go, or even the best way of solving this - please push back if not.

Support multiple API keys (command-line and config) (fixed #2747)

---

gui/default/index.html

gui: add tooltips (title) to the folder path and syncthing version

---

AUTHORS
NICKS
gui/default/index.html

(to indicate it is a master directory)

gui: add a lock icon to the folder title for easy overview (fixes #2703)

---

lib/model/model.go

When an existing file becomes ignored we set the invalid bit on it. If we then unignore it, the scanner will clear the invalid bit when it sees it again. But if we delete the file, then unignore it, it stays marked as invalid and not-deleted. With this change it correctly transitions to deleted and not-invalid.
It helped me resolve my way out of https://forum.syncthing.net/t/what-to-do-with-files-when-they-become-ignored/7111 but these parts are a bit murky...

lib/model: Correctly detect deleted but previously ignored files as deleted

---

gui/default/assets/lang/lang-en.json
gui/default/syncthing/folder/editIgnoresModalView.html
lib/connections/kcp_dial.go
lib/connections/kcp_listen.go

Merge manually to prevent squashing.
The "hey it no longer connects" issue is not solved though.

Small fixes

---

lib/connections/kcp_dial.go
vendor/github.com/AudriusButkevicius/kcp-go/sess.go
vendor/manifest

vendor: Update kcp, removes closeConn (fixes #4343)

vendor: Update kcp, removes closeConn (fixes #4343)

---

lib/fs/basicfs_watch_test.go

Always explicitly allow the directory create event that we might get.

lib/fs: Further unflake watch tests

---

cmd/strelaypoolsrv/main.go

The current 500 "test failed" looks and sounds like a problem in the relay pool server, while it actually indicates a problem on the announcing side. Instead use 400 "connection test failed" to indicate that the request was bad and what was the test.

cmd/strelaypoolsrv: Return better error codes and messages

---

cmd/syncthing/main.go

https://forum.syncthing.net/t/logging-to-several-files/11364/4

cmd/syncthing: More information in help about -logfile option

---

cmd/syncthing/main.go

cmd/syncthing: Rename weak to rolling

---

gui/default/assets/css/overrides.css
gui/default/syncthing/device/globalChangesModalView.html

It starts looking bad as the names get long, but life is hard and then we all die anyway.

gui: Add folder label to global changes, use bootstrap table (fixes #4828)

---

lib/osutil/lowprio_linux.go
lib/osutil/lowprio_unix.go

Not sure if the tags are right, but I hope :)

lib/osutil: Use unix lowprio implementation on Android

---

cmd/syncthing/main.go

cmd/syncthing: Correct --paths in some cases

---

cmd/strelaypoolsrv/main.go

Caddy only sets the IP in `X-Forwarded-For` (i.e., no port). We only use the host/port split thing in order to throw away the port, so there is no reason we should not support this.

cmd/strelaypoolsrv: Handle portless X-Forwarded-For

---

README-Docker.md

docker: Add README from old Docker repo (fixes #4868)

---

lib/model/model.go

See #4870 for purpose. 
I didn't check that the race between connection drop and incoming request checks out, I just added the appropriate check for a paused folder to `Request`. In there I also stumbled over some pre-fs cruft and removed that as well. No specific testing done.

lib/model: Prevent warning on request in paused folder (fixes #4870)

---

vendor/github.com/syncthing/notify/node.go
vendor/github.com/syncthing/notify/notify.go
vendor/github.com/syncthing/notify/tree.go
vendor/github.com/syncthing/notify/tree_nonrecursive.go
vendor/github.com/syncthing/notify/tree_recursive.go
vendor/manifest

vendor: Update github.com/syncthing/notify (fixes #4885)

---

lib/protocol/luhn.go

Better documentation.
Doesn't require testing.

It's good etiquette to let others know that this deviates from the algorithm

---

lib/model/rwfolder.go

Not allocate infinite RAM
👍 In prod

lib/model: Units are hard (fixes #4910)

---

lib/model/model.go
lib/model/model_test.go

Since #4095 folder roots are created for paused folders, which isn't desirable (#4903) - don't do that anymore. To keep the ability to set ignore patterns on paused folders (#4094), check and create the folder root when setting ignore patterns. Folder marker wasn't touched before and isn't touched now, so that safety mechanism wasn't/isn't jeopardized.
Add tests for both #4903 and #4094.

lib/model: Don't create folder root when paused (fixes #4903)

---

lib/ignore/ignore.go
lib/ignore/ignore_test.go
lib/model/model.go

lib/ignores: Fix ignore loading, report errors to UI (fixes #4901)

---

gui/default/syncthing/core/syncthingController.js

gui: Don't save ignores if they haven't been loaded (fixes #4915)

---

cmd/strelaypoolsrv/main.go
cmd/syncthing/gui_statics.go
lib/auto/auto_test.go
script/genassets.go

Angular upgrade breaks everything spectacularly

gui: Enable proper asset caching

---

lib/osutil/osutil_test.go

lib/osutil: Add test for IsDeleted (ref #4925)

---

gui/default/syncthing/device/globalChangesModalView.html

gui: Fallback to folder ID in recent changes (fixes #4947)

---

gui/default/syncthing/core/syncthingController.js

gui: Check if folder exists in folderLabel (fixes #4965)

---

gui/default/index.html

Disable (not hide) rescan button while scanning (fixes #4977)

gui: Disable rescan button while scanning (fixes #4977)

---

gui/default/syncthing/device/editDeviceModalView.html

Hello everyone. This is long due update to GUI aimed at exposing bandwidth throttling (should have done that long ago, sorry!). I created it following @imsodin suggestion from a few weeks back on IRC. In case you would like to see other things exposed in each tab I'll happily add them.
Not much. Clicked through device editor and checked most of its existing functionalities and the new one.
https://imgur.com/a/EEHGyTY

gui: Add tabs in device editor

---

lib/model/model.go
lib/model/model_test.go

lib/model: Don't panic when rechecking file (fixes #5002)

---

gui/default/syncthing/device/editDeviceModalView.html

As tittle suggests, fixes the issue with adding new device. Moreover I discovered a bug with entering rational numbers as limiter values hence the pattern and changed error message.
Adding new device with and without editing limiter values and editing existing device limiter values.

gui: Fix add device (fixes #5012)

---

gui/default/syncthing/core/logViewerModalView.html
gui/default/syncthing/core/syncthingController.js

Previously you had to explicitly click in which was annoying.

gui: Stop log tailing on scroll

---

gui/default/syncthing/app.js

Closing this issue - it being open annoyed me. Given I also found two missing `var`s it was almost worth the time.
None.

gui: kiB -> KiB (fixes #5017)

---

vendor/github.com/syncthing/notify/debug_debug.go
vendor/github.com/syncthing/notify/debug_nodebug.go
vendor/github.com/syncthing/notify/notify.go
vendor/github.com/syncthing/notify/watcher_fsevents_cgo.go
vendor/github.com/syncthing/notify/watcher_readdcw.go
vendor/github.com/syncthing/notify/watcher_stub.go
vendor/github.com/syncthing/notify/watcher_trigger.go
vendor/manifest

Get some bug-fixes from upstream, hopefully (likely! :) ) fixing #4854

vendor: Update github.com/syncthing/notify (fixes #4854)

---

vendor/github.com/syncthing/notify/watcher_notimplemented.go

Followup to #5032 where I forgot to git add this file.

vendor: Add missing file to github.com/syncthing/notify

---

lib/fs/basicfs_watch_eventtypes_readdcw.go

lib/fs: Catch size-preserving changes on windows (fixes #5050)

---

.github/ISSUE_TEMPLATE.md

Add a section on using the correct issue tracker
Add a section on database corruption

github: Add sections to issue template

---

lib/upnp/upnp.go

Ignore device type `upnp:rootdevice` in discovery (fixes #5038)

Fixes(#5038):Ignore UPnP device of type `upnp:rootdevice`

---

lib/model/folder_sendrecv.go

#4958 already fixed the performance part, but the folder still went into syncing state for a really short time. Therefore I added a call to `WithNeed` before entering the pulling state, just to check whether there is anything to pull.
The alternative was to check on `updateGlobal` whether the global changed, or a new device now has a file we need, or our needs changed and then return a bool whether we should pull or not. However I quickly aborted that, because there are lots of edge cases and while it probably can be properly, it's still prone to mistakes. And it mixes model/pulling concepts into the folder. This option is much simpler and also achieves the goal.
Tests still pass.

lib/model: Don't enter pulling state if we need nothing (fixes #4782)

---

Dockerfile

Reduce the number of layers by consolidating a number of steps in the Dockerfile.
Tested resulting image works.

Reduce number of container layers for final image

---

cmd/stdiscosrv/replication.go

This PR fixes #5117 - it adds keepalive support to stdiscosrv
This change should be backwards-compatible, i.e. older versions of stdiscosrv should ignore the heartbeats, though it has not been tested.
Manually tested the replication keepalives by setting up a replicated setup of two stdiscosrv processes and testing if the connection is not being torn down after 60 seconds as it used to.

Add heartbeats to stdiscosrv

---

lib/model/model.go

lib/model: Process download progress messages for all folder types (fixes #5131)

---

gui/default/syncthing/device/editDeviceModalView.html
gui/default/syncthing/settings/settingsModalView.html

- Add icons to tabs in settings modal (like in folder and device modal)
- Fix spacing in device modal
cold beer was good

gui: Add icons to settings tabs

---

lib/config/wrapper.go

lib/config: Actually modify config element (fixes #5185)

---

gui/default/syncthing/core/syncthingController.js
lib/config/config_test.go

gui: Add arrays for pending/ignored folders (fixes #5190)

---

gui/default/syncthing/core/syncthingController.js

should also take into account new ldap config option

Gui open no auth check

---

lib/model/folder_sendrecv.go

The function `shortcutFile` is used in just one place and handles just part of the "shortcutting" a file. Now it handles all of it, removing some code from the already long `handleFile` function, fixing `newError` being called twice on the same error and needing one db lookup less.
Nothing new.

lib/model: Extend shortcutFile

---

gui/default/syncthing/core/syncthingController.js

gui: Update device name properly when saving config (fixes #5249)

---

cmd/stindex/idxck.go
cmd/stindex/main.go
lib/db/lowlevel.go

Run some diagnostics on an index grabbed from somewhere...

cmd/stindex: Add index checking mode ("idxck")

---

lib/db/schemaupdater.go
lib/db/set_test.go
lib/db/structs.go
lib/db/transactions.go

#5294 
New unit test reproducing the issue.

lib/db: Update local need on device removal (fixes #5294)

---

cmd/syncthing/gui.go
cmd/syncthing/gui_test.go

This implements #1347 making directory auto-completion case insensitive.
Added tests to `gui_test.go`.

Make directory auto-complete case insensitive

---

gui/default/syncthing/core/syncthingController.js

Fix from https://github.com/syncthing/syncthing/issues/4738#issuecomment-434463688
Fixes #4738
Not tested yet, I will try to test it in my installation.

Defer restore versions

---

gui/default/syncthing/device/editDeviceModalView.html
gui/default/syncthing/folder/editFolderModalView.html

Move sharing for folders to separate tab (like sharing tab for devices)
:ok: sharing works as before

gui: Sharing tab for folders

---

gui/default/index.html
gui/default/syncthing/device/editDeviceModalView.html

Display rate limit for own device and connected devices

gui: Display rate limit (fixes #5320)

---

cmd/syncthing/gui.go
cmd/syncthing/mocked_model_test.go
gui/default/index.html
gui/default/syncthing/core/syncthingController.js
gui/default/syncthing/transfer/localChangedFilesModalView.html
gui/default/syncthing/transfer/neededFilesModalView.html
lib/db/set.go
lib/db/structs.go
lib/model/model.go

#5336
Manual testing in a test setup with a single file (I don't use receive only).
I did not put much thought into the visual representation, feel free to suggest improvements.
Document `/rest/db/localchanged`.

all: Display list of locally changed items in UI (fixes #5336)

---

lib/scanner/walk.go

Fix #5369 introduced in #5215
None.

lib/scanner: Fix empty path on normalization error (fixes #5369)

---

lib/model/folder.go

#5392  
The reported race is harmless, as `f.watchCancel` is always called before it is replaced and thus the context that is passed to all goroutines (not as part of the folder struct) cancels them (thus it doesn't matter if they got outdated/nil/... channels). Nevertheless the data race is prevented here by renaming `f.watchErrLock` to `f.watchLock` and moving all read/write access to `f.watchChan` and `f.watchCancel` under it's "protection".
None.

lib/model: Do folder watch operations under lock (fixes #5392)

---

lib/model/folder_sendrecv.go

lib/model: Don't pass nil *Matcher to performFinish (fixes #5401)

---

lib/model/folder_sendrecv.go

Reset pull errors when pulling was successful (fixes #5450).
And change iteration, such that really `maxPullerIterations` are done, not `maxPullerIterations - 1`, and polish the result a bit.

lib/model: Reset pull errors when succeeding (fix #5450)

---

docker/hooks/build
docker/hooks/push

Implements changes requested in #5446.

build: DockerHub Script Optimization

---

docker/hooks/archs.csv
docker/hooks/build
docker/hooks/push
docker/multiarch.Dockerfile

~ Outsources configuration data to .csv
~ Improves comments
~ Checks Docker version before upgrade
~ Makes array variables readable
~ Creates a manifest with the correct architecture for individual images
~ Fixes the multiarch Dockerfile

build: Further DockerHub Script Optimization (#5459)

---

lib/db/namespaced.go

This one is quite ridiculous, nevertheless it happened when repeatedly running this test (for entirely different reasons):
```
=== RUN   TestRequestRemoteRenameChanged
23:14:39 INFO: No stored folder metadata for "default": recalculating
23:14:39 INFO: Ready to synchronize "default" (default) (sendreceive)
23:14:39 INFO: Completed initial scan of sendreceive folder "default" (default)
23:14:39 INFO: Device AIR6LPZ-7K4PTTV-UXQSMUU-CPQ5YWH-OEDFIIQ-JUG777G-2YQXXR5-YD6AWQR client is " " named "" at 
==================
WARNING: DATA RACE
Write at 0x00c001fd26fd by goroutine 63:
runtime.slicecopy()
/media/ext4_data/Linux/source/go/src/runtime/slice.go:197 +0x0
github.com/syncthing/syncthing/lib/db.(*NamespacedKV).Delete()
/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/db/names …
```

lib/db: Fix unlikely race

---

lib/beacon/broadcast.go
lib/beacon/multicast.go
lib/config/config.go
lib/config/config_test.go
lib/config/folderconfiguration.go
lib/config/wrapper.go
lib/connections/limiter.go
lib/connections/service.go
lib/connections/structs.go
lib/connections/tcp_listen.go
lib/db/db_test.go
lib/db/instance.go
lib/db/namespaced.go
lib/db/set.go
lib/db/smallindex.go
lib/db/transactions.go
lib/db/util_test.go
lib/dialer/internal.go
lib/discover/cache_test.go
lib/discover/global_test.go
lib/fs/basicfs_test.go
lib/fs/basicfs_watch_test.go
lib/fs/fakefs.go
lib/fs/fakefs_test.go
lib/fs/mtimefs.go
lib/fs/mtimefs_test.go
lib/fs/tempname.go
lib/ignore/ignore.go
lib/ignore/ignore_test.go
lib/logger/logger.go

all: Bunch of more linter fixes

---

lib/osutil/atomic.go
lib/osutil/osutil.go
lib/osutil/osutil_test.go
lib/osutil/traversessymlink_test.go
lib/protocol/benchmark_test.go
lib/protocol/deviceid.go
lib/protocol/deviceid_test.go
lib/protocol/hello_test.go
lib/protocol/protocol.go
lib/protocol/protocol_test.go
lib/rand/random.go
lib/rc/rc.go
lib/relay/client/methods.go
lib/scanner/blocks.go
lib/scanner/blocks_test.go
lib/scanner/walk.go
lib/scanner/walk_test.go
lib/sha256/sha256.go
lib/sync/debug.go
lib/tlsutil/tlsutil.go
lib/upgrade/upgrade_supported.go
lib/versioner/simple.go
lib/versioner/staggered.go
lib/versioner/staggered_test.go
lib/versioner/trashcan.go
lib/versioner/trashcan_test.go
lib/watchaggregator/aggregator_test.go
lib/weakhash/benchmark_test.go

More of same, except there was an actual error checking bug in this one. :)

all: Even more boring linter fixes

---

cmd/stdiscosrv/main.go
cmd/stindex/idxck.go
cmd/strelaypoolsrv/stats.go
cmd/strelaysrv/session.go
cmd/syncthing/auditservice_test.go
cmd/syncthing/gui.go
cmd/syncthing/locations.go
cmd/syncthing/usage_report.go
lib/connections/service.go
lib/db/set_test.go
lib/fs/basicfs_test.go
lib/fs/fakefs.go
lib/fs/fakefs_test.go
lib/ignore/ignore_test.go
lib/model/model.go
lib/model/model_test.go
lib/model/progressemitter.go
lib/model/progressemitter_test.go
lib/model/requests_test.go
lib/watchaggregator/aggregator_test.go

A couple of minor bugs and simplifications

all: A few more interesting linter fixes

---

cmd/syncthing/monitor.go

Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>

cmd/syncthing: fix strings.HasPrefix args order

---

build.go

In addition I also added a command to check/install gogofast when running `proto`.

build: Remove outdated&non-functional setup command (fixes #5454)

---

gui/default/index.html

There were a few places that I noticed where counts weren't getting comma separated in the UI.
Frankly, I have not tested this, just fixed through observation of what's being done elsewhere.

ui: Localize items counts

---

lib/model/folder_sendrecv.go
lib/model/requests_test.go

The functional change is to scan for newly created conflicts. With watching for changes enabled this isn't much of an improvement (but doesn't hurt either), without it means those files will be propagated much faster - we already know about them anyway.
`TestRequestRemoteRenameChanged` was flaky, as it depended on a race between the remote and local change. If the local change comes out as the winner (global file), which happened in most cases, no conflict was created and the test passed. If the remote wins the local change is moved for conflict and the file overwritten with the remote -> test fails. Now the test is adjusted such that always the remote version wins and it is tested that both the remote version and the local version (as conflict) are sent to the remote and exist with the …

lib/model: Scan conflicts after creation

---

cmd/syncthing/gui.go
cmd/syncthing/main.go

https://github.com/syncthing/syncthing/pull/5529#discussion_r256592700

cmd/syncthing: Introduce exiter to handle termination

---

gui/default/index.html

GUI: Use handshake icon for "Introduced by" (Fixes #5560)

---

lib/model/folder_sendrecv.go

Moves creation and globbing for conflicts to helper functions. Required for testing regarding conflicts (see #5567). No change in functionality.

lib/model: Refactor conflict name handling

---

lib/model/folder_sendrecv_test.go

In principle this is very much not worthy of a PR, then again it's noise in any other PR and it annoyed me too many times.

lib/model: setUp -> setup

---

lib/scanner/walk.go

The removed comment simply isn't true and hasn't been in a while. I can't think of why I didn't use `CreateFileInfo` for symlinks, now I do.  
No change in functionality. The added `NoPermissions` line in `CreateFileInfo` does not have any effect, as permissions are never considered for symlinks, but it's still the correct thing to do.

lib/scanner: Consistently use CreateFileInfo and remove outdated comment

---

lib/model/folder_sendrecv.go

Saving and iterating the files twice is totally unnecessary. That I used `fileInfoBatch` is tangential - it's just convenient.
Sorry (well not so much actually) for the flood of low-impact PRs, it's a consequence of me trying to stop carrying around unrelated changes in feature branches that may eventually come to light (probably not).

lib/model: Optimize dbUpdaterRoutine

---

lib/model/model_test.go

Not much to say, it's just as boring as it looks like.

lib/model: Introduce waitForState test utility

---

lib/model/model.go

These `ignores` are simply not used anywhere.

lib/model: Remove unused code

---

etc/linux-systemd/system/syncthing@.service

Should fix the issue:
Systemd unit should declare after=multiuser.target #5346

PR for Systemd unit should declare after=multiuser.target #5346

---

lib/model/folder.go
lib/model/folder_sendrecv.go
lib/model/model.go

Less moving parts, less lines, simpler, ...

lib/model: Integrate stat refs in folder

---

cmd/syncthing/main.go

I just could not resist.
Compiled and tested manually, works as expected.

cmd: Add a check for particular far-future version of config (fixes #1101)

---

lib/model/folder_recvonly_test.go

Receive only folder tests should also run in separate, temporary directories and clean up after themselves (wrapper files were not removed before).

lib/model: Run recvonly tests in temporary dirs

---

lib/model/folder_sendrecv.go

#5616 
This needs to go into v1.1.1 RC.

lib/model: Pass correct file info to deleteItemOnDisk (fixes #5616)

---

lib/model/folder_sendrecv.go
lib/model/folder_sendrecv_test.go

lib/model: Remove unnecessary arguments in pulling functions

---

gui/default/syncthing/core/aboutModalView.html

Compiled, ran, works. (linux-amd64)

gui: Add licensing information to aboutModalView (fixes #1223)

---

lib/model/folder.go

https://github.com/syncthing/syncthing/issues/5641#issuecomment-481227444
> Potentially the high cpu usage is due to a discrepancy between the pauses between successive failed tries and how long one try takes: If it takes e.g. 10min, you get 10min activity, 1min pause, 10min activity, 2min pause, 10min activity, 4min pause, ... - so essentially lots of activity. I'd propose to time the try and set the pause to at least that time (capped at 1h). If anything happens (scan, remote changes) that triggers a pull anyway, so you shouldn't "miss out" on a resolution like this. Does this sound reasonable?
The change means, that if e.g. a pull took 30min and failed, the pause will be immediately 32min instead of just 1min. Or if it took longer than an hour, the pause will immediately be 1h (well …

lib/model: Pause pull for at least as long as failed pull took (fixes #5641)

---

lib/fs/basicfs_test.go
lib/fs/walkfs_test.go

Just want to use CI to check a hunch.

lib/fs: Add test that symlinks are skipped on walk

---

gui/default/syncthing/core/syncthingController.js
gui/default/syncthing/transfer/failedFilesModalView.html
gui/default/syncthing/transfer/localChangedFilesModalView.html

#5421  
And while at it I changed `folder/pullerrors` to `folder/errors` as the former is deprecated.
Manual testing.

gui: Fix setting page size on failed and locally changed modals

---

gui/default/assets/css/overrides.css
gui/default/index.html

Fixes #4531
Large:
Medium:
Small:

Change remote device table column proportions

---

lib/model/model.go

This does not change any behaviour, just some maintenance done due to #5657, but not relating to the functional change in that PR.

lib/model: Use RLock and legacy polish

---

lib/model/folder_sendrecv.go

lib/model: Pass the old not new fileinfo to deleteItemOnDisk (fixes #5654)

---

lib/ignore/ignore_test.go

I just want to see what the windows builder says because I'm too lazy to boot a VM

lib/ignore: Additional test case

---

lib/protocol/protocol.go

This does not change any behaviour at all, it just changes a misleading function argument: `writeMessage` took `asyncMesage` as argument, implying it does anything with the `done` channel which is part of that struct. However it only ever accesses the message part. This would have already bitten me in the luckily unmerged PR  #5645, where I waited for `done` to be closed after passing it to `writeMessage`.

lib/protocol: Refactor to pass only relevant argument to writeMessage

---

lib/model/folder_sendrecv.go

This removes transient pull errors when a second iteration is run, instead of keeping them until all potentially very long sync operations are done.  
Fixes #5659

lib/model: Remove individual pull errors on retry (fixes #5659)

---

lib/model/sharedpullerstate.go

Improve quality of life for our users.
None, it just looks good to me. I know, I hate that kind of development yet here we are.

lib/model: Don't fail operation when fsync() fails (fixes #5704)

---

lib/fs/basicfs_watch.go
lib/fs/basicfs_watch_test.go

Predecessor: #5633 reverted in https://github.com/syncthing/syncthing/commit/a04fcfe7494a6e3ede091534597539b77dc05a52 due to https://github.com/syncthing/syncthing/issues/5695
The problem was, that the prefix was removed only on the watched path, but not on the path that events were compared against.

lib/fs: Remove \\?\ for drive letters when watching (fixes #5578)

---

lib/api/api_test.go

Tests take unusually long at the moment. The culprit is the cmd/syncthing to lib/api refactor: Tests left csrftokens.txt behind, thus preventing test cache to kick in. Also `TestCSRFTokens` takes really long, I added a shorter variant to be triggered by `-short` (was nice for testing and why not).

lib/api: Clean up after test, enables test caching

---

lib/model/folder_sendrecv.go

Tiny improvement split from #5680:  
Immediately delete symlinks and files, that are not candidates for renames. And reuse the file info from database if possible.

lib/model: Refactor file deletions when pulling

---

lib/protocol/protocol_test.go

This is a test that reproduces the deadlock scenario described in #5442.

lib/protocol: Test for Close on blocking send deadlock (ref #5442)

---

lib/model/model_test.go

The test introduced in https://github.com/syncthing/syncthing/pull/5707 is racy in that it checks for the removed connection right after `RestartFolder` returns, but at that point the call to `Closed`is not guaranteed to have happened yet (example test failure: https://build.syncthing.net/viewLog.html?buildId=39675&buildTypeId=Syncthing_BuildWindows).

lib/model: Unflake folder restart with blocking conn test (ref #5707)

---

lib/protocol/common_test.go
lib/protocol/protocol.go
lib/protocol/protocol_test.go

https://github.com/syncthing/syncthing/issues/5794

lib/protocol: Don't block on Close (fixes #5794)

---

lib/model/requests_test.go

I couldn't reproduce the failure, but I am hopeful this PR fixes it:
The missing item is the one that doesn't exist locally, meaning it is picked up in the second stage of the scan, where the db is traversed and files which can't be found on disk are marked as deleted. For a reason I can't remember (but I vaguely remember there was one) we flush the batch of changes before that second stage. Now if the second stage is faster than the index sending interval, the two changes are sent together, if not they are sent separately. The second option would result in a failure like the one reported.

lib/model: Unflake TestPullInvalidIgnoredSR/SO (fixes #5796)

---

lib/model/folder.go
lib/model/folder_sendrecv.go
lib/model/model.go
lib/model/queue.go
lib/model/queue_test.go

Be a bit more efficient (#5754).
None except for existing tests.

lib/model: Make jobQueue.Jobs paginated (fixes #5754)

---

lib/api/api.go
lib/beacon/multicast.go
lib/connections/quic_listen.go
lib/connections/service.go
lib/connections/structs.go
lib/connections/tcp_listen.go
lib/discover/global.go
lib/model/folder.go
lib/model/folder_sendonly.go
lib/model/folder_sendrecv.go
lib/model/folder_summary.go
lib/model/model.go
lib/model/progressemitter.go
lib/relay/client/client.go
lib/relay/client/dynamic.go
lib/relay/client/static.go
lib/stun/stun.go
lib/ur/usage_report.go
lib/util/utils.go
lib/versioner/staggered.go
lib/versioner/trashcan.go

> Yeah this goes back to the "we need a template for suture services"
https://github.com/syncthing/syncthing/pull/5802#issuecomment-502695914
I created such a template and put it into place wherever there already was a `stopped` channel.

lib: Add util.Service as suture.Service template (fixes #5801)

---

gui/default/syncthing/settings/settingsModalView.html

gui: On update setting don't show RC msg when disabled (fixes #5803)

---

lib/model/model.go
lib/model/model_test.go

Not much to say: Problem happened in #5829 for no good reason. Only upside: There's now a unit test.

lib/model: Close conn on dev pause (fixes #5873)

---

lib/model/model.go
lib/model/requests_test.go

Partial revert of https://github.com/syncthing/syncthing/pull/5804 to actually define the variables and unit test to reproduce #5872.

lib/model: Prevent panic in NeedFolderFiles (fixes #5872)

---

lib/model/folder.go
lib/nat/service.go

Some more service termination speedup from what I noticed on my production system.

lib/model, lib/nat: More service termination speedup

---

lib/api/api.go

lib/api: Don't log random stuff in the HTTP server (fixes #5738)

---

lib/db/benchmark_test.go

There are benchmarks that change the global fileset `benchS`. For some reason or another benchs still pass, but that's clearly not good. To prevent that from happening I changed the setup to only pregenerate the list of items, but not the actual db and fileset. On my computer this increases bench time from ~26s to ~34s, which in my opinion is acceptable.

lib/db: Don't use global fileset in benchmarks

---

lib/config/folderconfiguration.go

https://github.com/syncthing/syncthing/pull/5852#discussion_r307451542
Also having numerous different branches just for debug logging gets silly.

lib/config: Handle empty Fstype for mtime-window

---

lib/model/requests_test.go

`secondIndex` is there to do the right thing (allow multiple indexes), but has no effect at all. Instead of fixing it I just removed it, as it's simpler and does the right thing too (we don't care about how index updates are split, just about them containing the right things).

lib/model: Unflake TestPullInvalidIgnored

---

lib/model/folder.go
lib/model/model.go

Problem detected by @AudriusButkevicius  in https://github.com/syncthing/syncthing/issues/5929#issuecomment-520578153. I then went for a little hunt of similar problematic patterns.

lib/model: Fix a few more problematic locks (ref #5929)

---

lib/model/folder_sendrecv.go

There is a race after passing the file to the copier routine having done the free disk check, between the file being created on disk and the next file arriving at the free disk check.
Solution is to move the check back in the pipeline to the same place where the file is also created. A side effect is, that the check is done for the full file size, not just the blocks we need to pull. I believe this is a good change too, as before we temporarily violated the free disk space requirement if we reused blocks and only got below the limit after replacing the original with the temporary file. If anything fails, we stay above the limit. Potentially this can fill the entire disk up if enough blocks are reused.

lib/model: Do free disk space check later on pull (fixes #5948)

---

lib/model/folder.go
lib/scanner/walk.go
lib/scanner/walk_test.go

lib/model, lib/scanner: Pass a valid event logger (fixes #5970)

---

lib/api/api_test.go

Isn't this just the most beautiful thing you've ever seen?
```
docker run -it --rm -v $(pwd):/foo -w /foo -e GOPROXY=direct \
golang:1.13rc2 go test -v -race -short ./lib/... ./cmd/...
```

lib/api: Skip an IPv6 specific test inside Docker (fixes #5991)

---

lib/model/model.go

These are the (probably) save, uncontroversial and most important changes from https://github.com/syncthing/syncthing/pull/5975: Replace write-locks with read-locks where possible and update device statistic references in `CommitConfiguration` to get rid of the write-lock when just lookup up the reference.

lib/model: Use read-locks wherever possible

---

.golangci.yml

build: Tweak golang-ci config to build

---

README.md

readme: Broken link to README-Docker.md fixed [skip ci]

---

gui/default/syncthing/core/syncthingController.js

fix openNoAuth with unix sockets (fixes #6040)

gui: fix openNoAuth with unix sockets

---

gui/black/assets/css/theme.css
gui/dark/assets/css/theme.css

Fixes black theme interface (fixes #5583)

GUI: Fixes Black theme interface (fixes #5583)

---

go.mod
gui/default/syncthing/core/syncthingController.js

gui: better info for stalled and lengthy scans (fixes #5627)

---

lib/connections/quic_listen.go

Produced completely in github web editor, let's see if it will blend.

lib/connections: Rate limit quic accept loop (fixes #6081)

---

gui/default/syncthing/core/syncthingController.js

Satisfy my need to decrement our bugcounter.
It works now for me.
PS: There's about 1001 different ways we loop in JS - luckily the one needing fixing was also used (correctly) in another place so I could mimick.

gui: Fix loop selecting all devices (fixes #5980)

---

go.mod
go.sum
gui/default/index.html
gui/default/syncthing/core/syncthingController.js

See #5968 and https://forum.syncthing.net/t/status-of-folder-with-pending-revert-local-changes for previous discussions about wording/meaning. "Local Additions" was chosen as this state only occurs, when the folder is up-to-date except for locally added/changed files that weren't changed on any remotes. Otherwise out-of-sync still applies.
Manual

gui: New folder state "Local Additions" for receive-only (fixes #5968)

---

lib/upnp/upnp.go

upnp: fix outdated comment

---

cmd/stcli/utils.go
cmd/syncthing/main.go
cmd/syncthing/monitor.go
lib/osutil/net.go
lib/protocol/protocol.go
lib/relay/protocol/protocol.go
lib/sha256/sha256.go
lib/syncthing/syncthing.go
lib/upgrade/upgrade_common.go

all: Remove dead code, fix lost msgLen checks

---

lib/api/api_statics.go

Because our themes are just magical variables in the backend, the browsers caches stuff, and even if the theme changes, the path does not (nor does the mtime) hence the browser has no reason to invalidate.
We now must refresh assets on theme change, and on startup, making the generation time moot.

lib/api: Reset mtime after theme change (fixes #5810)

---

gui/default/assets/css/theme.css
gui/default/syncthing/core/syncthingController.js

Addresses @wweich's comment.
Tested on IE 11 and Chrome.

lib/api: Make the paths relative

---

lib/model/folder_sendrecv.go

Change counter zero does not mean there weren't any errors -> resetting all errors is incorrect. So instead of the global error reset on "success" errors are now reset every iteration (this makes sure we catch transient errors, which we didn't before). I.e. no more error resetting for individual items (which is anyway pretty fragile as it's easy to forget it). Same for incrementing `changed`: It's now done globally in the beginning instead of in various places, and decremented in the one place we don't do anything ever and thus don't want to retry (windows invalid filenames).

lib/model: Simplify pull error/retry logic (fixes #6139)

---

lib/model/folder_sendrecv_test.go

I got a race in testing (unrelated) and the trace contained lots of  goroutines from tests that were already finished. Fixing that a `DeregisterOn...` test flaked out on me. I noticed the test takes a bit more than a second to run, and the timeout is 1s. That might be the entire reason those tests are flaky on CI. So I increased that to 5s.

lib/model: In tests prevent goroutine leaks and increase timeouts

---

lib/connections/quic_dial.go
lib/connections/relay_dial.go
lib/connections/service.go
lib/connections/structs.go
lib/connections/tcp_dial.go

I have a change brewing towards https://github.com/syncthing/syncthing/issues/5298 and that diff is going to be hideously huge. This PR is part of making it a bit smaller by separating whatever I can.

lib/connections: Dialer code deduplication

---

lib/upnp/upnp.go

Minor change to fix unnecessary label

upnp: Use simple continue in loop

---

go.mod
lib/fs/fakefs.go
lib/fs/fakefs_test.go

Yep, "a little step for a man" in the direction of #2739.

lib/fs: add case-insensitive fakefs

---

lib/api/api.go
lib/api/mocked_model_test.go
lib/db/namespaced.go
lib/db/namespaced_test.go
lib/db/schemaupdater.go
lib/fs/mtimefs.go
lib/fs/mtimefs_test.go
lib/model/model.go
lib/model/model_test.go
lib/stats/device.go
lib/stats/folder.go
lib/syncthing/syncthing.go

As foretold by the prophecy, "once the database refactor is merged, then
shall appear a request to propagate errors from the store known
throughout the land as the NamedspacedKV, and it shall be good".

all: Propagate errors from NamespacedKV

---

lib/osutil/rlimit_unix.go

lib/osutil: Increase maxfiles on macOS properly (Fixes #6206)

---

lib/stun/stun.go

Currently if a NAT is not punchable, the type is reset and thus logged on the next iteration. Now the NAT type is only reset when `serve` exits and when stun is disabled. In addition I simplified a few things (it took me a moment to figure out what the return value of `runStunServer` does - and it's only ever false if context was canceled or stun disabled, which is detectable outside without the return value) - if you mind/disagree I'll just revert that part.

lib/stun: Refactor to remove unnecessary logging (fixes #6213)

---

lib/db/backend/backend_test.go
lib/db/backend/leveldb_backend.go

Wraps the error from `Iterator.Error` in the leveldb backend.

lib/db: Wrap errors from leveldb iterators (fixes #6263)

---

lib/model/model.go

This hardly seams relevant any more; 0.14.14 (Dec 14, 2016) is dead since a long time.

lib/model: Remove legacy handling of symlinks

---

lib/db/backend/leveldb_backend.go

We could potentially get a snapshot and then fail to get a releaser,
leaking the snapshot. This takes the releaser first and makes sure to
release it on snapshot error.

lib/db: Don't leak snapshot when closing

---

lib/api/api.go
lib/model/bytesemaphore.go
lib/model/folder.go
lib/model/folder_sendrecv.go
lib/model/model_test.go
lib/nat/interface.go
lib/nat/service.go
lib/pmp/pmp.go
lib/relay/client/dynamic.go
lib/stun/stun.go
lib/syncthing/syncthing.go
lib/upnp/igd_service.go
lib/upnp/upnp.go
lib/ur/usage_report.go
lib/util/utils.go

This is based on https://crash.syncthing.net/report/7c648d3d2f73cb2f95010df0c6fc6f886b2f68a5b08440bfe3b0aeb740219539

lib: More contextification

---

lib/connections/connections_test.go
lib/connections/service.go

This probably overkill but I just felt the urge to write a test, even if that test comes too late.

lib/connections: Refactor status for testing (ref #6361)

---

build.go

Pass `int`s instead of `string`s where `goversioninfo` wants them.
Tested manually, works as expected.

build: fix syso creation (fixes #6386)

---

lib/db/lowlevel.go
lib/db/schemaupdater.go

lib/db: Prevent GC concurrently with migration (fixes #6389)

---

gui/default/syncthing/device/editDeviceModalView.html

gui: Display device name in modal

---

gui/default/syncthing/folder/restoreVersionsModalView.html

On restoreVersionModalView we add name of current folder

gui:add folder name for restore version modal

---

gui/default/syncthing/folder/editFolderModalView.html

Display folder name in edit modal

gui: Display folder name in modal

---

cmd/stdiscosrv/main.go

We check if error is File not found before generate a keypair

keypair generate: check if keypair doestn't exist for genrate one

---

cmd/ursrv/static/index.html

I remove google map for leaflet and leafletheatmap.
I added the data locally to test directly on the HTML template file.

ursrv: remove google map and add leaflet heatmap

---

lib/model/model.go

Dabbled with connections and realised this function is never used -> purged.

lib/model: Remove unused func

---

go.mod
go.sum

go.mod: Use github.com/twmb/murmur3 for murmur3

---

gui/default/syncthing/core/syncthingController.js

Fix the message that appears in red and quickly disappears(fixes #3808)

gui: Number of days must be number flashes red then disappears

---

gui/default/syncthing/settings/advancedSettingsModalView.html

One tiny step friendlier than vi on config.xml

gui: Expose LDAP config in advanced config editor

---

cmd/strelaypoolsrv/gui/index.html

Remove google map and add Leaflet for relays.syncthing.net

strelaypoolsrv: remove google map and add leaflet map

---

lib/ur/usage_report.go

Don't touch that body when errored...

lib/ur: Correct freaky error handling (fixes #6499)

---

cmd/strelaypoolsrv/main.go

Follow-up to #6496. I felt bad about the complicated locking, so I rewrote the method. It now has one Unlock at the same level of nesting as the Lock.
There is a functional change here: when a new rate limiter is constructed, it is used in the very same call. In the old implementation, clients got their first request for free. This has been the case since the rate limiting was introduced in 3cacb48f3cdf8c8e3d4c331ad737df69a1aaea65, but I assume it was an oversight.

cmd/strelaypoolsrv: Simplify LRU usage

---

lib/fs/errorfs.go
lib/scanner/virtualfs_test.go

lib/{fs,scanner}: gofmt from Go 1.14

---

lib/osutil/atomic.go
lib/osutil/atomic_test.go

So, in a funny plot twist, it turns out that WriteFile in Go 1.13
doesn't actually set the read only bit on Windows when called with
permissions 0444 so my test was broken. With an improved test it turns
out that Rename does not, in fact, overwrite a read-only file on
Windows. This adds a fix for that.
(Rename might get improved in Go 1.15...)

lib/osutil: Fix "atomic" rename on Windows (ref #6495, ref #6493)

---

lib/connections/service.go
lib/protocol/protocol.go

As suggested I added replacing connection when the current one is older than 5 seconds. To do that I added new field in Statistics structure.

Accept new connections in place of old ones when appropriate #5224

---

lib/model/bytesemaphore.go
lib/model/folder_sendrecv.go
lib/model/folder_sendrecv_test.go
lib/model/sharedpullerstate.go

The actual fix is super small, just what @AudriusButkevicius wrote in #6559. Writing the test caused most of the diff :)

 lib/model: Don't exit pullerRoutine on cancelled ctx (fixes #6559) 

---

lib/config/versioningconfiguration.go

Don't randomly change the config on save

lib/config: Sort versioning options on marshal (fixes #6576)

---

gui/default/index.html

gui: Allow rescan on local additions (fixes #6578)

---

gui/default/index.html
gui/default/syncthing/core/syncthingController.js

I added the pause all/resume all button for devices.

Add "Pause All"/"Resume All" button for devices #6530

---

lib/config/folderconfiguration.go
lib/model/folder_sendrecv.go
lib/model/folder_sendrecv_test.go
lib/model/sharedpullerstate.go

I guess it's somewhat against the spirit, but I don't think there is any harm in making it configurable.

lib/model: Add option to disable fsync

---

lib/model/folder.go
lib/model/model.go
lib/model/model_test.go

See original ticket for explanation

lib/model: Do file recheck in folder loop (fixes #6583)

---

lib/model/folder.go

This came up in the exchange leading up to https://forum.syncthing.net/t/what-makes-syncthing-decide-when-to-send-data-or-not/14907/29  
We schedule a new pull when the current one fails with a configurable delay plus the time the pull took. That includes the time waiting due to the io limit, which can be a very long time. Plus we didn't always use the `pull` closure in `folder.serve`, which anyway seems out of place since `folder.pull` exists. So all of the pull fail timer handling now lives in `folder.pull`.
Nothing new.

lib/model: Don't include iolimiter wait into sync duration

---

lib/fs/basicfs.go
lib/fs/basicfs_fileinfo_unix.go
lib/fs/basicfs_fileinfo_windows.go
lib/fs/basicfs_test.go
lib/fs/filesystem.go
lib/fs/lstat_regular.go
lib/fs/lstat_windows.go
lib/fs/walkfs.go
lib/fs/walkfs_test.go

Implementation of
1. Traversing of directory junctions on Windows, https://forum.syncthing.net/t/option-to-follow-directory-junctions-symbolic-links/14750
2. Check for infinite recursion when directory junctions or Linux directory mounts are used.
Tested on Windows, unit tests created. Absolutely untested on Linux, I don't even know whether it's buildable.
na
https://forum.syncthing.net/t/option-to-follow-directory-junctions-symbolic-links/14750/58?u=xarx

Directory junctions

---

lib/model/model.go

I haven't done any testing, but it looks pretty straight forward: It's simply been forgotten to close connections to removed devices.

lib/model: Close conns when devices are removed (fixes #6564)

---

gui/default/syncthing/core/notifications.html
gui/default/syncthing/core/syncthingController.js
lib/config/config.go
lib/config/config_test.go
lib/config/migrations.go
lib/config/testdata/overridenvalues.xml

Recreation of #6444 PR. Add warning about setting up auth on initial startup (fixes #4703).
Building and checking if everything is working properly.

gui, lib/config: Add GUI user and password notification (fixes #4703)

---

gui/default/syncthing/core/syncthingController.js

Tested manually. Please check whether I did any JS blunders.

gui: Preserve folder-device info on folder edit (fixes #6706)

---

gui/default/assets/lang/lang-en.json
gui/default/syncthing/core/notifications.html

Proposed by @greatroar  in https://github.com/syncthing/syncthing/pull/6713#discussion_r435904410

gui: Fix newly introduced string (ref #6536)

---

cmd/ursrv/static/index.html

Following what was said in:
https://support.google.com/maps/thread/44057943?hl=en

cmd/ursrv: Attempt to fix js failure to load

---

lib/fs/basicfs_copy_range_duplicateextents.go
lib/fs/filesystem_copy_range_allwithfallback.go
lib/fs/filesystem_copy_range_method.go

lib/fs: Add support for Windows duplicate extents

---

lib/model/model.go
lib/model/model_test.go

Not sure wtf happened here. Did this never work sensibly?

lib/model: More connection closing

---

lib/ur/contract/contract.go
lib/ur/contract/contract_test.go

lib/ur: Zero our the value before unmarshal

---

lib/protocol/nativemodel_windows.go

lib/protocol: Don't warn when dropping deleted invalid item (fixes #6795)

---

lib/db/set_test.go
lib/protocol/bep_extensions.go

Because it helps debugging and why not.

lib/protocol: Add BlocksHash to FileInfo string

---

gui/default/syncthing/core/syncthingController.js
gui/default/syncthing/folder/editFolderModalView.html

Actually allow someone to set the option in question.
Clickety click

gui: Add GUI control for versioning cleanup interval (ref #6693)

---

lib/model/folder.go
lib/model/model_test.go

The main change is fixing #6864 by checking on unchanged deleted items if the local flags changed and adjusting accordingly. Also resolving deleted, receive-only items that no-one else had was convoluted (and potentially resulted in duplicate db updates, which shouldn't do any harm though), so I refactored that too. And there's a unit test for #6864).

lib/model: Detect deleted RO items scanning on non-RO (fixes #6864)

---

lib/model/folder_sendrecv.go
lib/model/folder_sendrecv_test.go

I guess this might explain why this doesn't actually work.

lib/model: Don't close file early (fixes #6875)

---

lib/model/folder_sendrecv.go

Locally changed items are by definition only present locally. Thus it's possible for a remote to delete their parent directory, even though it isn't empty locally. This is shown as a sync error, while there's actually a clear solution: Mark the directory as a local change just like it's children.

lib/model: Handle del. dir with locally changed items on pull (fixes #6873)

---

gui/default/syncthing/core/syncthingController.js
gui/default/syncthing/folder/editFolderModalView.html
lib/versioner/simple.go
lib/versioner/simple_test.go
lib/versioner/trashcan.go
lib/versioner/trashcan_test.go
lib/versioner/util.go
lib/versioner/versioner_test.go

Describe the purpose of this change. If there is an existing issue that is
resolved by this pull request, ensure that the commit subject is on the form
`Some short description (fixes #1234)` where 1234 is the issue number.
https://github.com/syncthing/syncthing/issues/6527
Adding the trash can feature of deleting files after certain amount days to Simple File folder type.
Describe what testing has been done, and how the reviewer can test the change
if new tests are not included.
I copied the test for trash can feature into simple feature. I did not write any test for gui.
to the …

Created cleanup functionality for syncthing

---

lib/model/model.go

This is still about those deadlock false positives (https://sentry.syncthing.net/syncthing/syncthing/issues/29/?query=is%3Aunresolved%20deadlock%20detected), but this time instead of butchering the deadlock detection (#6909) I propose to acquire locks inside the loop when needed, instead of for the entire duration. The `FileSet.Drop` operation in there needs to potentially update a whole lot of global lists, which can take a while (longer than the deadlock interval apparently)

lib/model: Do db heavy ops without holding fmut

---

lib/db/transactions.go
lib/model/model_test.go
lib/protocol/bep_extensions.go
lib/protocol/vector.go

Avoid havoc when discovering locally-deleted-upgraded files during repair / need calculation...
Fixes a broken database I had laying around.
@imsodin mentioned wanting to write a real test for this...

lib/db, lib/protocol: Never need empty-version entries (fixes #6961)

---

lib/model/folder_sendrecv.go
lib/model/folder_sendrecv_test.go

Bug reported in https://forum.syncthing.net/t/given-name-xyz-differs-from-name-xyz-in-file-system-error/15605
The problem is that if we have a case conflict for something we want to delete (want to delete `foo`, but there is only `Foo` on disk), that's not a problem, that just means it doesn't exist in the first place, i.e. we can just mark it as deleted.
I took the opportunity to move sending db updates out of `checkToBeDeleted` - that was simply obscure and unexpected given the name.
New unit test.

lib/model: Consider case conflicts when checking to be deleted items

---

lib/fs/util.go
lib/fs/util_test.go

Things like nul.whatever.txt are also not allowed.

lib/fs: Be even more strict about Windows names (ref #7008)

---

lib/db/lowlevel.go

Adds context to the errors in `getMetaAndCheck` to know where it originates from.
Also ignores not found errors when deleting in `checkLocalNeed`. I don't think we should ever get such errors there, but they are the only possible source I see for the panics in #7026, and it doesn't hurt.

lib/db: Improve error handling checking db (ref #7026)

---

lib/api/confighandler.go

Oversight in #7001. Luckily that's not released at all.

lib/api: Add missing config mod. locks (ref #7001)

---

gui/default/syncthing/core/syncthingController.js

gui: Fix another undefined variable access (fixes #7077).

---

lib/model/model.go

The current code violates the "fmut-pmut-locking-order". I can't find any deadlock panics pointing at this nor is there a big increase in deadlocks panics on sentry - maybe I got lucky and this somehow doesn't have consequences.

lib/model: Fix locking when resending cluster-configs

---

lib/model/requests_test.go

In https://build.syncthing.net/buildConfiguration/Syncthing_BuildFreeBSD/85280 this test got stuck because somehow after/while the test finished, an index was sent. The test doesn't process that index anymore and thus shutting down the model deadlocked with sending the index. That results in a TC timeout and thus totally unintelligible output in the TC interface.

lib/model: Prevent test deadlock

---

build.go

Minor url fix in comments (saves time for devs in case they visit the issue)
N/A
N/A
N/A
N/A

minor doc comment fix

---

lib/model/model.go
lib/model/requests_test.go

We must treat not having a fileset for a specific folder the same way we treat a paused folder: Store the index data from the cluster-config (L1237) and use that when adding the folder later (L554+).
I also moved getting the file-set from the model map after handling encryption metadata, as that does not depend on the file-set.

lib/model: Handle cluster-config before folder start (fixes #7122)

---

lib/db/schemaupdater.go

Problem:  
If an error occurs while migration the db, we do not update the schema/migration versions in the db. That means if multiple migrations need to take place, and some of them pass successfully but a later one fails, Syncthing stops, restarts and tries to redo the already successful migrations. Which will fail for some, e.g. when trying to read legacy types to convert them.
Fix;  
Now we are writing versions after every successful migration.

lib/db: Store versions for last successful db migration

---

lib/api/api.go

#7138 actually has a proper bug as a cause :) 
We do reload the UI when the theme was changed by the user, in the success callback of the api call changing the config. However that call errors out, as it waits for the config change to take place, and while doing so the config change restarts the api server, terminating all outstanding api calls. Now we are giving the API a chance to shut down gracefully, and thus the config change succeeds.

lib/api: Shut the api down gracefully (fixes #7138)

---

lib/stun/stun.go

lib/stun: Don't notify about address changes if it's not useful (fixes #7144)

---

lib/model/requests_test.go

That new test is super flaky: https://build.syncthing.net/project.html?projectId=Syncthing&testNameId=-4005993063680092438&tab=testDetails  
Couldn't repro locally, but adding the callback to the connection after passing the connection to the model seems like a very probably culprit.

lib/model: Unflake TestRequestReceiveEncryptedLocalNoSend

---

gui/default/untrusted/index.html
gui/default/untrusted/syncthing/core/syncthingController.js

Applied the GUI changes from #6443 to the untrusted files.

gui: Apply changes to untrusted (ref #6443)

---

lib/model/folder_sendrecv.go
lib/model/folder_sendrecv_test.go

When deleting a directory we check it's contents. However we do so only superficially, i.e. do not recursive into child directories. And items that match a `(?d)` ignore pattern are removed with `RemoveAll` (and errors are swallowed). This means that if an item within such `(?d)`-dirs is un-ignored (`!`), it gets removed too (unit test exercises this scenario). I don't think this is a big issue - I wouldn't expect anyone to mark something for deletion that may contain valuable files. Nevertheless it's wrong.  
Now we walk the directory to be removed, thus find any non-ignored children of children, and use `Remove`, not `RemoveAll`.

lib/model: Fix child-check when deleting dirs in pull

---

gui/default/assets/lang/lang-en.json
gui/default/syncthing/device/editDeviceModalView.html
gui/default/syncthing/device/removeDeviceDialogView.html
gui/default/untrusted/syncthing/device/editDeviceModalView.html

Fixes #5426 according to https://github.com/syncthing/syncthing/issues/5426#issuecomment-748635865
Not approved yet, but since the PR is small enough, I went ahead in case you think it makes sense.
Not tested yet.

gui: Allow device removal even if possibly reintroduced (fixes #5426)

---

gui/default/untrusted/syncthing/core/syncthingController.js

Minimizes the diff between untrusted and default again.

gui/untrusted: Mirror changes from #7205 and #7192

---

lib/model/folder.go

A user reported very slow scans and looking at a crazy volume of FS debug logs revealed that the rename detection is inefficient if a lot of data is newly scanned that contains a lot of duplicates. Not a very common case, but still something that's simple to improve on by caching not only files that were already detected as deleted/renamed, but also files that were already checked with `IsDeleted` during rename detection.
I also added a check for the filename of the file for which we want to find duplicates and "delete" the cache map afterwards, as it isn't used any more but the function might live on for quite some time.

lib/model: Optimize rename detection in scanner

---

lib/model/sharedpullerstate.go

Now we return a progress of `blockSize / 2` for files with a single block. That means that the reported progress is potentially larger than the total amount of bytes to sync in total. That leads to the 100% progress reported from the start reported in #7263.
Because I felt like it I adjusted the bytes estimate to be based on the probability that the small block is part of the given number of blocks, based on the total number of blocks in the file. That returns the actual file size for single block files, which fixes the above problem (which could obviously have been achieved in a much simpler way). For larger files the estimate will be a bit "better", probably entirely unnoticeably better.

lib/model: Correct pull progress for small files (fixes #7263)

---

lib/api/api_test.go

lib/api: Give the config changes some more time?

---

gui/default/syncthing/core/syncthingController.js
gui/default/syncthing/folder/editFolderModalView.html
gui/default/untrusted/syncthing/core/syncthingController.js
gui/default/untrusted/syncthing/folder/editFolderModalView.html

Regression introduced in https://github.com/syncthing/syncthing/pull/7131

gui: Fix setting external versioning command (fixes #7361)

---

go.mod
go.sum

Fixes a nil-deref:  https://sentry.syncthing.net/share/issue/95994db5cc04489dad325034dac269e5/
https://github.com/AudriusButkevicius/pfilter/pull/3

build: Update pfilter

---

cmd/strelaypoolsrv/gui/index.html

Avoid mixed content warning on https://relays.syncthing.net/

Default to loading tiles via https

---

lib/connections/quic_listen.go

Companion to https://github.com/syncthing/syncthing/pull/7417:  
Quic needs the `SetReadBuffer` method available on `net.UdpConn`, that's not part of the `net.PacketConn` and gets "lost" in the stun connection wrapping. I thus add a small wrapper that bundles the stun conn with the original conn to expose `SetReadBuffer` of the original conn.

lib/connections: Expose SetReadBuffer on conn passed to quic (ref #7417)

---

go.mod
go.sum

Fixes https://github.com/rjeczalik/notify/issues/200, upstream PR still pending: https://github.com/rjeczalik/notify/pull/201

build: Update notify

---

cmd/ursrv/main.go
lib/ur/contract/contract.go
lib/ur/usage_report.go

To see how much testing actually goes on.

cmd/ursrv, lib/ur: Collect and present encryption usage

---

lib/db/db_test.go
lib/db/lowlevel.go
lib/db/meta.go
lib/db/schemaupdater.go

Static analysis revealed some weirdness.

lib/db: Fix some omitted error checks, unused variable

---

cmd/syncthing/main.go

cmd/syncthing: Error handling on upgrade

---

cmd/uraggregate/main.go

We were already ignoring them, it just didn't look like it.

cmd/uraggregate: Ignore errors harder

---

cmd/stvanity/main.go
cmd/ursrv/main.go
lib/connections/quic_listen.go
lib/connections/service.go
lib/fs/filesystem.go
lib/locations/locations.go
lib/model/model.go
lib/protocol/deviceid.go
lib/upnp/upnp.go
lib/versioner/external.go

strings.Replace(a, b, c, -1) -> strings.ReplaceAll(a, b, c)
(Go 1.12) and who knows what was up with that dialQueue.Sort() thing.

all: Simplify some method calls

---

README.md

https://en.m.wikipedia.org/wiki/Fitt's_law

Docs: Larger link for Fitt's law, still semantic

---

go.mod
go.sum

build: Bump go-stun to v0.1.3 (fixes #7568)

---

gui/default/syncthing/core/editShareTemplate.html

Missed checking in this file in #7567.

gui: Add missing file (fixes #7571, ref #7567)

---

lib/model/folder_sendonly.go

I noticed a weird failure event on sentry: `got deleted file that doesn't exist locally as needed when pulling on send-only`
https://sentry.syncthing.net/syncthing/syncthing/issues/10537/?environment=Stable&referrer=alert_email
Its informational only - the condition is not acted upon (the item is just ignored). It will lead to incorrect remote out-of-sync status for the affected device on other devices.
Most likely the cause is #7476, where now invalid files are considered needed. In that PR I only handled that case in send-receive folders, and forgot about the send-only folder having its own `pull` method.
I also took the opportunity to use `fileInfoBatch` instead of the "legacy manual way" (no behaviour change).

lib/model: Handle invalid needed items on send-only (ref #7476)

---

lib/model/model.go

We get a few failure reports (1) about encryption that can't be read/written on disk. The bad thing is: Those errors include the file path. In this PR I remove that info from the reported error and also only send the failure when the error changes (same as when we let the user know with a warning as opposed to just debug logging).
(1) Those are weird, as they are "open ...: no such file ..." errors and there is a `!fs.IsNotExist` check in place. No idea yet what's going on there - it's a rare occurrence though.

lib/model: Remove path from enc errors and report ony once

---

gui/default/syncthing/core/syncthingController.js
next-gen-gui/src/app/device.ts

This addresses recommendations from LGTM about Semicolon insertion (https://lgtm.com/rules/4860080/). This change makes the JavaScript more consistent and predictable.
I have not performed any testing. I do not believe the function of the program will be changed by this pull request. Automated testing should be sufficient for this PR.
This will not change the way the code runs for the user.

Avoid Semicolon Autoinsertion

---

.gitignore
go.mod
go.sum
lib/connections/quic_listen.go
lib/stun/stun.go

lib/connections: Update pfilter to pick up bugfix/oob stuff, support OOB connections (fixes #7636)

---

cmd/stdiscosrv/database.pb.go
lib/config/config.pb.go
lib/config/deviceconfiguration.pb.go
lib/config/folderconfiguration.pb.go
lib/config/guiconfiguration.pb.go
lib/config/ldapconfiguration.pb.go
lib/config/observed.pb.go
lib/config/optionsconfiguration.pb.go
lib/config/size.pb.go
lib/config/versioningconfiguration.pb.go
lib/db/structs.pb.go
lib/discover/local.pb.go
lib/protocol/bep.pb.go
lib/protocol/deviceid_test.pb.go

I did a change to one `.proto` file and every `.pb.go` changed :)
It just merges two consecutive `if` blocks into a single one. I'd rather have that in a different commit, which is this PR.

all: Regenerate proto

---

lib/db/lowlevel.go

If GC (respective) compaction takes a long time, this will stall most operations on Syncthing via gc lock => index updates => model.fmut. Why GC might take so long is not yet clear - just that it happens: https://forum.syncthing.net/t/syncthing-stuck-gui-seemingly-responsive-but-nothing-is-happening/16828/6. Regardless of whether that's going to be fixed or not, I think it's a good idea to notify users at least in logs if the process is taking a long time. I chose "a long time" > 10s  by magic.

lib/db: Add logging for GC

---

lib/db/lowlevel.go

<del>The GC's logging goroutine races with its parent on the variables (discarded|matched)(Blocks|Versions). This new version only accesses the variables in one goroutine, so it's safe. It also cleans up its Timer.</del>

lib/db: Clean up Timer and wait for logging before return in GC

---

CONTRIBUTING.md

Fixed format.
```
Github -> GitHub
```

contributing: fix GitHub format

---

go.mod
go.sum

build: go mod tidy

---

gui/default/syncthing/core/syncthingController.js

The various refresh functions that aren't debounced now return a promise, and the online event handler uses those to prevent racing (and thus potentially accessing undefined stuff) with the refresh functions it started.
I found a similar issue in `saveConfig`, where the callback is called before `refreshConfig` is actually done.

gui: Fix race in online event callback (fixes #7733)

---

lib/model/indexhandler.go

There's a lot of `index handler got resumed while not paused` failure events on sentry: https://sentry.syncthing.net/organizations/syncthing/issues/11603/
It's not an actual issue though, but an incorrect failure event: An index sender also gets "resumed" when the folder is restarted (to get the new folder-runner and fileset). I removed the event and renamed one method to hopefully suggest less that the folder wasn't running before.

lib/model: Remove bogus failureevent when restarting folder

---

lib/db/lowlevel.go

Topic came up in https://github.com/syncthing/syncthing/pull/7726#issuecomment-855205470:
calmh:
> [...] Those entries will have taken up a sequence number, removing them and doing a meta recalculation would rewind the sequence number which is not great.
imsodin:
> That's a good point: Recalculating metadata and not resetting delta indexes seems like a dangerous thing to do in general. Even today where there should be no way the sequence number decreases when recalculating metadata, I think it would be better to ensure it doesn't (or reset delta indexes).
I added a step at the end of the db check/repair that compares meta-sequences for all devices between before and after repair. If any of them are changed, the respective index id is reset.

lib/db: Check if sequences change when repairing metadata

---

gui/default/assets/lang/lang-en.json
gui/default/index.html

Ref #7769.
Please pull into next rc, this is a bug introduced in the current release v1.18.0.

gui: Fix typo "recurr", again and for real.

---

lib/db/transactions.go

The event logger has been forgotten when creating the read-transaction inside a write-transaction, leading to panics when logging failures (which are there to replace panics - bit of the irony there): https://sentry.syncthing.net/organizations/syncthing/issues/12148

lib/db: Missing event-logger in write-transaction

---

lib/relay/client/client.go
lib/relay/client/dynamic.go
lib/relay/client/static.go

In particular, this makes it impossible to accidentally stack dynamicClients.
commonClient.invitations was protected by a mutex, but never set after construction. I moved that mutex; I also changed it to a vanilla stdlib mutex because its use is so trivial, but I can of course change that back if you want.

lib/relay/client: Stricter typing and remove unused code

---

lib/model/model.go

Likely the cause for https://sentry.syncthing.net/organizations/syncthing/issues/12681

lib/model: Missing fmut-lock on encryption failures

---

lib/model/indexhandler.go

This PR fixes a bug which causes the config service to deadlock when trying to delete a folder which has been paused for over a minute. The API call block and future attempts to modify the config will block without ever succeeding. This was caused by two bugs  in the `indexHandler` routine:
* it was blocking while waiting for the resume signal, so it could not handle the context being cancelled
* the cond was not signaled when resuming, so even resuming before deletion would not fix the issue
This PR fixes these bugs by waiting for the resume signal asynchronously, while also checking if the context is cancelled.
**Follow these steps to reproduce the bug or verify the fix:**
1. Have a connected device with a shared folder `x`
2. Pause the folder:
`curl -d '{"paused":true}' -X PATCH -H …

Fix config deadlock when deleting a paused folder

---

lib/watchaggregator/aggregator.go

Micro-optimization: watchaggregator.aggregator uses a map to keep track of three types of filesystem events, but it really only cares about the number of removes and non-removes. This replaces the map by two integer counters.

lib/watchaggregator: Replace counter map by two integers

---

lib/fs/casefs.go
lib/model/folder_sendrecv_test.go

Use non-technical language in the message to make clear what exactly
the error is talking about. Also, mention a possible solution on how to
fix the problem.

lib/fs: Improve case conflict error message (fixes #7827)

---

lib/model/folder_sendrecv.go

There is an issue reported about slowness/huge memory usage while syncing to an encrypted folder here: https://forum.syncthing.net/t/untrusted-device-never-finishes-syncing-very-high-memory-usage/17187  
The memory dump points at `HashFile` inside `handleFile`. We shouldn't ever hash files in a receive-encrypted folder, as hashes there aren't really hashes but just encrypted strings basically.
In this PR I factor out the parts that deal with hashes from `handleFile` and skip those if the folder is receive-encrypted. 
I have still no clue how this could cause such exorbitant memory usage.

lib/model: Don't consider hashes pulling on recv-enc

---

lib/db/backend/backend.go

https://sentry.syncthing.net/organizations/syncthing/issues/13738
https://sentry.syncthing.net/organizations/syncthing/issues/13739

lib/db/backend: Prevent panic in errors.As

---

lib/ur/failurereporting.go

Issue introduced in #7785 thus latest RC, affected 3 users so far - I'll do an rc.2: https://sentry.syncthing.net/organizations/syncthing/issues/13771

lib/ur: Fix panic getting goroutines for failures (ref #7785)

---

cmd/syncthing/cli/index_dumpsize.go

indexDumpSize uses a heap to sort. It can use sort.Slice instead, which may be faster (lower expected number of comparisons and swaps) and certainly takes less boilerplate.

cmd/syncthing/cli: indexDumpSize doesn't need a heap

---

meta/forbidden_words_test.go
meta/gofmt_test.go

Forbid usage of deprecated package `ioutil`.

meta: Add test for deprecated package ioutil

---

cmd/stdiscosrv/apisrv.go
lib/osutil/lowprio_windows.go
lib/protocol/deviceid.go
lib/sync/sync.go
lib/sync/sync_test.go
lib/upgrade/upgrade_supported.go

Some patches that clean up some bits of the codebase. See the commit messages for details.

Minor cleanup

---

lib/protocol/protocol.go

Having a separate mutex for the three or four instructions needed to fetch and increment nextID means the overhead exceeds the cost of this operation.  nextID is now handled inside the critical section for awaiting instead, while the more expensive channel creation has been moved outside it.
This is mostly a simplification, though it may have minor performance benefits in some situations. The single-threaded sender benchmark shows no significant difference:
name               old speed      new speed      delta
RequestsRawTCP-8   55.3MB/s ± 7%  56.6MB/s ± 6%   ~     (p=0.190 n=10+10)
RequestsTLSoTCP-8  20.5MB/s ±20%  20.8MB/s ± 8%   ~     (p=0.604 n=10+9)

lib/protocol: Use one mutex for rawConnect.awaiting and nextID

---

gui/default/index.html
gui/default/syncthing/core/syncthingController.js

The link in the bottom bar was "raw", should include a version parameter.

gui: Use versioned link to documentation in bottom bar

---

lib/db/backend/backend.go
lib/db/backend/leveldb_backend.go

lib/db: Make err(Closed|NotFound) values

---

lib/db/db_test.go
lib/db/structs.go
lib/discover/global.go

lib/db, lib/discover: Minor cleanup

---

cmd/syncthing/cli/errors.go
cmd/syncthing/cli/operations.go
gui/default/syncthing/core/eventService.js
lib/api/api.go
lib/model/folder.go
lib/model/model.go

Assortment of clean-ups and small fixes noted during recent PR activity.  See commit messages for explanation.
Test suite passes locally.  Most of these should be no-ops.

all: Comments and cosmetics

---

lib/connections/service.go
lib/model/model.go

A user report was the trigger to look at the code: https://forum.syncthing.net/t/connection-attemps-do-not-stop-when-connected-across-multiple-local-networks-across-repeaters/18264/11
Some (not so weird) network topology results in connections between already connected devices. The resulting error message is about hellos and cryptic. There's one obvious improvement: Do checks if a connection is even viable before the hello message. I extracted the code that is concerned with that from `Model.OnHello` to the connections package. The other issue in said report was that hello-ing timed out - and we do that in a single loop for all incoming connections/devices. Meaning one connection can block other connections being established. I thus split `service.handle` into `service.handleConns` and …

lib/connections, lib/model: Improve new conn handling

---

build.go

Correct comment typo in build.go

---

cmd/syncthing/cli/operations.go
cmd/syncthing/decrypt/decrypt.go
cmd/syncthing/generate/generate.go
lib/protocol/deviceid.go

Replaced by errors.New where appropriate.

all: Clean up fmt.Errorf usage

---

cmd/strelaysrv/testutil/main.go

remove invalid code in `cmd/strelaysrv/testutil/main.go`
Not tested
No changed

remove invalid code

---

cmd/syncthing/decrypt/decrypt.go

Directories are not represented in the encrypted storagage so they get
to keep default permissions...

cmd/syncthing: Apply file permissions and modtimes when decrypting

---

gui/default/index.html

gui: Fix missing span end tag and missing nbsp semicolon in HTML

---

go.mod
go.sum

build(deps): Bump github.com/pierrec/lz4

---

lib/connections/quic_misc.go
lib/connections/structs.go
lib/osutil/net.go
lib/pmp/pmp.go
lib/relay/client/methods.go
lib/relay/client/static.go
lib/upnp/upnp.go

... and add fast paths for common cases.

lib: Factor out getting IP address from net.Addr

---

gui/default/assets/css/overrides.css
gui/default/index.html
gui/default/syncthing/core/syncthingController.js

Random trailing spaces and inconsistent indentation.

Fix whitespace and indentation errors from recent PRs.

---

lib/protocol/bep_extensions.go

This should be printed in trace logs and whatnot

lib/protocol: Show inode change time in FileInfo debug string

---

lib/osutil/atomic.go

Given:
- Syncthing home directory is owned by user OWNER and group GROUP
- Syncthing runs as user NOTOWNER who is member of group GROUP
In this case, Syncthing cannot chmod the configuration file `config.xml` while saving it:
```
Saving config: chmod /[...]/config.xml: operation not permitted
```
That is because only the owner, not the group, can change permissions. Observed on Linux.
Since the config file is first atomically written, and then `chmod` attempted, the config file still gets written. But the `Save` function logs and returns this error and therefore also shows an error dialog in the GUI. To avoid running into this, my change ~only calls `Chmod(...)` if permissions differ~ **[UPDATE]** only fails after a `Chmod(...)` error if desired permissions really differ.
Ran Syncthing …

Only fail after chmod error if permissions differ (e.g. on config file)

---

lib/protocol/encryption.go

The layout of the request differs based on whether it comes from an untrusted device or a trusted device with encrypted enabled. Handle both.
Also closes #8819.

lib/protocol: Handle encrypted requests without encrypted hash (fixes #8277)

---

cmd/ursrv/main.go
cmd/ursrv/static/index.html
gui/default/syncthing/core/syncthingController.js
lib/config/config_test.go
lib/config/wrapper.go
lib/fs/basicfs_xattr_bsdish.go
lib/model/folder.go
lib/model/model.go
lib/model/model_test.go
lib/model/requests_test.go
man/syncthing-rest-api.7
next-gen-gui/src/app/http-interceptors/caching.interceptor.ts
next-gen-gui/src/app/services/db-completion.service.ts
next-gen-gui/src/app/services/db-status.service.ts

Fix typos, mostly in comments, but not only.

Fix new typos found by codespell

---

man/README.md
man/syncthing-rest-api.7

Following up on #8856, this one is actually a typo worth fixing.

docs: fix typo

---

lib/model/model.go

- Make sure we don't try to use empty last path components
- Create the directory to "reserve" it once we've decided to use it

lib/model: Improve path generation for auto accepted folders (fixes #8859)

---

lib/model/model_test.go

The test was flaky, and appears not to test what it should. This fixes that, I hope.

lib/model: Improve test for unignored parent directories

---

gui/default/syncthing/folder/editFolderModalView.html

The filter applies for sending as well.

gui: Show xattr filter editor when send xattrs checked (fixes #8958)

---

cmd/strelaypoolsrv/gui/index.html

See https://github.com/openstreetmap/operations/issues/737

Update tile URL

---

lib/fs/filesystem.go
lib/model/model.go
lib/model/model_test.go
lib/versioner/simple.go
lib/versioner/simple_test.go
lib/versioner/util.go
lib/versioner/versioner.go

Some random stuff found during research for https://github.com/syncthing/docs/pull/813.  See individual commit messages for details.

lib/versioner: Minor fixes in comments and error message

---

gui/default/assets/lang/lang-en.json
gui/default/syncthing/device/editDeviceModalView.html

gui: Add missing translation related to Number of Connections (ref #8918)

gui: Add missing translation related to Number of Connections (ref #8918)

---

lib/protocol/protocol.go

In principle a connection could close while it's in progress with starting, and then it's undefined if we wait for goroutines to exit etc. With this change, we will wait for start to complete before starting to stop everything.

lib/protocol: Ensure starting & closing a connection are exclusive (fixes #9102)

---

cmd/syncthing/generate/generate.go
lib/api/api_auth_test.go
lib/api/confighandler.go
lib/config/config_test.go
lib/config/guiconfiguration.go

lib/config: Accept pre-hashed password (fixes #9123)

---

GOALS.md
README.md

* Add oxford commas
* Fix writing style
* Add note (copied from https://syncthing.net/security/) about reporting security bugs

Style fixes in README, add security contribution note

---

cmd/ursrv/serve/serve.go

See https://github.com/syncthing/syncthing/issues/9140#issuecomment-1740981519

cmd/ursrv: Fix f-droid detection

---

lib/config/guiconfiguration.go

https://forum.syncthing.net/t/patch-improve-parsing-of-gui-address-overrides/20867
make checks for whether the gui-address is overridden consistent by checking whether the environment variable is set and not an empty string. the `Network()` function however checked for the inclusion of a slash instead of the presence of any characters. If the config file's gui address was set to a unix socket and the gui override to a tcp address, then the function would have wrongly returned "unix".
the `URL()` function always returned the config file's gui address if a unix socket was configured, even if an override was specified.
the `URL()` function wrongly formatted unix addresses. the http(s) protocol was used as the sheme and the path was percent escaped. because of the previous bug, this could …

lib/config: Improve parsing of gui-address overrides

---

gui/default/syncthing/core/syncthingController.js

Fixes #9149
Live edit in Chrome.

gui: Fix favicon status (fixes #9149)

---

cmd/stdiscosrv/apisrv.go

cmd/stdiscosrv: Handle unescaped cert header from Traefik (fixes #9143)

---

gui/default/index.html

Add an id attribute to the submit button shown on the login form. This allows my password manager's form filling function to interact with the button after filling in username and password (which already have the id attribute in place).
Minimal change, does not require a test routine.
The change is not visible to the user.

Web UI: Add id attribute to login button, allows form filling tools to be used (fixes #9200)

---

lib/api/api_auth.go

This handles the presence of multiple session cookies, thus easing the transition from previous login sessions.

lib/api: Improve cookie handling (fixes #9208)

---

lib/logger/logger.go

Currently `IsTraced("xyz")` will return true for
any inclusion of "xyz" in string.
This change splits `STTRACE` using `','`, `' '` and `';'`
as delimiters. That makes facilities separation
more clear.

lib/logger: split STTRACE into list of strings

---

build.go
cmd/stcompdirs/main.go
cmd/stcrashreceiver/main.go
cmd/stdisco/main.go
cmd/stdiscosrv/main.go
cmd/stevents/main.go
cmd/stfileinfo/main.go
cmd/stfinddevice/main.go
cmd/stfindignored/main.go
cmd/stgenfiles/main.go
cmd/strelaypoolsrv/main.go
cmd/strelaysrv/main.go
cmd/strelaysrv/testutil/main.go
cmd/stsigtool/main.go
cmd/stupgrades/main.go
cmd/stvanity/main.go
cmd/stwatchfile/main.go
cmd/syncthing/main.go
cmd/ursrv/main.go
lib/automaxprocs/automaxprocs.go

all: Use own automaxprocs package that doesn't log (ref #9436)

---

lib/connections/quic_listen.go

lib/connections: Use proper errors.Is check

---

lib/api/api_test.go

lib/api: Increase test request timeout (fixes #9455)

---

lib/fs/fakefs.go

lib/fs: Add missing locks to fakeFile methods (fixes #9499)

---

cmd/syncthing/main.go
internal/db/sqlite/db_open.go
internal/db/sqlite/db_service.go
relnotes/v2.0.md

365 + 90 days = 10920h.
Also, actually enforce the minimum interval of 24h.

fix: increase default delete retention to 15 months

---

.github/workflows/build-infra-dockers.yaml
.github/workflows/build-syncthing.yaml
go.mod
lib/api/api_test.go
lib/ignore/ignore_test.go

build: bump required language level to 1.24, compiler to 1.25

---

internal/db/sqlite/db_bench_test.go
internal/db/sqlite/db_global_test.go
internal/db/sqlite/db_indexid_test.go
internal/db/sqlite/db_local_test.go
internal/db/sqlite/db_mtimes_test.go
internal/db/sqlite/db_open.go
internal/db/sqlite/db_test.go
internal/db/typed_test.go
lib/api/api_auth_test.go
lib/api/api_test.go
lib/model/testutils_test.go
lib/stats/stats_test.go
lib/syncthing/syncthing_test.go

Filled up my tmpfs with test DBs when running benchmarks :)

chore(db): cleanup DB in tests and remove OpenTemp

---

internal/db/sqlite/db_bench_test.go
lib/syncthing/utils.go

chore(db): benchmark output, migration blocks/s output

---

.golangci.yml
internal/db/sqlite/basedb.go
internal/db/sqlite/db_test.go
internal/db/sqlite/sql/README.md

Replaces the #10321 change with a simpler version.

fix(db): apply all migrations and schema in one transaction

---

lib/model/sharedpullerstate.go

When handling files that consist only of power-of-two-sized blocks of zero we'd know we have nothing to write, and when using sparse files we'd never even create the temp file. Hence the sync would fail.
Fixes #10331.

fix(model): correctly handle block-aligned empty sparse files

---

lib/scanner/blocks.go

There are some return statements in between, but putting back the values isn't my motivation (hardly ever happens), I just find this more readable. Same with moving `hashLength`: Placed next to the pool the connection with `sha256.New()` is closer.
Followup to:  
chore(scanner): reduce memory pressure by using pools inside hasher #10222  
6e26fab3a0a17018079e3161c8115f72caa26653

chore(scanner): always return values to the pools when hashing blocks

---

cmd/infra/ursrv/serve/serve.go

According to https://forum.syncthing.net/t/thank-you/24857/7

chore(ursrv): update regex patterns for Syncthing-Fork entries

---

cmd/syncthing/main.go

Remove the migrated v0.14.0 database format after two weeks. Remove a few old patters that are no longer relevant. Ensure the cleanup runs in both the config and database directories.

chore: clean up migrated database
