syncthing/syncthing

lib/osutil/osutil_test.go

lib/osutil: Use filepath.Join in tests

---

lib/model/folder.go
lib/scanner/walk.go

Two small improvements around scanning:
When we encounter a folder error while scanning, we return early without telling the scanner about that. Now there's a derived context passed to the scanner, that is defer-cancelled.
Currently we log scan errors on the scanner side, but also pass the error on to the model, which takes further action on the error. The logging is now done by the model.

lib/scanner, lib/model: Improve error handling when scanning

---

cmd/syncthing/main.go
lib/db/backend/backend.go
lib/db/backend/badger_backend.go
lib/db/backend/leveldb_backend.go
lib/db/backend/leveldb_open.go
lib/db/db_test.go
lib/db/schemaupdater.go
lib/discover/global.go
lib/osutil/traversessymlink.go
lib/relay/client/methods.go
lib/relay/client/static.go
lib/upnp/upnp.go

This matches the convention of the stdlib ([json.MarshalerError](https://godoc.org/encoding/json#MarshalerError), [net.AddrError](https://godoc.org/net#AddrError), [os.PathError](https://godoc.org/os#PathError)) and avoids ambiguity: when customErr{} and &customErr{} both implement error, client code needs to check for both. The current lib/db/backend.{IsClosed,IsNotFound} do exactly that.
Memory use should remain the same, since storing a non-pointer type in an interface value still copies the value to the heap:
```
// foo.go
package foo
type customErr struct{}
func (customErr) Error() string { return "" }
func Foo() error { return customErr{} }
```
```
$ go build -gcflags=-m foo.go
./foo.go:6:6: can inline customErr.Error
./foo.go:8:6: can inline Foo
./foo.go:8:36: customErr literal …
```

all: Make all error implementations pointer types

---

cmd/stdiscosrv/apisrv.go

cmd/stdiscosrv: Dont abuse wrong header

---

build.go
test/h1/config.xml
test/h2/config.xml
test/h3/config.xml
test/usage_windows.go

I added flags and targets to build.go to run only specific tests/benchs and run integration tests. And updated configs (well just committed the end results of running integration tests) and fixed a build failure on windows.

build: Update integration tests and add to build.go

---

lib/fs/filesystem.go
lib/model/folder_sendrecv.go
lib/model/folder_sendrecv_test.go

The main fix in this PR is that an unscanned directory was deleted when pulling a deletion for said path. That likely didn't cause much real-world problems, as it would later fail if there's any content in the directory. Nevertheless it's wrong.
Another discovered issue: `scanIfItemChanged` scheduled a scan for an empty string whenever there wasn't anything in the db yet, but something on disk. That's because if the the db fileinfo `cur` is empty, `cur.Name` is empty too naturally. Again, that "just" meant needless scanning, the outcome was still correct.
One new unit test for deleting an unscanned directory (which also fails on the empty string to be scanned).
One existing unit test failed due to that change, thus needed a scan before the scenario to make sure the scenario in said test …

lib/model: Check dir before deletion when pulling

---

lib/db/keyer.go

This makes Go 1.15 test/vet happy, avoiding "conversion from untyped int
to string yields a string of one rune" warning where we do
string(KeyTypeWhatever) in namespaced.go.
It also clarifies and enforces the currently allowed range of these
numbers so I think it's fine.

lib/db: Use explicit byte type for type prefixes

---

lib/db/lowlevel.go
lib/db/meta.go

Not a functional change, just don't be actively confusing towards users:
> 2020-06-16 03:10:04 Stored folder metadata for "y9qce-uafde" is 442306h10m4.252789s old; recalculating
> 
> I don’t know if the ‘old’ time is a red herring, but I restarted this instance yesterday whilst looking at this issue; it certainly wasn’t 50 years ago…

lib/db: Improve error message on meta inconsistency

---

lib/db/lowlevel.go
lib/model/folder.go
lib/util/utils.go

Forgot about @calmh's suggestion regarding rounding times in https://github.com/syncthing/syncthing/pull/6751, thus now in a followup. It's still not a particularly meaningful kind of rounding, but at least better than no rounding as in the default.

lib: Print nicely rounded durations

---

gui/default/syncthing/core/syncthingController.js
gui/default/syncthing/folder/editFolderModalView.html
lib/api/api.go
lib/ignore/ignore.go
lib/ignore/ignore_test.go
lib/model/model.go

This changes the error handling in loading ignores slightly:
- There is a new ParseError type that is returned as the error
(somewhere in the chain) when the problem was not an I/O error loading
the file, but some issue with the contents.
- If the file was read successfully but not parsed successfully we still
return the lines read (in addition to nil patterns and a ParseError).
- In the API, if the error IsParseError then we return a successfull
HTTP response with the lines and the actual error included in the JSON
object.
- In the GUI, as long as the HTTP call to load the ignores was
successful we can edit the ignores. If there was an error we show this
as a validation error on the dialog.
Also some cleanup on the Javascript side as it for some reason used
jQuery instead of Angular for …

gui, lib/ignore: Handle editing ignores with error (fixes #5425)

---

lib/model/folder.go

Just stumbled across this by accident: Folder stays in scanning state forever if scan fails (if it's the first scan, because then nothing ever happens, otherwise forever=next triggered action).

lib/model: Don't stay scanning forever on fail

---

lib/model/folder_sendrecv.go

When stating in the last stage of the puller to compare what's on disk with what is in db we ignore an error from stat. Probably has no implications, as the ensuing operation will likely fail as well, nevertheless, it's wrong.

lib/model: Don't ignore stat failure in performFinish

---

build.go
lib/build/build_test.go

Currently a random dev version has a version string like this:
v1.7.0-rc.1+22-g946170f3f
That is, the tag name followed by a plus sign and the git describe
metadata (number of commits and hash) plus -dirty or -branchname in some
cases.
We introduced the plus sign in #473, where a dev version would
previously be called v0.9.0-42-gwhatever which is considered older than
v0.9.0 and hence caused a downgrade. The problem with the plus is that
per semver everything after the plus is ignored as build metadata, which
means we won't upgrade from v1.7.0-rc.1 to v1.7.0-rc.1+22-g946170f3f.
With this change the we use dots instead, and a "0-dev" marker, making
dev versions greater than the tag they come from but lesser than any
future real version:
v1.7.0-rc.1.0-dev.22.g946170f3f
Or, after a release …

build: Change version strings to not have plus in them (ref #6758)

---

lib/model/folder.go

The db snapshot gets released after scanning the filesystem and before finding deleted items. The part that checks if the locally changed item is equal to the global one uses the same, initial db all the time. I noticed this thinking about https://sentry.syncthing.net/syncthing/syncthing/issues/2426/?cursor=1591889609680%3A0%3A0&query=is%3Aunresolved+version%3Av1.7.0-rc.1+global+list+but+missing, but I couldn't think of a scenario how this bug could result in that error - but maybe it helps. Anyway this should be fixed. I did it by introducing a wrapper to `batch.append` that takes a snapshot as an argument - the recvonly-resolving happens there now.

lib/model: Use right db snap when scanning recvonly folder

---

build.go

Cgo is optionally required by badger only (not for long any more hopefully https://github.com/dgraph-io/badger/issues/1162). Lets just not use that and prevent any hassle around getting a C compiler set up.

build: Disable Cgo on windows

---

lib/scanner/blocks.go

As spotted by @crzbear in a comment on 9c0825c0d99e4b13d965f721a3592e8bdff45a97, the description of blocks.Validate is incorrect. If a weak hash is given, only that is checked.

lib/scanner: Fix Validate docs

---

lib/protocol/deviceid.go

This is shorter, skips two allocations, makes the function inlineable and is safer, since the compiler now check whether DeviceIDLength == sha256.Size.

lib/protocol: Use sha256.Sum256 in NewDeviceID

---

lib/pmp/pmp.go
lib/upnp/upnp.go

 lib/nat: Make service termination faster

---

lib/connections/connections_test.go
lib/connections/util.go

Previously tcp://[fe80::1] would get "fixed" to tcp://[[fe80::1]]:22000
which is not great.

lib/connections: Correctly fixup port in IPv6 listen URLs

---

lib/model/folder_sendrecv.go

Just doesn't belong there, the the caller of `performFinish` already passes any returned error to `newPullError`.

lib/model: Remove double error handling in performFinish

---

lib/model/model.go
lib/scanner/blocks_test.go

Relevant much earlier changes:
9b1c592fb7e7ca86fec25545be742c13bdae25b9
bd1c29ee323573bf66d01b9d2887e1e8cb70ab68
Make sure vanilla and rolling adler are consistent. And that they match
with scanner.Validate.
I just set up a new node and went down a little rabbit whole when I noticed tons of `no such file` sync errors and the remote doing tons of very short scans. I was worried the weak hashing is broken due to some mismatch between the standard and rolling implementation (see linked commits/PR), but it turned out this is "age-old data" (pre 2017) that was hashed with whatever we used before adler. All is good.
I added tests that ensure that both standard and rolling adler give the same results, as well as that `scanner.Validate` agrees with the hash too (which is somewhat redundant right …

lib/scanner: Test weak hash consistency (ref #5556)

---

lib/model/folder.go

If we are waiting (iolimiter) for scanning/pulling and during that time force rescan requests come in, they will persist even if during that scan/pull the very file that's scheduled to be rehashed gets rehashed already.

lib/model: Don't force rescan already changed items

---

lib/api/api.go
lib/api/mocked_events_test.go
lib/events/events.go
lib/model/folder_summary.go

Two small things:
1. When refactoring the api I clearly didn't grok the function of the "minute-variable" in the folder summary service. Luckily I only changed the name but not semantics, so nothing broke but the name was completely off.
2. We don't register all calls to the event endpoint, e.g. not those to the `event/disk` endpoint. I don't see why we'd do that, thus I moved the `OnEventSub` call to the generic `getEvents` function.

lib/api, lib/model: Fixes around event request tracking

---

lib/model/model.go
lib/model/model_test.go

Still discovered an issue while "cleaning up" pre-adler weak hashes: I saw almost no progress and lots of hashing, leading to this pattern on the new/pulling side:
```
$ journalctl -u syncthing@simon.service | grep "Brittannia-1-NE.pdf"
[...]
Jun 25 14:51:53 simon-t450s-deb syncthing[28769]: [GQ5Y5] INFO: Puller (folder "Dokumente" (Dokumente), item "Bergsteiginfos/Kartenausschnitte/Brittannia-1-NE.pdf"): no connected device has the required version of this file
Jun 25 14:57:07 simon-t450s-deb syncthing[28769]: [GQ5Y5] INFO: Puller (folder "Dokumente" (Dokumente), item "Bergsteiginfos/Kartenausschnitte/Brittannia-1-NE.pdf"): pull: no such file
Jun 25 15:02:31 simon-t450s-deb syncthing[28769]: [GQ5Y5] INFO: Puller (folder "Dokumente" (Dokumente), item …
```

lib/model: Consider weak hash on recheckFile

---

lib/db/schemaupdater.go
lib/protocol/bep_extensions.go
lib/protocol/protocol_test.go

The resolution of way too much debugging is just a single line...
All my pre-adler weakhash files were being rehashed over and over again, even after applying the other two PR fixes from today. That's because on rehash the weak hashes changed, but the sha256 hashes didn't. And as the `BlocksHash` doesn't consider weak hashes, block deduplication kicked in and prevented the new block list from being saved. Thus when the file was requested again, the block hash still didn't match and it got scanned again.
This will prevent the scan rename detecting by blockhash map to kick in for new files, as existing files have the sha256-only bockshash, while new files include the weak hash. It's not critical, but also somewhat ugly - a migration won't hurt. I'll consider that tomorrow :)
Testing: I …

lib/protocol: Include WeakHash in BlocksHash

---

lib/api/api.go
lib/model/model.go
lib/model/model_test.go
test/h2/config.xml

This makes the /rest/db/completion call more useful and user friendly.
Prior to this change the only supported use was with both "folder" and
"device" parameters, where the device is a remote device. This then
gives the completion status for specifically that folder on that device.
With this change we also allow the following:
- Omitting the "device" parameter, in which case it means the local
device (and returns the local completion)
- Explicitly specifying the local device ID, which means the same thing.
- Omitting the "folder" parameter, in which case it means all folders.
- Omitting both, which logically then means the completion percentage
for all folders as a whole on this device.
This should be closer to what people expect usage wise, while also now
giving a single place to check …

lib/api, lib/model: Improve folder completion API (fixes #6075)

---

lib/config/wrapper.go

We generally copy everything in/from config.Wrapper, except for this. I personally wouldn't have been conscious about not changing the returned device map from `Wrapper.Devices`, and apparently there is some kind of problem (#6816), though I have to admit  I didn't search for what it is exactly.

lib/config: Don't cache device map (fixes #6816)

---

gui/default/syncthing/folder/editFolderModalView.html

Fixes issue #6807
As stated by the below article, update default gui folder. Then run syncthing and setup new folder or edit existing folder, go to the Advanced tab and chage "Folder Type" to "Send Only" and observe "File Pull Order" is set to disabled.  
https://docs.syncthing.net/dev/web.html# 
NB: May need to force refresh to ensure html page isn't cached.

gui: Disable file pull order when for send-only (fixes #6807)

---

go.mod
go.sum
lib/db/lowlevel.go

This fixes the following GC issue. If the GC finds a key k that it wants to keep, it records that in a Bloom filter. If a key k' can be removed but its hash collides with k, it will be kept too. Since the current Bloom filter code is completely deterministic, the next run will encounter the same collision, assuming k must still be kept, so k' can be kept indefinitely.
Randomizing the hash function and using all the SHA-256 bits solves this problem: the second run has a non-zero probability of removing k', as long as the Bloom filter is not completely full. (It's full at 268M entries with the current max. memory use.)
I considered three options for hash randomization:
* [hash/maphash](https://golang.org/pkg/hash/maphash) is fast at ~1GiB/s (older amd64), but requires Go 1.14.
* …

lib/db: Use SipHash to deal with hash collisions in GC

---

lib/scanner/blocks.go

This fixes the change in #6674 where the weak hash became a deciding
factor. Now we again just use it to accept a block, but don't take a
negative as meaning the block is bad.

lib/scanner: Less strict validation (fixes #6827)

---

lib/nat/service.go

There's now an `.enabled` boolean that prevents processing when disabled, even if the timer fires. The timer is now a local variable to `.serve` and only used/set there. If mappings need to be processed by trigger, there's now a channel for that. Feels simpler and safer (no race potential/locking) to me.

lib/nat: Make sure nat keeps being disabled (fixes #6823)

---

script/docker-entrypoint.sh

Modified the Docker entrypoint so that the Syncthing Docker image can be started as a non-root user
Allow running the Syncthing Docker image as a non-root user (fixes #6832)
Before change:
<pre>
rm -rf data && mkdir data
docker run -p 8384:8384 -p 22000:22000 \
-v "$(pwd)/data":/var/syncthing \
syncthing/syncthing:latest
rm -rf data && mkdir data
docker run -p 8384:8384 -p 22000:22000 \
-v "$(pwd)/data":/var/syncthing \
--user 1000:1000 \
syncthing/syncthing:latest
</pre>
After change:
<pre>
rm -rf data && mkdir data
docker run -p 8384:8384 -p 22000:22000 \
-v "$(pwd)/data":/var/syncthing \
syncthing:latest # Local syncthing Docker image
rm -rf data && mkdir data
docker run -p 8384:8384 -p 22000:22000 \
-v "$(pwd)/data":/var/syncthing \
--user 1000:1000 \
syncthing:latest # Local …

Modified the Docker entrypoint so that the Syncthing Docker image can be started as a non-root user

---

gui/default/assets/css/overrides.css

This commit will add the rule [`shape-rendering: crispEdges`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering) to the `.identicon` class to remove blurry grid lines within device icons.
This fixes #5579.
No tests are included but can be added if necessary.
No documentation changes are included but can be added if necessary.

gui: sharpen device icons (fixes #5579)

---

lib/db/backend/backend.go
lib/db/backend/badger_backend.go
lib/db/backend/leveldb_backend.go
lib/db/db_test.go
lib/db/lowlevel.go
lib/db/meta.go
lib/db/meta_test.go
lib/db/transactions.go

This moves the preFlush/commit hooks to be a property of the transaction.
I noticed that flushes might happen during Put's, which can happen when updating block map, or simply during t.updateGlobal while iterating over updateLocalFiles/updateRemoteFiles, which might flush out the transaction, but not run any hooks hence would not serialise the metadata.
In theory is should never happen as Checkpoint flushes over dbFlushBatchMin (64k), where as Put flushes over dbFlushBatchMax (1mb), so I think it's unlikely that in a tight loop where we call checkpoint after every file we go from less than dbFlushBatchMin in the previous iteration and suddenly to over dbFlushBatchMax in a single iteration, but regardless, this feels like a more robust way to do this.
I started looking at this effectively …

lib/db: Rework flush hooks

---

lib/fs/walkfs.go
lib/fs/walkfs_test.go

Prompted by https://forum.syncthing.net/t/infinite-filesystem-recursion-detected/15285. In my opinion the filesystem shouldn't throw warnings but pass on errors for the caller to decide what's to be happening with it. Right now in this PR an infinite recursion is a normal scan error, i.e. folder is in failed state and displays failed items, but no warning. I think that's appropriate but if deemed appropriate an additional warning can be thrown in the scanner.

lib/fs: Pass inf. rec. err on instead of warning

---

lib/db/set_test.go
lib/db/transactions.go

In the global list we don't have an info on why a file is invalid, e.g. if it's a receive-only item or ignored. However that's relevant for metadata accounting. Thus we now always remove the old global and add the new global from metadata, even if from the perspective of the global list nothing changed (i.e. versions equal and both invalid or not).

lib/db: Update global meta even if unchanged (fixes #6850)

---

build.go

Just wanted to switch one of my devices from "custom nightlies" to "official nightlies" and it didn't upgrade. Apparently I was running a dirty version, which contains two hyphens and was thus considered newer than the significantly newer "official nightlies". The printed version with this change before committing is now: 
```
$ ./bin/syncthing -version
syncthing v1.8.0-rc.2.dev.5.g08e0f938.dirty "Fermium Flea" (go1.14.4 linux-amd64)
```

build: Replace hypen in -dirty for version (ref #6758)

---

lib/db/lowlevel.go

This is not a fix for #6855 or anything else, but given missing blocks are a thing, I don't see why we should do all the expensive db checking but omit blocklists from it.

lib/db: Include blocks in db check (ref #6855)

---

lib/db/backend/backend.go
lib/db/lowlevel.go

The only thing changing behaviour is on `dropDeviceFolder`: We previously did change, but not commit meta there.
In addition I updated the comments on backend.go regarding the new `CommitHook` and used `CommitHook` when recalculating metadata instead of directly calling `toDB` (because blingbling and shorter).

lib/db: Commit meta when dropping device

---

lib/db/meta.go
lib/db/set.go
lib/db/set_test.go
lib/db/transactions.go
lib/model/folder_recvonly_test.go

https://github.com/syncthing/syncthing/issues/6850#issuecomment-665031731:  
> [...] why do we include receive-only changed items in the global count in the first place? That seems completely wrong to me: The global state is what everyone agrees upon. Receive-only changed items are the complete antithesis to that. If we didn't add it to the global state, receive-only items would lead to a higher local than global state, which seems right. It also removes the need for the workaround added in #6852. Thus I propose to not add invalid items to the global state. 
This behaviour also fixes #6850, and in addition to the previous fix (which is reverted here) covers removing items from the global state as well.

lib/db: Don't count invalid items to global state (ref #6850)

---

lib/model/folder.go
lib/model/folder_sendrecv.go

There's two related elements here: 1. `folder.pull` should not `defer f.setState(FolderIdle)`. The actual underlying pull already takes care of folder state (either error or idle). 2. For scanning and (real) pulling we always check folder health/error before setting status. We don't do the same for sync-waiting. This means an existing error gets "half-cleared": State changes to sync-waiting, but error remains (as errors are only touched by `setError`). Thus when the actual puller calls `setError`, it sees the same error before and after and thus returns early without setting the folder state back to error. Regardless of this issue I believe it makes sense to check folder health before acquiring the iolimiter token to get the error notification to the user faster.
I don't entirely get the …

lib/model: Check folder error before sync-waiting (fixes #6793)

---

gui/default/index.html

https://github.com/syncthing/syncthing/issues/6807#issuecomment-667172474:
> [...] I have just noticed that the "File Pull Order" is still shown in the GUI for "Send Only" folders, after unfolding the folder's details. This only happens when it has been set to a non-default value before setting the folder type to "Send Only".
> 
> I think that it should be hidden here too.
Didn't test.

gui: Don't show pull order on SO folders (ref #6807)

---

lib/db/set.go

Right now the only thing we know on panicking is that it panics, not on what. The function is clear from the traces, but not the file it panics on. Maybe that would show a pattern. May become obsolete by the next release depending on how fast the suture error handling and the subsequent db error handling comes to pass (unless there's another reason for an RC bump, then I'd propose also adding this commit (which I don't hope happens)).

lib/db: Log context on panic

---

lib/osutil/atomic.go
lib/osutil/atomic_test.go

Preserves permissions if a file is replaced/truncated. Reported in https://forum.syncthing.net/t/preserve-chmod-permission-after-editing-stignore-via-webui/15461, waiting for the issue (number) to fix the commit msg.

lib/osutil: Preserve perms in AtomicWriter (fixes #6886)

---

lib/osutil/atomic.go

> Info might theoretically be non-nil yet garbage if the file didn't exist. (As in I think info is undefined if err != nil)
https://github.com/syncthing/syncthing/pull/6885#discussion_r468083541

lib/osutil: Check returned error instead of info (ref #6885)

---

lib/db/backend/backend.go
lib/db/db_test.go
lib/db/lowlevel.go
lib/db/schemaupdater.go
lib/db/transactions.go

> Calling `.putFile` with `truncate == true` and a file with less blocks than `blocksIndirectionCutoff` puts a fileinfo without blocks. `truncate == true` is only the case when repairing sequence indexes, so this "shoudn't happen"™. However it does, so it's a real practical issue.
https://github.com/syncthing/syncthing/issues/6855
The tiny change in `TestRepairSequence` triggers the problem described above. To prevent it, don't ever write truncated files infos. If we wanted to write truncated files, we'd need to always redirect blocklists and check that a block list for the given `BlocksHash` of the truncated file already exists. Given we only write truncated files when repairing sequences and it's just an irrelevant "optimisation", I don't want to go there and instead just write full …

lib/db: Don't put truncated files (ref #6855, ref #6501)

---

cmd/syncthing/main.go
lib/api/api.go
lib/api/mocked_discovery_test.go
lib/config/migrations.go
lib/config/optionsconfiguration.go
lib/discover/cache.go
lib/discover/cache_test.go
lib/discover/discover.go
lib/discover/global.go
lib/discover/manager.go
lib/model/model.go
lib/model/model_test.go
lib/syncthing/syncthing.go
lib/ur/usage_report.go

This removes the need to restart syncthing in almost all cases.
The only two left are:
1. Crash reporting - happens in the monitor (and monitor only re-reads the option on restart of the child process)
2. Database tuning - everything depends on this, so we pretty much have to tear down the whole application anyway.

all: Remove need to restart syncthing

---

lib/dialer/public.go

Reusing the listen address influences the routing decision, which is not what we want in some cases.

lib/dialer: Try dialing without reuse in parallel (fixes #6892)

---

lib/fs/basicfs_copy_range_ioctl.go

lib/fs: Disable ioctl on ppc (fixes #6898)

---

lib/nat/service.go

The timer chan might already be drained at this point.

lib/nat: Don't hang on draining timer chan (fixes #6908)

---

lib/config/config.go
lib/config/config_test.go
lib/config/folderconfiguration.go
lib/config/migrations.go
lib/fs/basicfs.go
lib/fs/basicfs_lstat_broken.go
lib/fs/basicfs_lstat_regular.go
lib/fs/basicfs_lstat_windows.go
lib/fs/fakefs.go
lib/fs/filesystem.go
lib/fs/walkfs_test.go

See https://forum.syncthing.net/t/option-to-follow-directory-junctions-symbolic-links/14750/126 and following.

lib/config, lib/fs: Make junction behaviour configurable (ref #6606)

---

lib/db/lowlevel.go
lib/model/folder.go

This adds debug logging to a few previously uncovered places. Relevant for debugging https://forum.syncthing.net/t/v1-8-0-local-and-global-state-swapped-between-two-nodes/15209/20.

lib/db, lib/model: Cover exec-paths with debug logging

---

lib/model/folder.go

Unfortunately, this is RC material:  
The fix for #6864 in #6865 was way too general: E.g. a deleted file in a receive-only folder, that doesn't exist anywhere else, gets the receive-only flag removed (because there's no local change). Thus it's local flags are different from the folder, which triggered the previous condition to readd the receive-only flag. And then the check for the first condition removes the flag again. And so on and so forth. Now the check is specific to the problem in #6864: If a deleted file has the receive-only flag set, but the folder is not receive-only, the flag is removed.

lib/model: Prevent localflag flipflopping on del. item (ref #6865)

---

cmd/strelaypoolsrv/main.go
cmd/strelaypoolsrv/main_test.go

In strelaypoolsrv's handleGetRequest, when `cap(permanentRelays) >= len(permanentRelays) + len(knownRelays)`,
append(permanentRelays, knownRelays...)
returns a slice of the array underlying permanentRelays. The subsequent rand.Shuffle then mixes the permanent and known relays. Worse, multiple goroutines may be shuffling the same slice concurrently.
I believe that as long as strelaypoolsrv is running on amd64 hardware, the worst things that can happen are
* duplicate relays being reported to clients, and
* permanent relays being forgotten over time until a restart.
The knownRelays array is never modified, so that is safe.

cmd/strelaypoolsrv: Fix relay shuffling

---

lib/syncthing/syncthing.go
lib/syncthing/syncthing_test.go

I mostly implemented sutures new wip api (https://github.com/thejerf/suture/issues/39) so far and as is to be expected, the diff humongous and I touching all this stuff also uncovered some problems/possible improvements. This is one where we currently do not cleanup when an error occurs on startup (cleanup as in shutting down services and closing db). Now we first start the supervisor and routine waiting for it to exit and do said cleanup, before doing the startup operations.

lib/syncthing: Also cleanup on startup error

---

lib/db/meta.go
lib/model/model.go

We created a new fileset before stopping the folder during restart. When
we create that fileset it loads the current metadata and sequence
numbers from the database. But the folder may have time to update those
before stopping, leaving the new fileset with bad data.
This would cause wrong accounting (forgotten files) and potentially
sequence reuse causing files not sent to other devices.
This change reuses the fileset on restart, skipping the issue entirely.
It also moves the creation of the fileset back under the lock so there
should be no chance of concurrency issues here.
Restarting a folder during initial scan no longer causes badness for me.

lib/db, lib/model: Avoid accounting mishap on folder restart (fixes #6938)

---

gui/default/syncthing/core/syncthingController.js

Use indexOf() == 0 instead of startsWith() to maintain compatibility
and prevent JavaScript error console spam in the Web GUI when used in
Internet Explorer 11 under Windows 7.

gui: Use indexOf instead of startsWith for IE11 compatibility (fixes #6940)

---

cmd/ursrv/main.go

Hi all!
To make the Arch Linux syncthing package reproducible, I've fixed the BUILDHOST variable in the build instructions. So I belive this code needs to be changed too, to reflect the change.
Some more details are in the bug report [here](https://bugs.archlinux.org/task/67279). The change was implemented in the last  [PKGBUILD](https://github.com/archlinux/svntogit-community/commit/705393bbda70210db9825da85c031435d1f2a5dc#diff-8d0411b338c83cd8cd8ad9d9db127101).
Cheers!
J

BUILDHOST name changed for Arch

---

lib/model/folder.go
lib/model/folder_sendonly.go

There's no point in send-only folders acquiring an io-limiter token on pull. They only check for out-of-sync items that don't actually differ from the local state and resolve those, there's no io happening. Came up in https://forum.syncthing.net/t/waiting-to-sync-95-0b-again/15564
Also there's no need for the initial scan check on the send-only folder, that already happens in `folder.pull`.

lib/model: Don't acquire io token for send-only pull

---

cmd/stindex/idxck.go
lib/db/transactions.go

Makes stindex/idxck use the same utility function as lib/db to check if a file is needed. Previously there were false positives if we didn't have a file info locally, but the global one was invalid or deleted.

cmd/stindex, lib/db: Use same condition to check for needed files

---

lib/db/db_test.go
lib/db/lowlevel.go
lib/db/transactions.go

I hate this as much as everyone else if not more, but it turns out it is needed: Wracking my brain on https://forum.syncthing.net/t/syncthing-stuck-syncing-because-of-device-that-doesnt-exist/15501 and the out-of-sync folders with nothing in the out-of-sync list, I realized we do check and repair all kinds of things but never our "cached" list of files we need locally. In this PR I add the check and run it in the usual place. I ran it on my devices and on both it did repair stuff. I don't know what the underlying issue is. It would be nice to have https://github.com/syncthing/syncthing/pull/6925 to report if there's anything to repair, to know if this is an ongoing problem or if I have just been cleaning up relics of the past on my devices (wishful thinking).

lib/db: Add local need check&repair

---

lib/model/folder.go
lib/model/model.go
lib/model/model_test.go
lib/rc/rc.go
test/filetype_test.go
test/h1/config.xml
test/h2/config.xml
test/h3/config.xml
test/h4/config.xml
test/override_test.go
test/reconnect_test.go
test/symlink_test.go
test/sync_test.go
test/util.go

- Didn't compile due to recent `config.Load` changes
- Reconnect tests were flaky. In the process of fixing that I added the sequence to the completion endpoints and added `sequence` fields in addition to the legacy `version` ones where those were missing (was already in place for folder summaries).
- Sync and reconnect tests now also consider remote device status and fail if those are not in sync.
- Update configs.
Integration tests now pass for me.

test, lib/model: Various integration test updates & improvements

---

lib/db/backend/badger_backend.go

Since iterators must be released before committing or discarding a
transaction we have the pattern of both deferring a release plus doing
it manually. But we can't release twice because we track this with a
WaitGroup that will panic when there are more Done()s than Add()s. This
just adds a boolean to let an iterator keep track.
(This is needed to let the conversion back from Badger to LevelDB work, which is a required step in retiring the Badger experiment...)

lib/db: Don't hang on double iterator release with Badger

---

lib/model/model.go
lib/model/model_test.go

Discovered this bug while creating a test for https://github.com/syncthing/syncthing/pull/6962. Not likely to ever be noticed in the wild: When everything is deleted globally, we will always be 100%, even if we still have things to delete (instead of 95%).

lib/model: Correct completion perc. when globalBytes is 0

---

lib/db/db_test.go
lib/db/meta.go

The duplicate need entry should have no practical consequences, as when the new, duplicate count is added, the old index in the map is replaced, thus nothing will ever reference the old count anymore.

lib/model: Prevent duplicate need count on recalculating metadata

---

lib/fs/casefs.go
lib/model/folder_sendrecv.go
lib/model/folder_sendrecv_test.go

Currently we fail pulling if an old tempfile with a case-conflicting name is laying around. Now the temp file is renamed to the new name when such an error occurs.

lib/model: Don't fail over case-conflict on tempfile (fixes #6973)

---

lib/fs/casefs.go
lib/fs/casefs_test.go
lib/fs/debug_symlink_unix.go
lib/fs/fakefs.go
lib/fs/filesystem.go
lib/fs/filesystem_test.go

This changes the cache to cache less things, yet retain the required
efficiency for our walk usecase. This uses less memory.
Specifically, instead of keeping result and child caches for each path
level, only keep a single cached child. In practice our operations are
depth-first, or almost depth-first, and then we retain the same hit
ratio for a smaller cache size.
I improved the benchmark so that it counts the Lstat and DirNames
operations performed, and they do not change significantly. The amount
of allocated memory is reduced by 20% and the walk itself is actually
slightly faster.
This also removes the clear based on number of cached names (as that is
not a thing any more) and the timer based clear (which was unused). This
means we'll retain the last cache state forever until it's …

lib/fs: More efficient casefs cache

---

lib/model/folder_sendrecv.go
lib/model/folder_sendrecv_test.go

When a remote does a case-only rename, our shortcut fails with:
```
2020-09-09 08:55:36 rename shortcut for 1tesT.txt failed: given name "1tesT.txt" differs from name in filesystem "1test.txt"
```
from https://forum.syncthing.net/t/brief-out-of-sync-on-case-changed-file/15582/6
The pull still does the right thing, just inefficiently in a delete and create.
New unit test.

lib/model: Fix case-only renames on pull

---

lib/model/folder_sendrecv.go

We never have symlinks on windows, so no need to try to delete them (and get confused by it being in db but not on disk).
Tested manually.

lib/model: Handle symlink deletion on windows (fixes #6972)

---

lib/model/folder_sendrecv.go
lib/model/folder_sendrecv_test.go

When a file is replaced with a symlink (on a non-windows device), we currently leave that file alone on windows and add the symlink with the unsupported flag to the db. On next scan it will see the old file on disk, bump the version and thus reintroduce the old file to the remote, overriding the new symlink. Now before marking the symlink as unsupported on windows, we do check what is on disk and remove it (or rescan if changed).
Came up here: https://github.com/syncthing/syncthing/pull/6976#discussion_r485501779
New unit test.

lib/model: Consider existing file when handling symlink on windows

---

lib/db/backend/backend.go
lib/db/backend/badger_backend.go
lib/db/backend/leveldb_backend.go
lib/db/backend/leveldb_open.go
lib/db/db_test.go
lib/db/lowlevel.go
lib/db/set.go
lib/model/model_test.go
lib/syncthing/syncthing.go

No longer repair the db unconditionally on upgrade (fixes #6917). Instead when an error due to an inconsistency occurs, mark the db as needing repair. Then on next startup, do the repair.

lib/db, lib/syncthing: Don't repair DB on upgrade, but on error (fixes #6917)

---

lib/fs/folding.go
lib/fs/folding_test.go

Most notably, it now detects all-lowercase files and returns these as-is. The tests have been expanded with two cases and are now used as a benchmark (admittedly a rather trivial one).
Benchmark results on Linux/amd64 (note that WalkCaseFakeFS100k creates all-lowercase filenames):
name                           old time/op         new time/op         delta
WalkCaseFakeFS100k/rawfs-8             388ms ± 1%          312ms ± 3%   -19.64%  (p=0.000 n=10+8)
WalkCaseFakeFS100k/casefs-8            718ms ± 1%          587ms ± 1%   -18.30%  (p=0.000 n=10+10)
UnicodeLowercaseMaybeChange-8         5.45µs ± 5%         4.57µs ± 1%   -16.20%  (p=0.000 n=10+10)
UnicodeLowercaseNoChange-8            5.33µs ± 4%         3.09µs ± 1%   -42.01%  (p=0.000 n=10+10)
name                           old B/entry …

lib/fs: Optimize UnicodeLowercase

---

lib/model/folder.go
lib/scanner/blockqueue.go
lib/scanner/walk.go

This addresses two races which may lead to the panic reported in https://github.com/syncthing/syncthing/issues/6994:
One when a db error occurs: We immediately return in `folder.scanSubDirs`, not waiting for the scanner to terminate (close the returned chan).
Another when the scan is cancelled by context: The hasher aborts on context, and if it does so faster than the walker routine, it may close the returned channel while the walker is still working. Now the context is only checked when sending to the returned channel. Sends to "internal channels" are done without consideration of context, such that we can be sure everything is done when closing the returned channel.
I can't actually be sure this fixes #6994, as I can't deduct what exactly is happening from the trace, but the fixed …

lib/model, lib/scanner: Prevent races aborting scans (fixes #6994)

---

lib/fs/util.go

Like we already do with names ending in space or containing invalid
characters.

lib/model: Disallow reserved names, and names ending with period on Windows (fixes #7008)

---

lib/fs/basicfs.go
lib/fs/filesystem.go
lib/fs/util.go
lib/model/folder_sendrecv.go

Add specific errors for the failures, resulting in this rather than just
the generic "invalid filename":
```
[MRIW7] 08:50:50 INFO: Puller (folder default, item "NUL"): syncing: filename is invalid: name is reserved
[MRIW7] 08:50:50 INFO: Puller (folder default, item "fail."): syncing: filename is invalid: name ends with space or period
[MRIW7] 08:50:50 INFO: Puller (folder default, item "sup:yo"): syncing: filename is invalid: name contains reserved character
[MRIW7] 08:50:50 INFO: default: Failed to sync 3 items
```

lib/fs: Be more clear about invalid file names (ref #7010)

---

lib/fs/util.go

COM0 and LPT0 are not listed in the official Microsoft's documentation
at https://docs.microsoft.com/windows/win32/fileio/naming-a-file, but
in reality are also invalid in Windows Explorer.

lib/fs: Add COM0 and LPT0 to invalid Windows file names

---

lib/api/mocked_model_test.go
lib/connections/structs.go
lib/model/fakeconns_test.go
lib/model/model.go
lib/model/model_test.go
lib/protocol/hello.go

For all I see `protocol.Hello` and `protocol.HelloResult` are the exact same thing - looks like legacy that didn't get cleaned up.

lib: Remove HelloResult type, same as Hello

---

lib/model/fakeconns_test.go
lib/model/model.go
lib/model/model_test.go
lib/protocol/protocol.go

Instead of dropping a connection when the config changes, a new cluster config is generated and sent.
On the receiving end this means we need to track index senders to reset them when a new cluster config comes in. There was a commit on the progress emitter that it breaks on multiple CCs. I couldn't figure out though what is supposed to break, the operation has the exact same effect if called on a newly established connection or a super old one.
On the sending side sending of cluster configs happens in the toplevel function now. Otherwise we might send multiple CCs to the same device, which is wasteful. We did wait on the connection being closed previously, which we obviously don't anymore. This was done to prevent incoming indexes to happen after folder objects are removed from the model …

lib/model, lib/protocol: Send ClusterConfig on config change (fixes #7020)

---

lib/config/folderconfiguration.go
lib/config/size.go
lib/config/size_test.go
lib/fs/basicfs.go
lib/fs/filesystem.go
lib/model/folder_sendrecv.go

We use https://github.com/shirou/gopsutil to get disk stats and they expose the values as uint64 (https://github.com/shirou/gopsutil/blob/master/disk/disk.go#L11), which we then convert to int64 for the filesystem interface. It's a minor change on our side and filesystems pretending to be just as large as an int64 are apparently a thing (see https://github.com/syncthing/syncthing/issues/3930#issuecomment-701983666 and issue linked just above that comment). For anything larger https://github.com/shirou/gopsutil would have to use floats or different units in their API (we are already using floats for any further calculations).

lib: Use uint64 for disk stats (ref #3930)

---

lib/model/model_test.go

The tests run in the `testdata` directory, i.e. there are files in them, but doesn't call `ScanFolders`. The test passes if it ends before the initial scan, and fails otherwise. I moved the test to tmp dirs to prevent that.

lib/model: Fix race in GlobalDirectory tests (fixes #7021)

---

gui/default/syncthing/core/syncthingController.js

Fixes #7002 by preventing division by zero.
Tested manually with two SyncThing instances running on the same Windows 10 machine, by reproducing a situation as described in #7002.
New behaviour:

gui: Fix NaN percentage for zero byte files (fixes #7002)

---

cmd/stcrashreceiver/main.go
cmd/stcrashreceiver/sentry.go
cmd/stcrashreceiver/sentry_test.go
lib/db/lowlevel.go
lib/db/set.go

This PR does a few related things regarding panics:
- We have plenty of IO errors from leveldb including the db path, which become panics. Yes they should be errors, yes the goal is still to do that. In the meantime lets remove the paths from the panic message. And anyway, even with errors those would be fatal so the path will have to be filtered eventually.
- Added the panic message to the fingerprint. That's absolutely necessary for https://github.com/syncthing/syncthing/pull/6925, otherwise all events from it will be merged together (as they don't have traces). I also did it for panics to prevent merging different errors with the same trace. There's some pattern matching to prevent stuff like indexes or db paths (old clients without the change above will keep sending them) prevent …

cmd/stcrashreceiver, lib/db: Improve panic message handling

---

lib/db/lowlevel.go

The added context on the error/panic message shows the `key not found` error still happens during metadata recalculation:
https://sentry.syncthing.net/syncthing/syncthing/issues/4397/?query=is%3Aunresolved%20version%3Av1.11.0-rc.1
Again it makes no sense at all that we get a `key not found` when deleting a key which just got from an db iterator, but nevertheless ignoring it feels more appropriate than panicking.

lib/db: Ignore not found on delete in recalcGlobal (ref #7026)

---

lib/db/lowlevel.go
lib/db/set.go

Removes context including user info like device IDs from panic message.
Was introduced in #7029, i.e. is RC material.

lib/db: Undo adding user info to panic msgs (ref #7029)

---

lib/model/folder.go
lib/model/folder_sendonly.go
lib/model/folder_sendrecv.go

This PR changes how we handle versions on resolving conflicts. What happens now is: The device losing the conflict pulls the file, moves it's own file to conflict and merges both versions on the pulled file. This PR changes this, such that no merging happens any more and we just keep the version of the pulled file (conflict winner).
The main advantage is that this saves syncing steps: If there's a conflict between A and B (loser), there are now 2 steps: B resolves conflicts and merges vectors, thus creating a new global file (which is the same except for the version to the old). Then A syncs that file back. Now after B resolves the conflict the global stays, A doesn't need to sync anything. This is minor in this scenario, but if you e.g. imagine 10 devices, all with pre-populated data, …

lib/model: Use winning version instead of merge on conflict

---

lib/db/transactions.go
lib/model/model_test.go

Huge thanks to @tomasz1986 for not letting loose on this issue until discovering a reproducer so... lacking a better word lets say intricate, and also providing all the logs and screenshots I could wish for. Really, this fix is your achievement!
Not much to say about the fix: Stupid little slip. The code in question was even test covered before, but apparently not checked.
There's one question: There's a good chance this affects a few users. Recalculating metadata when releasing the fix seems in order - how should we trigger that? A db transition would work, but is a bit ingenious as there isn't any actual transition. We could also add an "upgrade hook" to syncthing.go that can do arbitrary stuff when updating to specific version, and export the db repair function again to call it there. …

lib/db: Remove need for the right dev removing globals (fixes #7036)

---

lib/connections/quic_listen.go
lib/connections/tcp_listen.go

A clear oversight. Verified manually by checking the logs.

lib/connections: Fix LAN addresses begin advertised even when disabled (fixes #7035)

---

lib/model/indexsender.go
lib/model/model.go
lib/model/model_test.go
lib/model/requests_test.go
lib/model/testutils_test.go

Manages life-time of index senders. Previously they were only tied to the connection staying alive and new cluster configs, in which case index senders are terminated. Now index senders are also un-/paused together with folders and stopped when removing a folder. When unpausing the newly generated fileset is passed, thus they stay up-to-date with changes in the newly created folder service - which fixes #7034.

lib/model: Handle index sender lifetime (fixes #7034)

---

lib/db/schemaupdater.go

This adds a similar db transition mechanism to the one already existing for schema changes. Schema transitions have in the past been "abused" for operations that did not actually change the db. This puts unnecessary limitations on downgrading. The added mechanism is meant to be used in these cases.
I also added the first such repair transition for #7044, which fixes a bug that could lead to corrupt metadata, and thus requires a metadata recalculation.

lib/db: Add mechanism to repair db without schema update (ref #7044)

---

lib/model/indexsender.go
lib/model/model.go

The actual bugfix is in line 238: I switched `local` and `remote`. To make such a switch impossible, the two `protocol.Device` arguments are now passed as a struct. Well not impossible, one might still create the struct with unnamed members, but lets just not do that generally.

lib/model: Pass device infos as struct (fixes #7051)

---

go.mod
go.sum
gui/default/syncthing/core/syncthingController.js
lib/api/api.go
lib/api/api_test.go
lib/api/confighandler.go
lib/api/mocked_config_test.go
lib/config/config.go
lib/config/migrations.go
lib/config/migrations_test.go
lib/config/wrapper.go
lib/protocol/deviceid.go

In this PR I add new rest endpoints at `/rest/config` to allow for partial config reading/changes. I mostly follow what was proposed in #6540, with the exception that I don't support setting individual options like e.g. `/rest/config/options/maxsendkbps`. To do that you do a `PATCH` request on `/rest/config/options` with just the options you want to modify in the body. Individual folders and devices can be modified (or deleted) using e.g. `/rest/config/folders/*folderid*`. It's manual, as in if we add new elements to `config.Configuration`, this needs updating (as in register new endpoint and add some boilerplate) - I am fine with taking care of that.
I added tests for all methods, but by no means exhaustively covering all endpoints.
This will require documentation updates, I'll do that …

lib/api: Add /rest/config endpoint (fixes #6540)

---

gui/default/index.html
gui/default/syncthing/app.js
gui/default/syncthing/core/syncthingController.js
gui/default/syncthing/core/validDeviceidDirective.js
gui/default/syncthing/device/editDeviceModalView.html
gui/default/syncthing/folder/editFolderModalView.html

A large part of the gui diff in https://github.com/syncthing/syncthing/pull/6727 are refactors to make my live easier or prevent duplication. To implement the feature flag and keep the diff minimal, I factored out all those changes that do not change behaviour and that I consider useful even if encryption wouldn't be there:
- Devices are now tracked as a map internally.
- Use `$scope.currentSharing` to track sharing changes instead of having "virtual attributes" on the device-/folderconfigs.
Testing: Un-/Sharing folders/devices still works.

gui: Refactor to make encryption diff smaller

---

gui/default/syncthing/core/syncthingController.js

Some accesses to the new $scope.devices object (instead of previously
array) used wrong / inexistent names for the index variable.

gui: Fix undefined variables fallout from #7049.

---

gui/default/syncthing/core/syncthingController.js

Another fallout from #7049.
Iterating over $scope.devices was done because of its array nature.
Since making it an object, the change can be targeted directly, so
remove the loop completely.

gui: Remove needless looping in ignoreFolder().

---

gui/default/syncthing/core/syncthingController.js

This reverts PR #7059 / commit c7d40ccbaee867b579ccb291b258fd28299b3464.
I was speeding when merging that: There is no looping, it's just a safety check that the device in question actually exists.

gui: Readd check if device exists (ref #7059)

---

lib/config/folderconfiguration.go

Apparently the FAT file system can be called "msdos" in Android. Thus,
in addition to looking for "fat", we should also check for "msdos" as
an alternative of FAT, and then apply the mtime window accordingly.

lib/config: Check for "msdos" when detecting FAT FS in Android

---

lib/api/api.go
lib/api/api_test.go

Extracted from #7017, I think this change is of general utility.  It reports the HTTP OPTIONS method as part of the allowed methods for the API.  That is normally used as part of the CORS preflight check when doing a GET or POST request.  When just trying to check API availability, a deliberate OPTIONS request is enough, but currently it fails because of the returned `Access-Control-Allow-Methods` header.
I don't see any security risks here and was hoping to get this small change into a release before #7017 is finalized, so that the probing done there actually works with as many instances as possible.
Verified that the header is set: `curl -X OPTIONS http://localhost:8384/ -v`.  Tested with Firefox (as part of #7017) that it no longer fails with a [CORS …

lib/api: Allow OPTIONS method in CORS preflight request handling.

---

lib/api/api.go
lib/api/api_test.go

Just noticed through #7079 that there's a method whitelist and thus added the new methods used in the `/rest/config` endpoints. And this also fixes an issue with `/rest/config` the only endpoint added in #7001 that I didn't add a test for. Weirdly enough adding the test wouldn't have helped: It doesn't fail (neither does the UI, which uses it too), while it does fail using curl. Anyway, works with curl too now.

lib/api: Fix /rest/config path and add methods to cors (ref #7001)

---

lib/build/build.go
lib/db/backend/backend.go
lib/db/db_test.go
lib/locations/locations.go

This removes the switch for using a Badger database, because it has bugs
that it seems there is no interest in fixing, and no actual bug tracker
to track them in.
It retains the actual implementation for the sole purpose of being able
to do the conversion back to LevelDB if anyone is actually running with
USE_BADGER. At some point in a couple of versions we can remove the
implementation as well.

lib: Remove USE_BADGER experiment

---

lib/ur/failurereporting.go

The main fix is in setting the channel variable to nil when unsubscribing (line 97). In addition I removed that var from the struct, because it's only used in `serve` and for good measure added a check that the channel wasn't closed when receiving from it. And finally added a context escape hatch to the goroutine doing the initial config setup.
EDIT: Actually if putting in extra safeties, lets do it right and also check the type conversion itself. And report if either of those two checks fail, because they shouldn't ever fail so I want to know if they do.

lib/ur: Fix panics in failure-reporting (fixes #7090)

---

lib/config/config_test.go
lib/config/folderconfiguration.go
lib/model/folder_sendrecv.go

This changes the meaning of `MaxConcurrentWrites <= 0` to mean default and additional puts an upper limit on the config value too. I guess the latter is going to be controversial, as it's clearly user error. My reasoning is that I'd rather check for that than have to explain the error to a user. And the limit of 64 is entirely randomly chosen, I do not know anything about concurrent IO, so if there is a technical reason to change that or drop it alltogether, please let me know.

lib/config: Sanity checks on MaxConcurrentWrites (ref #7064)

---

lib/api/api.go

I missed adjusting the debug endpoint in #7001 to the new httprouter library: It doesn't match subpaths automatically, one needs to specify desired matching behaviour. Thus it returned 404s for the debug endpoints.

lib/api: Fix debug endpoints (ref #7001)

---

lib/model/folder.go
lib/model/folder_sendrecv.go
lib/model/folder_sendrecv_test.go

There's a shortcut that prevents acquiring an IO token for pulling if there's nothing to pull. However that shortcut did not take care of pull errors. Thus if pulling failed, then a remote index comes in such that we don't need the file anymore (e.g. deletion), the earlier failure is never cleared.
As the IO limiting happens in `folder`, and pull errors are managed in `sendReceiveFolder`, I refactored error management: Now all errors are stored in `folder` under a single lock (we never scan and pull at the same time, so having two locks is pointless).

lib/folder: Clear pull errors when nothing is needed anymore

---

lib/model/indexsender.go
lib/model/model.go

Folders which are newly added/shared fell through the cracks regarding sending indexes, as we reject them in cluster config and that's where we initialise index sending. Now in `newFolder` and in `restartFolder` when a folder is shared to a new device, we call a new method `indexSenderRegistry.addNew`. This starts the index sender with no index info (the folder/device is new, we need to transfer everything).

lib/model: Send indexes for newly shared folder (fixes #7098)

---

lib/model/folder.go

We can't use the context in exported functions, as we get it as an argument to `serve` and those functions may be called before/after serve is started/returned.

lib/model: Add done chan to track folder-lifetime (fixes #6664)

---

gui/default/assets/css/overrides.css
gui/default/index.html

When using a Web browser with JavaScript either disabled or unavailable,
show a warning to let the user know that the Web GUI requires JS in
order to operate.
To achieve this, add a `div` that wraps both the navbar and the main
content, and then move the CSS class `ng-cloak` from the `html` element to
that `div`. This way, only the JavaScript-dependent part is hidden when
JS is unavailable, and not the whole website, as it is the case right
now. Then, add a `<noscript>` element right at the start of the `body`
element, so that the warning is also shown right away in text-based Web
browsers. The `noscript` element includes a stripped down version of the
navbar showing only the Syncthing logo, and then a container with the
warning itself. Lastly, leave the footer untouched and always …

gui: Add warning when JavaScript is disabled in Web browser (fixes #7099)

---

go.mod
go.sum

I added the commits of the following two PRs filed upstream to our fork. They contain a fix for the dangling symlink issue on BSDs (#5360) and add more meaningful info to a panic we see quite frequently in sentry. I'll keep trying to get this upstreamed.
https://github.com/rjeczalik/notify/pull/194
https://github.com/rjeczalik/notify/pull/193

build: Update notify (fixes #5360)

---

lib/tlsutil/tlsutil.go

This adds O=Syncthing, OU=Automatically Generated to our certificates,
making it clearer where it came from even when the CN is not
"syncthing", such as it is with for example the relay server
(CN=strelaysrv).

lib/tlsutil: Add O and OU to generated certificates (fixes #7108)

---

lib/api/api.go
lib/db/set.go

The `/rest/db/file` endpoint already has a good amount of helpful info when debugging weird out-of-sync issues, but it doesn't give the full picture. I added a `/rest/debug/file` endpoint which in addition to the info already contained in `/rest/db/file` also prints the global versions. Thus one can see at a glance all involved devices and at which versions they are (plus if ignored and/or deleted). I named all the involved method with `Debug` and the api data is a string, as it is an internal implementation detail and should not be used for anything but debugging.

lib/api, lib/db: Add file debug endpoint

---

gui/default/syncthing/core/syncthingController.js
gui/default/untrusted/syncthing/core/syncthingController.js

I missed this code path in https://github.com/syncthing/syncthing/pull/7049
This affects the current RC.

gui: Initialise sharing when accepting new device (fixes #7113)

---

lib/config/optionsconfiguration.go

Somehow `RawMaxFolderConcurrency` sneaked its way into a method that's actually concerned with `RawMaxCIRequestKiB`.

lib/config: Use correct var in MaxConcurrentIncomingRequestKiB()

---

gui/default/syncthing/core/validDeviceidDirective.js

Fixes #7124, which is a regression introduced in #7049. The function argument `scope` doesn't get a `$` here, while it does in the main controller - I don't know why that is, but I'd rather not touch it (as in add the `$` for consistency) and just fix the newly introduced code by removing the `$`.

gui: Remove erronous $ from scope in directive (fixes #7124)

---

lib/model/indexsender.go
lib/util/utils.go

In #6947 I missed that the `suture.IsComplete` interface has been removed in suture/v4. I replaced that with a function to wrap errors such that the returned error fulfils `errors.Is(err, suture.ErrDoNotRestart) == true`.
I discovered this while investigating https://forum.syncthing.net/t/device-stays-out-of-sync-until-restart/15891 - that's what the additional debug line is for.

lib/model, lib/util: Replace IsComplete with NoRestartErr (ref #6947)

---

lib/model/model.go
lib/model/model_test.go

More fixes regarding races between folders being started and cluster configs based on the logs provided in https://forum.syncthing.net/t/device-stays-out-of-sync-until-restart/15891
There's an issue with sending cluster configs: When a folder is not paused, but hasn't been started yet, we send an info that says that the folder is running, but there's no index id/sequence. The remote then drops all info on us. Once the folder is started, we happily start sending from a non-zero starting sequence. Thus the remote will be missing index info from us between 0 and that starting sequence.  
The fix for this is to pretend the folder is paused if it isn't running, even if it isn't paused in config. Then when it is actually started resend the cluster-config including the proper index info.
How I …

lib/model: Never send unpaused folder without index info

---

lib/db/set.go

When we drop all index information on a device, we should also make sure their index id is zero for consistency. This ensures a subsequent full index exchange (which we need, as we just dropped all info) even if something goes wrong (like incoming index updates after dropping: #7134).

lib/db: Reset index-id when dropping device

---

cmd/strelaysrv/main.go
lib/api/api_test.go
lib/api/mocked_config_test.go
lib/config/commit_test.go
lib/config/config.go
lib/config/config_test.go
lib/config/folderconfiguration.go
lib/config/guiconfiguration.go
lib/config/optionsconfiguration.go
lib/config/wrapper.go
lib/connections/lan_test.go
lib/connections/limiter_test.go
lib/discover/cache_test.go
lib/model/model_test.go
lib/nat/structs_test.go
lib/syncthing/syncthing_test.go
lib/syncthing/utils.go
lib/util/utils.go
lib/watchaggregator/aggregator_test.go

Working on configurable folder/device defaults, I noticed we do not ensure that the local device is always added to folders. We only check that when creating a new config, which is kind of useless. Adding that check requires the wrapper to know about it's own - which is why all the files not in lib/config changed. And working on `Configuration.prepare` made my head spin, so I decided to split that up into smaller functions and methods on the sub-types. And while at it, I changed `util.SetDefaults` to recurse into structs, such that we only need to call it once at the top-level (the current way is repetitive and prone to error by forgetting a member).

all: Refactor preparing configuration

---

lib/model/indexsender.go
lib/model/model.go
lib/model/requests_test.go

More fixes regarding races between folders being started and cluster configs being processed based on the logs provided in https://forum.syncthing.net/t/device-stays-out-of-sync-until-restart/15891
The fix for race on incoming cluster-configs in #7100 works, but it's an unclean and partial fix:  
Index senders are started without index info, as the folder/device is new. That's correct for the starting sequence, but it's still bad because we don't store the index id. Meaning on a successive connect, we will re-exchange all index data. That is fixed by always storing the index data received in cluster-configs, even if we don't share the folder so far.  
And we should also resend cluster-configs when adding folders on starting the model - connections may happen before that.
Extended the unit …

lib/model: Retain index info for new folders/devs (ref #7100)

---

gui/default/untrusted/syncthing/core/syncthingController.js

After reverting the folder was still shown as having locally changed items in the header (not in the folder details). That's because deleted items don't count. Fix: Use `hasReceiveEncryptedItems` which takes care of that.

gui: Incorrect recv-enc folder status after revert

---

lib/protocol/encryption.go
lib/protocol/encryption_test.go

That code just asks for the panic - luckily my testing folder answered. There's a unit test now.

lib/protocol: Fix OOR panic on recv-only folders

---

go.sum
lib/model/indexsender.go
lib/model/requests_test.go

I lost the line
```
folderIsReceiveEncrypted: folder.Type == config.FolderTypeReceiveEncrypted,
```
in some merge/rebase operation.
Added a unit test ensuring that we don't send indexes for locally changed items on receive-encrypted folders.

lib/model: Don't send locally changed on recv-enc (fixes #7137)

---

gui/default/untrusted/syncthing/core/editShareTemplate.html
gui/default/untrusted/syncthing/device/editDeviceModalView.html

Fix a copy&paste error in the sharing tab of the device edit modal and change the help text in the password input field if the device is untrusted.

gui: Fix & improve sharing with untrusted device

---

gui/default/assets/lang/lang-en.json
gui/default/index.html
gui/default/syncthing/core/syncthingController.js
gui/default/untrusted/index.html
gui/default/untrusted/syncthing/core/syncthingController.js

This removes the probing for the remote side, instead making it so we
simply construct the address based on the currently connected address,
if any, and let the user sort out whether it works or not.

gui: Remove probing for remote GUI address (ref #7017)

---

script/translate.go

There were some strings without the translation attribute/directive and the script was complaining about the new noscript stuff (which can't be translated).

build: Ignore noscript in translation-script

---

lib/model/model.go

Use the config wrapper's accessor methods with a device / folder argument instead of looking up in a temporary map of the same data.
Slight performance optimization by not re-creating the maps repeatedly.
None so far, as it seems an obvious change.

lib/model: Simplify access to Folder and Device configuration.

---

lib/fs/util.go
lib/fs/util_test.go
lib/model/model.go
lib/model/model_test.go

Moves `sanitizePath` from model to `fs.SanitizePath` and in addition to what it already sanitizes, it now also adds an underscore to windows reserved names, fixing #7075.

lib/fs, lib/model: Cover more windowsyness sanitizing paths (fixes #7075)

---

lib/db/set.go
lib/db/set_test.go

This reverts commit 641b7aee384f9490e747abd1c61a4b987018de4a respectively PR #7135.
I created a unit test to make sure that behaviour doesn't erroneously get changed again in the future, and added a comment there why this behaviour is correct/needed:
```
// Dropping the index ID on Drop is bad, because Drop gets called when receiving
// an Index (as opposed to an IndexUpdate), and we don't want to loose the index
// ID when that happens.
```

lib/db: Do not reset index-id when dropping device (ref #7135)

---

lib/model/folder_sendrecv.go
lib/model/sharedpullerstate.go

The problem in #7152 is the trailer we add to the file containing the encrypted file info and the connected file size change: We adjust that when actually pulling the file. On index retransfer, we get a new global file, as the version always changes when encrypting a file info. That triggers a pull, but as the contents didn't change, that can be shortcutted. In the shortcut we do not adjust the filesize. So on next scan, the scanner notices the changed file size and thus the file gets marked as locally changed.
Now the file size adjustment happens in the db updater routine of the puller, not in the shared puller state.

lib/model: Fix enc file size when pulling (fixes #7152)

---

lib/api/api.go
lib/api/mocked_model_test.go
lib/db/set.go
lib/model/model.go
lib/model/requests_test.go

Deleted items in a receive-encrypted folder must be tagged as a local change, as we mustn't send them to remotes. However those are not a problem, they are meant to be deleted, and thus shouldn't show up as locally changed. To filter those files out, we need to know the folder type. That information is not available in the db package. Thus in the api, instead of getting a db-snapshot from the model and getting locally changed items from that snapshot, this information is now directly obtained from the model (thus having all of these file list methods (need, remote-need, locally-changed) in the model. instead of spread between model and db).

lib: Skip deleted, locally changed on recv-enc folders (fixes #7153)

---

go.sum
lib/protocol/protocol.go
lib/protocol/protocol_test.go
lib/testutils/testutils.go

Doing some testing for untrusted feature I noticed that errors processing cluster-config didn't result in the connection being dropped on the remote device. We are currently just closing the underlying connection in that case, not sending a BEP close-message, thus the connection first needs to time out on the remote to be noticed as closed.

lib/protocol: Send Close message on read error

---

gui/default/syncthing/core/syncthingController.js
gui/default/syncthing/device/editDeviceModalView.html

Refactoring in #7049 broke the "Select All" and "Deselect All" buttons under the Sharing tab for editing devices.  It was supposed to work just like for the folder editing modal, but the distinction between already shared and not shared is not made in the edit device modal yet.
Fixing that properly (by splitting just like it is done in the edit folder modal) will come in a separate PR, but I wanted to get this one out as a quick regression fix.
Both buttons confirmed working when editing an existing device.

gui: Restore Select / Deselect All buttons in device sharing tab.

---

cmd/stcrashreceiver/main.go
cmd/stcrashreceiver/stcrashreceiver.go
lib/ur/failurereporting.go

Failure reporting is broken because the timer is never reset when there's nothing to report. I also added/improved some logging on `stcrashreceiver`.
I tested failure reporting by running `stcrashreceiver` locally and triggering a "failure report testing" event - it works: https://sentry.syncthing.net/syncthing/syncthing/issues/5741/?query=test

lib/ur: Reset timer when there's nothing to report

---

gui/default/syncthing/core/syncthingController.js
gui/default/untrusted/syncthing/core/syncthingController.js

Fixes the device showing up as blank under recent changes if the friendly name is known. This also appears to have been mentioned in the [forum](https://forum.syncthing.net/t/device-name-is-blank-in-recent-changes/15970).
If the friendly name is unknown, eg if the remote device is removed after making a change, the short ID is still shown properly both before and after this change.

gui: Fix blank device name under recent changes.

---

gui/default/syncthing/core/syncthingController.js
gui/default/syncthing/device/editDeviceModalView.html
gui/default/untrusted/syncthing/core/syncthingController.js
gui/default/untrusted/syncthing/device/editDeviceModalView.html

This is the proper fix for the problem mentioned in #7161.  While the former is meant as a hot-fix, this one actually changes the GUI layout and functionality.
When editing folders, the checkboxes have been split into two categories for some time now.  This one mirrors the same to adding / editing a device.  Also properly fixes copy-paste errors introduced with #7049.
This PR does not include replicating the changes to the `untrusted` GUI, as it is nontrivial in this case.

gui: Split folders into two categories on the sharing tab for devices.

---

lib/protocol/encryption.go
lib/protocol/encryption_test.go

This PR just adds awareness of slashified paths to existing methods that check if a given path could have been auto-generated by our encryption code (of course it's still possible to create an extraneous dir that looks like an encrypted one to sneak past this detection, that's not an issue though, we'll just ignore it (or delete if empty)). This does not address the point brought up in #7184 that it might be better to just not care about extraneous stuff in encrypted folders at all, it just fixes the behaviour as it is.

lib/protocol: Handle slashified paths in IsEncryptedParent (fixes #7184)

---

lib/connections/deprecated.go
lib/connections/quic_dial.go
lib/connections/quic_listen.go
lib/connections/quic_misc.go
lib/connections/quic_unsupported.go
lib/connections/service.go

This does two things:
- Exclude QUIC from go1.16 builds, automatically, for now, since it
doesn't work and just panics.
- Provide some fake listeners and dialers when QUIC is disabled.
These fake listeners and dialers indicate that they are disabled and
unsupported, which silences "Dialing $address: unknown address scheme:
quic" type of stuff which is not super helpful to the user.

lib/connections: Handle QUIC not being available

---

lib/api/api.go
lib/build/build.go

The GUI expected the version.tags field to be a list of current build
tags, but the thing the API sent was actually the comma separated string
set by the build script. (This was broken in d53a2567a.) First of all
this is the wrong format, secondly it doesn't include all the things we
actually consider tags. This fixes that.
Technically it's a breaking API change. I don't think anyone cares; it's
a bugfix of the previous unintentional API change.

lib/api: Returns tags in version as list

---

go.mod
go.sum

Pulls in the fix for #7076 in upstream and brings us back in sync with upstream.

build: Update notify (fixes #7076)

---

go.mod
go.sum
lib/config/folderconfiguration.go
lib/fs/basicfs.go

While we are depending on gopsutil v3, we are actually using v2 code. The breaking changes don't concern our usage and we lose dependencies in the process, which is always nice.

build: Switch to gopsutil's v3 module

---

gui/default/syncthing/core/syncthingController.js

Use alphabetical order for the name / label instead of ID, just like in the main page listings.
Manual verification in the GUI.

gui: Sort folders and devices in advanced config modal (fixes #6985)

---

lib/config/config.go
lib/config/migrations.go

Removes the pending entries in config, which live in db since #6443.  
We discussed that there's no need to transfer existing pending entries in config over to db as that's low-value info and will get reintroduced on next connect (and would also be hard to do due to package dependency issues), but they still should be erased.

lib/config: Remove deprecated pending entries from config (ref #6443)

---

lib/model/requests_test.go

Finally a flaky test that I can trigger :)
`folderIgnoresAlwaysReload` causes a folder restart, thus an initial scan. And writing a test file is a two step procedure: 1. write contents. 2. chmod. If that initial scan falls in between those two operations, the test fails :D

lib/model: Unflake TestIgnoreDeleteUnignore

---

lib/api/api_test.go
lib/beacon/beacon.go
lib/connections/service.go
lib/db/lowlevel.go
lib/discover/local.go
lib/discover/manager.go
lib/model/folder_summary.go
lib/model/model.go
lib/syncthing/syncthing.go
lib/util/utils.go

I got some log lines like this in my testing logs:
```
2020/12/16 11:57:51 broadcastBeacon: Failed service 'Service@0xc000046500 created by broadcastBeacon@0xc000272460/reader' (1.000000 failures of 2.000000), restarting: true, error: listen udp4 :21027: bind: address already in use
```
The supervisor for local discovery didn't set the suture event (log) hook, thus it got logged to stdout via `log`.
To prevent that oversight I added an `eventHook` argument to our `util.Spec` convenience function.

lib: Consistently set suture logging

---

lib/model/folder.go
lib/model/folder_recvonly_test.go

Another flaky test fix:
The test checks that the locally changed items get resolved when the remote has identical files (but different version). That happens in the puller, but the test calls `ScanFolders`. In most cases a pull will happen before that, but in rare cases not.  
Solution: Do a pull from the test instead of calling `ScanFolders`.
I sneaked in some debug logging, because frankly we are super verbose all over model, but scanning is kind of a black box (concretely the lack of indication that a scan actually happens confused me looking at logs).

lib/model: Fix flaky test and add some scanning debug

---

lib/db/keyer.go
lib/db/lowlevel.go
lib/db/set.go
lib/db/transactions.go

We don't remove index-id entries from the database when removing a folder. I initially thought this is the culprit for https://github.com/syncthing/syncthing/issues/7198, however it is not: We do remove the folder index, thus we cannot reach the existing indexid, even though it still exists, and a new one is created. So all this PR does is clean up those unreachable index ids.

lib/db: Remove index ids when dropping folder

---

gui/default/untrusted/syncthing/core/syncthingController.js
gui/default/untrusted/syncthing/device/editDeviceModalView.html
gui/default/untrusted/syncthing/folder/editFolderModalView.html

In the device edit modal, changing the "Untrusted" setting has no effect on the sharing tab (requiring an encryption password or not). I changed that by making it a variable binding, instead of passing an attribute once at creation.

gui: Reflect change in untrusted in sharing tab

---

lib/db/lowlevel.go
lib/db/set.go
lib/db/set_test.go

When anyone calls `FileSet.IndexID` and the local one is zero, we create a new one. Thus two goroutines calling it concurrently may return two different IDs, and the later one will be persisted. I realised this because of logs connected to https://forum.syncthing.net/t/mismatching-index-id-for-us-on-almost-every-restart-again/16036/8:
```
129:[RTF25] 14:24:38 INFO: Device DWJVRMJ-... folder "A" (a) has mismatching index ID for us (0xA0175C8807ED7CBB != 0x42C01C3C03087F58)
[...]
566:[RTF25] 15:10:32 INFO: Device DWJVRMJ-... folder "A" (a) has mismatching index ID for us (0x42C01C3C03087F58 != 0x6F4E1206A392035F)
```
However it still seems quite improbable: The race would be between any incoming and any outgoing CC (both call `IndexID`). Then again, there's quite a few devices and folders …

lib/db: Prevent IndexID creation race

---

lib/api/mocked_model_test.go
lib/connections/service.go
lib/connections/structs.go
lib/model/fakeconns_test.go
lib/model/model.go
lib/model/model_test.go
lib/protocol/benchmark_test.go
lib/protocol/encryption.go
lib/protocol/protocol.go
lib/protocol/protocol_test.go
lib/testutils/testutils.go

From https://github.com/syncthing/syncthing/issues/7165:
> Came up starting in #7141 (comment), short summary: A protocol connection doesn't control the underlying tls connection, thus it cannot close it. All the methods that supposedly close it, just tell the model that it's closed and potentielly send a Closed BEP msg, but don't actually close the connection.
What I did is to move the entire connection interface to lib/protocol, and pass the necessary pieces (closer and connection info) to from lib/connections to lib/protocol. The main advantage is that the protocol can now close the underlying connection on any error. Additional it's also a bit cleaner, removing some type aggregation and an interface in lib/connections.
No new tests. The changes are just adjustments to the new API. …

lib: Close underlying conn in protocol (fixes #7165)

---

cmd/strelaypoolsrv/main.go
cmd/strelaysrv/main.go
cmd/strelaysrv/pool.go

As discussed in #7196, there might be some scenarios where a relay server might want to advertise itself from a different IP address from which it is actually listening on. This is currently not possible, as the relay pool server rejects join requests whose advertised remote address does not match the address used to make the join request.
This PR enables relay servers to send their TLS certificate in the join requests, provided the pool is contacted via https. The relay pool server will capture this certificate, generate the Device ID from it, and compare it to the advertised device ID. If they do not match, the request is rejected straight away.
This ensures that the agent sending the join request is indeed in possession of the key corresponding to the advertised device ID. This …

Allow validation of relay join requests by certificate

---

lib/db/set.go
lib/fs/casefs.go
lib/fs/filesystem.go
lib/fs/mtimefs.go
lib/fs/mtimefs_test.go

With `fs` debug logging we print information about what called the fs method. However for case- and mtime-fileysstems, this information is entirely useless, as it just points at the overriding method in those wrappers (e.g. chmod just says it was called by chmod). To prevent that I added a utility function that ensures proper wrapping order:
```golang
// wrapFilesystem should always be used when wrapping a Filesystem.
// It ensures proper wrapping order, which right now means:
// `logFilesystem` needs to be the outermost wrapper for caller lookup.
func wrapFilesystem(fs Filesystem, wrapFn func(Filesystem) Filesystem) Filesystem {
```

lib/fs: Correct wrapping order for meaningful log-caller

---

gui/default/syncthing/core/syncthingController.js
gui/default/untrusted/syncthing/core/syncthingController.js

The merge of #6443 apparently introduced a wrong argument name in
$scope.ignoreFolder().  This fixes the regression.

gui: Fix nonfunctional ignore button on pending folder notification.

---

cmd/stevents/main.go

Add a `-types` flag which can be set to a comma-separated list of event
types.  The contents will be included verbatim in the URL parameter
`events`.
Tested against a devopment instance of Syncthing running locally, with two event types specified.

cmd/stevents: Add command line argument for event type filtering.

---

gui/default/syncthing/core/syncthingController.js
gui/default/untrusted/syncthing/core/syncthingController.js

When adding a folder from the pending folder from another device
through the Add button on the "New Folder" notification panel, the
offering device should be preselected for sharing with.  The selection
works, but the checkmark for that device is not shown at all.
Do not filter out the preselected device ID when building the
currentSharing.unrelated member in addFolderAndShare() to actually
show all devices under the "Unshared Devices" heading.
Tested with local development instance where several folders are pending from other devices.  Offering device appears again, with the checkmark pre-selected.  Also verified on the "untrusted" GUI variant.

gui: Fix missing sharing device when adding pending folder.

---

lib/model/model.go

Small cleanup: Since moving the pending folders/device to db, `model.ccHandleFolders` doesn't modify the config anymore, thus the `changed bool` return value is unused.

lib/model: Remove obsolete return val from ccHandleFolders (ref #6443)

---

gui/default/syncthing/core/syncthingController.js
gui/default/untrusted/syncthing/core/syncthingController.js

Align GUI default handling with
```golang
// If we're configured to not do version cleanup, or we don't have a
// versioner, cancel and drain that timer now.
if f.versionCleanupInterval == 0 || f.versioner == nil {
```
```golang
if f.Versioning.CleanupIntervalS > MaxRescanIntervalS {
f.Versioning.CleanupIntervalS = MaxRescanIntervalS
} else if f.Versioning.CleanupIntervalS < 0 {
f.Versioning.CleanupIntervalS = 0
}
```

gui: Do not replace zero versioning cleanup interval

---

lib/model/folder.go
lib/model/folder_recvenc.go
lib/model/folder_recvonly.go
lib/model/folder_sendonly.go
lib/model/folder_sendrecv.go
lib/model/folder_sendrecv_test.go
lib/model/model.go

Filesystems are created/stored redundantly in folders: The basic filesystem lives in the folder config, the mtime-fs is created in the model and passed to folder factories, where it is stored in `sendReceiveFolder` only, but created again on every scan in `folder`. Now it isn't passed in the factory anymore and lives as `folder.mtimefs`, thus being available in all folders.
This saves us the massive amount of 4 lines of code (and shortens some lines) :)

lib/model: Cleanup redundant filesystem variables in folders

---

lib/fs/basicfs_test.go

The test would fail if the umask on UNIX is greater than 0022, because
the OS transparently subtracts it from the mode passed to Mkdir(), as
the Go documentation confirms.
Our goal here is not to test os.Mkdir(), so just make sure the desired
mode is actually set by forcing it afterwards.

lib/fs: Fix TestChmodDir depending on umask (fixes #6551)

---

lib/model/indexsender.go

Index-senders are unblocked/cleaned up when the underlying connection closes, however not when they fail on their own due to a db error. Now there's an additional channel that gets closed when the index-sender stops, and that's used instead of the connection to unblock method calls.
And there was a copy&paste error when cleaning up index-senders of folders no longer mentioned in a cluster-config.

lib/model: Handle index sender terminating due to error (fixes #7231)

---

lib/ur/memsize_linux.go

On Linux, memorySize in lib/ur would open /proc/meminfo but never close it.

lib/ur: Plug file descriptor leak in Linux memorySize

---

lib/fs/casefs.go
lib/model/model.go

This makes it faster to get a caseFs when it's already cached, which it almost always is. It also moves the filesystem touching things in the request path to until after we've passed the limiter, so that we block there instead on the casefs lock.

lib/fs, lib/model: Reduce lock contention on NewCaseFilesystem (fixes #7268)

---

lib/api/api.go
lib/api/mocked_model_test.go
lib/model/folder_summary.go
lib/model/model.go
lib/model/model_test.go

This splits the ignore getting to two methods, one that loads from disk
(the old one) and one that just returns whatever is already loaded (the
new one). The folder summary service which is just interested in stats
now uses the latter method. This means that it, and API calls that call
it, does not get blocked by folder I/O.

lib/api, lib/model: Avoid contention on filesystem for DB status call (ref #7270)

---

gui/default/syncthing/core/logViewerModalView.html
gui/default/syncthing/core/syncthingController.js

Fixes reported issue #7267
1) Open logging modal
2) Scroll to top to stop log-tailing
3) Close modal
4) Reopen modal and see log-tailing resumes and displays log instead of blank textarea as shown in issue repoort

gui: Fix log-tailing behavior when scrolled to top (fixes #7267)

---

gui/default/index.html
gui/default/untrusted/index.html

Disable rescan all when at least one folder is not paused (fixes #7257)
1. Click on pause all
2. Confirm rescan all button is in disabled state (visually confirm greyed out and clicking does not rescan)
3. Click on resume all
4. Confirm rescan all button is in enabled state (visually confirm not greyed out and clicking does rescan)

gui: disable rescan all when at least one folder is not paused (fixes #7257)

---

lib/model/folder.go

Schedule a pull when a folder error is cleared. Pulls are only done on demand (incoming indexes or scanned changes), which means a pull may not happen for a long time if the folder was out-of-sync while being in error state.

lib/model: Pull when folder leaves error state (fixes #7280)

---

cmd/syncthing/main.go
lib/syncthing/syncthing.go

Don't hang on startup.
(We should push a new nightly after merging...)

cmd/syncthing: Provide early startup for config service (ref #7188)

---

lib/util/utils.go

This changes util.UniqueTrimmedStrings to not modify its input. The in-place modification is fine at all call sites (AFAICT), but not documented and not necessary. I also changed the comment to reflect the return value's properties more precisely.

lib/util: Don't modify input in UniqueTrimmedStrings

---

lib/util/utils.go

There's some error handling code that is duplicated between lib/svcutil and lib/util. The code in the latter package goes unused, so I removed it.

lib/util: Remove duplicate error handling code

---

lib/svcutil/svcutil.go

With this patch, OnSupervisorDone no longer allocates.

lib/svcutil: Simplify doneService

---

gui/default/syncthing/settings/advancedSettingsModalView.html

Fix the label and input IDs so that each of them is unique. Also, fix
some bugs where panel names where mixed, e.g. options and not gui was
used for elements inside gui, etc. In particular, make sure that each
folder and each device has its own numbering.

gui: Make label and input IDs in Advanced Configuration unique (fixes #7287)

---

gui/default/assets/css/overrides.css

Reduce the size of checkboxes in the Advanced Configuration, so that it
matches the rest of the Web GUI.

gui: Reduce checkboxes size in Advanced Configuration (fixes #6949)

---

lib/stun/stun.go
lib/util/utils.go

This is an alternative to #7304: it inlines util.OnDone at its only call site and replaces its comment by one that explains why the separate goroutine is necessary.
I didn't add the second CallWithContext as I didn't find the resulting code much clearer than this version. In fact, I'm wondering if the CallWithContext around Discover cannot be removed instead?
Closes #7304.

lib/stun: Inline util.OnDone, comment on its purpose

---

lib/scanner/blocks.go
lib/scanner/walk_test.go

scanner.Blocks promises, in a comment, to allocate space "once and for all" if it knows the file size. It only did so, however, when the block size divided the file size. The pre-allocation now works as intended for files of all sizes.
Benchmark results on Linux/amd64, using updated benchmark for old and new:
```
name        old time/op    new time/op    delta
HashFile-8    88.6ms ± 1%    88.3ms ± 1%   -0.33%  (p=0.046 n=19+19)
name        old speed      new speed      delta
HashFile-8   201MB/s ± 1%   202MB/s ± 1%   +0.33%  (p=0.044 n=19+19)
name        old alloc/op   new alloc/op   delta
HashFile-8    59.4kB ± 0%    46.1kB ± 0%  -22.47%  (p=0.000 n=14+20)
name        old allocs/op  new allocs/op  delta
HashFile-8      29.0 ± 0%      27.0 ± 0%   -6.90%  (p=0.000 n=20+20)
```

lib/scanner: Allocate structure for final partial block

---

lib/protocol/encryption.go
lib/protocol/encryption_test.go

Adds the block offset as additional data into the AES-SIV encryption of the block hash, thus making it not possible to correlate blocks at different offsets within a file. (These are never decrypted so there is no "other side" to this change.)

lib/protocol: Hide repeated data blocks in a given file

---

lib/scanner/blockqueue.go

This removes an unused field and applies a very minor optimization.

lib/scanner: Remove unused field, move WaitGroup.Add out of loop

---

gui/default/syncthing/core/syncthingController.js
gui/default/untrusted/syncthing/core/syncthingController.js

Do not touch .stignore when not needed (fixes #7284)
* saved without changes (mtime unchanged)
* saved with real changes (mtime changed)
* saved with whitespace changes (mtime unchanged)

gui: do not touch .stignore when not needed (fixes #7284)

---

lib/db/db_test.go
lib/db/lowlevel.go

For all the other repair functions we do print the number of repaired entries, but we don't for globals. Which sucks when debugging a problem where we do a db repair check on startup (which is logged), but there's no indication if that check did something - which is the case for https://forum.syncthing.net/t/how-do-i-repair-the-index-database/16280.

lib/db: Report number of repaired items from checkGlobal

---

lib/ignore/cache.go

This halves the size of cache entries on amd64 (32 bytes -> 16 bytes). A quick simulation suggest the total memory footprint should get about a third smaller: I put strconv.Itoa(j) for j = 0 through 10000 in a cache and saw the allocation rate go down from 1.91 to 1.31 MiB.

lib/ignore: Store cache timestamps as Unix ns counts

---

cmd/stcrashreceiver/main.go
lib/db/lowlevel.go
lib/ur/failurereporting.go

Failure reports should be arriving on sentry, but didn't: Forgot the crash reporting url has a path already, `newcrash`.
Also empty failure reports are sent on shutdown. And `GET` used for sending failure reports - which works as we don't care, but is still weird. And finally: There's lots of "failure report is not a string" failure reports, because errors from the db have not been stringified.

all: Failure reporting fixes

---

lib/model/model.go

An untrusted device will receive padded info for small blocks, and hence
sometimes request a larger block than actually exists on disk.
Previously we let this pass because we didn't have a hash to compare to
in that case and we ignored the EOF error based on that.
Now the untrusted device does pass an encrypted hash that we decrypt and
verify. This means we can't check for len(hash)==0 any more, but on the
other hand we do have a valid hash we can apply to the data we actually
read. If it matches then we don't need to worry about the read
supposedly being a bit short.

lib/model: Correctly verify short read blocks (fixes #7333)

---

gui/default/syncthing/core/syncthingController.js

#7131 included a typo, reading `DeviceID` from `$scope.currentDevice` instead of `deviceID`. Then currentDevice is added to `$scope.devices` with key undefined. I'm not sure how exactly the undefined entry appears in the PUT /rest/config body, but the effect is some device attributes are not saved. For example: changing the selected Shared Folders.
There is also an error reported from angular when it tries to render a duplicate device, since currentDevice now appears with key undefined and its own device ID key.
Edit a device's shared folders, save, ensure changes are persisted.

gui: fix device config not saving after changes

---

lib/db/db_test.go
lib/db/transactions.go

Due to a support request about a panic in drop I was looking at the db code once again. And did find *something*, though I don't see how it would cause a panic. It still is incorrect and I have a test to prove that :)
In the code updating the needs, the check only looks at whether a device needed the file with the old global (using `removedFV` which is confusing, but at this point equal to `globalFV` - that's not the problem). However the device might still need the file now, compared to the new global.

lib/db: Fix and improve removing entries from global (ref #6501)

---

lib/model/folder.go
lib/model/requests_test.go

`folder.scanSubdirs` is really long and has some ugly variable scopes, mainly regarding db snapshots. Separating the two phases of the scan (walking filesystem to get new/changed files and walking the db to find deleted and ignored files), as well as the folder-type specific shenanigans into separate functions creates nice scopes for db snapshots. And is more readable in my opinion.
There's no behaviour change in this PR at all - only code being moved around.

lib/model: Refactor folder.scanSubdirs into smaller parts

---

gui/default/syncthing/settings/advancedSettingsModalView.html

> The set of configurable options in the default settings dialog is somewhat limited; should these new pseudo-device/folders perhaps show up in the advanced config editor as well?
Did that.
Also moved all the folders and device under a folders resp. devices parent panel - that view got too crowded and thus hard to find things for my taste.

gui: Add defaults config to advanced menu (ref #7131)

---

lib/db/schemaupdater.go
lib/db/set_test.go
lib/db/structs.go
lib/model/folder.go
lib/model/folder_sendonly.go
lib/model/folder_sendrecv.go
lib/protocol/bep_extensions.go
lib/protocol/protocol_test.go

Setting `ModifiedBy` when marking a file as ignored, unsupported or must be rescanned is confusing (and wrong).

lib: Do not set ModifiedBy on meta only changes

---

cmd/syncthing/main.go

Got this on nightly upgrade:
```
Feb 11 06:16:28 homeserver syncthing[29565]: syncthing: error: unknown flag --logflags, did you mean "--log-flags"?
```
The variable is named `LogFlags`, so kong makes that `--log-flags`, while it was `-logflags` previously. Same for `LogFile`. While for `AuditFile` there is already a `name:"auditfile"`, so I did the same for the former too.
Also stumbled over one missing hyphen in the extra usage text.

cmd/syncthing: Fix hyphenated flag names (ref #7330)

---

cmd/syncthing/decrypt/decrypt.go
cmd/syncthing/main.go
lib/config/folderconfiguration.go
lib/model/model.go

This adds the `syncthing decrypt` subcommand that is used to
(offline-)decrypt or just verify the contents of an encrypted folder.
```
% syncthing decrypt --help
Usage: syncthing decrypt <path>
Decrypt or verify an encrypted folder
Arguments:
<path>    Path to encrypted folder
Flags:
-h, --help                Show context-sensitive help.
--to=PATH             Destination directory, when decrypting
--verify              Don't decrypt, just verify that the files are valid
--password=STRING     Folder password for decryption / verification ($FOLDER_PASSWORD)
--folder-id=STRING    Folder ID of the encrypted folder, if it cannot be determined automatically
--continue            Continue processing next file in case of error, instead of aborting
--verbose             Show verbose progress …
```

cmd/syncthing: Add decrypt subcommand

---

gui/default/syncthing/folder/editFolderModalView.html

As for right now, the External File Versioning does not support Cleanup
Interval. Therefore, the option should no be available at all when using
it.
Ref: https://forum.syncthing.net/t/16346

gui: Disable Cleanup Interval with External File Versioning as unsupported

---

lib/api/api.go
lib/api/mocked_model_test.go
lib/model/model.go
lib/model/model_test.go
lib/versioner/external.go
lib/versioner/util.go
lib/versioner/versioner.go

Attaches stderr (shortened if long) to the error when external versioner fails and adds a `*type* versioner: *operation*:` prefix to all errors returned for context (e.g. `simple versioner: get versions: permission denied`). 
All the change outside of `lib/versioner` is just noop boilerplate to use `errors.Is` in one test instead of fragile string testing.

lib/versioner: Improve error messages (fixes #7354)

---

gui/default/index.html
gui/default/untrusted/index.html

The button does nothing when the External Versioning is being used, so
it should not be displayed at all to avoid confusing the users.

gui: Hide non-functional Versions button when using External Versioning

---

lib/connections/quic_dial.go
lib/connections/quic_listen.go
lib/connections/quic_misc.go
lib/connections/quic_unsupported.go

This appears to work for me locally, even though there isn't a newer released version of quic-go yet, and the master branch of quic-go has references to a qtls package for 1.16 that is not pulled in here...

lib/connections: Allow QUIC with Go 1.16

---

gui/default/index.html
gui/default/untrusted/index.html

If there are no folders present, show only the "Add Folder" button, and
hide the "Rescan All" button. Only show the latter when at least one
folder exists.

gui: Hide the Rescan All button when no folders exist

---

cmd/stcrashreceiver/main.go
cmd/stcrashreceiver/sentry.go

Adds a new tag to distinguish panics from failures (events) in sentry. There's a lot of noise in sentry (also signal), and I'd like to have a way to see all failure events at a glance.

cmd/stcrashreceiver: Add tag for report type (crash/failure)

---

lib/scanner/blockqueue.go
lib/scanner/walk.go

A user reported that files failed to be scanned, however there was no errors in the web ui. Turns out Syncthing is able to stat the files, but not to open them for hashing. And errors while hashing aren't passed on to the model and thus do not turn up in the web UI. With this PR they now are passed on.
Came up in https://forum.syncthing.net/t/not-all-files-getting-scannned-synced/16365/8)

lib/scanner: Pass on errors while hashing

---

lib/config/folderconfiguration.go
lib/fs/basicfs.go
lib/fs/casefs.go
lib/fs/filesystem.go

This adds an url query like `id` internal member to `fs.Options`. The case-fs then creates a query-like options-string and uses that for caching in addition to the path.

lib/fs: Consider options in case-fs caching (fixes #7371)

---

gui/default/syncthing/core/syncthingController.js
gui/default/syncthing/folder/editFolderModalView.html
gui/default/untrusted/syncthing/core/syncthingController.js
gui/default/untrusted/syncthing/folder/editFolderModalView.html

Setting a custom path is already possible through config.xml, but using
the Edit Folder modal in the GUI resets it, unless Staggered Versioning
is being used. This commit removes this restriction, allowing custom
versioning paths for all types of versioning, except for external.
Ref: https://forum.syncthing.net/t/16357

gui: Allow setting custom path for all versioning except external

---

gui/default/syncthing/core/syncthingController.js
gui/default/untrusted/syncthing/core/syncthingController.js
gui/default/untrusted/syncthing/folder/editFolderModalView.html

Remove the redundant cleanupIntervalS code related to the External
Versioning, which does not use this functionality at all. Also, the
commit 5e9c7bc022040555d56860148352e5862737889f did not hide the
relevant GUI part for Untrusted GUI, so let us do it here too.

gui: Remove cleanupIntervalS leftovers from External Versioning (ref #7360)

---

gui/default/index.html
gui/default/untrusted/index.html

Move the "Last seen" field to the very top in the device information.
This way, if a device has disconnected unexpectly, we can quickly check
the time when it was last available. Right now, due to the very long
address field, it is usually necessary to scroll down in order to view
the "Last seen" field.

gui: Show "Last seen" at the top when device is disconnected (ref #7166)

---

gui/default/assets/css/overrides.css

Apply to table headers the same code as already used for table data.
This way, the headers will be either pushed to the next line, or cut
with an ellipsis if the single word is too long.

gui: Handle info labels that are longer than available space (fixes #944)

---

lib/fs/basicfs_copy_range_duplicateextents.go
lib/fs/basicfs_lstat_windows.go
lib/fs/debug_symlink_windows.go
lib/fs/util.go
lib/osutil/lowprio_windows.go
lib/syncthing/superuser_windows.go

Replace the old MSDN links with their counterparts on the Microsoft
Docs, and remove the hardcoded language codes to make the other ones
language-agnostic.

all: Fix Microsoft documentation links in code comments

---

etc/firewall-ufw/syncthing

The current ufw template only allows 22000/tcp and therefore blocks UDP based QUIC.

Allow QUIC traffic

---

build.go

Fixes #7199 by making build targets conditional. Currently only stupgrades is conditional.
Ran go run build.go test
N/A
N/A
Steven Eckhoff
steven.eckhoff.opensource@gmail.com

build: Make stupgrades build target conditional (fixes #7199)

---

lib/api/api.go

`insync` isn't a very descriptive name, thus proposing to change it to `restart-required` as brought up in https://github.com/syncthing/docs/pull/616. The currently incorrect docs can then be switched to reference `restart-required`.

lib/api: Rename config insync endpoint to restart-required

---

gui/default/syncthing/core/syncthingController.js
gui/default/syncthing/folder/editFolderModalView.html
gui/default/untrusted/syncthing/core/syncthingController.js
gui/default/untrusted/syncthing/folder/editFolderModalView.html

Main purpose: Less javascript - as in fewer or shorter lines :)
Secondary purpose: Don't clobber versioning parameters in case there's any that do not exist in the web UI, but do exist in the config.
Accidentally found a bug too: An incorrect default versioning parameter name.

gui: Folder versioning editing cleanup

---

lib/api/api.go
lib/api/api_test.go

This loosens the ‘is this localhost?’ check to include *.localhost host
names.
This allows for clearer (hence better) names to be used in browsers,
e.g. when accessing a remote syncthing instance ‘foo’ using a ssh port
forward, one can use foo.localhost to remind oneself which one is which.
💡 Without these changes, Syncthing shows a ‘Host check error’ when
pointing a browser at http://foo.localhost/, and with these changes, the
interface loads as usual.
The .localhost top level domain is a reserved top-level domain (RFC 2606):
> The ".localhost" TLD has traditionally been statically defined in
> host DNS implementations as having an A record pointing to the
> loop back IP address and is reserved for such use.  Any other use
> would conflict with widely deployed code which assumes this …

Treat *.localhost as valid localhost addresses

---

lib/protocol/protocol.go

This sprinkles `BufferPool.Put` in a lot of early returns due to errors. And there's one instance where we used the buffer after putting it back for debug logging.
I look at this because of an unusually large memory usage in the buffer-pool (see https://forum.syncthing.net/t/syncthing-using-all-ram-and-then-locking-up-the-system/16400). I don't expect the fixes in this PR to be the culprit for that usage though, as the errors are unlikely (marshalling, compression, ...).

lib/protocol: Always return buffers to the pool

---

lib/protocol/encryption.go
lib/protocol/encryption_test.go

Here's three minor changes for the encrypted filename handling in lib/protocol:
* The base32.Encoding object that encryptName and decryptName use is allocated once, instead of in every call. This also counts as DRY, since both functions necessarily use the same encoding.
* deslashify now does some light input validation. It used to strip out any occurrences of ".syncthing-enc", without requiring that string to even occur. It now checks for that string in the exact place where it should appear, and removes it only there.
* The tests cover more cases and more extensively check encryptName output.
I don't believe any of these changes address any existing issues; they just protect against potential future mistakes.

lib/protocol: Optimize encrypted filename handling + make it more strict

---

gui/default/syncthing/folder/editFolderModalView.html
gui/default/untrusted/syncthing/folder/editFolderModalView.html

Use textarea instead of input in the command field for the External File
Versioning. This way, it is possible to resize it at will, so that we
can input and view even a very long command in full, without it being
cut off and forcing us to scroll horizontally.
Tested in IE 11, Chromium 88, and Firefox ESR 78.7.1.
Before:
After:

gui: Allow to resize command in External Versioning

---

lib/protocol/encryption.go
lib/rand/random.go
lib/rand/securesource.go
lib/sha256/sha256.go
lib/signature/signature.go
lib/ur/usage_report.go

This reroutes some uses of crypt/rand through the buffered version in lib/rand for efficiency. It also removes its use from some benchmark functions, which aren't concerned with security.

all: Use crypt/rand through its buffered version, but not in benchmarks

---

Dockerfile
Dockerfile.buildx
README-Docker.md

Docker defaults to TCP for `EXPOSE` and `--publish` if no protocol is specified. This PR adds an UDP port mapping to allow QUIC transfer if host networking isn't used.
* https://docs.docker.com/engine/reference/builder/#expose
* https://docs.docker.com/config/containers/container-networking/#published-ports

Expose and publish 22000/udp for the docker container

---

gui/default/syncthing/core/syncthingController.js

After editing the folder default config, the tab was still hidden when
editing regular folder.

gui: Fix hidden Ignore Patterns tab for folder editing (fixes #7429)

---

cmd/syncthing/main.go

I noticed there wasn't any time-stamps in logs when running tests. Turns out the defaults set at runtime for command line flags are overriden with null values by kong. I fixed that using kongs "templating".

cmd/syncthing: Set flag defaults through kong vars

---

build.go
etc/linux-sysctl/30-syncthing.conf
etc/linux-sysctl/README.md
script/post-upgrade

This PR provides a sysctl configuration to increase the maximum receive socket buffer on Linux as suggest by https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size
The configuration gets placed in `/usr/lib/sysctl.d` according to [sysctl.d(5)](https://manpages.ubuntu.com/manpages/focal/en/man5/sysctl.d.5.html). The prefix `30-` causes the file to be applied early as the processing is done in lexicographic order. This should be low enough that configuration files of other packages can still overwrite this value.
I picked the `30-` prefix so that the file can be also used for manual installs in `/etc/sysctl.d` according to the older naming schema in Ubuntu Bionic:
>  Other packages install their files in the 30-*.conf range, to override system defaults.
I also modified the …

Package sysctl configuration to raise UDP buffer size on Linux

---

go.mod
go.sum
gui/default/syncthing/core/syncthingController.js
gui/default/untrusted/syncthing/core/syncthingController.js
lib/api/api.go
lib/db/benchmark_test.go
lib/db/db_test.go
lib/db/meta_test.go
lib/db/set.go
lib/db/set_test.go
lib/db/util_test.go
lib/model/folder.go
lib/model/folder_recvenc.go
lib/model/folder_recvonly.go
lib/model/folder_recvonly_test.go
lib/model/folder_sendonly.go
lib/model/folder_sendrecv.go
lib/model/folder_sendrecv_test.go
lib/model/folder_summary.go
lib/model/indexsender.go
lib/model/mocks/model.go
lib/model/model.go
lib/model/model_test.go
lib/model/testutils_test.go
lib/svcutil/svcutil.go

Another step towards better database error handling (#5907), fixing #7419: Now `db.FileSet.Snapshot` returns an error instead of panicking.  
Most of the diff is boilerplate of adding error returns all over the place. One larger change regards folder error handling: Previously we did not bubble errors consistently (as in already existing errors unrelated to this PR). Now we do need errors in `Serve` to shut the service down in case of fatal errors. I thus opted to bubble "folder-level" errors (as opposed to item level errors, e.g. errors scanning/pulling an item) up to the main loop in the service. That means the folder state is set with any error that reaches that point and isn't fatal. 
Existing unit tests pass and the UI still comes up - haven't done any manual testing beyond that.

lib: Return error from db.FileSet.Snapshot (fixes #7419, ref #5907)

---

cmd/syncthing/monitor.go
etc/linux-systemd/system/syncthing@.service
etc/linux-systemd/user/syncthing.service

There are timing parameters to catch frequent failure restarts in our monitor, and exit with an error. Systemd units also have such a mechanism by default, but with much less strict parameters that often allow infinite restart loops in case of DB problems. One example is this report, where a single user sent 3.5k events in a few hours: https://sentry.syncthing.net/syncthing/syncthing/issues/8679
Now the same restart parameters are used in the monitor as in the systemd service.

cmd/syncthing, etc: Consistent failure restart backoff

---

lib/protocol/encryption.go
lib/protocol/encryption_test.go

Use lib/sha256 to get the fast Minio hash, allocate the salt at init time. Benchmark results on Linux/amd64 with STHASHING=minio:
```
name       old time/op    new time/op    delta
FileKey-8    6.27µs ± 3%    4.58µs ± 3%  -26.91%  (p=0.000 n=20+19)
name       old alloc/op   new alloc/op   delta
FileKey-8    1.47kB ± 0%    1.17kB ± 0%  -20.58%  (p=0.000 n=20+20)
name       old allocs/op  new allocs/op  delta
FileKey-8      19.0 ± 0%      16.0 ± 0%  -15.79%  (p=0.000 n=20+20)
```

lib/protocol: Optimize FileKey

---

next-gen-gui/src/app/app.component.html
next-gen-gui/src/app/app.component.scss
next-gen-gui/src/app/app.component.ts
next-gen-gui/src/app/dashboard/dashboard.component.html
next-gen-gui/src/app/dashboard/dashboard.component.scss
next-gen-gui/src/app/services/system-config.service.ts

This adds a button in the top right that changes the config back to the
default theme.
Code wise, it takes the header that was previously a part of the
dashboard component and moves it to the app component, and then adds the
button there. Possibly the header should be a component of it's own, but
that's more of refactor that can happen separately I think.
The config change uses the new config API to just patch the relevant
setting.
I'm not going an automatic reload because 1) I don't want to figure out
how to do it correctly and 2) this doesn't work reliably anyway, as
for example the current gen GUI does a reload and ends up with
connection refused as the API service is still reloading...

next-gen-gui: Add button to restore default theme

---

cmd/syncthing/main.go
cmd/syncthing/options_others.go
cmd/syncthing/options_windows.go

This fixes #7446 by adding the `name:"no-console"` tag. I also moved it into a separate file with build tags, such that it only shows up on windows as before, because why not.

cmd/syncthing: Correct name of HiddenConsole flag (fixes #7446)

---

gui/default/syncthing/core/syncthingController.js
gui/default/untrusted/syncthing/core/syncthingController.js

Regression introduced in #7384: Previously we always created a new versioning object. That was changed on purpose to not clobber existing values, however the case that there's no existing object wasn't dealt with.

gui: Check if versioning object exists (fixes #7449)

---

cmd/strelaysrv/main.go
cmd/syncthing/main.go
lib/api/api_test.go
lib/config/config_test.go
lib/config/mocks/mocked_wrapper.go
lib/config/wrapper.go
lib/connections/limiter_test.go
lib/model/testutils_test.go

strelaysrv hung on startup because it uses the config wrapper, but the config wrapper needs to be running as a service. The comments on the constructor says this, but the returned type isn't actually a suture.Service so it's cumbersome and non-obvious to use. I fixed that by making it a service as I didn't see any reason for it being otherwise.

all: Make config.Wrapper an actual suture.Service (fixes #7451)

---

lib/config/folderconfiguration.go
lib/fs/basicfs.go
lib/fs/basicfs_lstat_windows.go
lib/fs/casefs.go
lib/fs/errorfs.go
lib/fs/fakefs.go
lib/fs/filesystem.go
lib/fs/walkfs.go
lib/fs/walkfs_test.go
lib/scanner/virtualfs_test.go

Fixes #7385 by only checking for infinite recursion if the junctions-as-dirs option is enabled.
Passing around options like I did in #7381 is tedious/repetitive. I thus changed the way options work from passing function `With...` style arguments to const/bitmask options. This allows knowing what options are active on any given filesystem, thus we don't need to pass options to the case- and walk-fs (and the case-fs can directly use option value for the key instead of constructing some arbitrary string).
One choice I am unsure about: I kept the variable length `opts ...FilesystemOptions` argument, even though multiple options can be passed by bitwise-or-ing options. I left that such that all `NewFilesystem` calls without options don't need to be changed to have an additional `, 0` (or …

lib/fs: Expose fs option on interface (fixes #7385, ref #7381)

---

lib/api/api.go
lib/api/confighandler.go

Just renaming the endpoint (#7402) isn't enough: The body also needs to change, both in key (`configInSync`) and reversing the value.

lib/api: Fix body of renamed config/restart-required endpoint (ref #7402)

---

cmd/strelaypoolsrv/main.go
lib/connections/structs.go
lib/db/observed.go
lib/events/events.go
lib/logger/logger.go
lib/model/folderstate.go
lib/model/model.go
lib/protocol/protocol.go
lib/stats/device.go
lib/stats/folder.go
lib/ur/usage_report.go

This truncates times meant for API consumption to second precision,
where fractions won't typically matter or add any value. Exception to
this is timestamps on logs and events, and of course I'm not touching
things like file metadata.
I'm not 100% certain this is an exhaustive change, but it's the things I
found by grepping and following the breadcrumbs from lib/api...
I also considered general-but-ugly solutions, like having the API
serializer itself do reflection magic or even regexp magic on returned
objects, but decided against it because aurgh...

all: Truncate some timestamps (fixes #7457)

---

lib/model/folder_sendrecv.go

The error at the end of `pullerIteration` isn't necessarily `nil`. The mistake isn't actually bad (i.e. no immediate release needed), because the only error that can occur there is a cancelled context, which will also be caught by the caller if the error is nil.

lib/model: Return correct error in puller-iteration (ref #7424)

---

lib/model/model.go

Adds a failure report if we drop a connection because of misconfigured encrypted folders (e.g. remote sends encrypt, local folder is not receive-encrypted, ...). Good to know whether that occurs often, i.e. if UX is bad.

lib/model: Send failure report on CC encryption check error

---

lib/fs/casefs.go

I can't think of any reason why we shouldn't test both the source and target path for case-conflicts, so I assume that was an oversight. It's not problematic in our usage, because in the puller we always check both source and target files against db (i.e. stat them) before renaming, but it still seems like the right/save thing to do.

lib/fs: Check both old and new path when renaming (fixes #7426)

---

gui/default/syncthing/folder/editFolderModalView.html
gui/default/untrusted/syncthing/folder/editFolderModalView.html

The trashcanClean input for the Simple File Versioning is currently
missing from the GUI due to a typo in the HTML code. Therefore, fix
the code to make it visible again. Until a new release, the user can
still edit the setting in config.xml manually.

gui: Fix missing trashcanClean in simple versioning

---

lib/protocol/encryption.go
lib/protocol/encryption_test.go

Without the invalid bit the untrusted device will complain that it gets a valid file without blocks.
Considering information available to the untrusted party: I consider it as a meta flag like `Deleted` that's necessary for syncing, thus ok to share.
I added a small unit test.

lib/protocol: Set invalid flag on encrypted file infos (fixes #7466)

---

gui/default/assets/css/overrides.css

Disabled options are currently barely distinguishable from enabled
ones. This changes their background to grey, following the Bootstrap
defaults already used for disabled \<select\>.
Before:
After:

gui: Use grey background for disabled options in form-control

---

lib/db/lowlevel.go
lib/db/schemaupdater.go
lib/db/set_test.go
lib/db/transactions.go
lib/model/fakeconns_test.go
lib/model/folder_sendrecv.go
lib/model/indexsender.go
lib/model/requests_test.go

Scenario (https://github.com/syncthing/syncthing/issues/7474#issuecomment-798881296):
> The reason is that we have an "efficiency" measure: We do not pull items that are not present at all locally and globally invalid or deleted. B sees valid items from A, thus their global is valid. C only sees invalid items from B, thus their global is invalid and they don't pull. B doesn't know about C's global, thus shows C as out of sync. The fix here is to always pull invalid files ("pull" as in create a local invalid entry too).
I adjusted `Need` to consider invalid files needed, and added a shortcut to the puller to send invalid files directly to the db. If at some point we do create a local file, that "trumps" the invalid file as usual (bumps the version of the invalid file, uninvalidates it, …

lib/db, lib/model: Allow needing invalid files (fixes #7474)

---

lib/protocol/protocol.go

The error messages have no info on which folders are affected, see e.g. #7466 
>  [J47TR] 13:37:50 INFO: Connection to BWYS6XV-XXXXXXXXXXXXXXXXXXXXXXX-RP6EJAB at 141.xxx.xxx.xxx:22000-xxx.xxx.xxx.xxx:5068/tcp-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256 closed: protocol error: index update: "9.syncthing-enc/45/F31BH51JPLO2N7T7MJ03AQ56Q0IIM1CTNE9A38NRNAOIU19NB5LGKF093B6M6D4U6SP5LKTN5NFA9GHN1PK4SK8LFD0K1R9R9S0CQKQQ86T1D7P1HG415P20JD299GNPTJPD54QSP0DKMF9T9D4SRO116INLTOC7DMIKUN1F6AED4D2P27NG": file with empty block list
And they aren't consistent in whether they include "receiving" and "message". I always added the former (the same method names exist for sending) and removed the latter.

lib/protocol: Improve messages when an error occurs receiving (ref #7466)

---

gui/default/syncthing/folder/editFolderModalView.html
gui/default/untrusted/syncthing/folder/editFolderModalView.html

Some previous refactor appears to have misunderstood Angular form
validation, breaking the help texts. This fixes that. Tested manually.

gui: Fix validation and help texts in versioning editor (fixes #7481)

---

cmd/syncthing/cli/operations.go
cmd/syncthing/cli/show.go

Split off from: https://github.com/syncthing/syncthing/pull/7454
> I removed the db reset operation: I don't think that should be so easily available. I also added a warning to the override operation.
And use the new/non-legacy endpoint to check if a restart is required due to config changes.

cmd/syncthing/cli: Remove db reset and adjust others

---

lib/model/model.go

The newly introduced method to get file availability providing a db snapshot didn't acquire the necessary pmut read-lock:
`fatal error: concurrent map read and map write`  
https://sentry.syncthing.net/share/issue/ab28509eab9742fa8995100d51bd5b0b/

lib/model: Add missing lock on availability func

---

.deepsource.toml
cmd/strelaypoolsrv/auto/noassets.go
lib/api/auto/noassets.go

This adds a couple of dummy asset files protected by the "noassets"
build tag. The purpose is that it should be possible for, for example,
CI tools and static analysis things to compile and analyze the source
tree without our custom asset generation step. Also makes `go test -tags
noassets ./...` work without building assets first.

lib/*/auto: Add noassets files

---

lib/model/folder_sendrecv.go

Current break does nothing (breaks the select).

lib/model: Actually break puller loop on context cancel

---

gui/default/untrusted/syncthing/folder/editFolderModalView.html

The current text gives an impression that we are currently using a
Receive Encrypted folder, even if we are not. Thus, make the current
text displayed only when the folder is in fact Receive Encrypted, and
add a new string to be displayed when using different folder types.

gui: Improve Receive Encrypted folder type requirements text

---

cmd/stcompdirs/main.go
cmd/stwatchfile/main.go
lib/fs/tempname.go
lib/ignore/ignore.go
lib/ignore/ignore_test.go
test/util.go

This is a mostly pointless change to make security scanners and static
analysis tools happy, as they all hate seeing md5. None of our md5 uses
were security relevant, but still. Only visible effect of this change is
that our temp file names for very long file names become slightly longer
than they were previously...

all: Remove crypto/md5

---

lib/osutil/rlimit_unix.go

There was a logic mistake, so the limit in question wasn't used. On my
macOS this doesn't seem to matter, the hard limit returned is 2^63-1 and
setting the soft limit to that works. However I presume that's not
the case for older macOSes since it was so nicely documented, so we
should still have this working. (10240 FDs should be enough for
anybody.)

lib/osutil: Fix raising max FDs on macOS

---

lib/model/model_test.go

This fixes a dropped error variable in the `lib/model` tests.
I verified that unit tests still passed.

lib/model: fix dropped test error

---

cmd/syncthing/decrypt/decrypt.go
lib/model/sharedpullerstate.go

This issue came up in https://forum.syncthing.net/t/how-to-restore-decrypt-an-encrypted-untrusted-folder/16520/11
If the untrusted devices is running windows, the `decrypt` tool errors on decrypting metadata. Because we wrote that metadata in native format, while the protocol code expects wire format (slashes).

all: Encrypted fileinfo trailer needs to be in wire format

---

lib/ur/usage_report.go

`blocksResult` can be `nil` at this point, e.g. due to already canceled context:
https://sentry.syncthing.net/share/issue/dea5883d4a654749a818d19ccbdf3448/
I assume the if check around setting it to nil will also satisfy the static analysis.

lib/ur: Prevent panic when blocksResult is nil (ref #7495)

---

cmd/strelaysrv/main.go

Increases throughput at the cost of more memory per connection

cmd/strelaysrv: Increase default strelaysrv network buffer size (fixes #7514)

---

lib/connections/service.go
lib/model/fakeconns_test.go
lib/model/mocks/model.go
lib/model/model.go
lib/model/model_test.go
lib/protocol/benchmark_test.go
lib/protocol/common_test.go
lib/protocol/encryption.go
lib/protocol/mocks/connection.go
lib/protocol/protocol.go
lib/protocol/protocol_test.go

Fixes #7509 by adding a method to the connection to set new folder passwords. This means that any connection may become (partly) encrypted. Thus there's no longer two separate factory methods, but every connection is a `encryptedConnection`.
The passwords on the connection are (re-)set when sending cluster-configs, meaning when a new connection is added, when a new folder is added or when a folder changes.

lib: Handle adding enc folders on an existing conn (fixes #7509)

---

lib/model/model.go
lib/model/model_test.go

When a receive-only folder is added, we don't have the folder token yet. However that is required to ensure a correct (consistent when there's more than 1 device) password. Thus we need to drop and reestablish the connection to ensure the remote sends the cluster-config with the token.

lib/model: Reset conn when enc token is missing (fixes #7198)

---

etc/linux-systemd/system/syncthing@.service
etc/linux-systemd/user/syncthing.service

https://github.com/syncthing/syncthing/commit/587c89d9798df451d1dced957196d9491a442e2f introduced a systemd unit based restart burst limit, but the directives have been added to the wrong section. StartLimitIntervalSec and StartLimitBurst need to be located in the `[Unit]` section of the systemd unit to be effective: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StartLimitIntervalSec=interval
To be true, I didn't test it, but the fact is trivial and well documented in the systemd documentation (see above), and it is a pretty common mistake as it's not intuitive with other restart-related directives being located in the `[Service]` section. Also it has changed with systemd v230, `StartLimitInterval` being renamed to `StartLimitIntervalSec` and both moved from …

etc: Fix start-limit parameters location in systemd units (ref #7439)

---

lib/db/set.go

Less bad, because it can only be triggered using `/rest/debug/file` and no-one uses that (except if I tell them to :| ).

lib/db: Don't panic debugging an inexistent file

---

README-Docker.md

Raises the UDP buffer size limit similar to #7417 for docker deployments if the host network isn't used.
I did not test it but it is explicitly stated in the docker documentation:
https://docs.docker.com/engine/reference/commandline/run/#configure-namespaced-kernel-parameters-sysctls-at-runtime

docker: Raise UDP buffer size in example

---

lib/protocol/encryption.go

Set the encrypted version counter to the sum of all real counters, instead of using `time.Now()`. Thus all trusted device agree on the version and sending an index for an already existing file-version to an untrusted device doesn't change their version, which did confuse their remote completion.

lib/protocol: Deterministic encrypted version (fixes #7533)

---

README-Docker.md

Example about how to spin-up syncthing container using docker compose.
Created my current Syncthing instance `docker-compose.yml` like this.

Docker compose example

---

lib/db/db_test.go
lib/db/lowlevel.go
lib/db/schemaupdater.go
lib/db/transactions.go

#7026 is about unspecific `key not found` errors on sentry. The only one that still gets events is https://sentry.syncthing.net/share/issue/270bbc681e3943f7a121268553e6f2e5/, and that's what I am addressing here:
`panic: repairing sequences: filling Blocks: key not found`
When repairing sequences all local files are deserialized, and apparently sometimes the blocks are indirected (or look like it), but theirs no entry for the hash. Instead of failing db repair and thus making the db entirely broken, the defective file info is now removed from the db - to be rescanned later.
Some related changes: I moved checking/repairing globals out of `recalcMeta` into `getMetaAndCheck`. Having that happen as a side effect of recalculating metadata is plain confusing (and I probably wrote that code :) …

lib/db: Handle indirection error repairing sequences (fixes #7026)

---

gui/default/syncthing/transfer/neededFilesModalView.html

Remove the animation due to its excessive CPU usage, especially when a
large number of files is being downloaded and listed at the same time.
Also, remove the stripes, as they serve no purpose in the now-static
progress bar.

gui: Remove download animation from Out of Sync Items modal (fixes #3322)

---

cmd/syncthing/main.go

This was inadvertently changed in the flag migration.

cmd/syncthing: Rename --conf back to --config (fixes #7549)

---

lib/db/observed.go
lib/model/model.go
lib/model/model_test.go

Remove expired pending folders without relying on timing. Also changed the update function signature to take a `ObservedFolder` instead of `string, string`, such that one can't switch label and id by mistake.

lib/db, lib/model: Refactor removing expired pending folders

---

lib/fs/casefs.go
lib/fs/util.go
lib/model/folder.go
lib/osutil/traversessymlink.go
lib/protocol/encryption.go
lib/protocol/encryption_test.go
lib/scanner/virtualfs_test.go
lib/scanner/walk.go

This fixes #7557, where we use the protocol method `IsEncryptedParent` with a native path, while protocol operates on `/`-delimited paths only - thus it fails. Now this helper method accepts a list of path components, thus requiring the caller to use the proper method to split paths. And I created such a method for native paths, living in `lib/fs/utils.go` and replaces various calls to `strings.Split(...` with that.

lib: Prevent using protocol method with native path (fixes #7557)

---

build.go
script/deb-post-inst.template
script/post-upgrade

Reuses the bits from https://github.com/syncthing/syncthing/pull/7552 that aren't related to nfpm (which requires go1.16), to fix #7548. Fixing as in not using `--deb-systemd` that was broken upstream, and doesn't get any attention, but restarting services in a script of our own. This is also a behaviour change, as `--deb-systemd` enables the service on install. I personally like that change: I dislike programs that enable their daemons automatically (thought that seems to be standard practice).
No testing yet: I was too lazy to install ruby or build/download the docker - will test after CI built something.

build: Do not use --deb-systemd with fpm (fixes #7548)

---

lib/api/api_auth.go

This enables usage of the audit log to e.g. automatically block remote addresses from connecting after repeated login failures, as requested [on the forum](https://forum.syncthing.net/t/can-the-syncthing-web-gui-report-authentication-errors/16642/11).
Manual verification of the audit log contents when the API authorization is enabled.
**TODO**: No docs PR prepared yet, waiting on feedback whether this is the right approach or if there are any other security implications.

lib/api: Log the remote address on login attempts.

---

lib/connections/quic_listen.go

Fixes https://github.com/syncthing/syncthing/issues/7551
Probably another dependency triggered us building with the new quic, which apparently uses a new interface now. This change adds the method required for that to the stun wrapper conn.

lib/connections: Add SyscallConn() to quic conn (fixes #7551)

---

lib/api/api_auth.go

This is intended as an enhancement for #7560, to make failed login attempts more easily visible even when the audit log is disabled.  Inspired by [this forum discussion](https://forum.syncthing.net/t/can-the-syncthing-web-gui-report-authentication-errors/16642).  The log level is kept to Info to avoid message panels in an already connected GUI.

api: Log warnings on API authorization failures.

---

lib/model/model.go

When a folder is removed we remove the marker. But there may be things
stored in it that have usefulness past the lifetime of the folder in
Syncthing, in particularly the folder ID marker for encrypted folders.
This changes the behavior to remove empty markers (or if the marker's a
file...) but otherwise rename it to `.stfolder.removed-$timestamp` so
that it's out of the way but the contents aren't lost.

lib/model: Don't remove non-empty .stfolder

---

gui/default/syncthing/core/pathIsSubDirDirective.js

Parses are only used when the input field is changed, thus not when we update the value from javascript. Change it to be a validator, which is used whenever the value changes.

gui: Fix folder path validation (fixes #7379)

---

gui/default/syncthing/core/syncthingController.js

We watch folder label to update the path if it hasn't been modified yet. However if the same folder is opened again, the folder label doesn't change and thus the watch isn't triggered. Now `$scope.currentFolder` is cleared when the modal is closed, thus the watch gets trigered.

gui: Unset current folder on modal close (fixes #7584)

---

cmd/syncthing/cli/client.go
cmd/syncthing/cli/config.go
cmd/syncthing/cli/errors.go
cmd/syncthing/cli/main.go
cmd/syncthing/cli/operations.go
cmd/syncthing/cli/utils.go

Instead of immediately exiting when encountering an error setting up the API client, the error is stored and returned if the api client is used. That ensures that the error does not come up if no operation involving the API is happening (like just querying `--help`).
To do so I added an interface for the api client and an `errorAPIClient` type that returns the error from setup when on all of it's methods.

cmd/syncthing: Don't fail early on api setup error (fixes 7558)

---

gui/default/syncthing/core/pathIsSubDirDirective.js

The validation now can also kick in when the path is empty, which produced a JS error.

gui: Handle empty path in validation (ref #7379)

---

lib/api/api_test.go
lib/connections/service.go
lib/util/utils.go

In order to fix issue #7600, we use the existing config commit listener in the connections service to check for new devices. If any exist, we signal on a new channel for the connection loop to stop sleeping.
There is technically a small edge case between the channel check and the config copy where if the config is updated during that time we would end up with two dialDevices immediately following each other. This is extremely low probability, so not addressed currently.
1) Run syncthing in the background
2) Use api to add new device (POST to `/rest/config/devices`)
3) See from GUI that device is immediately connected to.
I'd be happy to make any changes needed. Thanks!

Trigger connection loop on config device addition (fixes #7600)

---

gui/default/index.html

The Remote Devices names now get cut off as folder names and This Device already do, if they don't fit inside the header.

gui: cut off long remote device names (fixes #7592)

---

gui/default/index.html

Disable the Versions button when the folder is paused, because it does
not work, i.e. the versioned files are not loaded. The folder needs to
be unpaused to actually be able to view the versioned file list.

gui: Disable versions button when folder is paused

---

lib/db/schemaupdater.go
lib/db/set_test.go
lib/db/transactions.go
lib/db/util.go
lib/model/folder.go
lib/model/folder_recvenc.go
lib/model/folder_recvonly.go
lib/model/folder_sendonly.go
lib/model/folder_sendrecv.go
lib/model/indexsender.go
lib/model/model.go
lib/model/requests_test.go

Unfortunately the solution for #7474 implemented in #7476 created a new, more severe problem: Files that should be synced, aren't: #7608. I couldn't come up with a way to fix #7474 without introducing this regression that doesn't add a lot of complexity. Thus I reverted that change and thus re-introduce #7474. As that is only a "presentation issue" that's clearly the more desirable issue to have.
Most of the diff here is due to the migration needed to resolve issues for users already affected by #7608. As I needed a file info batch in this migration, I moved the `fileInfoBatch` from model to db.
I introduced a new unit test reproducing #7608 and removed the test for #7474.

lib: Revert needing invalid files (fixes #7608, ref #7476)

---

lib/fs/basicfs_watch_eventtypes_inotify.go
lib/fs/basicfs_watch_eventtypes_kqueue.go
lib/fs/basicfs_watch_test.go

I wrote a test to check whether the watcher picks up modification time only changes or not (due to https://forum.syncthing.net/t/syncthing-not-syncing-modification-time/16729) - and inotify didn't. I fixed that. Lets see how it works out on other OSes.

lib/fs: Watch attrib. changes on inotify for mod. time

---

build.go
go.mod
go.sum
lib/config/wrapper.go
lib/connections/service.go
lib/discover/manager.go
lib/events/events.go
lib/logger/logger.go
lib/model/folder_summary.go
lib/model/model.go
lib/protocol/protocol.go
lib/relay/protocol/packets.go
script/prune_mocks.go
tools.go

This reuses [conventional go build machinery](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module) to simplify build.go, as suggested by @imsodin at #7552. `go generate` just works, without having genxdr or counterfeiter installed. `go mod tidy` no longer removes counterfeiter.
There's more work to be done on this front, in particular wrt. protobufs, but I figured I'd send a PR to test the waters and see if you want to move in this direction at all.

build: List go:generate tools in tools.go

---

lib/connections/quic_listen.go

Marten from the quic project mentioned a few more methods required by quic from the underlying connection in https://github.com/syncthing/syncthing/issues/7636#issuecomment-835482900

lib/connections: Add more methods to the quic conn wrapper

---

lib/connections/quic_listen.go

Removes an incorrect comment and adds references to where quic uses said methods.

lib/connections: Correct comments on quic wrapper type

---

go.mod
go.sum
lib/syncthing/syncthing.go

The way we start the main supervisor currently is against upstreams recommendation - we just needed the error returned from `Serve`. Now that this is also available on `ServeBackground`, this PR makes use of that.
> Calling ServeBackground will CORRECTLY start the supervisor running in a new goroutine. It is risky to directly run
> 
> ```
> go supervisor.Serve()
> ```
> 
> because that will briefly create a race condition as it starts up, if you try to .Add() services immediately afterward.

lib/suture: Use ServeBackground to start main supervisor

---

cmd/strelaysrv/testutil/main.go
lib/connections/relay_listen.go
lib/relay/client/client.go
lib/relay/client/methods.go
lib/relay/client/static.go

While investigating and changing stuff related to how relay failures are handled and logged, I noticed that the invitations channel is handled badly on service restart: When creating a relay client, one might or might not provide the invitation channel. If one is not provided, it is closed when the service exits. That means the service can't be restarted, while the suture service model requires services to be restartable.
I removed the invitations channel from `NewClient`, as the ambiguity of providing one or not needlessly creates the opportunity to close the channel in the wrong place. Now it's clear that invitations belong to the `lib/relay/client` package and no-one ought to close it from outside.
Two related changes I made:
- Refactor the relay listener service loop to directly get …

all: Refactor relay invitations

---

lib/relay/client/dynamic.go
lib/relay/client/static.go
lib/svcutil/svcutil.go

Sutures logging provides a lot of info, but is not very user friendly. I thus created a custom events hook that prints user-friendly messages when a service fails and prints everything else at debug level.
And when playing around with loosing connection while relaying is enabled, I got flooded with info logging from the dynamic relay client: It tried to connect to every known relay and printed the same error about not being able to connect over and over again. I changed all of that to debug logging. A failed relay will still print one info level line due to the service terminating.

lib/relay, lib/svcutil: Improve service logging (fixes #7580)

---

lib/connections/service.go

The relay listener exits with an error when the internet connection is lost. This makes the supervisor of all listeners back off. Which usually isn't a problem, as the other listeners don't exit. However if they did, they wouldn't be restarted either, as the supervisor in backoff state doesn't restart any services, not just the failed service. That's clearly not the intention here. Thus I wrapped each listener into their own supervisor, and add that to the main connections supervisor instead of a single supervisor for all listeners.
In addition I think 10 minutes backoff times is too long. In the same scenario of loosing wifi, we might not start listening after reconnecting for 10 minutes. Trying to re-establish listening every minute seems more reasonable to me.

lib/connections: Separate listener supervisors and lower backoff time

---

lib/model/model.go
lib/model/model_test.go

An attempt at making the errors about encryption mis-configuration more understandable, i.e. the goal is that the user is more likely to understand what is wrong and what they can/need to change to get it working.

lib/model: Improve encryption cluster-config errors

---

lib/connections/service.go

Fixes sloppyness in #7644 that causes https://sentry.syncthing.net/syncthing/syncthing/issues/11040/?environment=Candidate&referrer=alert_email
Will release the rc.2 asap - pulling the release isn't necessary: This only happens when reconfiguring to remove a listening protocol.

lib/connections: Actually remove listenerSupervisor (ref #7644)

---

cmd/uraggregate/main.go

After this is merged and rolled out we should do:
`DELETE FROM performance WHERE day > '2020-08-11'` and let it re-aggregate;
Fixes #7661

cmd/uraggregate: Cap memory size at a petabyte (fixes #7661)

---

README-Docker.md

Basically reverts https://github.com/syncthing/syncthing/pull/7536
Fixes #7668 
Shame on me for trusting the documentation of docker...
https://github.com/moby/moby/issues/30778

Remove sysctl parameter from docker readme

---

lib/db/lowlevel.go
lib/db/schemaupdater.go
lib/db/set.go
lib/model/indexsender.go
lib/model/model.go

~~Adds more debugging to analyse https://github.com/syncthing/syncthing/issues/7649~~
Still contains the debugging, but mainly now a fix for #7649.
The diff has too little content to see what the problem is, so here is a larger section:
```diff
cfg, ok := m.cfg.Folder(folder.ID)
if ok {
folderDevice, ok = cfg.Device(deviceID)
}
if !ok {
indexSenders.remove(folder.ID)
if deviceCfg.IgnoredFolder(folder.ID) {
l.Infof("Ignoring folder %s from device %s since we are configured to", folder.Description(), deviceID)
continue
}
delete(expiredPending, folder.ID)
of.Label = folder.Label
of.ReceiveEncrypted = len(ccDeviceInfos[folder.ID].local.EncryptionPasswordToken) > 0
if err := m.db.AddOrUpdatePendingFolder(folder.ID, of, deviceID); err != nil {
l.Warnf("Failed to persist pending folder entry to …
```

lib/model: Don't use empty folder cfg for index sender (fixes #7649)

---

lib/scanner/walk.go

Another debugging PR for https://forum.syncthing.net/t/german-umlaute-like-aou-seems-to-make-trouble/16804/12

lib/scanner: Do not drop all not-exist-errors and debug logging

---

cmd/uraggregate/main.go

So this actually uses the index.
Seems postgres can't work out that it can use an index scan if something is done with the indexed field.
Even if I disable seq scans on the optimiser, it still picks a seq scan.
Beware, I think this is equivalent, but off by one errors are super hard, hence give it a proper review.

cmd/uraggregate: Optimise queries

---

lib/model/fakeconns_test.go
lib/model/folder_recvonly_test.go
lib/model/folder_sendrecv_test.go
lib/model/model_test.go
lib/model/requests_test.go
lib/model/testutils_test.go

There's one test bugfix on `addFakeConn`, where `device1` was hardcoded in the cluster-config instead of using the argument `dev`. The rest is adding `folderID` arg to `addFakeConn` to use instead of the hardcoded `"default"`, wrapping `Index`/`IndexUpdate` in `must` to see the test-failure cause immediately and a few other minor test improvements.
Apparently none of the current tests is affected by this, but one on a local branch is. And this change would add a lot of clutter to that diff, and is useful/correct in general - thus filing it separately here.

lib/model: Fix addFakeConn and other test improvements

---

lib/fs/basicfs_windows.go
lib/fs/casefs.go
lib/fs/fakefs.go
lib/fs/folding.go
lib/fs/folding_test.go
lib/fs/mtimefs.go
lib/scanner/walk_test.go

This one was somewhat tricky; macOS does normalization-insensitive lookups so Lstat will find a file regardless of the normalization on disk vs in lookup, but out caseFS is more sensitive.
Initially I thought we should simply normalize in caseFS on macOS, but that means we return
normalization issues as case conflicts. That then means we should allow renames over case conflicts but that's risky as macOS can also have case sensitive filesystems.
Instead I changed checkCase to handle "not found" from the case insensitive lookup in the same manner as "not found" from Lstat. This works and I don't see any obvious negative side effects...

lib/fs: Handle normalization on macOS (fixes #7677)

---

lib/fs/folding.go
lib/fs/folding_test.go

#7678 changed UnicodeLowercase to do normalization, but missed the first return statement.

Fix UnicodeLowercaseNormalized on lowercase NFD

---

cmd/strelaypoolsrv/gui/index.html

Add a few minor grammatical/stylistic fixes. Use `https` instead of
`http` in the MaxMind link in the footer.

cmd/strelaypoolsrv: Fix minor grammar, use https in links

---

cmd/syncthing/cli/main.go
go.mod
go.sum

Makes stdin handling less magical, and picks up an update to recli which fixes handling TextUnmarshal interface on structs when field is a non-pointer.

cmd/syncthing/cli: Update recli, fix stdin handling (fixes #7685, fixes #7673)

---

lib/config/config_test.go
lib/config/folderconfiguration.go

We already do not send any progress updates by not registering files when pulling, but don't reflect that in the config and thus don't announce it correctly to remotes. As those are dropped in the end anyway it shouldn't be of any consequence except for a few pointless messages sent.

lib/config: Set DisableTempIndexes to true on receive-encrypted

---

lib/model/model.go
lib/model/requests_test.go

Two untrusted devices connect and send requests like normal ones, i.e. including hashes, even though those hashes are garbage. We then try to validate, which obviously fails, and thus trigger a forced rescan. That then leads to the locally changed items as seen in #7699.

lib/model: Fix incoming request on receive-enc (fixes #7699)

---

build.go
lib/model/model.go

This adds a `-long` flag to `build.go` to run all the slow test, i.e. not set `-short`.
To my surprise running with `-long` did result in a test failure, luckily just a cosmetic one: When I improved the encryption error messages, I swapped to error messages.  
We could run the coverage tests with `-long`, then it won't require much more CI time, but we at least run those tests on on platform (linux, the others being a lot slower). Long tests took 2m7s on my machine.

build, lib/model: Add flag to run tests without -short and fix failure

---

lib/model/model.go
lib/model/model_test.go

Checks if the introducing device encrypts data to the introduced device, and if it does, don't share the folder. The user must enter the password to encrypt the data as well.
I extended an introducer test to cover this scenario.

lib/model: Don't share with introduced device if encrypted (fixes #7724)

---

lib/model/folder_recvonly.go
lib/model/folder_recvonly_test.go

This condition based on only our own ID being in the version vector of our own, locally changed item is flawed. Not only if the folder type changes, but also in general: We might just never have had the global item (with other IDs), and directly have scanned our own file. Now we get the global file, check if that is locally changed, then indeed the file only exists here, if not check if what we have is equivalent to the global file to shortcut and otherwise just proceed normally (reset our version vector to make pulling resolve everything).
I added a unit test reproducing #7708

lib/model: Fix reverting when version has only our own ID (fixes #7708)

---

lib/model/model.go
lib/model/model_test.go

I was testing some encryption related UI changes (not this PR) when suddenly all hell broke loose: The trusted side treated received encrypted file indexes like normal files. Reason is that the change in #7198 is just plain broken, luckily it only matters if you have encrypted folders both ways (folder1: A untrusted <-> B, folder2: A <-> B untrusted). That is uncommon enough that no-one seems to have run into it yet - yeii for not cleaning up old test folders on test setups.
The completely broken part is returning early from `generateClusterConfig` with `passwords == nil`, and then ignoring that error in `AddConnection`, thus going ahead and calling `Connection.SetPasswords` with a nil map.
I basically reverted #7518 and to keep #7198 fixed, I added a new check to `CommitConfiguration`: …

lib/model: Fix passwords on receive-enc needing token (ref #7518)

---

lib/model/folder_recvonly_test.go

Adds the fake connection required since #7689 to the test newly introduced in #7714. This slipped through, as both were PRs at the same time and were built without the respective other one.

lib/model: Fix test introduced in #7714 failing due to #7689

---

lib/model/model.go

When a unknown/new folder is later accepted in the UI, and that folder is paused on the remote, we start sending indexes. The remote then drops the connection, because they don't like getting indexes for a paused folder. Solution: Don't add the index info to the index handler when the folder is paused (same as for regular, already known folders).

lib/model: Fix indexhandling for new folders paused on remote

---

lib/model/folder_recvonly_test.go
lib/model/model_test.go
lib/model/testutils_test.go

`TestNeedMetaAfterIndexReset` failed pretty consistently on the coverage test and adding a bit of sleep in the test that's reproducible. Turns out the the test is only racy, because it doesn't do what it is supposed to, due to a fault test helper: `testCompletion` uses hardcoded values instead of the arguments. I had a quick look if there's more such blunders and didn't find any, however renamed `needSize` to `needSizeLocal` to make the name more closely represent what it does.

lib/model: Fix wrongly hardcoded arguments in test helper

---

lib/db/lowlevel.go
lib/db/transactions.go

This changes the GC mechanism so that the first pass (which reads all
FileInfos to populate bloom filters with block & version hashes) can
happen concurrently with normal database operations.
The big gcMut still exists, and we grab it temporarily to block all
other modifications while we set up the bloom filters. We then release
the lock and let other things happen, with those other things also
updating the bloom filters as required. Once the first phase is done we
again grab the gcMut, knowing that we are the sole modifier of the
database, and do the cleanup.
I also removed the final compaction step.

lib/db: Use a more concurrent GC (fixes #7722)

---

lib/db/transactions.go

There's been a case of those errors reported to the forum recently. Unfortunately no cause has been determined. I want to know if that happens frequently. If it does, we should consider adding mitigation/self-repair measures. Or find a cause and fix that, but until that happens mitigation would be good anyway. The only way to fix it now is removing the folder (resetting db).

lib/db: Add failure reports to failures iterating over hashes

---

lib/db/observed.go
lib/model/model.go

Error handling around pending entries in the db is inconsistent: Some errors are dropped, some logged at info level, some at warning level. And all errors are passed on to the caller, but still many are logged inside the method (above debug level, at debug level is always fine), while a few are logged by the caller.
I see two reasonable ways to handle this: 1. Don't ever return errors from the database. The concerned information isn't important, so reporting nothing or success when there's an error won't cause serious problems. There will just be some information missing. If the problem is serious (db corruption), some vital process will error out and produce logging/take syncthing down. 2. Do return errors, such that we can report errors on the API, but always let the caller handle the …

lib/db, lib/model: Improve error handling on pending items

---

gui/default/assets/lang/lang-en.json

Fixes a typo introduced in #7712.  That happened after the last release, but has been included in the `-rc.1` version and propagated to transifex.

gui: Fix typo in new tooltip.

---

gui/default/assets/css/overrides.css
gui/default/syncthing/device/editDeviceModalView.html

Trying to avoid one source of confusion when using QR codes to mutually add devices, where the local ID / QR code is needed but the user ended up with the remote device's ([forum link](https://forum.syncthing.net/t/great-technology-bad-user-interface/16781/4?u=acolomb)).
The "Show QR" button shows a different representation of the device ID input field contents, so move it right next to that one.  There are now two possible incarnations because in the `editingExisting` case, the read-only device ID is not actually an HTML input.  Treat both cases as Bootstrap input groups with attached button.
Note this removes access to the "Show QR" function when any other tab than "General" is active.  That is intentional to better guide the user about which device ID will be shown (not the local one). …

gui: Move the QR code button next to device ID in editDevice modal.

---

lib/db/schemaupdater.go
lib/db/set_test.go
lib/db/structs.go
lib/db/transactions.go

There still too much bogus remote out-of-sync reports floating around on the forum:  
https://forum.syncthing.net/t/list-of-out-of-sync-items-is-empty/16906  
https://forum.syncthing.net/t/folders-up-to-date-but-stuck-in-syncing-with-empty-out-of-sync-items-v2/16850  
And a bit more staring at the db code turned up a bug - yeiii :)
My initial hypothesis was, that update code uses `.copy()` on `FileVersion` objects that might get modified. However I didn't find a scenario where that leads to a bug. Still added the `.copy()` in the PR.
More staring made me notice a weird condition regarding `globalChanged` at the end of `VersionList.pop`: There's even a comment trying to explain it, with emphasis on "trying" - it is just incorrect as shown by the added testcase. The global is always changed …

lib/db: Fix accounting bug when dropping indexes

---

script/codecov-upload.sh

Coverage CI jobs are failing since a while (curl missing - huh?). They still show up as successful, because the failure is within a bash command substitution, and those errors aren't passed on. I think the `bash <(curl something)` is ugly anyway (and has been shown as unsafe recently), so I'd prefer having that script in the repo and manually upgrading it (basically whenever uploading breaks, hopefully almost never).

build: Add codecov upload script to repo

---

lib/connections/connections_test.go
lib/connections/service.go
lib/model/fakeconns_test.go
lib/model/model_test.go
lib/protocol/encryption.go
lib/protocol/mocks/connection.go
lib/protocol/protocol.go

When a connection is closed (config change, pausing/resuming, error, ...) it may take a while for a connection to be re-established (up to a minute by default). When just running unsupervised that's fine, but when setting something up in the UI or debugging it's annoying. Now the connection service tracks the lifetime of established connections and triggers dialling when it's closed.
That requires removing all keys in `nextDialAt` for a device. To simplify that, I refactored it to have a (typed) double map instead of a composed `*deviceID*/*addr*` string key.

lib/connections: Trigger dialer when connection gets closed

---

lib/connections/service.go

https://sentry.syncthing.net/organizations/syncthing/issues/11957
Mistake made in #7753: Map isn't initialized.

lib/connections: Missed map init in nextDialAt (ref #7753)

---

gui/default/index.html

The only way to discover that there is a modal showing info on the listeners/discovery is to hover them. That's unnecessarily confusing, see e.g. https://forum.syncthing.net/t/android-cant-find-truenas-and-vice-versa/16977/10 . Now they look like normal links (same as e.g. the device id)

gui: Make listener/discovery modal more discoverable

---

lib/api/api.go

Currently it uses the "current version" which may be -1 (disabled),
resulting in blank performance data in the support bundle. The intention
was never to couple this to the anonymous usage reporting policy, it's
merely a way to get statistics about the device into the support bundle.

lib/api: Always include usage reporting data in support bundle

---

lib/fs/casefs.go

Slightly refactors the case-filesystem with the main goal of setting the expiry after calling `DirNames`. As that can take a long time for large directories and slow systems (see https://github.com/syncthing/syncthing-android/issues/1630). As the expiry needs to be set while holding the cache lock, I moved the entire node creation including calling `DirNames` into `newCaseNode` - thus the `sync.Once` isn't needed any more.

lib/fs: Set expiry after DirNames in case-fs

---

lib/model/folder.go
lib/model/folder_recvenc.go

First two commits are the same as on https://github.com/syncthing/syncthing/pull/7726: Replaces the `batchAppendFunc` being passed around as a function argument with a dedicated `scanBatch` type that has an `append` method.
The main change fixing #7740 is, that we now compare every new, scanned file with the current global file. If they are equivalent, the global file info is used, thus saving the detour over syncing to resolve the conflict (that isn't actually a conflict). This also benefits initial scan scenarios, where both sides have the data: If files are scanned after the index is received from the remote, they will immediately be in sync (instead of looking out of sync until all of the scan is done and a sync happens to resolve the conflicts).

lib/model: Compare all items with global on scan (fixes #7740)

---

build.go

Remove dead code - no longer used temporaryBuildDir.
It was added in #4253 and no longer necessary after #5384.
Dead code detected by gometalinter.
Ran `./build.sh` and `./build.sh test`. Everything still works.
n/a
n/a

build: Remove no longer used temporaryBuildDir (dead code).

---

lib/protocol/protocol.go
lib/protocol/protocol_test.go

When a message becomes bigger after compression, the uncompressed version can be sent instead to not waste bandwidth and receiver CPU time. I've been keeping track of compressed message sizes and I've found it extremely common that metadata messages become larger from compression; it's only the longer ones that actually benefit (so maybe the threshold should be increased too).
I've merged the various send*Message methods so that there's less copying of compressed messages and less reallocation when compression fails. The cost of that is having to serialize the header of the uncompressed version unconditionally.

lib/protocol: Write uncompressible messages uncompressed

---

lib/model/folder_recvenc.go

We correctly remove the directory, but never update the db -> kick off a scan on the removed directories.

lib/model: Scan removed dirs when reverting recv-enc (fixes #7706)

---

lib/model/model.go

Adds a config verification step that checks that no folder type is changed from/to receive-encrypted.

lib/model: Prevent folder-type change from/to encrypted (fixes #7704)

---

lib/connections/service.go

This improves/extends the mechanism to dial changed devices introduced in https://github.com/syncthing/syncthing/pull/7604: So far it covers newly added devices and addresses. It does not cover resumed devices, as they are still subject redial delays (e.g. when quickly pausing/unpausing a device to trigger a reconnect). Now new or previously paused are added to `dialNowDevices`, thus not subject to any delays.

lib/connections: Fully dial resumed devices

---

lib/connections/quic_dial.go

Before this patch, IPv4-compatible addresses (`::ffff:aaa.bbb.ccc.ddd`)
may be used if a `quic6://some.domain:port` is specified and both IPv4 and
IPv6 addresses exist for that domain name.
Fixes #7809
Follow "steps to reproduce the problem" as described in #7809, and check if I got connections with normal IPv6 addresses.

lib/connections: Resolve IPv6 for quic6:// peers

---

lib/connections/quic_dial.go
lib/connections/quic_listen.go
lib/connections/quic_misc.go

This patch determines the network (udp, udp4, udp6) for QUIC URLs in a more explicit way than strings.ReplaceAll.

lib/connections: switch statement to get the QUIC network

---

gui/default/syncthing/settings/advancedSettingsModalView.html

The GUI section is one of the least commonly accessed sections, which is accessed. Maybe accessed once, on first install. Compared to other sections, such as Folders, Devices, or Options, it shouldn't be more important.
Currently, it fills the screen (especially 100% zoom resolutions less than 2K (with FHD you still need to scroll around, with HD, and HD+, both still common resolutions, it's 1.5-2 pages of scrolling).  
When accessing the menu, it's almost always more practical to first collapse the GUI section, since scrolling takes more time.
Collapsing the GUI tab by default removes the need to collapse it, removing annoyance and saving time, while not removing much discoverability. Perhaps even making it not so welcoming for users, and dumber password managers, to start changing …

advancedSettings: Collapse all, inc. GUI section, on open.

---

cmd/stcrashreceiver/main.go
cmd/stcrashreceiver/sentry.go

Sentry (and my mailbox) is getting flooded with database corruption events because they can since a while occur as failures instead of panics, and the fingerprint isn't sanitized on failures. Now it is.

cmd/stcrashreceiver: Sanitize failure report fingerprints

---

lib/model/folder_recvonly.go

Reported here by @tomasz1986. We try to delete a file that doesn't exist, which unsurprisingly fails.

lib/model: Don't try to delete deleted item on revert

---

lib/protocol/bep_extensions.go
lib/protocol/encryption.go
lib/protocol/encryption_test.go

Possible root cause of https://github.com/syncthing/syncthing/issues/7861 / https://forum.syncthing.net/t/untrusted-device-never-finishes-syncing-very-high-memory-usage/17187.
Files predating the variable block sizes might have `RawBlockSize` set to 0. Which we handle in `.BlockSize`, however when encrypting we add `blockOverhead` to `RawBlockSize`, ending up with a block size below `MinBlockSize` but not `0`. Which then uses tons of memory when hashing a large file with such a small block size.
I both corrected `encryptFileInfo` to set a valid `RawBlockSize` and made `BlockSize` return `MinBlockSize` if it encounters a raw value smaller than `MinBlockSize`, to cover any file infos already affected by this issue.

lib/protocol: Ensure correct blocksize on enc. fileinfo (ref #7861)

---

lib/stun/stun.go

https://sentry.syncthing.net/organizations/syncthing/issues/11568
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x12cf8e4]
goroutine 320 [running]:
github.com/syncthing/syncthing/lib/stun.New(0x1942ad8, 0xc000434000, 0x1926670, 0xc000115200, 0xc0000d4238, 0x0, 0x0, 0x0)
github.com/syncthing/syncthing/lib/stun/stun.go:111 +0x2e4
github.com/syncthing/syncthing/lib/connections.(*quicListener).serve(0xc000115200, 0x19308a8, 0xc0000de700, 0x0, 0x0)
github.com/syncthing/syncthing/lib/connections/quic_listen.go:98 +0x365
github.com/syncthing/syncthing/lib/svcutil.(*service).Serve(0xc0000d07c0, 0x19308a8, 0xc0000de700, 0x192c698, 0xc0001977c0)
github.com/syncthing/syncthing/lib/svcutil/svcutil.go:125 +0xa3 …
```

lib/stun: Prevent nil deref when naming service

---

lib/syncthing/time_android.go

Go doesn't use the system timezone on android.
https://forum.syncthing.net/t/is-it-possible-to-use-local-time-in-logfile-instead-of-utc-on-android/17199
https://github.com/golang/go/issues/20455

lib/syncthing: Set system timezone on android

---

gui/default/syncthing/core/connectivityStatusModalView.html

Right now, small modals are used for Listeners and Discovery. However,
especially in the case Discovery, quite a lot of information is crammed
into the modal, which basically fills it completely in order to fit the
long sentences and long error messages. Because of this, change the type
of the modal to "large", so that everything has more space to fit more
comfortably.
Before:
After:

gui: Use large modals for Listeners and Discovery

---

lib/model/folder.go
lib/model/model.go

The scan call may block for a long time - no need to let the API caller wait for it to finish when the actual operation, setting ignores, has finished.

lib/model: Do not wait for scan when setting ignores

---

go.mod
go.sum

Updating x/sys so that this project supports go 1.17.
More context: https://github.com/Homebrew/homebrew-core/pull/83413

build: Update x/sys to fix new issue in go 1.17

---

lib/connections/quic_dial.go
lib/connections/quic_listen.go
lib/connections/quic_misc.go
lib/connections/quic_unsupported.go

I checked and the quic folks already supported go1.17 since beta, so I'd say it's fairly save to stop guarding against future go releases (and forgetting to adjust it on every go release - I would have forgotten if not for the PR from the brew people). While at it I also bumped the lower constraint to go1.15 which is the oldest they support on the quic version we have (not that it matters much as we don't support go1.14 anyway).

lib/connections: Remove future go build constraints on quic

---

lib/ur/failurereporting.go

lib/ur: Fix panic build goroutines for failures

---

lib/fs/tempname.go
lib/fs/tempname_test.go

Micro-optimizations for fs.TempName. The test has also been made more strict.
There's at least one change that should be reviewed carefully, which is that the long filename handling now hashes the basename of a file instead of a full path. Since f4372710bfa57abd9ae22d8de6d22c38c25b01eb also changed the hash, I reckoned this should be safe to do.
I was aiming for a lower allocation rate, but got a nice speedup too:
```
name             old time/op    new time/op    delta
TempNameLong-8     4.05µs ± 4%    3.76µs ± 3%   -7.13%  (p=0.000 n=10+10)
TempNameShort-8     635ns ± 2%     440ns ± 3%  -30.76%  (p=0.000 n=9+10)
name             old alloc/op   new alloc/op   delta
TempNameLong-8       672B ± 0%      560B ± 0%  -16.67%  (p=0.000 n=10+10)
TempNameShort-8      128B ± 0%       96B ± 0% …
```

lib/fs: Optimize TempName + some cosmetic changes

---

README.md

Jump to docs source is now possible, when you already know where you want to go. The usual Ctrl-f source for docs doesn't work (most repos keep their docs in the same repo, so PRs can/must include docs for the changes.

Add a link to docs source.

---

lib/model/folder_recvonly.go

chore: fix typo in folder_recvonly.go

---

gui/default/index.html

Currently, the dismiss button is displayed as the first of the three
buttons. However, the most common action that the user wants to do when
sharing a new folder is to add it on a different device. Because of
this, the add button should be displayed first as the most prominent of
the three. The ignore button is the opposite of the add button, and also
results in a parmenent action, hence it makes sense to lump the two
together. Thus, the dismiss button should be moved to the last place as
an alternative to the two main actions, when the user is yet unsure what
they want to do with the notification.
Before:
After:

gui: Move dismiss button after add/ignore buttons

---

lib/discover/local.go
lib/protocol/hello.go
lib/relay/protocol/packets.go

Here's some small optimizations to buffer allocations. They remove a public method that was used only once.

Buffer allocation optimizations

---

cmd/stfindignored/main.go
cmd/syncthing/cli/utils.go
cmd/syncthing/main.go
cmd/syncthing/monitor.go
lib/api/api_statics.go
lib/beacon/broadcast.go
lib/db/lowlevel.go
lib/db/schemaupdater.go
lib/db/transactions.go
lib/ignore/ignore.go

Also two typos. These were all found by golangci-lint or DeepSource.

all: Unused args, retvals, assignments

---

lib/model/model.go
lib/syncthing/syncthing.go

Instead of data (could be read as user data), use metadata.
Alternatively, s/metadata/internal data/g
Needed to read it twice to be 'ok we are not going to restore a snapshot today'. A casual user might panic.
Not tested, change in string.

logmsg: Clarify 'Cleaning data for folder'

---

lib/db/backend/backend.go

Clarifies the code: having a pointer to a Once suggests that it is shared with other objects, but it never is.
Also removed a useless anonymous function.

lib/db/backend: Inline sync.Once in releaser

---

gui/default/syncthing/core/syncthingController.js

The list of unshared devices is built from deviceList(), which sorts
the result.  But the shared devices are listed in undefined order from
the unsorted currentFolder.devices array.  Apply the same sorting
after building the array used in the dialog.
Manual GUI verification.

gui: Sort already shared devices in edit folder modal (fixes #7940).

---

build.go

See #7445 .
https://github.com/go-ole/go-ole/pull/223 has been merged. 
Once https://github.com/shirou/gopsutil/pull/1132 is merged, we should be able to target windows/arm and windows/arm64.

Add windows/arm{,64} support

---

lib/tlsutil/tlsutil.go
lib/tlsutil/tlsutil_test.go

Another micro-optimization: a UnionedConnection takes at most two allocations to set up, but it can be done in one.

lib/tlsutil: Allocate UnionedConnection in one go

---

gui/default/syncthing/settings/settingsModalView.html

This change removes the superfluous quotes in the settings/settingsModalView.html file. The issue was discussed in #7853.
The HTML was previously invalid however, web browsers fix the incorrect code when rendering it. The code runs successfully after the change and the results in the UI are not affected.

settings/settingsModalView: Removed superfluous quotes (fixes #7853)

---

go.mod
go.sum
lib/db/lowlevel.go

SipHash was introduced in #6826 because maphash wasn't available in Go 1.13. Syncthing now requires 1.14, so we can drop one dependency. In Go 1.17, maphash is also significantly faster than SipHash (see /restic/restic#3519: restic also hashes SHA-256s).
The go.mod file has some unrelated changes from go mod tidy. Maybe there should be a CI test for that?

lib/db: Replace SipHash with hash/maphash

---

.deepsource.toml

Those patterns didn't actually match everywhere as they look like they do.

build: Fix deepsource test & exclude patterns

---

lib/rand/random.go
lib/rand/random_test.go
lib/rand/securesource.go

rand.secureSource.Uint64 no longer allocates. rand.String uses a strings.Builder. Benchmark results on linux/amd64:
```
name            old time/op    new time/op    delta
SecureSource-8    69.1ns ± 3%    51.7ns ± 3%   -25.21%  (p=0.000 n=20+10)
String-8          2.66µs ± 2%    1.95µs ± 1%   -26.61%  (p=0.000 n=10+10)
name            old alloc/op   new alloc/op   delta
SecureSource-8     8.00B ± 0%     0.00B       -100.00%  (p=0.000 n=20+10)
String-8            288B ± 0%       32B ± 0%   -88.89%  (p=0.000 n=10+10)
name            old allocs/op  new allocs/op  delta
SecureSource-8      1.00 ± 0%      0.00       -100.00%  (p=0.000 n=20+10)
String-8            33.0 ± 0%       1.0 ± 0%   -96.97%  (p=0.000 n=10+10)
```

lib/rand: Optimizations

---

gui/black/assets/css/theme.css
gui/dark/assets/css/theme.css

Because of a disappearing border, the navigation tabs jump when being
hovered or focus. Thus, instead of removing the border, let us change
its colour to transparent, which preserves the layout.
This is the jumping I'm talking about :smile:. If you look closely, you'll see the tabs keep moving a little bit.
https://user-images.githubusercontent.com/5626656/134932288-cc9fe75b-0762-4450-b82c-d6a9dc8cb71a.mp4

gui: Fix jumping nav tabs in black and dark themes

---

lib/config/folderconfiguration.go

The current detection is flawed, because it looks for a few specific
file systems like "msdos" or "fat" to set the mtime window, while in
reality Android seems to report names like "fuseblk", which can stand
for fat, ext4, or even f2fs.
At the moment, we set the mtime window only for a few known names used
for the fat filesystem. With this change, we take a safer approach of
always setting the time window unless we explicitly detect file systems
like ext2/ext3/ex4, which are known not to experience issues with moving
timestamps on Android.

lib/config: Always set mtime window to 2 on Android unless ext detected (ref #7963)

---

gui/default/syncthing/folder/editFolderModalView.html

This reverts commit cca17f53064b1b567a3275eadd5467af1e810f47.
Using textarea instead of input makes it possible to enter new lines,
which then are added to config.xml as `&#xA;`. This breaks the whole
script, because these characters are passed to the command line as `\n`.
Therefore, the script should rather remain a single-lined input field.

Revert "gui: Allow to resize command in External Versioning (#7410)"

---

gui/default/syncthing/core/syncthingController.js

Currently, the default sorting of the file list in the Restore Versions
modal in both case sensitive, and it also does not distinguish between
files and folders. With this change, which uses a slightly modified code
from the fancytree itself (with added folder prioritisation), the sort
becomes case insensitive and also always places folders on top. This is
to make it behave more similar to what file managers do in the commonly
used operating systems (including popular Linux desktop environments).

gui: Use case insensitive sort with folders on top in Restore Versions

---

lib/model/folder_sendrecv.go
lib/model/sharedpullerstate.go

I initially intended to never shortcut files on receive-encrypted folders, making them go through the entire copier-puller-finisher routines (first commit). However since this is a single write, and a failure will just result in a locally modified file, i.e. cannot propagate to other devices, I believe writing directly to the file for speed-up over the entire copier-puller-finisher routine is warranted.

lib/model: Write trailer when shortcutting on recv-enc (fixes #7991)

---

lib/protocol/encryption.go
lib/protocol/encryption_test.go

Adds a check to the en/decryption test to ensure sequences are preserved and preserves the sequence on decryption (was already on encryption).

lib/protocol: Preserve sequence decrypting fileinfos (fixes #7994)

---

lib/model/queue.go
lib/model/queue_test.go

By truncating time.Time to an int64 nanosecond count, we lose the ability to precisely order timestamps before 1678 or after 2262, but we gain (linux/amd64, Go 1.17.1):
```
name                      old time/op    new time/op    delta
JobQueuePushPopDone10k-8    2.85ms ± 5%    2.29ms ± 2%  -19.80%  (p=0.000 n=20+18)
JobQueueBump-8              34.0µs ± 1%    29.8µs ± 1%  -12.35%  (p=0.000 n=19+19)
name                      old alloc/op   new alloc/op   delta
JobQueuePushPopDone10k-8    2.56MB ± 0%    1.76MB ± 0%  -31.31%  (p=0.000 n=18+13)
name                      old allocs/op  new allocs/op  delta
JobQueuePushPopDone10k-8      23.0 ± 0%      23.0 ± 0%     ~     (all equal)
```
Results for BenchmarkJobQueueBump are with the fixed version, which no longer depends on b.N for the amount of …

lib/model: Optimize jobQueue performance and memory use

---

gui/default/syncthing/device/editDeviceModalView.html

In the Add Device modal dialog, there is a list of up to five locally discovered device IDs.  Choosing from them is a great time-saver, but identifying which is the wanted one requires comparing (partial) device ID strings.  Especially when integrating a new device into an existing cluster, one can more easily remember the identicon shown on one of the existing cluster devices.  Make it easy to recognize that device in the discovered ID list by replacing the bullet points with the corresponding identicon.
Open the Add Remote Device modal and admire the beautifully listed identicons.  Requires not yet added remote devices on the local network.

gui: Display identicons for discovered device IDs.

---

cmd/syncthing/cli/main.go
cmd/syncthing/cmdutil/util.go
cmd/syncthing/decrypt/decrypt.go
cmd/syncthing/main.go
lib/locations/locations.go
lib/syncthing/utils.go
test/cli_test.go
test/override_test.go
test/util.go

Consistently use double dashes for option flags, as the CLI help output does as well.
Fix typos:
* `-conf` :arrow_right: `--config`
* `-data-dir` :arrow_right:  `--data`
* `-verify.` :arrow_right: `--verify-only`
Applies also to tests running the syncthing binary for consistency.  Other binaries (`stevents`, `stsigtool`, `build.go`, `stdisco`, `strelaysrv`) are not affected as they output single-dash options in their own CLI help.
No functional changes, only affects help strings and uses options already parsed correctly in test, just now with two dashes.
Related: https://github.com/syncthing/docs/pull/692

Normalize CLI options to always use two dashes.

---

lib/api/api_auth.go

This is just cleanup, except that the stdlib method also recognizes case variants of the string "Basic " for closer conformance to RFC 7235.

lib/api: http.Request.BasicAuth instead of custom code

---

cmd/syncthing/main.go
lib/api/api_test.go
lib/connections/connections_test.go
lib/discover/global_test.go
lib/syncthing/syncthing_test.go
lib/syncthing/utils.go
lib/tlsutil/tlsutil.go

Just some cleanup around the `LoadOrGenerateCertificate()` function.  It should adhere to the given arguments instead of delegating to the `locations` package.  This is technically a no-op change, because the only place calling this function passes exactly the same values.
I've chosen to keep the arguments although in principle the `locations` package already provides the desired paths.  Many other functions here take a path as argument and mix it with some `locations.Get()` values.  If you think the latter should be used consistently, I will switch over to that method as far as possible.
Also a no-op is to factor out the second half of that function and reuse it in `cmd/syncthing`.  That previously had its own independent (but matching) values for certificate name and lifetime, which is …

lib/syncthing: Clean up / refactor LoadOrGenerateCertificate() utility function.

---

lib/api/api_auth.go
lib/api/api_auth_test.go
lib/api/confighandler.go
lib/config/config_test.go
lib/config/guiconfiguration.go

This is part of the solution for #8021, but makes sense as an isolated change.
What hash is used to store the password should ideally be an implementation detail, so that every user of the GUIConfiguration object automatically agrees on how to handle it.  That is currently distribututed over the confighandler.go and api_auth.go files, plus tests.
Add the `SetHasedPassword()` / `CompareHashedPassword()` API to keep the hashing method encapsulated.  Add a separate test for it and adjust other users and tests.  Remove all deprecated imports of the bcrypt package.
`TestGUIPasswordHash()` added for the new config API.  Adjusted `lib/api/api_auth_test.go` to the different `authBasic()` function signature.  All tests still passing.

lib/config: Move the bcrypt password hashing to GUIConfiguration

---

cmd/syncthing/cmdutil/options_common.go
cmd/syncthing/cmdutil/options_others.go
cmd/syncthing/cmdutil/options_windows.go
cmd/syncthing/generate/generate.go
cmd/syncthing/main.go
lib/syncthing/utils.go

The `--generate` option for the `syncthing serve` subcommand allows creating an initial configuration and keypair given a home / config directory.  This functionality is mirrored to a new subcommand `syncthing serve` with the following extensions:
1. Do not require a directory to be specified, but use the default location.
2. Accept the standard `--home` or `--config` options to override the default location, as used in the `serve` subcommand.
3. Accept `--gui-user=...` argument to preconfigure the generated config for GUI authentication.  This overwrites the setting should the `config.xml` file already exist.
4. Accept `--gui-password=...` argument to preconfigure the generated config for GUI authentication.  This overwrites the setting should the `config.xml` file already exist.  The …

cmd/syncthing: Implement generate as a subcommand with optional API credential setting (fixes #8021)

---

cmd/strelaysrv/main.go
lib/connections/tcp_listen.go
lib/nat/service.go
lib/nat/structs.go

The locking protocol in nat.Mapping was racy:
* Mapping.addressMap RLock'd, but then returned a shared map, so the lock didn't do anything.
* Operations inside Service.{verifyExistingMappings,acquireNewMappings} would lock the map for every update, but that means callers to Mapping.ExternalAddresses can be looping over the map while the Service methods are concurrently modifying it.
The Service methods now lock the map once and release the lock only when done.
Also, subscribers no longer get the added and removed addresses, because none of them were using the information. This was changed for a previous attempt to retain the fine-grained locking and not reverted because it simplifies the code.

lib/nat: Fix race condition in Mapping

---

lib/relay/client/static.go

Allow easier running of relay servers behind proxies.
I added `relay://www.google.com:443/` and looked in Wireshark, and saw SNI.

lib/relay: Send SNI when the address is a host name (fixes #8014)

---

lib/api/api.go
lib/config/wrapper.go
lib/connections/limiter.go
lib/connections/service.go
lib/discover/manager.go
lib/model/model.go
lib/model/progressemitter.go
lib/nat/service.go
lib/ur/failurereporting.go
lib/ur/usage_report.go
lib/watchaggregator/aggregator.go

... and remove 8/10 implementations, which were no-ops. This saves code and time copying configurations.

lib/config: Decouple VerifyConfiguration from Committer

---

build.go
lib/config/config_test.go
lib/config/wrapper.go
lib/ignore/ignore.go
lib/ignore/ignore_test.go
lib/osutil/replacingwriter.go

Write config.xml and .stignore with appropriate line endings.

lib/config, lib/ignore: Write Windows line endings (fixes #7115)

---

gui/default/syncthing/device/removeDeviceDialogView.html
gui/default/syncthing/folder/removeFolderDialogView.html

Remove the embedded CSS that prevents the lines from wrapping, resulting
in device and folder names being hidden on small screens.
The old code prevents wrapping, which cuts the lines on mobile. I'd say this is very bad, because the folder path and/or device names end up being hidden.

gui: Allow text wrapping in remove folder/device modals

---

lib/fs/filesystem.go
lib/fs/util.go
lib/fs/util_test.go

Two independent optimizations to path handling. Benchmark results on Linux/amd64, Go 1.17.1:
name                old time/op    new time/op    delta
TraversesSymlink-8    8.86µs ± 3%    8.53µs ± 4%  -3.79%  (p=0.000 n=18+20)
name                old alloc/op   new alloc/op   delta
TraversesSymlink-8    1.06kB ± 0%    1.06kB ± 0%    ~     (all equal)
name                old allocs/op  new allocs/op  delta
TraversesSymlink-8      15.0 ± 0%      15.0 ± 0%    ~     (all equal)
name                          old time/op    new time/op    delta
WindowsInvalidFilenameValid-8     875ns ± 1%     150ns ± 1%  -82.84%  (p=0.000 n=9+9)
WindowsInvalidFilenameNUL-8       276ns ± 4%     121ns ± 3%  -56.26%  (p=0.000 n=10+10)
name                          old alloc/op   new alloc/op   delta …

lib/fs: Path handling optimizations

---

gui/default/assets/css/overrides.css
gui/default/index.html

Some users have experienced unexpected behavior with unknowingly having the `ignoreDelete` option enabled (#8050). This adds a simple warning at the bottom of the expanded folder view, on folders with the setting enabled.
Uses the `text-danger` class to make the text red.

gui: Warning in folders with ignoreDelete enabled (fixes #8050)

---

lib/model/deviceactivity.go
lib/model/deviceactivity_test.go
lib/model/folder_sendrecv.go

This way, we don't need a second loop over the Availabilities to remove the selected item. This might improve performance, although I didn't measure. It certainly saves some code.

lib/model: Return index from deviceActivity.leastBusy

---

cmd/syncthing/cli/main.go
cmd/syncthing/cli/pending.go
cmd/syncthing/cli/show.go

…the CLI (fixes #8068)
Simple wrapper for an API call.
fixes #8068
All tests pass.

cmd/syncthing/cli: Add command to show pending devices/folders (fixes #8068)

---

lib/model/folder_summary.go
lib/syncthing/auditservice.go
lib/syncthing/verboseservice.go
lib/watchaggregator/aggregator.go

We see occasional panics in complex tests when the main service's context is closed, causing the events channel to be closed. If this happens during the running of the processUpdate() on the next loop the select may choose either of the branches. If the select processes the events channel closing first, it leads to the following panic, due to the ev.Data being nil (due to ev being an empty struct).
```
github.com/syncthing/syncthing/lib/model.(*folderSummaryService).processUpdate(0xc000150c80, {0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, {0x0, 0x0}})
/home/runner/go/pkg/mod/github.com/rafttio/syncthing@v0.0.0-20211207134221-cceb0242bfe8/lib/model/folder_summary.go:255 +0x557
github.com/syncthing/syncthing/lib/model.(*folderSummaryService).listenForUpdates(0xc000150c80, {0xf8ebe8, 0xc000424e40}) …
```

lib: Fix panic due to closed event subscriptions on shutdown

---

cmd/stdiscosrv/apisrv.go

- Log certificate error
- Add `X-Tls-Client-Cert-Der-Base64` header for Caddyserver, so that
Caddyserver could set `{tls_client_certificate_der_base64}` in the header
Support deploy discovery server behind Caddyserver
- Add `header_up X-Tls-Client-Cert-Der-Base64 {tls_client_certificate_der_base64}`  directive in Caddyfile
- Check discovery server debug log, and check Syncthing client discovery status

cmd/stdiscosrv: Support deploying behind Caddyserver

---

gui/default/syncthing/core/syncthingController.js

Use indexOf instead of startsWith to make the now translatable theme
names appear correctly in IE11. This also prevents console log error
spam in the browser. The same problem was previously reported in #6940.

gui: Use indexOf instead of startsWith for IE11 compatibility (ref #6940)

---

cmd/syncthing/generate/generate.go
cmd/syncthing/main.go
cmd/syncthing/monitor.go

For usage in installers or similar, a pre-populated `config.xml` file should be able to get parsed, validated and expanded with default values when calling `syncthing generate` (or the deprecated `--generate` option).  That currently only happens when an option to override the GUI credentials was passed.  Doing it always makes it easier to override some options using a minimal `config.xml` and validate it before running `syncthing serve` for the first time.
This includes some code cleanup and a fix for misleading info log messages from the monitor process.
* `syncthing serve --home=/tmp/foo1 --upgrade-check ; ls /tmp/foo1/` creates no `config.xml` and therefore doesn't claim "We will skip creation of a default folder on first start".
* `syncthing serve --home=/tmp/foo2 ; ls /tmp/foo2/` …

cmd/syncthing: Always update config.xml with generate subcommand (ref #8090)

---

cmd/syncthing/cmdutil/options_common.go
cmd/syncthing/generate/generate.go
cmd/syncthing/main.go
cmd/syncthing/monitor.go
lib/config/config.go
lib/syncthing/utils.go

The conditions during `syncthing generate` (or the first run of `syncthing serve`) do not necessarily reflect what network ports will be available later on.  The new command line option allows to skip the probing heuristics to use currently unused port numbers for the GUI and listen addresses in a freshly created `config.xml`.  Instead the default ports are simply applied, avoiding unexpected firewall alert messages on Windows at least.
This is based on (and includes the commits of) #8098.  Same origin issue #8090, but the two independent changes should not be munged into one commit.
With a running Syncthing instance on the default ports, `syncthing --home=/tmp/foo --skip-port-probing` now fails because it cannot bind the default addresses, instead of choosing random different ports. …

cmd/syncthing: Add --skip-port-probing (fixes #8090)

---

gui/default/assets/css/overrides.css

Currently, language names are always displayed in two columns and sorted
from left to right first, and from top to bottom next. This commit
changes the sort order to go from top to bottom first, and only then
move to the next column.
Also, on small screens, display the languages in a single column only,
which allows for language names not to be truncated as much as they are
right now.

gui: Sort language names vertically and don't truncate on small screens

---

lib/model/model.go
lib/protocol/protocol.go

Switch the returned data type for the /rest/system/connections element
"total" to use only the Statistics struct.  The other fields of the
ConnectionInfo struct are not populated and misleading.
Make sure the JSON attributes are lowercased as documented.
Manual API and GUI verification.
https://github.com/syncthing/docs/pull/708

lib/model: Remove bogus fields from connections API endpoint (fixes #8103)

---

.github/workflows/update-docs-translations.yaml

Move the automation which ran elsewhere to an action, where it's visible and can be debugged / tended to by other people than me. Tested in my fork, did what it was supposed to there.

github: Add docs update workflow

---

build.go

When GOBIN is set, 'go install' cannot install cross-compilied binaries.
To satisfy cross-compilation, it's necessary to add the '-o' to build
target, otherwise 'go build' will discarding the resulting objects when
compiling multiple packages.
~~To satisfy cross-compilation~~.
To satisfy cross-compilation for 'all' target.

build.go: add an option to specify '-o' option when build

---

gui/default/syncthing/core/syncthingController.js

https://forum.syncthing.net/t/broken-web-gui-with-typeerror-cannot-set-properties-of-undefined-setting-errors/17840

gui: Handle folder missing in model on error event

---

go.mod
go.sum
gui/default/syncthing/core/aboutModalView.html
lib/protocol/protocol.go
lib/protocol/protocol_test.go

The LZ4 package we used was archived, and linked to this one as a replacement.
- Unit test to verify that decompression of old data works, and that new compressed data is identical to how it was before. (I can't say if this is a guaranteed property, but it seems to hold for this replacement at least).
- Also ran against an older binary and verified stuff can be synced in both directions, which seems like it should cover it.

lib/protocol: Switch to a newer lz4 package

---

gui/default/syncthing/core/syncthingController.js

Reported here: https://forum.syncthing.net/t/default-ignores-wont-save-7428/17912
Nothing is shown when editing existing defaults. They are shown when adding a new folder.
Fix for #7530 and RC material.

gui: Fix loading default ignores (ref #7530)

---

lib/protocol/protocol.go
lib/protocol/protocol_test.go

The new lz4 library doesn't need its output buffer to be the maximum size, unlike the old one (which would allocate if it weren't). It can take a buffer that is of a smaller size and will report if compressed data can fit inside the buffer (with a small chance of reporting a false negative). This patch uses that property by requiring compressed data to be at most n-n>>5 = .96875*n bytes long for n input bytes.

lib/protocol: Require at least 3.125% savings from compression

---

cmd/stdiscosrv/main.go

The intention was that if no peers are given, we shouldn't start the
listener. We did that anyway, because:
- splitting an empty string on comma returns a slice with one empty
string in it
- parsing the empty string as a device ID returns the empty device ID
so we end up with a valid replication peer which is the empty device ID.
(For the avoidance of doubt, this is not a security issue. Empty device ID doesn't mean we'd accept any replication peer, it means the remote device would need to present precisely an all-zeroes device ID. ("Empty" is perhaps not the best name, it's really the "zero" device ID.))

cmd/stdiscosrv: Don't start replication listener without peers (fixes #8143)

---

gui/default/syncthing/core/syncthingController.js
gui/default/syncthing/core/validDeviceidDirective.js
gui/default/syncthing/device/editDeviceModalView.html

Currently, there is no distinction between adding "new" and "pending"
devices. For this reason, the user is always presented with a list of
"nearby devices" to choose from. This commit adds such distinction to
the code, and in the case of "pending" device, both the device ID is
made read-only and the nearby devices list is hidden.
As a by-product of the function rename and clean-up, this commit also
hides the non-functional "remove" button that is shown when editing
device defaults.

gui: Make device ID read-only and hide "nearby devices" when adding a new pending device (fixes #8083)

---

gui/default/index.html

The ignoreDelete warning code originally comprised of two sentences,
which in total were much longer than the current one. Because of that,
some additional fixes were added to make it present itself better, e.g.
white-space was set to normal to allow for text wrap on narrow screens,
and the help link was moved to a new line to make sure both the anchor
and the question mark always stayed together.
However, the code fixes remained despite the final text being much
shorter than the original. Therefore, remove the unnecessary white-space
formatting, and also move the help link right next to the warning. This
makes it clear that the link is related to this particular warning when
both it and the ignore patterns warning are displayed at the same time.
Ref: …

gui: Fix ignoreDelete warning formatting (ref #8054)

---

lib/fs/basicfs_watch_eventtypes_darwin.go

Add the `FSEventsChangeOwner` event to the `permEventMask` on Darwin, which was previously 0. This allows Syncthing to handle chmod events, which were previously ignored. 
Fixes #7924
Create a shared folder, add a file, chmod, check that permissions are synced within FSWatcherDelay window
[Script](https://gist.github.com/yyogo/62d41e0013fd38e8cfce4cc5cae04b06)
Tested on macOS Monterey 12.1 21C52 (x86_64)

lib/fs: Handle permission change events on macos (fixes #7924)

---

lib/db/benchmark_test.go
lib/db/db_test.go
lib/db/meta_test.go
lib/db/set.go
lib/db/set_test.go
lib/db/util_test.go
lib/model/folder.go
lib/model/folder_sendrecv_test.go
lib/model/model.go
lib/model/model_test.go
lib/model/testutils_test.go

We don't replace the `FileSet` on folder restart (as that's a potentially heavy/slow operation), but the filesystem is stored in it and thus any changes to the filesystem won't apply. I don't see any good reason to keep the filesystem in state in the db/fileset, it also removes a lot of boilerplate from tests.
Fixes #7850

lib/db, lib/model: Remove filesystem state from FileSet (fixes #7850)

---

lib/model/folder_sendrecv.go

There's a ton of info in these lines, but not which device caused the error. Which is/was annoying for debugging https://forum.syncthing.net/t/kdbx-files-cannot-be-synced/17944/15

lib/model: Print device when a block request fails

---

lib/api/api.go
lib/model/model.go

Some cleanup of comments regarding the API which were noticed while researching https://github.com/syncthing/docs/pull/727.

lib/api: Fix comments for endpoint parameters

---

gui/default/syncthing/core/syncthingController.js
lib/config/config.go
lib/config/migrations.go

Staggered File Versioning used to have its own cleanInterval that
controlled how often file versions were cleaned. Nowadays, there is a
seperate setting called cleanupIntervalS responsible for the cleanup,
which applies to all File Versioning (except External). Thus, remove the
unneeded code and don't set the param up on new folders anymore.

lib, gui: Removed unused cleanInterval from Staggered Versioning (ref #541)

---

gui/default/assets/css/overrides.css
gui/default/syncthing/core/localeService.js

Even though technically possible, CJK languages normally don't use
italic text at all, as not only does it make the characters/letters look
unnatural, but also, in the case of complex characters, unreadable too.
For these reasons, it is usually recommended not to use the italic font
style at all [1][2].
This commit changes the default font-style of the i element for Chinese,
Japanese, and Korean language to "normal" instead of "italic". In order
to do so, the HTML lang attribute is also changed following each change
of the GUI language.
[1] https://bobtung.medium.com/best-practice-in-chinese-layout-f933aff1728f
[2] https://devblogs.microsoft.com/oldnewthing/20060914-02/?p=29743
Tested in modern browsers and IE11.

gui: Don't use italic text for CJK languages

---

gui/default/syncthing/folder/editFolderModalView.html

Right now, the Trash Can versioning info text is displayed for both the
Trash Can and Simple versioning. However, the Simple versioning has its
own info text that is also displayed, which results in two very similar
sentences being shown on the screen.
This commit limits the Trash Can info text to be displayed only when the
Trash Can versioning is selected, and moves the Simple versioning info
text up to the same location as the other one.

gui: Remove superfluous Trash Can info text from Simple Versioning

---

gui/default/syncthing/settings/advancedSettingsModalView.html

Add a link next to each setting's label to its explanation in the Docs.
This way, it is easy to quickly check what the setting is about without
going to the Docs site separately and searching for it manually.

gui: Add Docs help links to each setting in Advanced Configuration

---

lib/config/folderconfiguration.go
lib/config/size.go
lib/config/size_test.go
lib/model/folder.go

This tweaks the folder and database free space errors so that the first part is either `insufficient space in folder $description ($folderPath):` or `insufficient space on disk for database ($databasePath):` followed by something on the form `current $value < required $value`, so for example:
- `insufficient space in folder "foto" (/data/foto): current 0.97 % < required 1 %` (we hit the configured threshold)
- `insufficient space in folder "foto" (/data/foto): current 100 KB < required 182 MB` (we're processing a file that won't fit)
- `insufficient space on disk for database (/home/jb/.config/syncthing/index-v0.14.0.db): current 100 KB < required 1 %` (threshold)
Hopefully this should make the errors a little bit more actionable. There'll be some redundancy because the errors will …

lib/config: Improve clarity of free space errors (fixes #8180)

---

cmd/syncthing/main.go

Previously was using CPUPROFILE, which goes against the pattern for
other similar variables.  The docs already mentioned the better
STCPUPROFILE name.
See also https://github.com/syncthing/docs/pull/733.

Rename environment variable STCPUPROFILE for consistency

---

README-Docker.md

Add an additional port to the recommended docker config.
For more details on this port, see https://docs.syncthing.net/specs/localdisco-v4.html

Add port for local discovery broadcasts to Docker documentation

---

gui/default/assets/lang/lang-en.json
gui/default/index.html

Allow to translate the word "Twitter" in the footer. This is useful for
non-Latin languages which write the name using their own letters or
characters. For instance, Twitter themselves officially write their name
as "트위터" in Korean.

gui: Allow to translate Twitter footer link

---

gui/default/assets/lang/lang-en.json
gui/default/syncthing/core/syncthingController.js

Allow to translate the "Apply" and "Cancel" buttons used in the date
picker calendar in the Restore Versions modal.

gui: Allow to translate calendar buttons in Restore Versions modal

---

lib/fs/basicfs_watch_eventtypes_fen.go

Dangling symlink prevents filesystem watcher on Solaris (fixes #8020)
In production on Solaris 11.4

lib/fs: Do not follow symlinks in watcher on solaris (fixes #8020)

---

.github/workflows/update-docs-translations.yaml

- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
>Pin actions to a full length commit SHA
>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
Also, dependabot supports upgrading based on SHA.
Signed-off-by: naveensrinivasan …

build: Pin actions to a full length commit SHA

---

lib/connections/service.go
lib/model/folder_sendrecv.go
lib/pmp/pmp.go
lib/upnp/upnp.go

Errors constructed with pkg/errors implement Unwrap, so both stdlib errors.Is and pkg/errors.Is work with them.
This should make it possible to migrate away from pkg/errors in the long run.

all: Replace errors.Cause with errors.Is

---

lib/model/util.go

inWritableDir doesn't need to make its directory world-readable. Also, it now preserves setuid/setgid/sticky bits and returns Chmod errors early instead of waiting for fn(path) to fail.
From what I understand of how Go simulates Unix file modes on Windows, including some light testing, I think this should be portable. syscall.Chmod on Windows just checks if S_IWRITE = 0200 is being set or unset and sets the read-only bit accordingly, preserving all the other file attributes:
https://github.com/golang/go/blob/489102de18cff38d1b12d09eeb7e60af42492d63/src/syscall/syscall_windows.go#L647-L662

lib/model: Chmod to mode|0700, not 755

---

lib/model/folder.go

We check health before acquiring the semaphore, but without loading ignores, then get the semaphore, and then check again with loading ignores (to get up-to-date info in case acquiring took a while). However we also clear the folder error after the check without ignores, which then immediately gets set again -> flip-flopperoo.

lib/model: Clear folder error after loading ignores (fixes #8232)

---

build.go
go.mod
go.sum

This should fix compiling from the source tarball with Go 1.18.

build: Update go directive to 1.17 (fixes #8258)

---

cmd/stfinddevice/main.go
lib/connections/connections_test.go
lib/connections/quic_dial.go
lib/connections/quic_listen.go
lib/connections/registry/registry.go
lib/connections/relay_dial.go
lib/connections/relay_listen.go
lib/connections/service.go
lib/connections/structs.go
lib/connections/tcp_dial.go
lib/connections/tcp_listen.go
lib/dialer/public.go
lib/discover/cache_test.go
lib/discover/global.go
lib/discover/global_test.go
lib/discover/manager.go
lib/syncthing/syncthing.go

This fixes the failing (not yet merged) connection tests in https://github.com/syncthing/syncthing/pull/7866 by replacing the global registry by a per service registry (thus being able to use 2 different registries in the test -> failure gone).

lib: Removal global connection registry

---

lib/api/api_test.go

I recently changed those test-cases to run in parallel, because parallel = more good - well obviously no: There's timeouts on individual requests, requests are not parallelizable and the tiny amount of time spent in between requests to check the results is, well tiny. The test has already flaked out on (slower) CI machines.

lib/connections: Make request tests sequential

---

lib/config/config_test.go
lib/config/folderconfiguration.go
lib/config/migrations.go
lib/db/set.go
lib/fs/basicfs.go
lib/fs/casefs.go
lib/fs/casefs_test.go
lib/fs/filesystem.go
lib/fs/mtimefs.go
lib/fs/mtimefs_test.go
lib/model/folder.go
lib/model/folder_recvonly_test.go
lib/model/folder_sendrecv.go
lib/model/folder_sendrecv_test.go
lib/model/model.go
lib/model/model_test.go
lib/model/requests_test.go
lib/model/testutils_test.go
lib/scanner/walk_test.go
lib/versioner/external.go
lib/versioner/simple.go
lib/versioner/simple_test.go
lib/versioner/staggered.go
lib/versioner/trashcan.go
lib/versioner/trashcan_test.go
lib/versioner/util.go

Investigating https://github.com/syncthing/syncthing/issues/7974 I found that the log-filesystem is incorrectly wrapped if `walkfs` debug facility is used. And fixing that I further noticed case-fs is also badly wrapped: It's outside of `walkFilesystem`, meaning walking doesn't use the case filesystem. Also there's code in `mtimeFS.Walk` to make walk aware of the mtime-ness - I removed that and instead now `walkFilesystem` wraps `mtimeFS`.  All this wrapping after a filesystem is created is ugly and error prone. Thus I removed the separate constructors for case and mtime fs, and instead made those options to `NewFilesystem`. Like that the "correct layering" happens right there in a single constructor, no re-wrapping later on.
So basically the largest part of the diff is just the refactor …

lib: Get rid of buggy filesystem wrapping

---

lib/connections/service.go

Devices running nightlies are not connecting today, thanks to my PR #8263 missing the initiliasition of the new channel.

lib/connections: Create the forgotten channel (ref #8263)

---

lib/model/folderstate.go

The feature in #8202 treats disconnected or paused devices as having all folders unaccepted.  Change the enum's default value to assume `remoteValid` folders in those cases.  Should be a big step towards fixing #8266.

lib/model: Switch the remoteFolderState default value to valid (ref #8202)

---

cmd/syncthing/monitor_test.go
lib/api/api_test.go
lib/config/config_test.go
lib/fs/basicfs_test.go
lib/fs/basicfs_windows_test.go
lib/fs/casefs_test.go
lib/fs/fakefs_test.go
lib/fs/mtimefs_test.go
lib/ignore/ignore_test.go
lib/model/folder_sendrecv_test.go
lib/model/model_test.go
lib/model/requests_test.go
lib/model/sharedpullerstate_test.go
lib/model/testutils_test.go
lib/model/utils_test.go
lib/osutil/atomic_test.go
lib/osutil/osutil_test.go
lib/osutil/traversessymlink_test.go
lib/scanner/walk_test.go
lib/versioner/simple_test.go
lib/versioner/staggered_test.go
lib/versioner/trashcan_test.go

Issue https://github.com/syncthing/syncthing/issues/8279
A testing cleanup.
This pull request replaces `os.MkdirTemp` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 

test: use `T.TempDir` to create temporary test directory

---

cmd/syncthing/main.go
lib/logger/logger.go

This changes the default log format to include the date.

cmd/syncthing, lib/logger: Add date to default log format (fixes #8272)

---

lib/model/folder.go

Fixes a bug in a new feature in the current RC (introduced in #8249). Thanks to checking the correctness of the type assertion and sending a failure report it's not an urgent problem (just no warning, but also no panicking): https://sentry.syncthing.net/share/issue/e142516b1b274570a7660c613f16e48a/

lib/model: Subscribe to correct event for fs watching (ref #8249)

---

gui/default/index.html

I asked for zero listeners and got zero listeners so this is a success case, not a failure.
Before:
After:

gui: Use neutral color for zero out of zero listeners

---

lib/model/folder.go

These things are fragile, every event should use an ${eventType}Data struct or something instead.
(This was changed recently because it *looks* like an innocent change...)

lib/model: Correct type of event data (fixes #8294)

---

gui/default/syncthing/core/eventService.js
gui/default/syncthing/core/syncthingController.js
lib/events/events.go
lib/model/folder_summary.go
lib/model/folderstate.go
lib/model/model.go
lib/model/model_test.go
lib/syncthing/verboseservice.go

As discussed in #8266, this replaces the `accepted` boolean in `FolderCompletion` with a string derived from the recorded `remoteFolderState` value.  A new event type `RemoteClusterConfigReceived` causes the folder summary to be sent again shortly after learning the remote updates.
The new event doesn't have any meaningful content yet, I'd welcome suggestions on how to handle that.  Skipping in case the remote folder states haven't changed would be easy though, if we want that.
Accepting or unsharing a folder on a remote device is reflected in the GUI within a few seconds now.
https://github.com/syncthing/docs/pull/736 needs to be adapted for this.

lib/model: Improve remoteFolderState reporting (fixes #8266)

---

gui/default/assets/css/overrides.css

This stops interface from jumping left and right when page content no longer fits into screen.
Before:
After:

gui: Always show vertical scroll bar.

---

lib/discover/global.go

Global discovery just failed for me being on a network with terrible latencies. I don't see a good reason for such a stringent global discovery timeout as we have now (while I agree any sensible network should be able to complete it in 5s - well, thanks UPC for that one :) ).

lib/discover: Increase global discovery timeout

---

gui/default/syncthing/core/syncthingController.js

Definitely a lazy fix, but the error is coming out of angularjs land (no desire to dive into that) and it's reproducible (needs some fix). Fixes #8261

gui: Bandaid for null http errors (fixes #8261)

---

lib/db/schemaupdater.go
lib/db/structs.go
lib/db/transactions.go

Some minor cleanup to lib/db:
* rewriteGlobals released an iterator twice.
* convertVersionList always returned a nil error.
* VersionList.pop ignored its second argument and always returned a nil error.
* keyer.GeneratePending(Device|Folder)Key were always called with a nil first argument.

lib/db: Constant/unused args and return values, double it.Release

---

lib/events/events.go

This was needed for the old suture API, abandoned in 9524b51708d57e90d9e7728f480ee3b84c997c25.

lib/events: Remove unused method noopLogger.Stop

---

cmd/strelaypoolsrv/main.go
cmd/strelaypoolsrv/main_test.go
cmd/strelaysrv/main.go

Use the proper encoding function in the relay server when constructing
the URL. In the pool server, parse and re-encode the query values to
sanitize whatever the client sent.

cmd/strelaysrv, cmd/strelaypoolsrv: Sanitize query strings (fixes #8314)

---

gui/default/index.html
gui/default/syncthing/core/syncthingController.js
gui/default/syncthing/device/editDeviceModalView.html
gui/default/syncthing/folder/editFolderModalView.html

Extending the idea of #8201 to paused folders.  This puts a footnote number 2 on every device's shared folder / folder's sharing device where we know from the ClusterConfig that syncing will not happen.  Together with an explanation / tooltip.
This is based on #8283 which extends the `remoteFolderState` representation in the event structure accordingly as a prerequisite.

gui: Mark folders paused on remote devices (fixes #8310)

---

lib/discover/local.go
lib/discover/local_test.go

Remove unusable stuff from the local announce packet.

lib/discover: Filter locally announced addresses (fixes #7289)

---

README.md

Have minimal instructions to build within the released source, i.e. without having to access the internet. We even add vendoring so it can be built offline.

build: Add concise build instructions to readme

---

lib/api/api_csrf.go
lib/api/api_test.go

An off-by-one error in validToken caused tokens to be forgotten, and newToken would reallocate the tokens slice in every call. See commit messages for details.

lib/api: Fix and optimize csrfManager

---

gui/default/assets/lang/lang-en.json
gui/default/syncthing/core/syncthingController.js
gui/default/syncthing/settings/advancedSettingsModalView.html

Fixes #8264.
Follow the XML / JSON structure and keep it under a separate headline instead of the "default folder" section (as in the regular settings modal).
This section slightly differs in the handling of list-type config options.  Usually they are represented as comma-separated single-line text inputs, which is unsuitable for ignore patterns which may rightfully contain commas.  Thus a textarea is used, using newline as the list delimiter.
Verified that patterns entered under Edit Folder Defaults are correctly adapted in Advanced Configuration and vice versa.  Leading and trailing spaces are preserved in both directions.

gui: Add default ignores to the advanced configuration editor modal (fixes #8264)

---

lib/model/util.go

This partially reverts #8235 and hopefully fixes #8355, which besides changing the mode bits also returned an error from trying to chmod the parent directory. Previously and again with this PR no such error was/is returned. I added some additional logging around this case (parent chmodding failing).

lib/model: Don't fail on temporary chmod (fixes #8355, ref #8235)

---

lib/assets/assets.go

Two patches for lib/assets. The main one updates the MimeTypeForFile switch with a case for ".eot" and updated cases for WOFF fonts. See the commit messages for details.

lib/assets: MIME types, time formats

---

gui/default/syncthing/folder/editFolderModalView.html

The function `deviceNameMarkUnaccepted()` was renamed to `deviceNameMarkRemoteState()`, but this one caller was not adjusted accordingly.  See #8369 for the respective defect.

gui: Fix use of old, renamed function in edit folder sharing tab (fixes #8369)

---

gui/default/syncthing/folder/editFolderModalView.html

Currently, the user is supposed to set the maximum age for Staggered
Versioning, with its default value being "365". However, there is no
indication what the value actually corresponds to.
This commit adds the text "days" displayed right to the input value,
which makes it clearer what the number actually means. This makes the
code identical to the clear out after input field in Simple Versioning
that also displays "days" next to its value.

gui: Display "days" next to "maximum age" in Staggered Versioning

---

gui/default/syncthing/device/editDeviceModalView.html

Another renamed function missed from the previous PR #8286 somehow.  Fixes #8369 again.
I'm clueless as to how this could have got lost originally.  I did test the code, but either there were some merge conflicts where I messed things up or my browser had somehow cached the old functions, thus I didn't notice the missing labels. Note to self (and reviewers): When renaming something, do a recursive grep for the old name over the entire code base as a last step.

gui: Fix missing folder names in Edit Device > Sharing tab (fixes #8369)

---

lib/osutil/lan.go

Syncthing will only announce address of interfaces which are up (fixes #7458)
Syncthing compiles
Check that Syncthing is announcing only addresses of interfaces which are up
Not sure if the change should be mentioned in the documentation

lib/osutil: Only announce address of interfaces which are up (fixes #7458)

---

cmd/syncthing/cli/show.go

Add show disovery command to cli (fixes #8007)
Execute `syncthing cli show discovery` on the command line
Since the other show commands are not described in the documentation as far as I have seen, I don't think a change is necessary.

cmd/syncthing/cli: Add show discovery command (fixes #8007)

---

gui/default/syncthing/core/syncthingController.js
gui/default/syncthing/device/editDeviceModalView.html

The GUI already does `refreshDiscoveryCache()` when it comes online and on every 10 second refresh cycle.  Querying the same information freshly in `addDevice()` seems unnecessary and adds some more round-trip delay on a possibly slow network link.  Instead use the IDs from the existing `discoveryCache` property to populate the suggested ID list.
Increase maximum suggested device ID count to 100, only for the auto-completion list.  It is hidden by default and filtered
by the browser, so we can offer more discovered device IDs without causing much disturbance.  The list of suggested "nearby" devices is still limited to the first five.
Manual GUI testing with locally discovered, not yet added devices.

gui: Use discovered IDs from cache when adding a new remote device

---

gui/default/syncthing/folder/editFolderModalView.html

Currently, the filesystem watcher explanation in the Advanced tab in the
Edit Folder modal window is split into two parts. The first is location
in a tooltip that is visible only when hovering the mouse over the small
checkbox, which makes it not easily accessible, e.g. for new or touch
screen users.
No other settings in the Edit Folder window have their explanation
presentend like that. When needed, it is always displayed in their
respective help blocks, which are always visible on the screen. Thus,
move the filesystem watcher explanation from the tooltip to the help
block, merging it with the other part of the explanation in the process.

gui: Move filesystem watcher explanation from tooltip to help block

---

lib/config/folderconfiguration.go
lib/model/model.go

Encrypted folders should not have the fs watcher enabled and rarely benefit from a scheduled rescan.  Versioning does not work well for them either.  The GUI adjusts the suggested settings accordingly (watcher disabled, one day rescan interval, no versioning) when accepting a receive-encrypted folder.  Mirror that behavior to the auto-accept case where the GUI is not involved.
For watcher and rescan, the defaults are overridden especially in `handleAutoAccepts()`, while the versioning is filtered out completely in the backend's `FolderConfiguration.prepare()`.
Fixes #8296.
Manual testing with auto-accept enabled or disabled from a certain remote device.
Is it worth mentioning this automatic override in the docs?  The only place I've found is at …

lib/model, lib/config: Apply sensible defaults for auto-accepted encrypted folder (fixes #8296)

---

gui/default/index.html
gui/default/syncthing/core/syncthingController.js
lib/model/folder_summary.go

Adds a sync status row to remote devices (fixes #7981)
Also updates device sync completion on folder rescan 
If device is unused, the row does not appear:
Device up to date:
Device out of sync:

gui: Add device sync status (fixes #7981)

---

cmd/strelaypoolsrv/stats.go
cmd/strelaysrv/listener.go
lib/connections/service.go
lib/model/folder_sendrecv_test.go
lib/relay/client/dynamic.go
lib/relay/client/static.go
lib/upnp/upnp.go

all: Remove or convert deprecated API usages

---

cmd/ursrv/main.go

cmd/ursrv: Silence linter with correct regexps

---

lib/config/config.go

lib/config: Use net.JoinHostPort instead of string manipulation

---

README-Docker.md

This should make the limitations a bit clearer.

docs: clarify docker network mode limitations

---

cmd/syncthing/cli/main.go

Currently the `Run()` function of the CLI always uses `os.Args` directly.
This change adds an additional `RunWithArgs()` function that allows passing
arguments as `[]string` instead.
This is useful when linking against Syncthing as a library to be able to also
expose the CLI. For instance, this is used by
[Syncthing Tray](https://github.com/Martchus/syncthingtray) which can have
Syncthing as built-in library. Like Syncthing itself it then features the `cli`
sub-command exposing Syncthing's CLI.
This change has been tested manually within the context of Syncthing Tray. It
is actually already part of recent Syncthing Tray releases (relevant commit is
in my forked Syncthing repository used by Syncthing Tray as submodule, e.g.
https://github.com/Martchus/syncthing/commit/ced426eac9a1ceb778c0c4 …

Refactor CLI code to allow passing CLI arguments via function parameter

---

cmd/syncthing/monitor.go

Apparently there's an `exec.ErrDot` error handling this case and it should return the local path in that case, however I did not get that behaviour playing around with it (`exec.LookupPath("test.sh")` returned `ErrNotFound`).  So I just "manually" handled it regardless of what the error is.

cmd/syncthing: Work around binary in current dir restriction (fixes #8499)

---

cmd/syncthing/cli/config.go
cmd/syncthing/cli/main.go
cmd/syncthing/main.go
go.mod
lib/config/config.go
lib/connections/quic_dial.go
lib/connections/relay_listen.go
lib/connections/service.go
lib/model/folder.go
lib/model/folder_sendrecv.go
lib/model/model.go
lib/model/model_test.go
lib/model/sharedpullerstate.go
lib/model/util.go
lib/osutil/lowprio_linux.go
lib/osutil/lowprio_unix.go
lib/osutil/lowprio_windows.go
lib/protocol/protocol.go
lib/relay/client/static.go
lib/syncthing/utils.go
lib/tlsutil/tlsutil.go
lib/upnp/upnp.go
lib/versioner/util.go

This replaces old style errors.Wrap with modern fmt.Errorf and removes
the (direct) dependency on github.com/pkg/errors. A couple of cases are
adjusted by hand as previously errors.Wrap(nil, ...) would return nil,
which is not what fmt.Errorf does.
Existing calls to errors.New, errors.Is and errors.As work the same as previously.

all: Modernize error wrapping

---

cmd/syncthing/monitor.go

Use `os.Executable` regardless of OS and only fall back to PATH lookups if that fails (not sure why it ever would).
Followup for https://github.com/syncthing/syncthing/pull/8500 to be delayed until the next release as it's a behaviour change that warrants a full RC phase of testing (thus draft).

cmd/syncthing: Use os.executable in monitor, only fallback to PATH

---

GOALS.md
cmd/stdiscosrv/replication.go
cmd/syncthing/cli/index_idxck.go
cmd/syncthing/main.go
cmd/syncthing/monitor.go
etc/freebsd-rc/README.md
gui/default/syncthing/app.js
gui/default/syncthing/core/syncthingController.js
gui/default/vendor/fancytree/jquery.fancytree-all-deps.js
lib/api/api_test.go
lib/config/folderconfiguration.go
lib/config/optionsconfiguration.go
lib/connections/dialqueue_test.go
lib/db/db_test.go
lib/db/set_test.go
lib/discover/global.go
lib/fs/basicfs_fileinfo_windows.go
lib/fs/casefs_test.go
lib/fs/mtimefs_test.go
lib/ignore/ignore.go
lib/model/folder_sendrecv.go
lib/model/model.go
lib/model/requests_test.go
lib/model/sentdownloadstate.go
lib/protocol/protocol_test.go
lib/syncthing/utils.go
lib/upgrade/upgrade_test.go
lib/watchaggregator/aggregator.go
man/syncthing-rest-api.7
script/codecov-upload.sh

Found via `codespell -q 3 -S lang,./gui/default/vendor -L benchs,bu,inflight,ro`

all: Fix various user-facing and non-user-facing typos

---

lib/tlsutil/tlsutil.go

*rsa.PrivateKey and *ecdsa.PrivateKey are both Signers, which have a method to get the public key. No need for the type switch.

lib/tlsutil: Use crypto.Signer interface

---

gui/default/index.html

Currently, the error message is often quite long and thus it appears truncated with no possibility for the user to view the full string. Thus, add a tooltip that displays the message in full on hover. This follows the convention used in other parts of the GUI in similar cases.

gui: Add tooltip to folder error message (fixes #7603)

---

gui/default/syncthing/app.js

The current code checks whether the same-named item exists in the tree,
and when it does, it re-uses it when adding new children to it. However,
the code doesn't check whether the existing item is a folder or a file.
It rather assumes that it is always a folder, which is not necessarily
the case.
This commit adds a new check to the code, so that the existing element
is reused only when it is a folder, and ignored otherwise.

gui: Fix error in Restore Versions when path exists as both directory and file (fixes #7068)

---

etc/linux-systemd/README.md
etc/linux-systemd/system/syncthing@.service
etc/linux-systemd/user/syncthing.service

Add a commented entry to the systemd service file templates to point the user in the right direction when using syncOwnership and starting via systemd.  Which is more upgrade-friendly than setting caps on the executable directly, as mentioned in the docs.
Based on info from https://forum.syncthing.net/t/problem-with-syncownership/18934/5
Verified the setting is correctly parsed by systemd.  I haven't tried myself whether it works, relying on the forum post instead.
See https://github.com/syncthing/docs/pull/764

etc/linux-systemd: Mention AmbientCapabilities for syncOwnership.

---

gui/default/assets/css/overrides.css

Currently, the code contains a "mobile phone" fix to allow wrapping of long lines in table heading and cells. However, the fix is applied to all screen sizes equal or below 768 px wide, which causes the layout to break on tablet-sized screens.
The commit moves the "mobile" fix to the actual mobile media query, which is applied to screens up to 419 px wide. It is only really needed there, where it synergises with the existing fix that changes table cell display to "block". There is no need to wrap the text on larger screens, as there is more than enough space to display the lines in full on them.
Below are two screenshots taken exactly at the 419 px breakpoint. Apart from the fix on resolutions between 419 and 768 px wide, there is …

gui: Fix text wrapping on tablet-sized screens (fixes #8529)

---

lib/versioner/trashcan.go
lib/versioner/trashcan_test.go

The restore function of Trash Can ran a rename action at the end of the process regardless of whether there was anything to rename. In this case, when the file-to-be-restored did not exist already in the destination folder, this non-existing file was not being archived resulting in an error when trying to rename this file even though the whole restore-process otherwise worked correctly.
I added a simple check which keeps track of whether the file existed in the destination folder prior to restoring. Depending on this value it will now return nil after the actual restoring procedure to prevent the renaming function from kicking in on a non-existing object. 
Added a test for this specific edge-case as well, which is perhaps a bit of an overkill.

lib/versioner: Fix error in Trashcan restore (fixes: #7965)

---

Dockerfile
README-Docker.md
script/docker-entrypoint.sh

As it's not simple to run a container under Docker/Kubernetes as non-root but with additional capabilities, add an internal hack.
Tested to work under TrueNAS Scale, which is Kubernetes...

docker: Add env var to control capabilities

---

cmd/syncthing/cli/main.go

The current help text for the gui-address option in the cli is incorrect.
It currently displays needing a full URL.
```
Override GUI address to `URL` (e.g. \"http://192.0.2.42:8443\")
```
If you pass a full url as the gui-address option, you get a failure.
```
syncthing cli --gui-address http://127.0.0.1:8385 --gui-apikey wjvTg743GgzEuUGJhG6QxVMMTpyX2gKi config folders list
parse "http://http:%2F%2F127.0.0.1:8385/rest/system/config": invalid URL escape "%2F"
```
If you pass without the protocol (http://) it works
```
syncthing cli --gui-address 127.0.0.1:8385 --gui-apikey wjvTg743GgzEuUGJhG6QxVMMTpyX2gKi config folders list
default
```
This fixes the help text to reflect what should actually be passed.
Run a cli command with the options as described above.

Fix incorrect cli help text

---

gui/default/syncthing/core/syncthingController.js

Currently, the link to remote GUI uses device addresses as they are advertised from the router. Because of this, they may end up having a scope ID attached to them. The problem is that browsers do not support such addresses, leaving the user with a non-working URL.
Because of the above, use regex to simply filter out the scope ID from the address before using it for Remote GUI.

gui: Filter scope ID out of IPv6 addresses in Remote GUI (fixes #8084)

---

cmd/strelaysrv/listener.go
cmd/strelaysrv/main.go
lib/relay/client/static.go
lib/relay/protocol/packets.go
lib/relay/protocol/packets_xdr.go
lib/relay/protocol/protocol.go

Attempt to implement a sort of authentication for relaysrv by checking for a simple token before allowing clients to join.
tested with
```
./bin/strelaysrv -debug -pools "" -token 'thetoken'
./cmd/strelaysrv/testutil/testutil -relay=relay://localhost:22067?token='thetoken' -keys=/home/user/.config/syncthing/ -test
```
I'm not quite sure if this is a good way to implement this, or if there are security-implications so i am happy for comments.
Relevant issue: https://github.com/syncthing/syncthing/issues/3987

cmd/strelaysrv: Add optional auth token (fixes #3987)

---

Dockerfile
script/docker-entrypoint.sh

This correctly handles the absense of the PCAP environment variable, which was broken in the previous change.
Requires a new RC.

docker: Fix handling of PCAP variable (fixes #8567)

---

gui/default/syncthing/core/syncthingController.js
lib/api/api.go

There are some situations where an upgrade wouldn't be supported, even though the noUpgrade bool isn't set. So when handling the errors that are caused by this, when attempting an upgrade, it shouldn't lead to some sort of offline-message/restart/warning/etc...
I added some checks on specific errors related to this and return a 501 (Not Implemented) response instead, in case of an "UpgradeUnsupported"-error. Additionally, on the GUI-side, the 501-response is now not to be considered an error to act upon.
Run it in Docker and use the related /rest/system/upgrade-call to see what it returns and verify whether the GUI stays silent / does something we don't want it to do. Used extra logging on 'upgrade' to pinpoint the causing lines and to see if it still results in a, potential, problem.

api, gui: Prevent connection issues due to unsupported-upgrade (fixes #8569) 

---

lib/api/api.go
lib/api/api_auth.go
lib/api/api_csrf.go

Added a status page to the REST API which can act as a health-check, this allows third-party services and devices to check the status of Syncthing without having to use an API-key or plain-texted credentials.
To accomplish this two things were adjusted:
- Exception for /rest/status to the CSRF-token-requirement
- Exception for /rest/status to the otherwise required authentication
And obviously the /rest/status functionality was added, which is a simple return of a JSON object. Since, if you reach that point - it all goes well anyways. If not, you'll get another kind of error before reaching this point.
Two parts:
1.) Functional; visit the url and call the url in several ways, browser/curl/wget/...
2.) Security: Since we made an exception in the security-layer; hack-and-slash the URL a …

lib/api: Add /rest/status health-check (#8430) 

---

lib/protocol/bep_extensions.go
lib/scanner/blockqueue.go
lib/scanner/walk.go

Previous debug input didn't really give enough info to show what was happening, while it also printed full block lists which are enormously verbose. Now it consistently prints 1. what it sees on disk, 2. what it got from CurrentFile (without blocks), 3. the action taken on that file.

lib/scanner: More sensible debug output

---

gui/default/index.html

In large setups, it is currently impossible to know the exact number of folders and remote devices without counting them manually, either in the GUI or in config.xml. Thus, to provide this information to the user, add a specific number right next to both Folders and Remote Devices headers in the Web GUI. The numbers are only displayed when two or more folders or devices are present.

gui: Display folder and device count number

---

gui/default/index.html

Right now, the Out of Sync Items list for a specific remote device is
available only when the device is online and currently synchronising.
However, the list itself is being created by Syncthing all the time, so
there is no need to hide it from the user even when the remote device is
offline or paused. This way they can always easily check which files
exactly have not been synchronised yet.
In addition, the Out of Sync Items entry already includes file size next
to it, so there is no need to display it again next to the Sync Status
entry. Thus, remove out-of-sync file size from Sync Status, leaving only
percentage next to it.

gui: Always show Out of Sync Items for remote devices

---

Dockerfile

Fixes #8638
Tested the cmd against a local instance with HTTP and HTTPS:
```sh
curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
```
Successful healthcheck:
```
OK
```
Failed healthcheck:
```
curl: (7) Failed to connect to 127.0.0.1 port 8384 after 0 ms: Connection refused
```
curl parameters:
* [-f](https://curl.se/docs/manpage.html#-f) Fail fast with no output at all on server errors. Otherwise error pages are passed to grep
* [-k](https://curl.se/docs/manpage.html#-k) Ignore certificate errors. Important if the UI is using HTTPS with a selfsigned certificate
* [-L](https://curl.se/docs/manpage.html#-L) Follow redirects. Handles the HTTP -> HTTPS redirect
* [-s](https://curl.se/docs/manpage.html#-s) Don't output download meter/progress
* …

docker: Use healthcheck endpoint

---

gui/default/assets/css/overrides.css

Currently, the connection type icon size is fixed at 1em (or 16px). This makes it behave differently from the other GUI icons coming from Fork Awesome, which automatically scale to their parent element's font size. Thus, set the background-size to contain in order to automatically let the icon resize itself to the font size.
Also, improve the alignment to a more middle position in relation to text, making it similar to Fork Awesome icons.

gui: Adjust connection type icon size scaling and alignment

---

gui/default/assets/css/overrides.css

The connection type icon comes from Bootstrap. As such, it does not follow the same dimensions as the other GUI icons, which come from Fork Awesome. Thus, add left and right margin to make its width roughly the same as the other GUI icons, which fixes its alignment in relation to text.

gui: Fix connection type icon width (fixes #8592)

---

.github/workflows/build-syncthing.yaml
build.go

This is sort of a proof of concept, but since our current Windows builder is down this might solve the problem. It includes a change for easier code signing (taking the certificate in a secret/env var rather than existing already on disk) but otherwise mirrors precisely what we already do in the build server.

build: Add GitHub actions build for Windows

---

lib/fs/basicfs.go
lib/fs/basicfs_unix.go
lib/fs/basicfs_windows.go
lib/fs/basicfs_windows_test.go

This adds a hack to remove read-only and retry remove on Windows. This works for me to sync and then remove a directory with a custom icon set on it, on Windows 11.

lib/fs: Try to remove read only Windows files (fixes #3744)

---

lib/protocol/bep_extensions.go

No point considering file infos different if only ctime changes but we don't care about the affected attributes (xattr, ownership) at all.

lib/protocol: Ignore inode time when xattr&ownership is ignored (fixes #8654)

---

lib/model/folder_sendrecv.go

I'd forgotten to add code to set xattrs to the directory handling paths. To fix that and avoid similar mistakes in the future I moved the xattr handling to a new adjustCommonMetadata function, which previously just handled ownership. The idea is for this function to apply common things to all file types, so we can add things in one place and not forget half of them...

lib/model: Correctly handle xattrs on directories (fixes #8657)

---

lib/model/folder_sendrecv.go
lib/model/folder_test.go

There was an error, where setPlatformData took the name to operate on from the FileInfo instead of the given parameter. This worked in some cases, but not when applied to a file being synced (new, or data was changed). Bonus: a small test.

lib/model: Correctly set xattrs on temp files (fixes #8667)

---

cmd/syncthing/generate/generate.go
cmd/syncthing/main.go

We had some unholy mix of our own logger and the stdlib logger, probably because for historical reasons we wanted the device ID to stdout and the rest to stderr? But that's not the case any more, and the mix of formats is weird. Ideally I think the generate command should be silent and just print the device ID and nothing else, but that's tricky to accomplish since we have other methods do logging on their own. Hence this just harmonizes it so that we at least use the same logger with the same format and target...

cmd/syncthing: Use main logger in generate subcommand (fixes #8682)

---

lib/fs/util.go

Replaced strings.Split with the new strings.Cut, which doesn't allocate.
```
name                           old time/op    new time/op    delta
WindowsInvalidFilenameValid-8     154ns ± 2%      89ns ± 0%   -42.09%  (p=0.000 n=10+9)
WindowsInvalidFilenameNUL-8       124ns ± 2%     124ns ± 1%      ~     (p=0.371 n=8+10)
name                           old alloc/op   new alloc/op   delta
WindowsInvalidFilenameValid-8     16.0B ± 0%      0.0B       -100.00%  (p=0.000 n=10+10)
WindowsInvalidFilenameNUL-8       19.0B ± 0%      3.0B ± 0%   -84.21%  (p=0.000 n=10+10)
name                           old allocs/op  new allocs/op  delta
WindowsInvalidFilenameValid-8      1.00 ± 0%      0.00       -100.00%  (p=0.000 n=10+10)
WindowsInvalidFilenameNUL-8        2.00 ± 0%      1.00 ± 0%   -50.00% …
```

lib/fs: Optimize WindowsInvalidFilename

---

.github/workflows/build-syncthing.yaml
build.go

Without this, we tag the build as made by some random user account on some random host name which is not useful.
(And minor bug in the cache key which has no effect on the build itself.)

Set build metadata correctly in Windows build

---

gui/default/index.html
gui/default/syncthing/core/syncthingController.js
lib/connections/service.go
lib/connections/structs.go
lib/model/model.go
lib/protocol/mocked_connection_info_test.go
lib/protocol/mocks/connection.go
lib/protocol/mocks/connection_info.go
lib/protocol/protocol.go

Following the discussion from https://forum.syncthing.net/t/towards-better-connection-type-icons/19333/23, this replaces the GUI's own logic of matching IP addresses against a regex with the backend's flag which already includes the subnet information and works for IPv6 as well.  The flag is exposed as a new `isLocal` attribute on the `ConnectionInfo`.
In addition, the "reception levels" displayed in the GUI are reassigned to no longer indicate TCP as better than QUIC.  The new order is {TCP,QUIC} LAN → {TCP,QUIC} WAN → Relay LAN → Relay WAN → Disconnected.
For lack of every possible connection scenario, I have so far only observed TCP LAN, TCP WAN and Disconnected states.

gui: Let the backend decide whether connection is local (fixes #8686)

---

lib/model/model.go

Fixed an obvious typo that resulted in empty entries in the device list.
Didn't do any testing.
For testing, you need to create 3 devices, connect 1 and 2, make 1 introducer for 2, connect 1 and 3, make sure that device 3 automatically appears on 2.
No need to change documentation.

lib/model: Fixed adding empty items to device list (fixes #8646)

---

Dockerfile.buildx

This is the Dockerfile that's actually used in the multi-platform builds published to Docker hub.

docker: Update healthcheck cmd for buildx (ref #8640)

---

Dockerfile

On systems with safe umasks (`umask 077`), the entrypoint as copied from the host may not be executable by other users. Ensure that it is set to be within the Dockerfile.

docker: ensure entrypoint is executable

---

lib/model/folder_sendrecv.go

By @tomasz1986 in https://github.com/syncthing/syncthing/issues/8583#issuecomment-1352971185
> [...] If this isn't a problem per se, is it really necessary to even notify the user about it?
Indeed the error is either inconsequential (if the file is gone, that's going to be picked up by the subsequent scan, change time doesn't matter) or at worst if it's indeed a temporary issue, the next scan will notice the changed time and bump the version. Info level logging seems appropriate, such that there's infos in the logs in case a user encounters weird issues due to that, but no need to warn/send a banner to the UI over this.

lib/model: Only log at info level if setting change time fails

---

lib/fs/basicfs_watch.go
lib/fs/basicfs_watch_unsupported.go

Apparently watching on android/amd64 causes a `SIGSYS: bad syscall` crash. This avoids that.

lib/fs: Watching is unsupported on android/amd64 (fixes #8709)

---

lib/fs/filesystem.go
lib/ignore/ignore_test.go

Stumbled over this randomly, small housekeeping: The os package tells one to use errors.Is with the errors in io/fs instead of these functions predating the newer style error handling.

lib/fs: Use io/fs errors as recommended in std lib

---

go.mod
go.sum
gui/default/index.html
gui/default/syncthing/core/syncthingController.js
lib/api/api.go

This adds a word to the version string when running containerized. The purpose is mostly to facilitate troubleshooting via screenshot by "leaking" this rather important aspect of the setup. Additionally, the version row gets "no-overflow-ellipsis" treatment so that the whole thing is actually visible in the GUI and the (now useless) tooltip is removed. In production releases this won't make a difference as the whole thing will typically fit, but in odd setups it provides more info up front.
Arguably this thing should be localized, but ... the version strings aren't currently, because they're proper names of sort, the "64-bit" part could be...

gui, api: Indicate running under container

---

gui/default/syncthing/core/syncthingController.js

The current code assumes that lastSeenDays is always set which is not
the case when device reports its lastSeen as equal to the Unix epoch.
Thus, make sure that lastSeenDays is set before proceeding with the
disconnected-inactive status check to avoid JS errors in the browser.

gui: Fix undefined lastSeenDays error in disconnected-inactive status check (ref #8530)

---

build.go
script/weblatedl.go

Based on the transifexdl.go script.  Map Weblate language codes to the existing ones during import.  Do not delete incomplete languages from repo.
Note this requires an API token from Weblate to use, passed via `WEBLATE_TOKEN`.  It needs to be run from the `gui/default/assets/lang/` directory.

script: Add weblatedl.go for downloading updated translations

---

.github/workflows/build-syncthing.yaml

The new Go patch version includes a fix for #8325.  The Synology package, where this error occurred frequently, is going to be built with it by default.  We should upgrade as well to avoid breaking existing installations again when they auto-upgrade to our upcoming release.  See also https://github.com/SynoCommunity/spksrc/issues/5289.
**Is there any other place (TeamCity?) where we need to specify this, or is only this GH action involved in building release artifacts?**

GitHub: Build with Go 1.19.5 (fixes #8325)

---

gui/default/assets/lang/README.txt

Updated URL
I decided to update the URL, since the old one did not lead to the project page

gui: Fix broken link to Transifex in lang/README.txt

---

cmd/strelaysrv/listener.go
cmd/strelaysrv/main.go
cmd/strelaysrv/session.go
cmd/strelaysrv/status.go
cmd/stvanity/main.go
lib/config/wrapper.go
lib/connections/limiter.go
lib/connections/limiter_test.go
lib/connections/quic_listen.go
lib/model/folder.go
lib/model/model.go
lib/model/model_test.go
lib/protocol/bufferpool.go
lib/protocol/bufferpool_test.go
lib/protocol/counting.go
lib/protocol/protocol_test.go
lib/scanner/walk.go
lib/stun/stun.go
lib/sync/sync.go

Better type-safety, less commenting on what needs to be aligned. Also a micro-optimizations, in a separate commit so it can be easily taken out of this PR if you don't want it.

all: Use new Go 1.19 atomic types

---

gui/default/index.html

The reference comes from fd0a6225aadce9cee19ab058465fa5c8658f0be9,
but the file itself was removed in the process of working on the pull
request, yet the reference to it was still left in the index.html.

gui: Remove non-existent customicons.css file reference (fixes #8797)

---

lib/api/api.go
lib/db/structs.go
lib/protocol/bep_extensions.go

This adds the BlocksHash field from the FileInfo to our API output. It can be useful for debugging, or for external tools. I'm intentionally leaving it as an opaque base64 string because no meaning should be derived from it: it's just a string.

lib/api: Expose `blocksHash` in file info

---

lib/model/folder_sendrecv.go
lib/model/sharedpullerstate.go

Fixes a regression due to PR #8563, while arguable the bug was actually introduced in a much older PR #7155, but didn't have any bad effects so far:
We account for the encryption trailer in the db updater routine, calculating the file-info size there. However there's no guarantee that the file-info at this point is still the exact same as when it was written. It was before, but isn't anymore since introducing the new EncryptedTrailerSize field.
Fix: Adjust the size in the info at the same place where the trailer is written, i.e. we definitely have the actual size on disk.

lib/model: Fix file size inconsistency due to enc. trailer

---

lib/model/sharedpullerstate.go

In the original fix in #8563 I simply forgot this. Which meant #8556 wasn't actually fixed, as the trialer size would have been 0 (default), and thus we would have still sent the inflated size to encrypted peers.

lib/model: Set enc. trailer size on pull (ref #8563, #8556)

---

lib/ignore/ignore.go
lib/ignore/ignore_test.go

In the sequence of loading ignores, the error `no such file or directory` is not being considered a fatal  error, since the `.stignore` file is allowed to not exist. However, included ignore files also tossed that same error in case those did not exist while in those cases it's actually considered an error that should impact the running-status of the folder. Changing the error when opening an included ignore file to something manually defined does fix this issue, as in it now works again as described in the Documentation.
Add/edit a folder. Add ignore-lines with `#include .somethingnonexisting` and it should now error out properly and the folder should be stopped, instead of having the ignores not being loaded and the folder remain in a running state.

lib/ignore: properly handle non-existing included ignore-files (fixes #8764)

---

.github/workflows/build-syncthing.yaml
.github/workflows/update-docs-translations.yaml

This PR fixes the Node 12 deprecation shown under the action runs of update-docs-translations.yaml by bumping the version of `actions/checkout` from `v2` (Node 12) to `v3` (Node 16). 
This PR also updates `actions/setup-go` to `v4`.
Closes #8832
These changes haven't been tested yet, but they are non-breaking changes.

CI: Bump actions version; fix Node 12 deprecation warning

---

lib/model/folder_sendrecv.go

Platform data (ownership, xattrs, etc.) is now set correctly for newly-received folders, even if the received folder has the NoPermissions flag. This fixes #8399.

Set Platform Data for New Folders w/ NoPermissions Flag

---

lib/api/api_auth.go
lib/api/api_auth_test.go

Fix the error string being injected when the template variable for username is omitted in the LDAP Bind DN string (fixes #8899).
Regression tests have been added to check the new behavior for the original use case and the new one.
No documentation change should be required, although the language for LDAP configuration could be changed to note that `%s` is optional. This would be in-line with the more useful use LDAP auth, which is locking a single syncthing instance to a single user account which manages it's password via LDAP.

Allow BindDN to exclude any username formatting

---

lib/api/api.go
lib/db/backend/leveldb_open.go

We can simplify the following code
```go
dir, err := os.Open(dirname)
if err != nil {
return err
}
defer dir.Close()
dirs, err := dir.Readdir(-1)
```
with just `os.ReadDir(dirname)`. `os.ReadDir` is recommended over `Readdir()`, as stated in the official doc [^1]
[^1]: "Most clients are better served by the more efficient ReadDir method." https://pkg.go.dev/os#File.Readdir

lib: replace `Readdir(-1)` with `os.ReadDir`

---

cmd/syncthing/monitor.go

The discrepancy was flagged by DeepSource; usually this will not matter as binary == args[0] but in the case there is a difference we have the parameter for a reason.

cmd/syncthing: Use correct binary when restarting monitor

---

.github/workflows/build-syncthing.yaml
lib/fs/basicfs_windows_test.go

Despite the discussion in #8889 we missed to actually enable the test runs on Go 1.20, and when you do we can see that the additional tests added there do not, in fact, pass. This (`\\.\...` paths) isn't something we tested before and I'm not really sure what they're supposed to mean anyway, so ...

build: Tests should run with Go 1.20 on Windows

---

lib/config/config.go
lib/config/config_test.go

We usually want to ensure that our own device is present. However if the given device ID is the empty ID, we shouldn't do that. This is a legimate (though way too non-obvious) use-case when opening the config without knowing/caring about the device ID.

Don't add empty device to config on init

---

lib/db/meta.go
lib/model/requests_test.go
lib/versioner/trashcan_test.go

staticcheck fix
should check returned error before deferring fd.Close()
unnecessary use of fmt.Sprintf
should use copy(to, from) instead of a loop
Describe what testing has been done, and how the reviewer can test the change
if new tests are not included.
to the corresponding pull request on https://github.com/syncthing/docs or describe
the documentation changes necessary.

chore: staticcheck fix

---

Dockerfile
cmd/syncthing/cmdutil/options_common.go
cmd/syncthing/main.go

This allows environment overrides for our directories. This is advantageous because, apart from the obvious, it means we can set it in the Docker file and not add command line options there. Having the command line option as we did meant that it was impossible to use the Docker image for other commands than `serve` (because that is implied when we see other options on the command line).

cmd/syncthing: Add environment variables for --home, --conf, and --data

---

gui/default/syncthing/core/syncthingController.js

This removes the tilde expansion we had in the GUI. I'm not sure why we had it, but there are valid reasons to have a folder path with tilde in it in the config, and it was previously impossible to enter one of those.

gui: Remove tilde auto-expansions (fixes #8890)

---

etc/linux-sysctl/30-syncthing.conf

quic-go v0.35.0+ tries to use a larger send buffer. This raises the necessary sysctl limit and follows the wikis recommendation of a 2.5MiB limit.

Update sysctl configs

---

gui/default/index.html
gui/default/syncthing/core/syncthingController.js

Filter the list before displaying it.

gui: Avoid spurious comma in shared-with device list (fixes #8967)

---

lib/fs/basicfs.go
lib/fs/util.go
lib/fs/util_test.go

With this change, error messages include the offending characters or name parts. Examples:
nul.txt: name is invalid, contains Windows reserved name: "nul"
foo>bar.txt: name is invalid, contains Windows reserved character: ">"
foo \bar.txt: name is invalid, must not end in space or period on Windows
(the last one refers to the `foo ` component)

lib/fs: Clarify errors for Windows filenames (fixes #8968)

---

gui/default/syncthing/core/syncthingController.js
lib/api/api.go
lib/build/build.go
lib/build/build_test.go

This adds an environment variable STVERSIONEXTRA that, when set, gets added to the version information in the API and GUI. In the CLI we see the following:
% STVERSIONEXTRA=foo ./bin/syncthing --version
syncthing v1.23.7-rc.1 (foo) "Fermium Flea" (go1.20.5 darwin...etc
In the GUI it's shown similarly in the About screen and in the local device box.
The purpose of all this is to be able to communicate something about the bundling or packaging, through the log & GUI and the end user, to the potential person supporting it -- i.e., us. :) A wrapper can set this variable to indicate that Syncthing is being run via `SyncTrayzor`, `Syncthing-macOS`, etc., and thus indicate to the end user that the GUI they are looking at is perhaps not the only source of truth and management for this instance.

gui, lib/api: Add possibility to feed through extra version information

---

lib/osutil/lowprio_windows.go

lib/osutil: Skip setLowPriority in Windows if already lower (fixes #6597)
Currently, setLowPriority always changes the process priority to "below
normal" even if the current priority is already equal or lower than
that. With this change, the process priority is changed only if the
current priority is higher than "below normal".

lib/osutil: Skip setLowPriority in Windows if already lower (fixes #6597)

---

lib/model/model.go

Use the WARNING log level for "Unexpected folder" messages.
So, this Syncthing client never complained that it could not sync a certain director^W folder to the Syncthing server. And with INFO messages ignored by monitoring, only logging in to the Syncthing GUI revealed that this new folder needed to be accepted by the server to be synced. As unexpected folder incidents may be uncommon enough, I feel WARNING to be more appropriate here.
none
n/a
n/a

model.go: use WARNING for "Unexpected folder" messages

---

lib/ur/usage_report.go

lib/ur: Don't report uptime if start time is in the past (fixes #7698)
Currently, because of devices with unset RTC clock, the 100% percentile
for Uptime on [1] is calculated since the Unix epoch which is useless as
far as usage statistics are concerned. Thus, if the Syncthing start time
is set to a past date, assume that the clock is wrong and do not even
try to report the uptime.
[1] https://data.syncthing.net

lib/ur: Don't report uptime if start time is in the past (fixes #7698)

---

gui/default/assets/lang/lang-en.json
gui/default/index.html

gui: Remove Twitter link from footer
There is a Twitter link at the very bottom of the GUI. However, the page
seems rather dead, as almost no updates or information have been posted
there for a long time. On top of that, Twitter has recently switched to
a login wall, meaning that without logging in, people cannot even access
the site.
Because of the above, remove the Twitter link from the GUI altogether.

gui: Remove Twitter link from footer

---

lib/api/api_auth.go
lib/api/api_csrf.go
lib/api/api_test.go

Currently, historically, we look for the `X-API-Key` header to authenticate with an API key. There's nothing wrong with this, but in some scenarios it's easier to produce an `Authorization` header with a `Bearer $token` content, which is nowadays more common. This change adds support for both, so that we will accept an API key either in our custom header or as a bearer token.

lib/api: Allow `Bearer` authentication style with API key

---

lib/api/api_test.go

Originally discovered on commit f71387cc841ca9f7a7c0c9aaebb9a67cd1556e9a in PR #8757. Commit 855c6dc67b96abdd1afcc66bad262bb9849d9189 introduces a data race in `TestCSRFRequired` because of how the `resp, err` variables are reused between the parallel test routines.
- Commit 2296c387137362781f5c6d23d05f402d60410f32 should fairly reliably reveal the data race. If not, increase the delay in `dataRaceSleep` and re-run the test.
- Commit 96013c373d005d736e1c72615b219540c62df615 fixes the data race.
- Commit 61c65ff1773a197a9cbf40efd24b3c48b5fe9df2 removes the delays introduced in 2296c387137362781f5c6d23d05f402d60410f32.
N/A

Fix data race in TestCSRFRequired

---

cmd/strelaysrv/listener.go

Fixes the crash when debugging a nil conn and, as a bonus, makes sure to actually close it when required.

cmd/strelaysrv: Handle accept error with debug set (fixes #9001)

---

gui/default/assets/css/overrides.css
gui/default/syncthing/device/editDeviceModalView.html

gui: Fix tooltips on buttons inside button groups (ref #7984)
As per Bootstrap recommendation, buttons with tooltips inside button
groups require to have container: 'body' set. This prevents tooltips
from causing the buttons to jump on hover and also allows the tooltips
to be wider instead of wrapping on every space.
Ref: https://getbootstrap.com/docs/3.3/components/#btn-groups

gui: Fix tooltips on buttons inside button groups (ref #7984)

---

lib/connections/quic_unsupported.go

Upcoming Go 1.21 needs quic-go 0.37.0, while Syncthing is not compatible with that version yet (#8930). This fix allows building Syncthing with Go 1.21 for testing purposes.
Building Syncthing with [go1.21rc3](https://go.dev/dl/go1.21rc3.linux-amd64.tar.gz) and run it.
(no documentation changes needed)

lib/connections: fix building with `-tags noquic`

---

lib/api/api_test.go
lib/model/fakeconns_test.go
lib/model/folder_recvonly_test.go
lib/model/folder_sendrecv_test.go
lib/model/indexhandler.go
lib/model/mocks/model.go
lib/model/model.go
lib/model/model_test.go
lib/model/progressemitter.go
lib/model/progressemitter_test.go
lib/model/requests_test.go
lib/model/testutils_test.go
lib/protocol/benchmark_test.go
lib/protocol/common_test.go
lib/protocol/encryption.go
lib/protocol/mocks/connection.go
lib/protocol/nativemodel_darwin.go
lib/protocol/nativemodel_unix.go
lib/protocol/nativemodel_windows.go
lib/protocol/protocol.go
lib/protocol/protocol_test.go

These are refactoring changes made in the multiple-connection PR (#8918), broken out to reduce the noise there. Hence reviewing it requires some suspension of disbelief in terms of whether these changes are necessary -- they are, over there, but not necessarily by themselves over here... :) The changes are:
- In `lib/protocol`, `func (Connection) ID() DeviceID` is now called `func (Connection) DeviceID() DeviceID()` to disambiguate it from future other kind of IDs (the connection ID).
- Also in `lib/protocol`, all the callbacks used to take the device ID as the first parameter to explain where they came from. These now get the actual Connection instead, which is more specific and enables things like replying on the same connection. There's some juggling to accomplish this, because the …

all: Refactor the protocol/model interface a bit (ref #8981)

---

gui/default/syncthing/core/syncthingController.js

gui: Use case-insensive versions filter and allow backslashes as path separators (fixes #7973)
Currently, the versions filter is case-sensitive regardless of the
underlying OS. With this change, the filter becomes case-insensitive
everywhere, which is more user-friendly and makes it easier to search
for files whose exact case the user may not remember.
In addition, allow backslashes to be used as filter path separators.

gui: Use case-insensive and backslash-agnostic versions filter (fixes #7973)

---

lib/model/folder_sendrecv.go

The call to set state to idle was removed in
https://github.com/syncthing/syncthing/commit/b9c08d3814685bc8c4a322756e042b9852e321b4#diff-8581eb7670c1f6463c9d9254d863d9137906c6055baeb124b9518ddabfc94167 for no reason I can discern. This results in folders apparently stuck "preparing to sync" when there is nothing for them to sync (they are actually idle). This reinstates it.

lib/model: Reinstate setting folder idle state

---

lib/osutil/net.go
lib/upnp/upnp.go

lib/osutil, lib/upnp: Check FlagRunning

---

lib/model/fakeconns_test.go
lib/model/indexhandler.go
lib/model/model.go
lib/model/model_test.go
lib/model/service_map.go
lib/model/service_map_test.go
lib/model/util.go

This is an alternative to #9035. There's a certain amount of overengineering here, possibly, but hear me out...
- There's a new thing called a `serviceMap`. This is essentially a map of key -> service plus key -> Suture-token and some management to make sure that adding and removing things from the map does the right things for the services in question. This reduces boilerplate since we have this pattern in a couple of places. The serviceMap is itself a Service that runs the children.
- The index handler registry now uses one of these to manage the index handlers
- The model now uses one of these to manage the index handler registries
- I think it all works out quite nicely, stopping one thing stops all the children, and we now remove (stop) the index handler registry for a device when we …

lib/model: Clean up index handler life cycle (fixes #9021)

---

lib/beacon/broadcast.go
lib/beacon/multicast.go
lib/upnp/upnp.go

Follow up PR for #9047 which adds the check to broadcast/multicast discovery.

lib/beacon: Check FlagRunning

---

lib/connections/util.go

Fixes #7456
The allowed IPv4 ranges are the same as before. But we now also accept IPv6 addresses in the ULA range `FC00::/7`. These addresses don't require an interface identifier and are roughly equivalent to the IPv4 private ranges.
Typical usecases:
* VPN interface IPs: Wireguard, OpenVPN, Tailscale, ...
* fixed IPv6 LAN addressing while the provider assigns a dynamic prefix. e.g used by pihole
https://cs.opensource.google/go/go/+/refs/tags/go1.21.0:src/net/ip.go;l=146
I checked the output of https://discovery.syncthing.net/?device=xxxxxxxxxxxxxxxxxxxx and my local `fd00::` IPs were listed.

lib/connections: allow IPv6 ULA in discovery

---

lib/discover/global.go

By creating the http.Transport and tls.Configuration ourselves we override some default behavior and end up with a client that speaks only HTTP/1.1.
This adds a call to http.ConfigureTransport to do the relevant magic to enable HTTP/2.
Also tweaks the keepalive settings to be a little kinder to the server(s) and adds a minimum TLS version requirement of TLS/1.2.

lib/discover: Enable HTTP/2 for global discovery requests

---

lib/upgrade/upgrade_supported.go

Same reasoning and mechanism as #9059. I verified that this still works with a manual `./syncthing -upgrade`

lib/upgrade: Enable HTTP/2 for upgrade checks

---

gui/default/assets/lang/lang-en.json
gui/default/index.html

gui: Show in GUI if limitBandwidthInLan is enabled
Currently, it is impossible to know whether the limitBandwidthInLan
option is enabled without going into the Advanced Configuration. With
this change, a note is added next to the bandwidth limit information
that informs the user that the limits are applied to LAN connections
too.

gui: Show in GUI if limitBandwidthInLan is enabled

---

gui/default/syncthing/device/editDeviceModalView.html
gui/default/syncthing/device/idqrModalView.html

gui: Automatically select device ID on click (ref #8544)
The CSS method to select device IDs on click was added in [1]. However,
it was later mistakenly overwritten by [2]. This commit fixes the
regression and also applies the same behaviour to the Edit Device modal
which was omitted in the original commit.
[1] 5baf5fedb5bf3acacc8eb5874a4ed10efd3effb8
[2] 5e384c918567c6b92b9ae63413639dcf9628b98e

gui: Automatically select device ID on click (ref #8544)

---

gui/default/syncthing/core/syncthingController.js

gui: Fix lastSeenDays error due to undefined deviceStats when adding new devices (ref #8730)
When adding new devices, the GUI may throw errors about being unable to
read properties of undefined when trying to read lastSeenDays. This is
because deviceStats may not yet exist at the very moment of adding a new
device. To prevent the error, add yet another check to see whether
deviceStats exists before trying to read lastSeenDays.
The GUI sometimes gets flooded with these errors right after adding a new device. I've experienced the problem for a long time, however I'm still unable to reproduce it at will. It seems to only happen in existing installations, only after running for some time, and still not always, so I'm not really sure why …

gui: Fix lastSeenDays error due to undefined deviceStats when adding new devices (ref #8730)

---

gui/default/assets/css/overrides.css
gui/default/index.html

gui: Remove footer and move links to header (fixes #5607)
Currently, the footer is always present and takes space at the bottom of
the GUI. However, the links listed there are not part of everyday user
interaction, and as such, they unnecessarily clutter the page, reducing
the usable screen space. Thus, transform the current Help link in the
header into a Help dropdown menu, and move the links from the footer
into it.
Also apply the following tweaks:
1. Move the About dialog from Actions to Help.
2. Add an Introduction (to the GUI) link to Help.
3. Change the Support icon from a question mark to a group of people.
4. Change the Changelog and About icons to a filled version to match the
other icons better.
5. Use a source code icon for Source Code instead of a wrench icon, and
move the …

gui: Remove footer and move links to header (fixes #5607)

---

gui/default/syncthing/core/logViewerModalView.html

The Logs icon was changed in [1] in the header, however the icon used in the modal was left out. This changes it, so that the header and the modal icons match.
[1] 2abba1dfb0f3337dd1e77c6584e7d12bdba284b9

gui: Fix Logs modal icon to match header icon (ref #9067)

---

gui/default/index.html
gui/default/syncthing/folder/editFolderModalView.html

Currently, different icons are used for File Versioning when displayed in the unfolded folder info in the main part of the GUI, and the icon used in the Edit Folder modal. This changes the main GUI icon to match the icon used in the modal.

gui: Fix File Versioning icon to match in all places

---

gui/default/index.html

gui: Don't hide default values for folders and devices
Currently, some of the information for folders and devices displayed in
the GUI relies on arbitrary values that come pre-set as defaults on a
fresh Syncthing installation, i.e. if the value matches the default, it
is hidden, and if does not, then it is displayed.
With this change, the GUI always displays all information regardless
of their value, making the overall experience more consistent and
predictable.

gui: Don't hide default values for folders and devices

---

lib/model/folder_recvonly_test.go
lib/model/folder_sendrecv_test.go
lib/model/indexhandler.go
lib/model/model.go
lib/model/model_test.go
lib/model/requests_test.go
lib/model/service_map.go
lib/model/service_map_test.go

Instead of separately tracking the token.
Also changes serviceMap to have a channel version of RemoveAndWait, so that it's possible to do the removal under a lock but wait outside of the lock. And changes where we do that in connection close, reversing the change that happened when I added the serviceMap in 40b3b9ad1.

lib/model: Refactor folderRunners to use a serviceMap

---

lib/connections/tcp_listen.go

This PR cherry-picks the fix for the bug in tcp_listen.go discovered in #9010, which caused only `0.0.0.0` to be returned as the IP address.
This has been tested in the context of the merge request. The code still builds with just this commit applied.

Fix WANAddresses returning only unspecified IPs

---

gui/default/syncthing/device/editDeviceModalView.html

Like so:
---
(An interesting side effect of our versioned documentation switcheroo is that this link currently doesn't work. It points to `...?version=v1.24.1`, but there is no 1.24.1 so the site redirects to version 1.24.0, and there the page is 404... Maybe we should just default to latest if the requested version is > latest tagged...)

gui: Add help link for numConnections

---

lib/versioner/util.go

https://forum.syncthing.net/t/versioner-error-scanning-versions-dir-context-canceled-when-trying-to-clean-versions/20778/2

lib/versioner: Don't complain when folder is stopping

---

lib/connections/service.go

* always treat link-local IPs as LAN
* if we're unable to determine our local networks, simply treat private IPs as LAN

lib/connections: Make assumptions about isLAN when interface address listing fails

---

gui/default/syncthing/device/globalChangesModalView.html

gui: Remove unused hard-coded styles from Recent Changes modal
Currently, the Recent Changes modal has hardcoded th and td
styles. However, they are not even used in the modal itself, because
Bootstrap overrides them with its own styles for these elements in the
same modal. Yet, when hard-coded like that, these styles can conflict
with other table elements in the GUI. Thus, remove them completely.
As seen below, the styles are overridden by Bootstrap in multiple places. I only found them, because they were messing up my table from https://github.com/syncthing/syncthing/pull/9094.

gui: Remove unused hard-coded styles from Recent Changes modal

---

gui/default/syncthing/core/syncthingController.js

gui: Block GUI when saving changes only if necessary (ref #9063)
Currently, the UI is always blocked from modifications when changes are
being saved, even if the save process takes very little time. This leads
to a situation where showing and closing the blocking modal can take
more time than is actually required to perform the whole operation. The
modal opening and closing very quickly can also cause the screen to
flash for a brief moment, leading to visual discomfort.
Because of this, wait for at least 200 ms and only show the blocking
modal if the changes have not been saved until then yet. The value of
200 ms is loosely based on [1] which states that 'a delay of 0.2–1.0
seconds does mean that users notice the delay and thus feel the computer
is "working" on the command, as opposed to …

gui: Block GUI when saving changes only if necessary (ref #9063)

---

lib/fs/metrics.go
lib/model/util.go

I don't really understand under what circumstances, but sometimes these calls panic with a "panic: counter cannot decrease in value" because the value passed to Add() was negative.

lib/fs, lib/model: Be careful about potentially negative durations (fixes #9112)

---

lib/connections/structs.go

Fixes #8274
The actual local address is not resolved for a QUIC connection, and will always report what we've passed to the listener. A dual-stack enabled host would simply return `[::]:xxxxx`, which is interpreted as `quic6`.
The remote address doesn't suffer from this problem.
https://github.com/syncthing/syncthing/issues/8274#issuecomment-1722490987

lib/connections: fix transport type detection for QUIC

---

gui/default/syncthing/core/syncthingController.js

gui: Add missing $scope in editDeviceUntrustedChanged function
Because $scope is missing, there are JavaScript errors when ticking and
unticking the "Untrusted" checkbox in the Advanced tab of the Edit
Device modal.

gui: Add missing $scope in editDeviceUntrustedChanged function

---

.gitignore

Ignore *.exe files by git.
After PR discussion .idea and .vscode removed from .gitignore.
Tested using git.
No changes.

adding exe files and .vscode to .gitignore

---

gui/default/index.html

gui: Show if device has Auto Accept enabled in GUI
Add a new entry to the unfolded device info to inform the user that the
device has Auto Accept enabled.

gui: Show if device has Auto Accept enabled in the main GUI

---

gui/default/index.html

gui: Show if device is untrusted in the main GUI
Add a new entry to the unfolded device info to inform the user that the
device has been marked as "untrusted" and all folders shared with it
have to be password-protected or already Receive Encrypted.

gui: Show if device is untrusted in the main GUI

---

gui/default/syncthing/core/logViewerModalView.html
gui/default/syncthing/core/syncthingController.js

That's a small usability feature enabling to scroll to the bottom in the log viewer by clicking 'Log tailing paused. Scroll to the bottom to continue.' (in the respective language).

gui: Scroll to bottom by clicking message in log viewer

---

cmd/ursrv/serve/serve.go

cmd/ursrv: Support new android build user

---

cmd/ursrv/serve/serve.go

See https://github.com/syncthing/syncthing/issues/9140#issuecomment-1741070101
Found a reddit [thread](https://old.reddit.com/r/docker/comments/13vq2ka/my_syncthing_container_refuses_to_write_to_my/) that confirmed my suspicion that `root@buildkitsandbox` is used by LinuxServer.io images.
https://docs.linuxserver.io/images/docker-syncthing

cmd/ursrv: Add linuxserver.io detection

---

lib/model/model.go

Reject the config instead of panicking when a bad versioning config is specified.

lib/model: Verify versioning on configuration reload (fixes #9106)

---

script/docker-entrypoint.sh

Maybe it fails, maybe it doesn't. If it fails and we didn't need it we don't need to complain. If it fails and we did need it, we'll fail on the next line instead.

docker: Allow start even if chown fails (fixes #9133)

---

lib/api/api_auth.go
lib/api/api_auth_test.go

Now handles an arbitrary number of username replacements. Also add some escaping for good measure.

lib/api: Better handle %s templates in LDAP strings (fixes #9072)

---

lib/api/api_auth.go
lib/api/api_test.go

This is motivated by the Android app: https://github.com/syncthing/syncthing-android/pull/1982#issuecomment-1752042554
The planned fix in response to basic auth behaviour changing in #8757 was to add the `Authorization` header when opening the WebView, but it turns out the function used only applies the header to the initial page load, not any subsequent script loads or AJAX calls. The `basicAuthAndSessionMiddleware` checks for no-auth exceptions before checking the `Authorization` header, so the header has no effect on the initial page load since the `/` path is a no-auth exception. Thus the Android app fails to log in when opening the WebView.
This changes the order of checks in `basicAuthAndSessionMiddleware` so that the `Authorization` header is always checked if present, and a …

Check basic auth (and set session cookie) before noauth exceptions

---

cmd/ursrv/serve/serve.go

This commit replaces "2006-01-02" to time.DateOnly. time.DateOnly is introduced since Go1.20
This commit replaces "2006-01-02" to time.DateOnly. time.DateOnly is introduced since Go1.20

cmd/ursrv:  : replace "2006-01-02" to time.DateOnly

---

gui/default/index.html
gui/default/syncthing/core/syncthingController.js
lib/api/confighandler.go
lib/config/guiconfiguration.go

This was an oversight in #8757: the new "Log out" button is always shown in the "Actions" menu, even when authentication is not enabled.
These manual tests have been done:
1. With authentication disabled (set username to empty): click the "Actions" menu. Verify that the "Log out" button is not shown.
2. Set a username and password and log back in. Click the "Actions" menu. Verify that the "Log out" button is shown.
3. Unset the username and save the config. Click the "Actions" menu. Verify that the "Log out" button is again not shown (do not refresh the page after saving the config).
Before (3d0da5ac60ab02cf47ca5cd4fada48cc70360ec9):
After (f032f079db283967423784ec3e3aadeb6ee2f755):
No changes needed.

Hide log out button when auth is not enabled

---

lib/fs/basicfs_fileinfo_linuxish.go

lib/fs: Fix conflicts on Android due to fluctuating inode change time
[1] added inode change time to file info in order to support syncing
extended attributes. However, in the case of Android, this inode change
time fluctuates, leading to unexpected conflicts even when the user has
not even touched the files on the Android device itself. Thus, in order
to prevent those conflicts from happening, do not write inode change
time on Android.
[1] 6cac308bcdf197f4bbe8bd36725d9ac92a622559

lib/fs: Fix conflicts on Android due to fluctuating inode change time

---

lib/locations/locations.go
lib/locations/locations_test.go

This makes the new default $XDG_STATE_HOME/syncthing or ~/.local/state/syncthing, while still looking in legacy locations first for existing installs.
Note that this does not *move* existing installs, and nor should we. Existing paths will continue to be used as-is, but the user can move the dir into the new place if they want to use it (as they could prior to this change as well, for that matter).
Needs update to the config docs about our default locations.

lib/locations: Change default config/data location to new XDG recommendation (fixes #9178, fixes #9179)

---

lib/locations/locations.go
lib/locations/locations_test.go

The new, supposedly better variable expansion would eradicate `${timestamp}` that was previously left alone. Now, instead, call it `%{timestamp}` to differentiate. Add a test to make sure it continues working.

lib/location: Fix regression of timestamp handling (ref #9180)

---

cmd/stdiscosrv/apisrv.go
cmd/stdiscosrv/apisrv_test.go

Treat X-Forwarded-For as a comma separated string to prevent Nil IP being returned by the Discovery Server
Fixes: [9189](https://github.com/syncthing/syncthing/issues/9189
)
Unit Tests implemented
Testing with a Discovery Client can be done as follows:
```
A simple example to replicate this entails running Discovery with HTTP, use Nginx as a reverse proxy and hardcode (as an example) a list of IPs in the X-Forwarded-For header.
1. Send an Announcement with tcp://0.0.0.0:<some-port>
2. Query the DeviceID
3. Observe the returned IP Address is no longer nil; i.e.  `tcp://<nil>:<some-port>`
```
Vishal A. Patel

Prevent Discovery from returning Nil IP (fixes #9189)

---

.github/workflows/build-syncthing.yaml

We use `env.GO_VERSION` as cache key for the build cache, but this is nowadays typically something like `~1.21.1` which doesn't change when 1.21.2, 1.21.3 etc are released, making the cache fairly useless as everything gets rebuilt. This re-sets the `GO_VERSION` variable after installing Go so that it contains the actual installed version.

build: Use actual Go version as cache key

---

gui/default/assets/lang/lang-en.json
gui/default/index.html
gui/default/syncthing/app.js
script/translate.go

This was extracted from PR #9175 as requested in https://github.com/syncthing/syncthing/pull/9175#discussion_r1370183132 .
In summary: some translations, especially single words or other short labels for buttons and the like, may not be transferable between contexts even if they happen to be equal in English. In these cases, setting an explicit translation ID is important for context separation. Angular Translate also supports nested JSON in translation tables, addressed using `.` as namespace separator; this enhancement makes use of this when extracting translation with an explicit translation ID.
See also the motivation I laid out in https://github.com/syncthing/syncthing/pull/9175#discussion_r1369930826 :
>```diff
>+<th><label …
```

 Support explicit translation ID and dotted namespaces in translation extraction 

---

.github/workflows/build-infra-dockers.yaml
.github/workflows/build-syncthing.yaml
Dockerfile
Dockerfile.builder
Dockerfile.stcrashreceiver
Dockerfile.stdiscosrv
Dockerfile.strelaypoolsrv
Dockerfile.strelaysrv
Dockerfile.stupgrades

The OCI image spec specifies well-defined [annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md) that can be added to images.
Theses annotations can then be used by other tools to gather more information of an image.
This PR adds the `org.opencontainers.image.source` to allow tools such as [renovate](https://github.com/renovatebot/renovate) to find the release notes of a give version.
~~I've only done this change for `Dockerfile`. Should I also add the label to the other dockerfiles?~~
I've now added the source annotations to all `Dockerfile`s & action workflows.
None, change was done by following the [renovate documentation](https://docs.renovatebot.com/modules/datasource/docker/).
based on …

Add `org.opencontainers.image.source` to Dockerfiles

---

cmd/ursrv/serve/static/index.html

To see that https://data.syncthing.net is open source, study the code and change it.
The bottom line of the https://data.syncthing.net/ should include the link to https://github.com/syncthing/syncthing/tree/main/cmd/ursrv

Link to data.syncthing.net source code

---

gui/default/assets/lang/lang-en.json
gui/default/syncthing/core/syncthingController.js

gui: Allow to translate "unknown device"
The string is currently hard-coded in English, so allow to translate it
into other languages. It appears mainly in the browser title bar before
logging in into the GUI or when the GUI is still loading.

gui: Allow to translate "unknown device"

---

lib/model/model.go

Towards the end of the function f.folderCfgs and f.folderRunners are read without the lock.

lib/model: Acquire fmut lock in ensureIndexHandler (fixes #9234)

---

gui/default/assets/css/overrides.css
gui/default/syncthing/folder/editFolderModalView.html

Discovered while working on the WebAuthn credentials table in #9175: there's a style on `td input[type="checkbox"]` that modifies margins for all checkboxes in `<table>`s. It looks like this style is specially tailored to the particular table that added it (PR #8734), so it should have a correspondingly special-purpose class to not accidentally apply it to other tables.
As best as I could tell there are only 2 instances of `<input type="checkbox">` in `<td>`s, shown in the screenshots below.
- Open "Actions > Logging > Debugging Facilities" and observe the vertical spacing of the checkboxes.
- Open "Edit Folder > Advanced", check "Sync Extended Attributes" or "Send Extended Attributes", click "Add filter entry" and observe the vertical spacing of the checkbox that appears.
Logs > …

Specialize a special-purpose checkbox style

---

lib/model/model.go

LastSeen for a device was only updated when they connected. This now updates it when they disconnect, so that we remember the last time we actually saw them. When asking the API for current stats, currently connected devices get a last seen value of the current time.

lib/model: Improve LastSeen handling

---

.github/workflows/build-infra-dockers.yaml
.github/workflows/build-syncthing.yaml

This reverts commit e477777f49ab2dd7cf3f29b88b4254ddb7e79f9b.
In principle, we could have stayed with `~1.21.1`, but `check-latest: true` apparently checks some cache/manifest/something that is only periodically refreshed and isn't aware of 1.21.5 yet. So update the constraints to force an upgrade.
Also the infrastructure images weren't actually using the constraint since there was no `setup-go` action...

build: Revert specifics for Go 1.21.4, build using Go 1.21.5

---

lib/model/model.go
lib/model/service_map.go

Before introducing the service map and using it for folder runners, the entries in folderCfgs and folderRunners for the same key/folder were removed under a single lock. Stopping the folder happens separately before that with just the read lock. Now with the service map stopping the folder and removing it from the map is a single operation. And that still happens with just a read-lock. However even with a full lock it’s still problematic: After the folder stopped, the runner isn’t present anymore while the folder-config still is and sais the folder isn't paused.
The index handler in turn looks at the folder config that is not paused, thus assumes the runner has to be present -> nil deref on the runner.
A better solution might be to push most of these fmut maps into the folder - they …

lib/model: Remove runner during folder cleanup (fixes #9269)

---

cmd/syncthing/cli/main.go

Seems to work for me, @AudriusButkevicius.

cmd/syncthing: Better cli stdin handling (ref #9166)

---

lib/model/folder.go

On kqueue-systems, folders listen for folder summaries to (be able to) warn for potential high resource usage. However, it listened for any folder summary and not for the summary which matches the folder it's about. This could cause that an unwatched folder causes a folder summary containing more files than the threshold (10k), and the listening folder (with the watcher enabled) triggers the warning.
This makes sure that only the folder summaries which are relevant to the specific folder are being handled.
- Fire up some kqueue-system (freebsd, I used).
- add folder A, disable the watcher, add 10001 files
- add folder B with the watcher enabled, no files are needed here
Before the change:
- add an item to folder A, trigger a rescan to speed up the process
- wait some seconds...warning …

lib/model: Only handle relevant folder summaries (kqueue) (fixes #9183)

---

etc/linux-desktop/syncthing-ui.desktop

Use a style for options that is consistent with the documentation and other uses.

etc/linux-desktop: use double dash for long options

---

lib/protocol/bep_extensions.go

If syncOwnership is enabled and the remote uses for example a dockerized Syncthing it can't fetch the ownername and groupname of the local instance. Without this patch this led to an endless cycle of detected changes on the remote and failing re-sync attempts.
This patch skips comparing the ownername and groupname if they are empty on one side.
See https://github.com/syncthing/syncthing/issues/9039 for details.
Proposed by @calmh in https://github.com/syncthing/syncthing/issues/9039#issuecomment-1870584783 and tested locally in my setup,
Setup PC 1:
- Syncthing is run in Docker as user `root` and has none of the users configured that synchronize their files
Setup PC 2:
- this PC has all users locally setup
- Syncthing runs as `systemd` service as user `syncthing` and has multiple …

lib/protocol: handle empty names in unixOwnershipEqual (fixes #9039)

---

gui/default/syncthing/core/syncthingController.js
lib/scanner/walk.go

This adresses a few things that came up in issue #8331. It might fix the issue, or it might not - it's not that clear-cut what exactly is happening there.
This avoids sending progress updates when there is nothing to hash. And ensures we send a final progress update when things are done. And in that latter case, avoid showing 100% in the UI while the scan is wrapping up.

gui, lib/scanner: Improve scan progress indication (ref #8331)

---

gui/default/index.html
gui/default/syncthing/app.js
gui/default/syncthing/core/syncthingController.js
lib/protocol/deviceid.go
lib/protocol/deviceid_test.go
next-gen-gui/src/app/api-utils.ts

Making short deviceID length consistent and referencing to protocol file for future-proof edits. Closes #9313.

gui: Keep short deviceID length consistent + xrefs (fixes #9313)

---

lib/build/build.go
lib/build/build_test.go

lib/build: Allow semver build in version regex (fixes #9267)

---

gui/default/syncthing/folder/restoreVersionsModalView.html

gui: Always inform about loading data in Restore Versions modal
Currently, with a large number of versioned files, there is a delay
between the Restore Versions modal showing up on the screen and
initialisation of the actual versions tree. This leads to a situation,
where the modal is initially empty, which confuses the user, making
them think that something is not working correctly.
To avoid the above, always show the loading data information. The string
is displayed using static HTML first, and then replaced with the exact
same content once the tree has been initialised. Both elements use the
same style and position, so there is no visual shift between the two.

gui: Always inform about loading data in Restore Versions modal

---

README.md

https://syncthing.net/security/
html file does not exist
Fixing link that is supposed to link to https://syncthing.net/security/

Fix website security link in README.md

---

lib/model/folder_recvonly_test.go
lib/scanner/walk.go

This PR changes behaviour of syncthing related to `receive-only` folders, which I believe to be a bug since I wouldn't expect the current behaviour. With the current syncthing codebase, a file of a `receive-only` folder that is only modified locally can cause the creation of a `.sync-conflict` file.
Consider this szenario: Setup two paired clients that sync a folder with a given file (e.g. `Test.txt`). One of the clients configures the folder to be `receive-only`. Now, change the contents of the file for the receive-only client **_twice_**.
With the current syncthing codebase, this leads to the creation of a `.sync-conflict` file that contains the modified contents, while the regular `Test.txt` file is reset to the cluster's provided contents. This is due to a …

lib/scanner: Prevent sync-conflict for receive-only local modifications 

---

lib/versioner/simple_test.go
lib/versioner/util.go

Fix #9241 by expanding tildes in version paths.
When creating the versioner file system, first try to expand any leading tildes to the user's home directory before handling relative paths. This makes a version path `"~/p"` expand to `"$HOME/p"` instead of `"/folder/~/p"`.
Added a test to lib/versioner that exercises this code path. Also manually tested with local syncthing instances.

lib/versioner: expand tildes in version directory (fixes #9241)

---

lib/fs/basicfs_watch.go
lib/fs/basicfs_watch_test.go
lib/fs/filesystem.go
lib/ignore/cache.go
lib/ignore/cache_test.go
lib/ignore/ignore.go
lib/ignore/ignore_test.go
lib/ignore/ignoreresult/ignoreresult.go
lib/ignore/ignoreresult/ignoreresult_foldcase.go
lib/ignore/ignoreresult/ignoreresult_nofoldcase.go
lib/model/folder_sendonly.go
lib/model/folder_sendrecv.go

This moves Result into a package of its own and cleans up the related naming a bit. The ShouldIgnore() method goes away, instead callers use the Match() method directly.
This enables the work in #9339.

lib/ignore: Refactor out result type

---

lib/fs/basicfs_watch.go
lib/fs/filesystem.go
lib/ignore/ignore.go
lib/ignore/ignore_test.go
lib/ignore/ignoreresult/ignoreresult.go
lib/ignore/ignoreresult/ignoreresult_test.go
lib/scanner/walk.go
lib/scanner/walk_test.go

This improves the ignore handling so that directories can be fully ignored (skipped in the watcher) in more cases. Specifically, where the previous rule was that any complex `!`-pattern would disable skipping directories, the new rule is that only matches on patterns *after* such a `!`-pattern disable skipping. That is, the following now does the intuitive thing:
```
/foo
/bar
!whatever
*
```
- `/foo/**` and `/bar/**` are completely skipped, since there is no chance anything underneath them could ever be not-ignored
- `!whatever` toggles the "can't skip directories any more" flag
- Anything that matches `*` can't skip directories, because it's possible we can have `whatever` match something deeper.
To enable this, some refactoring was necessary:
- The "can skip dirs" flag is now a …

Optimise ignoring directories for filesystem watcher (fixes #9339)

---

cmd/ursrv/serve/serve.go

Classify `syncthing@archlinux` as `Arch (3rd party)`

cmd/ursrv: Fix Arch detection

---

cmd/ursrv/serve/serve.go

Classify `ports@freebsd` as `FreeBSD (3rd party)`

cmd/ursrv: Add FreeBSD detection 

---

gui/default/index.html

gui: Remove non-functional HTML from External Versioning tooltip (ref #8923)
Since [1], it is no longer possible to use HTML in tooltips. This was
addressed in [2], however the commit missed one instance of HTML that
was used to change the font type of the External versioning command
tooltip. This remaining HTML is removed in this commit.
[1] f5e5af391a6583047c64ef8c51642003a79b75cf
[2] 73c52eafb6566435dffd979c3c49562b6d5a4238

gui: Remove non-functional HTML from External Versioning tooltip (ref #8923)

---

lib/fs/basicfs_watch.go
lib/ignore/ignore.go

Add invalid UTF-8 guards to fix #9369. Probably not a permanent fix, but putting it up here in case someone else encounters the same panic.
All tests pass. I was going to add a test to `basicfs_watch` but there doesn't seem to be a straightforward way to test for unexpected events.

lib/fs: Add invalid UTF-8 guards to Matcher and Watcher (fixes #9369)

---

lib/model/fakeconns_test.go
lib/model/folder_recvonly_test.go
lib/model/folder_sendrecv_test.go
lib/model/mocks/model.go
lib/model/model.go
lib/model/model_test.go
lib/model/requests_test.go
lib/model/testutils_test.go
lib/protocol/benchmark_test.go
lib/protocol/common_test.go
lib/protocol/encryption.go
lib/protocol/nativemodel_darwin.go
lib/protocol/nativemodel_windows.go
lib/protocol/protocol.go
lib/protocol/protocol_test.go

This is a refactor of the protocol/model interface to take the actual message as the parameter, instead of the broken-out fields:
```diff
type Model interface {
// An index was received from the peer device
-       Index(conn Connection, folder string, files []FileInfo) error
+       Index(conn Connection, idx *Index) error
// An index update was received from the peer device
-       IndexUpdate(conn Connection, folder string, files []FileInfo) error
+       IndexUpdate(conn Connection, idxUp *IndexUpdate) error
// A request was made by the peer device
-       Request(conn Connection, folder, name string, blockNo, size int32, offset int64, hash []byte, weakHash uint32, fromTemporary bool) (RequestResponse, error)
+       Request(conn Connection, req *Request) (RequestResponse, error)
// A …
```

lib/protocol: Refactor interface

---

lib/api/debug.go
lib/logger/logger.go

There is no need to expose the IsTraced() thing; it's just used in initialisation, and thereafter ShouldDebug() is the corresponding correct call.

lib/logger: Reduce API surface

---

lib/model/indexhandler_test.go

The new test has a flakiness factor on slow platforms, where the close on the sending connection races with the last index message, potentially messing up the count. This adds a wait to ensure that all sent messages are received, or the test will eventually fail with a timeout.

lib/model: Deflake new IndexHandlerTest

---

lib/api/api_test.go

Somewhere along the way, the non-parallel test became parallel, and at that point, timeouts occurred. Parallel is better, so increase the timeout on the offending call a bit...

lib/api: Deflake TestAPIServiceRequests

---

.github/workflows/build-syncthing.yaml

The changes to go.mod in latest Go 1.21/1.22 are not fully understood by older Go that might be pre-installed on builds, so make sure we always have a modern one in place even for running small release scripts etc.

build: Use correct Go version also for script runs

---

README-Docker.md
script/docker-entrypoint.sh

Add support for setting umask value in the Docker `entrypoint.sh` script. This is useful when
not syncing permissions and working with groups, and needing umask values like `002` instead of `022`.
This is vaguely related to https://github.com/syncthing/syncthing/pull/5857 but as this
is about the Docker setup I figured it might be worth trying a PR.
Since the current setup uses entrypoint instead of a combination of entrypoint and command,
I had to edit `entrypoint.sh`.
An alternative workaround for not adding the `UMASK` environment variable would be to set:
```dockerfile
ENTRYPOINT ["/bin/entrypoint.sh"]
CMD ["/bin/syncthing"]
```
That way it would be easier for the user to change the command in the `compose.yml` to something like:
```yml
command: "/bin/sh -c 'umask 002 && …
```

Add Docker umask Support

---

build.go
cmd/stcompdirs/main.go
cmd/stcrashreceiver/main.go
cmd/stdisco/main.go
cmd/stdiscosrv/main.go
cmd/stevents/main.go
cmd/stfileinfo/main.go
cmd/stfinddevice/main.go
cmd/stfindignored/main.go
cmd/stgenfiles/main.go
cmd/strelaypoolsrv/main.go
cmd/strelaysrv/main.go
cmd/strelaysrv/testutil/main.go
cmd/stsigtool/main.go
cmd/stupgrades/main.go
cmd/stvanity/main.go
cmd/stwatchfile/main.go
cmd/syncthing/main.go
cmd/ursrv/main.go
go.mod
go.sum

Go is not cgroup aware and by default will set GOMAXPROCS to the number of available threads, regardless of whether it is within the allocated quota. This behaviour causes high amount of CPU throttling and degraded application performance.
Fixes: #9435

all: Use Linux container CPU quota (fixes #9357, fixes #9435)

---

lib/model/folder_sendrecv.go

alternate solution (no longer just macOS specific) that adds a bool flag to `scanIfItemChanged()` to indicate when the scan was initiated from a delete function, and if so, tell `IsEquivalentOptional()` to ignore Xattrs and Ownership regardless of the global setting.
I tested this with my sledgehammer and it seems to pass.

lib/model: Ignore difference in extended attributes & ownership when deleting (fixes #9371)

---

lib/scanner/walk.go

Move the ticker closer to where it's used and defer stop it to avoid missing a branch.
Fixes regression introduced in https://github.com/syncthing/syncthing/commit/2f3eacdb6c1c33650ccdd91f42e842c116200d92
Fixes https://github.com/syncthing/syncthing/issues/9417

lib/scanner: Fix ticker leak in scanner (fixes #9417)

---

lib/model/indexhandler.go

Explanation of what/why in a code comment.
Fixes https://github.com/syncthing/syncthing/issues/9407

lib/model: Prevent infinite index sending loop (fixes #9407)

---

lib/model/indexhandler.go

This likely doesn't matter, as if the batch flush fails, the connection likely failed. So we'll get a new connection with a new cluster config and a new sequence to start from, thus it doesn't matter that we bump the sequence even though we didn't actually successfully sent the indexes. It's still wrong though :)

lib/model: Don't bump seq on error in index handler

---

README.md

Bountysource no longer exists and the readme link 404s. This removes the Bountysource link and corresponding readme section.
Perhaps the section should instead be replaced by other instructions for voting on features.

Removed no longer relevant Bountysource link

---

lib/db/keyer.go
lib/db/lowlevel.go
lib/db/schemaupdater.go

Resend our indexes since we fixed that index-sending issue.
I made a new thing to only drop the non-local-device index IDs, i.e., those for other devices. This means we will see a mismatch and resend all indexes, but they will not. This is somewhat cleaner as it avoids resending everything twice when two devices are upgraded, and in any case, we have no reason to force a resend of incoming indexes here.
It happens on my computer...

lib/db: Drop indexes for outgoing data to force refresh (ref #9496)

---

etc/linux-sysctl/30-syncthing.conf

In preparation for quic-go v0.43.0. see https://github.com/quic-go/quic-go/pull/4455

etc: Use 7MiB buffer size

---

lib/connections/metrics.go
lib/connections/service.go
lib/protocol/metrics.go

Adds a new metric `syncthing_connections_active` which equals to the amount of active connections per device.
Fixes #9527 
I've manually tested it by running syncthing with these changes locally and examining the returned metrics from `/metrics`.
I've done the following things:
- Connect & disconnect a device
- Increase & decrease the number of connections and verify that the value of the metric matches with the amount displayed in the GUI.
https://github.com/syncthing/docs/blob/main/includes/metrics-list.rst needs to be regenerated with [find-metrics.go](https://github.com/syncthing/docs/blob/main/_script/find-metrics/find-metrics.go)

lib/connections: Add syncthing_connections_active metric (fixes #9527)

---

lib/db/backend/leveldb_open.go
lib/db/namespaced.go
lib/db/structs.go

fix function names
Describe what testing has been done, and how the reviewer can test the change
if new tests are not included.
to the corresponding pull request on https://github.com/syncthing/docs or describe
the documentation changes necessary.

lib/db: Correct function name in comments

---

lib/config/folderconfiguration.go
lib/model/model.go

Avoid the issue where the folder marker is deleted by overzealous cleanup tools because it's just a useless, empty directory.
We create a small file containing a an admonishment to not delete the directory, and some metadata that is just for human consumption at the moment. (But it would parse as a valid yaml file if we wanted to read this, at some point.)
This will only apply when _creating_ a folder marker, that is, existing setups will not gain the file automatically. Obviously, when using a custom folder marker none of this applies.
I've created and deleted a few folders and it appears to behave as I expect.
```
jb@ok:~/somefolder % ls -la
total 0
drwxr-xr-x   3 jb  staff   96 May  1 08:52 ./
drwx------  12 jb  staff  384 May  1 08:52 ../
drwxr-xr-x   3 jb  staff   96 May  1 08:52 …
```

lib/config: Add file inside folder marker directory

---

gui/default/index.html
gui/default/syncthing/core/durationFilter.js
gui/default/vendor/HumanizeDuration.js/LICENSE.txt
gui/default/vendor/HumanizeDuration.js/Makefile
gui/default/vendor/HumanizeDuration.js/humanize-duration.js

https://github.com/syncthing/syncthing/pull/8291 inpired me to develop this. I tested it with all the languages Syncthing currently supports, and they all work.
The only issue is that when you change the language in the GUI, you have to either refresh the page, or wait a few seconds for the page to refresh by itself, before the duration is translated into the new language.
The documentation for the translation widget is at https://github.com/EvanHahn/HumanizeDuration.js/blob/main/README.md

gui: Use localised time in duration

---

lib/ignore/cache.go
lib/ignore/cache_test.go
lib/ignore/ignore.go

Tiny cleanup I noticed while trying to fix/test another issue (https://github.com/syncthing/syncthing/pull/9600). I shortly tried to figure out what it was used for in the past, but gave up without results.

lib/ignore: Remove unused patterns in cache

---

AUTHORS
lib/fs/basicfs.go
lib/fs/basicfs_copy_range.go
lib/fs/basicfs_watch.go
lib/fs/basicfs_watch_eventtypes_darwin.go
lib/fs/basicfs_watch_eventtypes_other.go
lib/fs/basicfs_watch_unsupported.go
lib/ignore/ignoreresult/ignoreresult_foldcase.go
lib/ignore/ignoreresult/ignoreresult_nofoldcase.go
lib/locations/locations.go
lib/model/folder_sendrecv.go
lib/model/folder_summary.go
lib/model/mocks/model.go
lib/model/model.go
lib/model/model_test.go
lib/model/progressemitter.go
lib/model/progressemitter_test.go
lib/model/sharedpullerstate.go
lib/osutil/lowprio_noop.go
lib/osutil/lowprio_unix.go
lib/scanner/walk.go
lib/syncthing/syncthing.go
lib/upgrade/upgrade_supported.go
lib/upgrade/upgrade_unsupp.go

This PR contains the set of changes needed to make Syncthing work on iOS for [my iOS app for Syncthing](https://github.com/pixelspark/sushitrain).
Most changes originate from [the Mobius Sync fork](http://github.com/MobiusSync/syncthing/tree/ios). I have removed the changes from their fork that are not strictly needed for my app (i.e. their changes to the GUI and command line utilities, for instance) and squashed it all in a single commit.
In summary, the changes are:
* Resolve non-absolute paths to the 'Documents' folder (basically the only one an app can/should write user data to by default on iOS)
* Tweaking of build flags/conditions for iOS (i.e. determine which basicfs_watch, ignoreresult variant to build for iOS)
* Disable upgrade mechanism on iOS
* Make `RequestGlobal` and …

ios: minimal set of changes for iOS app to work

---

cmd/syncthing/cli/main.go
go.mod
go.sum
gui/default/syncthing/core/aboutModalView.html

`github.com/kballard/go-shellquote` is already used in Syncthing, there's no need to have two shell splitting library. go-shellquote isn't marked as archived, hence the preference.
Tested on Linux

cli: Remove `go-shlex` dependency

---

lib/fs/filesystem.go
lib/fs/logfs.go

Reasoning in comments. The main motivation is to avoid all the case checks when walking the filesystem.

lib/fs: Put the caseFS as the outermost layer

---

gui/default/syncthing/core/localeService.js

gui: Fix incorrect UI language auto detection (fixes #9668)
Currently, the code only checks whether the detected language partially
matches one of the available languages. This means that if the detected
language is "fi" but among the available languages there is only "fil"
and no "fi", then it will match "fi" with "fil", even though the two are
completely different languages.
With this change, the matching is only done when there is a hyphen in
the language code, e.g. "en" will match with "en-US".

gui: Fix incorrect UI language auto detection (fixes #9668)

---

gui/default/syncthing/core/localeService.js
lib/api/api.go

The preference for languages in the Accept-Language header field should not be deduced from the listed order, but from the passed "quality values", according to the HTTP specification: https://httpwg.org/specs/rfc9110.html#field.accept-language
This implements the parsing of q=values and ordering within the API backend, to not complicate things further in the GUI code.  Entries with invalid (unparseable) quality values are discarded completely.
Example based on the RFC, modify to taste:
```
curl -X GET -H "Accept-Language: da, en-GB;q=1.8, en;q=1.0" http://localhost:8384/rest/svc/lang
```

lib/api: Correct ordering of Accept-Language codes by weight (fixes #9670)

---

cmd/syncthing/main.go
lib/syncthing/utils.go

This adds a temporary GUI/API server during the database migration. It responds with 200 OK and some log output for every request. This serves two purposes:
- Primarily, for deployments that use the API as a health check, it gives them something positive to accept during the migration, reducing the risk of the migration getting killed halfway through and restarted, thus never completing.
- Secondarily, it gives humans who happen to try to load the GUI some sort of indication of what's going on.
Obviously, anything that expects a well-formed API response at this stage is still going to fail. They were already failing though, as we didn't even listen at this point before.

fix(cmd): provide temporary GUI/API server during database migration

---

gui/default/syncthing/device/editDeviceModalView.html
gui/default/syncthing/settings/settingsModalView.html

Currently, the bandwidth limit input fields have no step defined, and as
such they use the default value of "1". Taking into account the fact
that these fields use KiB as their measurements, it makes more sense to
use larger steps, such as "1024" (1 MiB), as in most cases, it is very
unlikely that the user needs to have byte-level control over the limits.
Note that these steps only apply to increasing the values by using the
arrow keys, and the user is still allowed to input any value they want
manually.

chore(gui): use steps of 1024 KiB for bandwidth rate limits

---

internal/db/sqlite/basedb.go
internal/db/sqlite/sql/README.md

Just to be entirely sure that if the migration succeeds the schema version is always also updated. Currently if a migration succeeds but a later migration doesn't, the changes of the migration apply but the version stays - if the migration is breaking/non-idempotent, it will fail when it tries to rerun it next time (otherwise it's just a pointless re-execution).
Unfortunately with the current `db.runScripts` it wasn't that easy to do, so I had to do quite a bit of refactoring. I am also ensuring the right order of transactions now, though I assume that was already the case lexicographically - can't hurt to be safe.

chore(db): update schema version in the same transaction as migration

---

cmd/syncthing/main.go
internal/db/sqlite/db_open.go
internal/db/sqlite/db_update.go
lib/syncthing/syncthing.go
lib/syncthing/utils.go

This adds an explicit open of all folder databases to when we open the main database, thus causing any required migrations to apply. Since this is just after the main migration step we have the opportunity to use the database migration API/GUI server to report back status.
I set a start delay of five seconds for the temporary server in question, so that during a normal startup it usually won't even start. Only when a longer running migration is in progress will it become available to show what's going on.

fix(syncthing): apply folder migrations with temporary API/GUI server

---

CONTRIBUTING.md

This copies the relevant parts of the contribution guidelines in the docs, for the purpose of keeping them in a single place. The in-docs contribution guidelines can become a link to this document.

docs: update contribution guidelines from the docs site

---

internal/db/sqlite/basedb.go

https://github.com/syncthing/syncthing/blob/4ad3f076910e79914bd5956450691352594f5b87/internal/db/sqlite/basedb.go#L123
@calmh it appears shouldVacuum is always true, even when no migration script had to be run. This increases startup time significantly since 2.0.4.
n/a
n/a
n/a

fix(db): only vacuum database on startup when a migration script was actually run

---

lib/model/folder_sendrecv.go

Since #10332 we'd create the temp file when closing out the puller state for a file, but this is inappropriate if the reason we're bailing out is that there isn't space for it to begin with. Instead, do the free space check before we even start copying/pulling.

fix(model): earlier free-space check (fixes #10347)

---

lib/syncthing/syncthing.go

On startup, a CPU benchmark is performed that delays start by 3*150ms. This is not a long time but also quite unnecessary, and especially on mobile eats the battery unnecessarily.
This change only executes the benchmark if the logging level INFO is enabled. If it is not enabled, the result is not going anywhere. If a tree falls in a forest and no one is around to hear it, does it make a sound?
Built & tested with Synctrain on macOS
n/a
n/a

fix(syncthing): do not perform CPU benchmark on startup unless logging enabled

---

.policy.yml

This replaces `allow_contributor` with `allow_non_author_contributor`, because the former allows authors to approve their own pull requests.
From https://github.com/syncthing/syncthing/pull/9818#issue-2651431707:
> This adds `allow_contributor: true` which allows approvals by contributors to the PR (**but still not the author themself**, which is a different thing).
This statement conflicts with [the policybot README](https://github.com/palantir/policy-bot/blob/c013552248d2a99911207fa5c0045428ac073fa2/README.md), which says:
> If true, the approvals of someone who has committed to the pull request are
> considered when calculating the status.
> **The pull request author is considered a contributor.**

fix(policy): only allow approvals by non-author contributors
